### ISSUE TITLE
android weex-sdk0.18.0  input输入框无法清空

### ISSUE THREAD

**Issue by guozai0806** [apache/incubator-weex#1391]
android手机 使用weex-sdk0.18.0 库   input无法达到清空的效果 例子如下：
      <input class="password_ip" ref="input1"  :value="textinput"  @input="getConfrimPassword"  />
  getConfrimPassword(event) 
{ this.textinput = event.value;
 }，
login() {
     this.textinput = "";
    }
每次执行login方法 只有第一次能清成功，其他时候都无法清除。  但是android playground每次都能成功

**Comment by PXLZHM** [comment]
换这个试试       v-model="textinput"

**Comment by guozai0806** [comment]
table.customTableClassName {margin-bottom: 10px;border-collapse: collapse;display: table;}.customTableClassName td, .customTableClassName th {border: 1px solid #ddd;}您好！:value 和v-model 都用过了同样的问题。只能第一次成功 。   另外  我反复找规律发现了如下现象：  如果在@input方法里面直接textinput=“固定值”  就可以清除成功。如果textinput=event.vlaue 就会有问题    姓名：郭凤华    电话：18618457893                    From: "PXLZHM <notifications@github.com>"To: "apache/incubator-weex <incubator-weex@noreply.github.com>"CC: "guozai0806 <guofenghua@csii.com.cn>","Author <author@noreply.github.com>"Sent: 2018-08-03 16:30Subject: Re: [apache/incubator-weex] android weex-sdk0.18.0 input输入框无法清空 (#1391)换这个试试       v-model="textinput"&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by guozai0806** [comment]
weex playgroud 没有这个问题  但weex sdk集成到应用中就存在

**Comment by LtHelo** [comment]
I foune that problem too

**Comment by dodola** [comment]
表示同样有这个问题，可以见：http://dotwe.org/vue/132a878488fb2d0a43af437c53d3d595 这个例子
@Hanks10100

**Comment by YorkShen** [comment]
Update to the latest version, if this issue still happens, you can reopen it again.

**Comment by varSmallRookie** [comment]
通过观察发现，其实只要两次的value不一致，就能生效，这是我的code
       clickDeleteWord(e) {
            e && e.stopPropagation();
            this.orgintxt = ' ';
            this.$nextTick(() => {
                this.orgintxt = ''; 
            });
        }
