### ISSUE TITLE
WeexSDK.podspec contains a part of headers

### ISSUE THREAD

**Issue by myeveryheart** [apache/incubator-weex#1399]
I see the podspec in [Specs](https://github.com/CocoaPods/Specs/blob/master/Specs/7/2/9/WeexSDK/0.18.0.2/WeexSDK.podspec.json) is different from [incubator-weex.](https://github.com/apache/incubator-weex/blob/master/WeexSDK.podspec)
Specs has public_header_files, which is not enough to use for second dev.

**Comment by xuyouyang** [comment]
@myeveryheart do you mean that any implements you need are not in the public_header_files yet? Can you describe it in more detail? Thanks.

**Comment by myeveryheart** [comment]
@xuyouyang Yes, you are right. Cocoapods can create public headers If no public headers are specified then all the headers in source_files are considered public. That would be better.

**Comment by xuyouyang** [comment]
@myeveryheart I am sorry that I maybe not agree with you. In my opinions, a SDK framework do not need to public every file, such as some inner utility files. If you want to use or add more implements, you can add 'Category' files in your own project.

**Comment by myeveryheart** [comment]
@xuyouyang Ok, I get it, thx
