### ISSUE TITLE
请问这个项目还继续开发吗，半年不更新了。

### ISSUE THREAD

**Issue by xudejian** [apache/incubator-weex#1428]
请问这个项目还继续开发吗，半年不更新了。

**Comment by Hanks10100** [comment]
Weex 的代码一直在更新，参考这里： https://github.com/apache/incubator-weex/pulse/monthly

> July 13, 2018 – August 13, 2018
>
> Excluding merges, 19 authors have pushed 84 commits to master and 93 commits to all branches. On master, 238 files have changed and there have been 13,389 additions and 1,138 deletions.
