### ISSUE TITLE
Weex failed to render in Fragment (Android)

### ISSUE THREAD

**Issue by shinyjacklee** [apache/incubator-weex#1430]
Hello, i try to render weex with Fragment (Android) but failed with error as below:

`08-13 12:16:36.360 20983-21003 E/weex: reportJSException >>>> 
instanceId:1, exception function:createInstance, exception:Exception: 
SyntaxError: Unexpected token '}'. Cannot parse statement.`

And i already tried this [ISSUE from alibaba-weex](https://github.com/alibaba/weex/issues/2593)
 My issue already posted in StackOverFlow,[Weex can not render in Fragment (Android)](https://stackoverflow.com/questions/51815239/weex-can-not-render-in-fragment-android).
Help

**Comment by Hanks10100** [comment]
The `SyntaxError: Unexpected token '}'` is quite a common error when parsing or executing incomplete js code. Maybe the js bundle of your page is not fully downloaded before rendering.

**Comment by shinyjacklee** [comment]
Hi Hanks,the problem is even the WXInstance isn't created successfully,

` reportJSException >>>> 
instanceId:1, exception function:createInstance, exception:Exception: 
SyntaxError: Unexpected token '}'. Cannot parse statement.
at (global function):8
Function@[native code]
Function@[native code]
(weex framework):1:148499
ei@(weex framework):1:148517
createInstance@(weex framework):1:151735
(weex framework):1:255299`

Using the Weex playground app and Activity implementation to scan the same page QR Code can be rendered .

Or can you please give me a sample to render in Fragment(Android) ,which can also close the [ISSUE](https://github.com/alibaba/weex/issues/2593) mentioned above.

Thanks

**Comment by shinyjacklee** [comment]
Dear Hanks,finally i make it to render weex page in Android Fragment.

The **mistake** is i used wrong method  to load the url ~~`mWXSDKInstance.render()`~~ instead of the correct ` mWXSDKInstance.renderByUrl()` 

And for the sample to render with Fragment  try this[weex-start-kit](https://github.com/w11p3333/weex-start-kit).

Thanks for you help :)
