### ISSUE TITLE
Android端，Refresh和v-if同时使用，当条件不渲染refresh后，再重新渲染无法渲染

### ISSUE THREAD

**Issue by kIdJoEy** [apache/incubator-weex#1441]
## Description

Android端，Refresh和v-if同时使用，当条件不渲染refresh后，再重新渲染无法渲染

## Environment

Weex Version:0.18.2.88
Device Mode:OC105

## Broken Example

http://dotwe.org/挂了，我贴code吧= =

## Steps to Reproduce
[pullRefresh.txt](https://github.com/apache/incubator-weex/files/2292374/pullRefresh.txt)
[shareFootprint.txt](https://github.com/apache/incubator-weex/files/2292375/shareFootprint.txt)

**Comment by dim0xff** [comment]
`refresh` must be inside `list` or similar element

Check this http://dotwe.org/vue/e037ebfcb46315001148699d33187329

**Comment by kIdJoEy** [comment]
@dim0xff 
Thanx for replying.
Please check shareFootprint.txt,`pullRefresh` with `refresh` is inside `list`.

**Comment by zshshr** [comment]
Provide a reproducible example at http://dotwe.org/vue

**Comment by fengmingye** [comment]
**这个是android原生代码的bug，当v-if=false的时候，list中remove掉了refresh，swipelayout容器中把refreshview移除掉了，但是当v-if=true的时候，并没有吧refreshview重新嫁到swipelayout中。修复代码如下：**
public void setHeaderView(WXComponent loading) {
        setLoadmoreEnable(true);
        if (swipeLayout != null) {
          *****新增下面这段代码*****
if (refreshView.getParent() == null) {//add to fix footerview not visiable when controled by js v-if(true-false-true)
swipeLayout.setRefreshView();
        }
         ***************
    }

**swipeLayout的setRefreshView改为如下：**
/**
   * Init refresh view or loading view
   */
  public void setRefreshView() {
    // SetUp HeaderView
    FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, 0);
    if(headerView!=null && headerView.getParent()==null){
      addView(headerView, lp);
    }

    // SetUp FooterView
    lp = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, 0);
    lp.gravity = Gravity.BOTTOM;
    if(footerView!=null && footerView.getParent()==null){
      addView(footerView, lp);
    }
  }
**WxRefreshView的setRefreshView方法新增一行代码**
public void setRefreshView(final View view) {
        if (view == null)
            return;
        post(WXThread.secure(new Runnable() {
            @Override
            public void run() {
                linearLayout.removeAllViews();//新增的代码
                View child = null;
                View temp = view;
                if (view.getParent() != null) {
                    ((ViewGroup) view.getParent()).removeView(view);
                }
                for (int i = 0; i < ((ViewGroup) temp).getChildCount(); i++) {
                    child = ((ViewGroup) temp).getChildAt(i);
                    if (child instanceof CircleProgressBar)
                        circleProgressBar = (CircleProgressBar) child;
                }
                linearLayout.addView(temp);
            }
        }));
    }

**Comment by fengmingye** [comment]
loading与v-if同时使用也有此问题，可以同步修改

**Comment by YorkShen** [comment]
Thanks for your effort.

Provide a PR with [dot.we](http://dotwe.org/vue) link, we are happy to have a community contributor.
