### ISSUE TITLE
iOS端一直打印  <Weex>[error]WXBridgeContext.m:546, Instance doesn't exist!

### ISSUE THREAD

**Issue by songxing10000** [apache/incubator-weex#1479]
## Description

iOS端一直打印  <Weex>[error]WXBridgeContext.m:546, Instance doesn't exist!

## Environment
iOS WeexSDK 18.0.1

**Comment by xuyouyang** [comment]
@songxing10000 can you give us an example on http://dotwe.org/vue . This error means WXSDKInstance object has been deallocated and page still execute some js methods.

**Comment by songxing10000** [comment]
@xuyouyang 项目结合了很多自定义模块，用在线的没法模拟，不知道是不是有个图片轮播的weex页面，在进入子页面时，还在定时轮播引起的，明天去试试

**Comment by xuyouyang** [comment]
@songxing10000 perfect,you can have a try.Forthemore, you can add a breakpoint at the dealloc method of wxsdkinstance.
