### ISSUE TITLE
weex create 无响应

### ISSUE THREAD

**Issue by cpu220** [apache/incubator-weex#1480]
完全按照官网流程操作，在执行 weex create 后。如下图，长时间（几十分钟）无响应
![snip20180828_1](https://user-images.githubusercontent.com/5085979/44697636-33cef500-aaaf-11e8-8394-062f317a2645.png)

   v1.3.11
 - weexpack : v1.0.15
 - weex-builder : v0.4.1
 - weex-previewer : v1.5.1
- node v8.9.4
- npm v6.0.1

**Comment by cpu220** [comment]
有一个包的资源有问题，在重复尝试了无数次后，莫名其妙的好了。。。

**Comment by erha19** [comment]
@cpu220 you can choose `not unit test` while you create your project, this module is using for the unit test.

**Comment by erha19** [comment]
@Hanks10100 issue should be close ~
