### ISSUE TITLE
input type为date的时候选择时间问题

### ISSUE THREAD

**Issue by WeibinZheng** [apache/incubator-weex#1484]
最近在使用的时候使用了input并设置type为date类型选择时间，发现在iPhone7 plus上面 点击done和cancel大部分不会触发事件， 后来看源码发现WXDatePickerManager类中使用了UIToolbar的方式去设置done和cancel按钮，目前我修改成view加两个UIButton的形式，未发现上述问题

**Comment by Hanks10100** [comment]
Please offer an example on http://dotwe.org/vue to reproduce it.

**Comment by WeibinZheng** [comment]
我以把问题视频发送到你zhanghan.me@gmail.com的邮箱
附件包括: 问题修复前视频录屏，修复后视频录屏，修复前后weexSDK中WXDatePickerManager.m中修改的代码截图，使用的vue文件，
目前只测试出当前的这个iPhone7 Plus有这个问题，其他的机型暂未发现此问题
忘查收邮件并关注此问题

**Comment by Hanks10100** [comment]
@WeibinZheng 我本人是前端开发，解决不了 iOS 相关的问题，你可以直接在 issue 里贴出来，这样大家都可以看到。

建议把复现问题的代码贴到 http://dotwe.org/ 里，涉及到的原生代码直接贴在 issue 里（GitHub 也支持传文件），并且介绍一下复现过程。

**Comment by WeibinZheng** [comment]
[input type为date的时候选择时间问题.zip](https://github.com/apache/incubator-weex/files/2345012/input.type.date.zip)
文件已经上传，内有出问题机型视频及vue代码和原生修改截图，因为这个问题只有在我公司的一台手机上复现，在 http://dotwe.org/ 及其他手机上并不能复现

原生出问题代码(此方法不能调用)
`-(void)done:(id)sender
{
    [self hide];
    if (self.delegate && [self.delegate respondsToSelector:@selector(fetchDatePickerValue:)]) {
        NSString *value = @"";
        if([_type isEqualToString:@"time"])
        {
            value = [WXUtility timeToString:self.datePicker.date];
        }else if([_type isEqualToString:@"date"])
        {
            value = [WXUtility dateToString:self.datePicker.date];
        }
        [self.delegate fetchDatePickerValue:value];
    }
    
}`

**Comment by zshshr** [comment]
@WeibinZheng Can you give us a pull request?

**Comment by EslYz** [comment]
安卓端使用input type为date，点击后会崩溃，查看源码发现DatePickerImpl.pickDate方法最后一个参数extras传值是null，setButtonText 这里又有使用到

**Comment by mahaiyannn** [comment]
> [input type为date的时候选择时间问题.zip](https://github.com/apache/incubator-weex/files/2345012/input.type.date.zip)
> 文件已经上传，内有出问题机型视频及vue代码和原生修改截图，因为这个问题只有在我公司的一台手机上复现，在 http://dotwe.org/ 及其他手机上并不能复现
> 
> 原生出问题代码(此方法不能调用)
> `-(void)done:(id)sender
> {
> [self hide];
> if (self.delegate && [self.delegate respondsToSelector:@selector(fetchDatePickerValue:)]) {
> NSString *value = @"";
> if([_type isEqualToString:@"time"])
> {
> value = [WXUtility timeToString:self.datePicker.date];
> }else if([_type isEqualToString:@"date"])
> {
> value = [WXUtility dateToString:self.datePicker.date];
> }
> [self.delegate fetchDatePickerValue:value];
> }
> 
> }`

无法复现，是否可以提供一个可复现的demo?

**Comment by WeibinZheng** [comment]
只有公司的一台测试机上有这个问题，文件中有演示的视频，目前测试的其他机器正常

**Comment by wqyfavor** [comment]
感谢你的提交，但是该PR不会采纳。原因是我们不能写死中文的确定和取消按钮。

**Comment by WeibinZheng** [comment]
此问题新版本weex iOS SDK已经解决
