### ISSUE TITLE
页面 http://dotwe.org/vue/ 无法访问

### ISSUE THREAD

**Issue by zersoon** [apache/incubator-weex#1486]
页面无法访问

**Comment by Hanks10100** [comment]
我这里可以打开，清除一下浏览器缓存再试试。

**Comment by zersoon** [comment]
清除了，公司和家的网络都试过了。还是无法打开

**Comment by zersoon** [comment]
我换了浏览器，可以了，为什么会跟浏览器缓存有关的。

**Comment by Hanks10100** [comment]
某些资源文件配置的 HTTP 缓存时间有问题，如果某些时候浏览器缓存了有问题的文件，就会一直有问题，除非缓存过期。这些问题后续会修复一下。
