### ISSUE TITLE
render error:-2013

### ISSUE THREAD

**Issue by kyriediculous** [apache/incubator-weex#1490]
Hi,

I just created a new project on weex through the cli. 

When running  `npm run serve` it runs fine but on ios (physical device through weex playground) or android (emulator) it doesn't render. 

I tried finding answers through google translate but nothing that could help me. 

![hello-world](https://user-images.githubusercontent.com/22256858/44884187-a9f37780-acba-11e8-87f0-3f00f6077592.PNG)

**Comment by Hanks10100** [comment]
This issue has been closed because of no feedback or lack of activity. It can be reopened If you offer more information about. Thank you for your contributions.

> 长时间没回复，issue 关掉了。如果还想继续讨论，请提供更详细的信息，然后会 reopen 此 issue。谢谢配合。
