### ISSUE TITLE
using unregistered weex module "swipeBack"

### ISSUE THREAD

**Issue by fishyumiao** [apache/incubator-weex#1494]
## Description

页面能够正常显示，但日志中说使用了没注册的module，工程中没有出现任何包含"swipeBack"的内容

日志：
```
<Weex>[warn]WXJSCoreBridge.m:146, jsLog: [JS Framework] using unregistered weex module "swipeBack"
```
不知道是什么原因造成的？
怎么解决？

## Environment

ios weex sdk 0.18.0.3

**Comment by aixiaoxiang** [comment]
我是自己写了一个，里面的实现是空的
Weex 编译js的时候会自动添加一个
![image](https://user-images.githubusercontent.com/8416556/44952343-dc19fa80-aeaf-11e8-9723-b932a2d9a5b7.png)

---
IOS

![image](https://user-images.githubusercontent.com/8416556/44952350-171c2e00-aeb0-11e8-88db-ccfb309a38b9.png)

# 但是只是解决不报错

**Comment by Hanks10100** [comment]
一般报 `using unregister weex module` 是因为用了没注册的原生模块。按照文档[自定义模块](http://weex-project.io/cn/guide/extend-ios.html#zi-ding-yi-module)里的介绍，除了写一份模块实现以外，还要在初始化好 Weex SDK 之后注册一下自定义的模块，这样页面里才能调用得到。
