### ISSUE TITLE
web 内的 视频无法播放   weex 

### ISSUE THREAD

**Issue by JackChengGZ** [apache/incubator-weex#1499]

**Comment by xuyouyang** [comment]
Please offer an example on http://dotwe.org/vue to reproduce it. @JackChengGZ

**Comment by Hanks10100** [comment]
This issue has been closed because of no feedback or lack of activity. It can be reopened If you offer more information about. Thank you for your contributions.

> 长时间没回复，issue 关掉了。如果还想继续讨论，请提供更详细的信息，然后会 reopen 此 issue。谢谢配合。

**Comment by JackChengGZ** [comment]
不好意思，最近比较忙；
http://dotwe.org/vue/1e8e0acd1004f7b8a0a2cb4e732a4fad

**Comment by Hanks10100** [comment]
你提供的例子我试了一下可以打开 bilibili 的网站，播放不了视频是因为视频链接是 `bilibili:video/xxxxx`， Weex 容器并不识别这种 schema，看起来不像 `<web>` 组件的问题，是 B 站不认识 Weex 容器。建议使用纯净的例子，不要包含这些网站。
