### ISSUE TITLE
iOS中textArea组件中频繁大量复制粘贴文字点击done隐藏键盘时会出现键盘隐藏但页面没恢复正常的情况，非必现

### ISSUE THREAD

**Issue by WeibinZheng** [apache/incubator-weex#1503]
在iOS WeexSDK中的WXEditComponent.m类中
- (void)keyboardWillHide:(NSNotification*)notification方法中
if (![self.view isFirstResponder]) 修改成  if (![self.view isFirstResponder] && rootView.frame.origin.y == 0.f) 可以修复此问题，但是并不清楚会不会出现其他问题，还望答疑

**Comment by Hanks10100** [comment]
请提供 demo 以及复现步骤详细描述一下这个问题，如果发现的修复方法，可以直接提 PR，在 PR 里讨论代码是否合理。谢谢配合。

**Comment by Hanks10100** [comment]
This issue has been closed because of no feedback or lack of activity. It can be reopened If you offer more information about. Thank you for your contributions.

> 长时间没回复，issue 关掉了。如果还想继续讨论，请提供更详细的信息。谢谢配合。
