### ISSUE TITLE
iOS源码集成问题

### ISSUE THREAD

**Issue by lixiangsanxun** [apache/incubator-weex#1504]
## Description
源码集成iOS WeexSDK 0.18.0后，在代码编译时WXJSASTParser.h文件报 'string' file not found 的错误请问是什么原因？还请答疑 十分感谢

**Comment by fishyumiao** [comment]
没有包含stdc++相关的库，应该是libstdc++.tbd

**Comment by lixiangsanxun** [comment]
@fishyumiao  谢谢您回答我的问题，我看WeexSDK自带的podspec内有写s.libraries = "stdc++" 应该是通过pod依赖了stdc++，还需要我自己引入吗

**Comment by fishyumiao** [comment]
可能是你的工程设置中库链接没有包含$(inherit)

**Comment by lixiangsanxun** [comment]
@fishyumiao  好的 谢谢啊 我看看
