### ISSUE TITLE
JS Service无法调用

### ISSUE THREAD

**Issue by HJaycee** [apache/incubator-weex#1513]
按照[官方文档](http://weex.apache.org/cn/references/js-service.html)编写了一个：[KSService.js](http://test-1252137158.file.myqcloud.com/myFloder/KSService.js)

原生中也注册了这个service，但是在vue中调用没有反应，是否因为文档中这个JS Service的编写例子不是完整的？

**Comment by chinabrant** [comment]
> 按照[官方文档](http://weex.apache.org/cn/references/js-service.html)编写了一个：[KSService.js](http://test-1252137158.file.myqcloud.com/myFloder/KSService.js)
> 
> 原生中也注册了这个service，但是在vue中调用没有反应，是否因为文档中这个JS Service的编写例子不是完整的？

你好，我还是跑不起来。官网上关于js service的文档太简单了。可以发个例子看看不？
