### ISSUE TITLE
 image 组件无法保存超过宽度750px或者高度1334px的图片，无法保存原图

### ISSUE THREAD

**Issue by kang558** [apache/incubator-weex#1514]
## Description
image组件保存设置的宽度超过750px或者高度超过1334px就无法保存, 错误信息：{"errorDesc":"Image is empty","success":false}
并且无法保存原图。受限于设置图片的宽高 

## Broken Example

示例：[http://dotwe.org/vue/478d1cff03da0c864fcd046bca366cd0](http://dotwe.org/vue/478d1cff03da0c864fcd046bca366cd0)

**Comment by kang558** [comment]
还有保存一次会保存两张出现在不同的文件夹里

**Comment by xuyouyang** [comment]
@kang558 iOS or Android?

**Comment by kang558** [comment]
@xuyouyang  both

**Comment by lucky-chen** [comment]
@kang558 weex_sdk 、机型 等验证环境标注下，

本地测试ok
- master最新代码
- 一加2

**Comment by kang558** [comment]
> @kang558 weex_sdk 、机型 等验证环境标注下，
> 
> 本地测试ok
> 
> * master最新代码
> * 一加2

最新版的weexplayground 保存成功了，但是会报error错误

**Comment by YorkShen** [comment]
Try the latest version of weex, it works well on my phone.

I will just close the issue. Feel free to reopen it if you have appending questions.
