### ISSUE TITLE
Android端input控件在默认输入一个字符后，删除不能调用input回调

### ISSUE THREAD

**Issue by tody123** [apache/incubator-weex#1519]
## Description
Android端input控件在默认输入一个字符后，删除不能调用input回调

## Environment
android  weex版本 0.18.0
小米3手机 6.0系统

## Broken Example
http://dotwe.org/vue/5064d32097f7242f97dfcc644ab8f538

## Steps to Reproduce

1、input控件默认有一个字符
2、弹起软键盘删除那个字符
3、监听input回调事件没有调用

**Comment by Hanks10100** [comment]
Please offer a complete example on http://dotwe.org/vue

**Comment by tody123** [comment]
for more example see https://issues.apache.org/jira/browse/WEEX-612

**Comment by tody123** [comment]
发现只在默认只输入一个字符才会出现这个bug。应该原生的Edittext 在输入值setValue会触犯onTextChanged事件，weex在setValue时候通过mIgnoreNextOnInputEvent变量对这种情况进行了过滤从处理。原因是AbstractEditComponent.java文件中当删除一个字符时候会触犯onTextChanged事件，
` 
public void onTextChanged(CharSequence s, int start, int before, int count) {
                    if (mIgnoreNextOnInputEvent) {
                        mIgnoreNextOnInputEvent = false;
                       return;
                    }
                    if (mBeforeText.equals(s.toString())) {
                        return;
                    }
`
当删除一个字符时候 ，这时候mBeforeText.equals(s.toString()) 成立都是空值，所以返回不触发事件。
可修改如：
`    if (mIgnoreNextOnInputEvent) {
               mIgnoreNextOnInputEvent = false;
               mBeoreText = s.toString();
               return;
                    }
`

已提交pull request:
https://github.com/apache/incubator-weex/pull/1522

**Comment by tody123** [comment]
@Hanks10100   a complete example on http://dotwe.org/vue/5064d32097f7242f97dfcc644ab8f538

**Comment by Hanks10100** [comment]
The PR has been merged. https://github.com/apache/incubator-weex/pull/1522
