### ISSUE TITLE
input组件唤起软键盘，ios会遮住input组建下面的内容

### ISSUE THREAD

**Issue by BrightMi** [apache/incubator-weex#1523]
## Description
input组件唤起软键盘，ios会遮住input组建下面的内容，android 没有问题

## Broken Example
示例：http://dotwe.org/vue/8f4d212bc548cd46510dbb15c720dc3c

**Comment by wqyfavor** [comment]
iOS与Android顶起的原理不同，iOS根据edit在WXRootView中的位置计算出顶起的距离，默认是输入框下边缘+20像素。同时提供完成按钮。

**Comment by wqyfavor** [comment]
we add upriseOffset attribute for input in master.

**Comment by Tingglelaoo** [comment]
> ## Description
> input组件唤起软键盘，ios会遮住input组建下面的内容，android 没有问题
> 
> ## Broken Example
> 示例：http://dotwe.org/vue/8f4d212bc548cd46510dbb15c720dc3c

是因为fixed定位导致的
