### ISSUE TITLE
Xcode10 不再默认支持stdc++

### ISSUE THREAD

**Issue by hdw09** [apache/incubator-weex#1530]
Xcode 10 不在默认支持stdc++, 在WeexSDK.podspec中对stdc++ 改为 c++吧，不然编译会失败

s.libraries = "stdc++"

to

s.libraries = "c++"

**Comment by Hanks10100** [comment]
I found a PR https://github.com/apache/incubator-weex/pull/1317 , maybe is the same question as you mentioned.
