### ISSUE TITLE
picker is undefined !

### ISSUE THREAD

**Issue by bcreation** [apache/incubator-weex#1558]
## Description
I try to import the picker module like this : 
const picker = weex.requireModule('picker')
But when I tried to call it, like in the exemple 
https://weex.apache.org/references/modules/picker.html

Nothing happend. So I put a console.log(picker) to see what inside. 
But it return undefined
Then I tries to search in the source code. 
I found this : 

requireModule (moduleName) {
    const metaMod = weex._meta.requiredModules
    if (!metaMod[moduleName]) {
      metaMod[moduleName] = 0
    }
    metaMod[moduleName]++
    return weexModules[moduleName]
  },

 weexModules['picker'] is undefined and weexModules list havent 'picker'. 

Can you help me ?

## Environment

"dependencies": {
    "phantom-limb": "0.0.1",
    "vue": "^2.5.11",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "weex-vue-render": "^1.0.17",
    "weex-vuex-loader": "^1.0.0"
  },

I run on the web weex playground in chrome

**Comment by Hanks10100** [comment]
The `weex-picker` has been moved out of the `weex-vue-render` package. Here is the source code, you can import manually. https://github.com/weexteam/weex-picker

By the way, I think the picker module should be put back to the `weex-vue-render` package. Maybe @imyzf can help with this.

**Comment by YorkShen** [comment]
I will close this PR as it seems resolved, feel free to reopen if there is still a problem.
