### ISSUE TITLE
Weex flavors 控制

### ISSUE THREAD

**Issue by fantasyRqg** [apache/incubator-weex#1560]
weex 如何能实现flavor 控制， 类似Android prodcutFlavors 控制， 可以维护细微的差异。 Phone 和Pad 共同开发过程中会遇到绝大部分的相同和细微的差异。 如果有  productFlavors 我们提高代码复用率。

**Comment by YorkShen** [comment]
Not supported yet.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
