### ISSUE TITLE
三星手机Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'boolean android.widget.Editor$SelectionModifierCursorController.isDragAcceleratorActive()' on a null object reference

### ISSUE THREAD

**Issue by dongrong-fu** [apache/incubator-weex#1576]
## Description

安卓weex平台线上监测到crash，98%都是来自三星手机，具体的错误描述如下文件

[com.fanli.android.apps_issue_13522_crash_5BA9D0E90351000171D764E73D482138_DNE_0_v2.txt](https://github.com/apache/incubator-weex/files/2414447/com.fanli.android.apps_issue_13522_crash_5BA9D0E90351000171D764E73D482138_DNE_0_v2.txt)

## Environment

Android平台，绝大部分来自三星手机，可能是三星手机改过sdk源码，没有catch住该错误。而且我们在6月份拉取的weex sdk都没有该错误，但是8月份重新拉取了一次，就报错了，希望帮忙看下

## Broken Example

从fabric报错日志中看出，应该是和edittext有关的错误

## Steps to Reproduce

目前没找到解决方案，希望官方帮忙看下，提出一些修改建议

**Comment by YorkShen** [comment]
Please update to the latest version.

I will close this issue and feel free to reopen if there is still a problem
