### ISSUE TITLE
Crash in Layout.c

### ISSUE THREAD

**Issue by rohitnareshsharma** [apache/incubator-weex#1578]
## Description

IOS Weex SDK Crash

Our application is crashing in production because of the below bug.
we are using 0.18.0 version of weex ios SDK. Please see the stack below.

Crashed: com.taobao.weex.component
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000018

Crashed: com.taobao.weex.component
0  Paytm                          0x1039253f4 wx_layoutNode (Layout.c:990)
1  Paytm                          0x1039253f4 wx_layoutNode (Layout.c:990)
2  Paytm                          0x103942db8 -[WXComponentManager _layout] (WXComponentManager.m:820)
3  Paytm                          0x103942c78 -[WXComponentManager _layoutAndSyncUI] (WXComponentManager.m:789)
4  Paytm                          0x10393f33c -[WXComponentManager _recursivelyAddComponent:toSupercomponent:atIndex:appendingInTree:] (WXComponentManager.m:310)
5  Paytm                          0x10393efc0 -[WXComponentManager addComponent:toSupercomponent:atIndex:appendingInTree:] (WXComponentManager.m:269)
6  Paytm                          0x103939110 __42-[WXBridgeContext registerGlobalFunctions]_block_invoke_2 (WXBridgeContext.m:139)
7  Paytm                          0x10393dec8 +[WXComponentManager _performBlockOnComponentThread:] (WXComponentManager.m:130)
8  Foundation                     0x185a4e0ec __NSThreadPerformPerform + 340
9  CoreFoundation                 0x184fab404 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
10 CoreFoundation                 0x184faac2c __CFRunLoopDoSources0 + 276
11 CoreFoundation                 0x184fa879c __CFRunLoopRun + 1204
12 CoreFoundation                 0x184ec8da8 CFRunLoopRunSpecific + 552
13 Foundation                     0x18593d674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
14 Paytm                          0x10393ddac -[WXComponentManager _runLoopThread] (WXComponentManager.m:122)
15 Foundation                     0x185a4defc __NSThread__start__ + 1040
16 libsystem_pthread.dylib        0x184c29220 _pthread_body + 272
17 libsystem_pthread.dylib        0x184c29110 _pthread_body + 290
18 libsystem_pthread.dylib        0x184c27b10 thread_start + 4

## Environment

iPhone, OS : 11.4.1

## Steps to Reproduce

Its not happening for our normal testing. But getting reported in Fabric crash reporting tools.
Please help us to get this fixed.

**Comment by rohitnareshsharma** [comment]
It is their in 0.18.0 version of weex sdk. Have we published ios SDK latest than this.

**Comment by cxfeng1** [comment]
What's the frequency of the crash， If it's not very high， I recommend you wait for the version 0.20.0 in which we have fixed the crash.

**Comment by rohitnareshsharma** [comment]
Last 7 Days, 996 Users with 1140 crash reported. We can wait for the version. Do you have any timeline for the same for 0.20.0. A rough estimate even.

**Comment by cxfeng1** [comment]
We will start 0.20.0 Apache release process in recent days, it will be released in Nov. if fortunately.

**Comment by wqyfavor** [comment]
0.20.1 already released, this issue should have been fixed.
