### ISSUE TITLE
WEEX waterfall组件中增加input组件，在input里输入内容，上拉或下拉后里面的数据没有了

### ISSUE THREAD

**Issue by yaorui2568** [apache/incubator-weex#1586]
waterfall组件中增加input组件，在input里输入内容，上拉或下拉后里面的数据没有了

**Comment by Hanks10100** [comment]
Please offer an example on http://dotwe.org/vue

**Comment by Hanks10100** [comment]
This issue is closed because not giving a response for a long time. If you still confused with this question, you can file a new issue according to the issue template with enough information.
