### ISSUE TITLE
Broken links in Example Guide

### ISSUE THREAD

**Issue by conejodan** [apache/incubator-weex#1592]
On README.md file the links are broken and send page not found (404)

Link Page:
https://github.com/apache/incubator-weex/tree/master/examples

Links Broken:
https://github.com/apache/incubator-weex/blob/master/examples/showcase/ui.we
https://github.com/apache/incubator-weex/blob/master/examples/template.we
https://github.com/apache/incubator-weex/blob/master/examples/index.we
https://github.com/apache/incubator-weex/blob/master/doc/components

**Comment by Hanks10100** [comment]
That legacy examples which is written by `.we` syntax, they will be removed someday. Please use Vue or Rax instead.
