### ISSUE TITLE
android使用源码导入工程失败，界面显示 reader error -1001 degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

### ISSUE THREAD

**Issue by fantasysea** [apache/incubator-weex#1596]
# 我使用weex 中文文档上写的源码方式导入现有的Android工程
## 导入步骤：
 - 下载源码 git clone https://github.com/apache/incubator-weex.git
 -  创建 Android 工程。
 -  通过以下路径引入 SDK Module
 -  File->New-Import Module-> 选择 WEEX SDK Module(weex/android/sdk) -> Finish
 -  app 的 build.gradle 中添加如下依赖:compile project(':sdk')
导入之后编译报错找不到  **path '../../weex_core/CMakeLists.txt'** 然后我把weex_core源码也导入了，编译继续报错，切换了NDK 14之后可以编译了。有几个小冲突，是因为recyleview缺少了。继续导入。最后成功编译了。但是打开页面。不是报错 reader error -1001，就是不显示页面。

**PS:文档真的和实际很不一样，怎么才能正确的用源码方式开发？**

log日志：

```

09-28 23:34:32.983 12385-12438/com.xxx.myapplication E/WeexCore: failed find class WMBridge
09-28 23:34:32.983 12385-12438/com.xxx.myapplication W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bridge.WMLBridge" on path: DexPathList[[zip file "/data/app/com.xxx.myapplication-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.myapplication-2/lib/arm, /data/app/com.xxx.myapplication-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
09-28 23:34:32.984 12385-12438/com.xxx.myapplication W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Runtime.nativeLoad(Native Method)
        at java.lang.Runtime.doLoad(Runtime.java:435)
        at java.lang.Runtime.loadLibrary(Runtime.java:370)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:140)
        at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:226)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    	Suppressed: java.lang.ClassNotFoundException: com.taobao.windmill.bridge.WMLBridge
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    		... 12 more
    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

补充说明 ：一开始使用     
```
mInstance.renderByUrl(
        getPageName(),
        url,
        options,
        jsonInitData,
        CommonUtils.getDisplayWidth(this),
        CommonUtils.getDisplayHeight(this),
        WXRenderStrategy.APPEND_ASYNC); 
```
打开会显示-1001，现在换了一种打开方式之后‘mWXSDKInstance.render("WXSample", WXFileUtils.loadFileOrAsset("index.js", this), null, null, -1, -1, WXRenderStrategy.APPEND_ASYNC);’，weex页面安装的第一次是空白的，返回但桌面，再次打开，就可以显示页面了。

- 2018-09-29更新，使用了0.16.0版本之后没遇到这个问题了。最新版本的bug吗？

**Comment by chris-wu2015** [comment]
升级0.19还是报这个错，求解

**Comment by fantasysea** [comment]
> 升级后解决了就好。现在最新版本应该是 0.19 了，可以升级到最新。

我就是使用0.19 版本出现的这个问题,0.16.0老版本不会出现.

**Comment by noman798** [comment]
请问怎么增加到19？
修改为    compile 'com.taobao.android:weex_sdk:0.19.0'
报错

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by chris-wu2015** [comment]
0.19.0.3和0.19.0-rc3是不一样的吧？确定有0.19.0.3这个版本吗？

**Comment by ttarigo** [comment]
@fantasysea 这个问题解决了吗？同样遇到这个问题

**Comment by brucetoo** [comment]
明显是so没引入。源码编译首先要打包so，不关心native层的话 建议直接[在此](https://gitbox.apache.org/repos/asf?p=incubator-weex.git;a=blob_plain;f=android/sdk/libs/armeabi/libweexcore.so;hb=refs/heads/master) 点击下载最新的 libweexcore.so 引入到自己工程，在引导android-sdk java层的源码 此问题就解决了

**Comment by brucetoo** [comment]
这个问题原因是你直接引入此库中的android-sdk源码，其中的build.gradle中有三行
`    delete 'libs/armeabi/libweexcore.so'
    delete 'libs/armeabi-v7a/libweexcore.so'
    delete 'libs/x86/libweexcore.so'`
已经将libweexcore.so 给删了，而后是通过直接编译出新的so。图简单的话，可以直接在[此路径中](https://gitbox.apache.org/repos/asf?p=incubator-weex.git;a=tree;f=android/sdk/libs;h=b32a7a5dbb58048c5d6d22785fdc06260d984537;hb=HEAD)将最近的匹配平台的so下载下来引入，并且注释上述三行代码，避免再次被删除

**Comment by lucky-chen** [comment]
> @fantasysea 这个问题解决了吗？同样遇到这个问题

gradle的配置发一下看看

**Comment by lucky-chen** [comment]
@fantasticcmm @ttarigo 尝试修改下gradle中的配置路径，sdk需要从weex的根目录拷贝so和js文件。
直接import，配置相对路径文件各种找不到
- 第一步，声明weex的根目录 `String weexRootPath = '/Users/xxx/xxx/incubator-weex"`
- 第二步，修改相对路径
   - `'../../pre-build'`改为`weexRootPath+'/pre-build'`
   - `'../../weex_core/CMakeLists'`改为`weexRootPath+'/weex_core/CMakeLists.txt'`
   - `dir:"../../weex_core"`改为`dir:weexRootPath+"/weex_core"`

**Comment by chris-wu2015** [comment]
这边终于解决了这个问题，根据以上几位的指点，发现可能是因为gradle插件版本不一致的问题，导致项目中生成的libweexcore.so的目录路径跟weex源码库中weex_core下release.sh或debug.sh脚本中的路径不一样，所以执行sh脚本时copy文件失败，但不会报任何异常，我这边的处理方式是在写一个task任务来自己copy so文件到libs下，避免直接修改源码，导致后续升级sdk困难

**Comment by flyminiboy** [comment]
使用最新的版本通过gradle接入，还是有偶现的该问题出现。
现在想确定一下如果初始化失败，之后再进行初始化，会不会一直失败。

**Comment by lufengd3** [comment]
> 初始化失败，之后再进行初始化，会不会一直

应该是 weex 还没初始化完，onException 里延时重试  render 可以解决，亲测有效

**Comment by Mrhejunjie** [comment]
你好，我这边也出现了该问题的，我看了一下，具体的报错时**lib*****.so” is 32-bit instead of 64-bit**现在weex提供了armeabi 和armeabi-v7a两种架构的so包，但是没有提供arm64-v8a架构的so包，导致初始化失败。建议官方生成arm64-v8a架构的so包，供开发人员自主选择。使用的weex版本是0.20.3.0-beta
@Hanks10100

**Comment by zacdaryl** [comment]
项目本身有一个so库，但是没有过滤ABI，默认生成了全部ABI对应的so库。观察apk中lib目录，发现只有x86、armeabi、armeabi-v7a中有对应的weex so库，于是过滤ABI后，问题解决。

`ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }`

**Comment by zhouxuemeng1988** [comment]
> 项目本身有一个so库，但是没有过滤ABI，默认生成了全部ABI对应的so库。观察apk中lib目录，发现只有x86、armeabi、armeabi-v7a中有对应的weex so库，于是过滤ABI后，问题解决。
> 
> `ndk { abiFilters "armeabi", "armeabi-v7a", "x86" }`

亲测对我有效。3Q
