### ISSUE TITLE
页面加载html标签无法显示

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#1599]
> `<div v-html="htmlData" style="height: 500px;width: 750px;background-color: red">{{htmlData}}</div>
<text>{{htmlData}}</text>`

htmlData是一段html源码：
`<p>虽然湖人队在勒布朗-詹姆斯时代的第一次正式训练是集中于防守和学习新战术，但是他们以一场老式的三分球大赛结束了这场比赛。</p>`
weex是否不支持vue的v-html语法？

**Comment by kang558** [comment]
这个是不支持的

**Comment by Hanks10100** [comment]
Weex 里不支持 `v-html`. http://weex-project.io/cn/guide/use-vue.html#mo-ban-zhi-ling

**Comment by liuyfl** [comment]
如果想要实现显示HTML标签的内容，有方案可以实现的吗
