### ISSUE TITLE
are there some methods to prevent <cell> support RecyclerView?

### ISSUE THREAD

**Issue by imfenghuang** [apache/incubator-weex#1626]
always, this feature is useful, however, sometimes it makes some difficulties. For example, if one `<cell>` has more than 30 images (or other things be added by ajax), it may be rerendered when it reenters to visual area, then it will make the page be blocked in a short time.

**Comment by gubaojian** [comment]
you can use recycle="false" to prevent the Image And Text Data ReBind。

https://github.com/apache/incubator-weex-site/pull/310/files

**Comment by imfenghuang** [comment]
> you can use recycle="false" in cell to prevent the Image And Text Data ReBind。
> 
> https://github.com/apache/incubator-weex-site/pull/310/files
> 
> Or you can use autoBitmapRecycle="false" in image to prevent the bitmap to be recycle when not visible.

let me try~

**Comment by YorkShen** [comment]
I will close this issue as it seems like solved. Feel free to reopen if there is still problem.
