### ISSUE TITLE
weex初始化进入onException回调

### ISSUE THREAD

**Issue by dongrong-fu** [apache/incubator-weex#1627]
weex偶现进入onException回调，多个安卓版本和手机类型都有，并且在出现问题的手机上也是非必现，经线上数据统计出错概率大约为0.8%，报错内容为：
erroecode -1001 degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

**Comment by Hanks10100** [comment]
可能是 js framework 初始化失败了，可以加一些错误处理确保 weex 正确初始化之后再执行页面。

**Comment by Hanks10100** [comment]
和 #1596 重复，先关掉了。
