### ISSUE TITLE
something wrong in <recycle-list> render 

### ISSUE THREAD

**Issue by Yhspehy** [apache/incubator-weex#1629]
## Description

Hi, in `recycle-list>`, i find something wrong in render when loading more data, .
Problems: 
1. some img is not rendered
2. some item element is mixed
3. some space in the bottom of the item

## Environment

ios, iphonexs

## Broken Example

Example: [dotwe url](http://dotwe.org/vue/9fa9d2f489d1988f7334aeabcae802df)

![image](https://user-images.githubusercontent.com/22761730/46859720-1d071680-ce41-11e8-86c9-0ee7e2085cf3.png)

**Comment by doumafang** [comment]
It looks like a bug.We will fix it ASAP.

**Comment by Yhspehy** [comment]
Waiting for good news

**Comment by mahaiyannn** [comment]
https://github.com/apache/incubator-weex/pull/1934 have fix this problem.

**Comment by wqyfavor** [comment]
Thanks. Already fixed with PR https://github.com/apache/incubator-weex/pull/1934
