### ISSUE TITLE
weex macbookpro安装失败

### ISSUE THREAD

**Issue by wangqian2017** [apache/incubator-weex#1630]
![wechatimg5](https://user-images.githubusercontent.com/25632596/46865760-43cd4900-ce51-11e8-97eb-fb6c40a3f028.jpeg)

**Comment by erha19** [comment]
@wangqian2017 you may have installed `weex-toolkit` before you run the above command, and that's bug is cause by `npm5`, you can delete the `weex-toolkit` cache on `/usr/local/lib/node_modules/weex-toolkit` or using `npm@4` to install it.
ps: do not use `sudo` command to install a npm package at all, it will cause many permission issues while you using npm package.

**Comment by erha19** [comment]
@Hanks10100 This issue is no longer active, it should be closed now.
