### ISSUE TITLE
新版本地址下载链接失败：404

### ISSUE THREAD

**Issue by KrMick** [apache/incubator-weex#1631]
Android studio:
Could not find weex_sdk.jar (com.taobao.android:weex_sdk:0.19.0.3).
Searched in the following locations:
    https://jcenter.bintray.com/com/taobao/android/weex_sdk/0.19.0.3/weex_sdk-0.19.0.3.jar

{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}

**Comment by joy2helloworld** [comment]
这个问题是解决了吗？

**Comment by noman798** [comment]
我也遇到同样的问题了 怎么搞？

**Comment by KrMick** [comment]
releaseCompile 'com.taobao.android:weex_sdk:0.19.0.4:release@aar'
    debugCompile 'com.taobao.android:weex_sdk:0.19.0.4:debug@aar'

**Comment by YorkShen** [comment]
#1694 

Sorry the delay, you can use `compile 'com.taobao.android:weex_sdk:0.19.0.7'`. I have checked, it worked well
