### ISSUE TITLE
ios Refresh component slide too much when refreshing is over

### ISSUE THREAD

**Issue by Yhspehy** [apache/incubator-weex#1633]
## Description
If list count is changed(add or delete), refresh component will slide too much when refreshing is over

## Environment
weex: v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.1.17
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

ios, iphonexs

## Broken Example

[example](http://dotwe.org/vue/f541ed72a121db8447a233b777003e8a)

**Comment by xuyouyang** [comment]
@Yhspehy  Hi, can you give us an example on http://dotwe.org/vue . Thx.

**Comment by Yhspehy** [comment]
@xuyouyang
http://dotwe.org/vue/f541ed72a121db8447a233b777003e8a

**Comment by mahaiyannn** [comment]
> @xuyouyang
> http://dotwe.org/vue/f541ed72a121db8447a233b777003e8a

Thank you for your example, we will check it ASAP.

**Comment by wqyfavor** [comment]
已修复 https://github.com/apache/incubator-weex/pull/2109
