### ISSUE TITLE
Android   0.19.0.3 404 NOT FOUND

### ISSUE THREAD

**Issue by joy2helloworld** [apache/incubator-weex#1640]
![image](https://user-images.githubusercontent.com/8622657/47057353-cc057280-d1f2-11e8-9631-0394a1496685.png)

gradle 文件：
![image](https://user-images.githubusercontent.com/8622657/47057392-07a03c80-d1f3-11e8-9c4f-32546701a91a.png)

**Comment by imcloud** [comment]
一样引用不到

上去bintray可以看到他们根本没有上传这个文件，aar也没有对应名字的文件

真坑人

**Comment by YorkShen** [comment]
@imcloud  Ref https://bintray.com/alibabaweex/maven/weex_sdk/0.19.0.3

**Comment by YorkShen** [comment]
Be aware of the GFW, thanks.
