### ISSUE TITLE
如何应对js劫持？

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#1642]
我在客户端渲染weex js 文件之前会对文件做md5 校验.
监控发现有些用户在某个网络环境下持续的md5校验失败，无法显示页面，切换网络环境就可以恢复.
怀疑是运营商对http 请求的js文件做了某些修改注入,有什么办法应对吗？

**Comment by imfenghuang** [comment]
http -> https

**Comment by chenzefeng09** [comment]
> http -> https

https还是比较慢，有什么方法，比如修改请求或返回header之类的让运营商认为这不是个js？

**Comment by Hanks10100** [comment]
https 是正解。 这个问题好像和 Weex SDK 无关，欢迎在其他地方讨论。
