### ISSUE TITLE
IOS - input 值精度丢失

### ISSUE THREAD

**Issue by leoyin** [apache/incubator-weex#1643]
## Description
千牛客户端，weex 开发的插件，input 输入框。
value值设置为部分浮点数值 如：8.55、8.53、8.88 等，展示值存在精度丢失问题。value值设置为字符串类型无此问题

## Environment
系统：i0S
WeexVersion 0.17.0

## Broken Example
<input value={8.55} /> 展示值为8.55000000001

**Comment by xuyouyang** [comment]
@leoyin This problem maybe cased by JSON serializing in iOS. So I think you'd better handle digital precision issues in front-end code.
