### ISSUE TITLE
box-shadow draw bug

### ISSUE THREAD

**Issue by zdqdtc** [apache/incubator-weex#1648]
## Description

i use box-shadow in list component ，when  i scroll the list，the shadow is drawed  out of the list

## Environment
Weex Version: 0.17.0
Device Mode: MI 5s  AND All Devices

## Broken Example

 .m-gift-card {
        flex-direction: column;
        justify-content: space-between;
        height: 105wx;
        margin-left: 10wx;
        margin-right: 10wx;
        border-radius: 5wx;
        margin-bottom: 5wx;
        margin-top: 5wx;
        border-width: 1px;
        box-shadow: 10wx,20wx 5px #666666;
    }

**Comment by Hanks10100** [comment]
Not support using `,` in box-shadow yet. You should write `box-shadow: 20wx 5px #666666;` without `10wx,`.

**Comment by crobotvip** [comment]
i find the problem in 0.20.0.2 version, your plan is useless, i do it by keep the theme color
