### ISSUE TITLE
how to use js service?

### ISSUE THREAD

**Issue by chinabrant** [apache/incubator-weex#1649]
My js service register code：
```objective-c
NSString *path = [[NSBundle mainBundle] pathForResource:@"utils_service" ofType:@"js"];
    NSString *content = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:nil];
    
    [WXSDKEngine registerService:@"utilsService" withScript:content withOptions:@{ @"serviceName": @"utilsService" }];
```

JS Service code:
```javascript
service.register("utilsService", {
   
    create: function (id, env, config) {
        return {
            NormalService: function (weex) {
                var modal = weex.requireModule('modal')
                return {
                    toast: function (title) {
                        modal.toast({ message: title })
                    },
...
```

use code:
var utilService = new service.normalService(weex) 

error:
service name not defined

Question:
Follow this [document](https://weex.apache.org/cn/references/js-service.html), i can't understand how to use JS Service.

If i want to register more than one JS Service, what should i do? 

Thanks.

**Comment by chinabrant** [comment]
I have fixed this.
change the use code:
var utilService = new service.NormalService(weex)

**Comment by iclinux** [comment]
> I have fixed this.
> change the use code:
> var utilService = new service.NormalService(weex)

请问，使用“service.register("utilsService", {”注册时，会提示service未定义，您是如何解决的？
