### ISSUE TITLE
【Need help】 how can i use buffer in js service?

### ISSUE THREAD

**Issue by chinabrant** [apache/incubator-weex#1653]
【Need help】
how can i use buffer in js service?
Can i do like this?
```javascript
const Buffer = require('buffer/').Buffer;
```

**Comment by Hanks10100** [comment]
Please refer to the document of this `buffer` package: https://www.npmjs.com/package/buffer

> The buffer module from node.js, for the browser.

Not for Weex. It's designed for browser and requires many browser specific APIs.
