### ISSUE TITLE
Sticky/Pinned header is not working for sdk version 0.18.0.

### ISSUE THREAD

**Issue by gaurav-mishra8** [apache/incubator-weex#1659]
## Description
Sticky/Pinned header is not working for sdk version 0.18.0.
Sticky header working in 0.16.0 sdk version
(Note: It is working with playground app (0.18.0-beta-3)

## Environment
Weex Version - 0.18.0
Device Info : 
JS Framework - 0.24.5
Android version -8.0.0 

## Broken Example
Following URL works fine in 0.16.0 sdk version
http://dotwe.org/vue/19d4544cc5053a829dbef5875ac6d868
In 0.18.0 sdk version, sticky header not working.

## Steps to Reproduce
Load URL : http://dotwe.org/vue/19d4544cc5053a829dbef5875ac6d868
and scroll list to observe.

**Comment by YorkShen** [comment]
Try update to the latest version of Weex. You can reopen this issue if there is still a problem.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
