### ISSUE TITLE
WXBridgeManager的一个Crash问题

### ISSUE THREAD

**Issue by erduoniba** [apache/incubator-weex#1671]
## Description

#0 Thread
NSGenericException
*** Collection <__NSArrayM: 0x2839bbc60> was mutated while being enumerated.

0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[__NSSingleObjectEnumerator initWithObject:]
3 CoreFoundation | -[NSArray containsObject:] + 212
4 WeexSDK | -[WXBridgeManager destroyInstance:] + 92
5 WeexSDK | -[WXSDKInstance destroyInstance] + 748
6 BHSmartHome | -[MideaWeexPluginViewController dealloc] + 48
7 libobjc.A.dylib | 0x00000001bea1f000 + 131980
8 CoreFoundation | _CFAutoreleasePoolPop + 28
9 CoreFoundation | ___CFRunLoopRun + 1972
10 CoreFoundation | CFRunLoopRunSpecific + 436
11 GraphicsServices | GSEventRunModal + 100
12 UIKitCore | UIApplicationMain + 212
13 meiju-ios | main (main.m:14)
14 libdyld.dylib | 0x00000001bf2a0000 + 2964

需要对WXBridgeManager对象的instanceIdStack属性做线程安全保护才行。

**Comment by xuyouyang** [comment]
@erduoniba Thank you for your feedback, we will fix it as soon as possible. BTW, welcome to submit PR for us.  :)

**Comment by xuyouyang** [comment]
@erduoniba Now, you'd better not call 'render' or 'destroyInstance'  method in child thread before this bug fixed.

**Comment by erduoniba** [comment]
@xuyouyang ok, thanks very much!

**Comment by wqyfavor** [comment]
Already fixed, we use Theadsafe container for instanceIdStack in WXBridgeManager.
