### ISSUE TITLE
ios 中 自定义component问题：

### ISSUE THREAD

**Issue by MrDragonn** [apache/incubator-weex#1672]
我自定义一个component 需要获取到这个component包含的两个div
weex 定义 bottom-sheet-container 
![image](https://user-images.githubusercontent.com/15952009/47488567-3ebbc100-d877-11e8-911d-1c7b0f52920c.png)

  在原生代码中通过self.subcomponents 来获取包含的view 
![image](https://user-images.githubusercontent.com/15952009/47488641-572bdb80-d877-11e8-9d3b-874a3cee85a0.png)

但是有时候 通过 self.subcomponents 来获取子view  时 只会返回一个view

**Comment by MrDragonn** [comment]
weex 社区没人了吗

**Comment by mahaiyannn** [comment]
麻烦提供完整代码和可复现Demo，谢谢！

**Comment by wqyfavor** [comment]
如果界面无异常的话，那就是取的时候，subcomponents里确实只添加了一个。
可以在自己的component里重写这个方法，获取子component的添加事件，再做逻辑。
- (BOOL)_insertSubcomponent:(WXComponent *)subcomponent atIndex:(NSInteger)index
