### ISSUE TITLE
0.19版本算是正式release了吗?

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#1674]
看到的还是rc版本，很久没有消息了，算是正式发了吗？

看了下目前淘宝应该使用了这个版本，对于外部开发者，是否已经推荐用于生产了？

**Comment by cxfeng1** [comment]
0.19.0 已经完成 apache 的 release 投票了， 这周应该就会正式对外发布

**Comment by chenzefeng09** [comment]
谢谢回复
