### ISSUE TITLE
iOS端无法获取instance.OnCreate渲染回调后View的fram，永远显示是0啊

### ISSUE THREAD

**Issue by stvenjobs** [apache/incubator-weex#1675]

**Comment by Hanks10100** [comment]
Thanks for your contribution, but this issue does not offer enough info, it will be closed for now. Please offer more information according to the issue template, then we can have a further discussion.

你好，这条 issue 提供的信息不足，暂时关掉了。欢迎按照 issue 格式提供更详细的信息，然后继续讨论。
