### ISSUE TITLE
奇怪，为什么安卓上，下面这个color不能覆盖上面的color ；css优先级是怎样的？

### ISSUE THREAD

**Issue by noman798** [apache/incubator-weex#1677]
![image](https://user-images.githubusercontent.com/12876555/47690969-3b378980-dc2b-11e8-8154-ae770d2d56ca.png)

见截图

**Comment by Hanks10100** [comment]
目前 Weex 里的 CSS 还没有实现“优先级”的功能，最终是转换成 JSON 格式的结构交给客户端处理的，某些行为可能和浏览器不一样。 
后续会考虑实现一部分 CSSOM 的能力，到时候能够支持最基本的选择器，也会有优先级的概念。
