### ISSUE TITLE
WXComponentManager's selector rootViewFrameDidChange:  occur to causing a crash

### ISSUE THREAD

**Issue by lixiangsanxun** [apache/incubator-weex#1678]
## Description

WXComponentManager's selector rootViewFrameDidChange:  occur to causing a crash

## Environment
WeexSDK Version:0.18.0
Device info:iOS 12.0.1  iPhoneX

##Crash info
0 WeexSDK | -[WXComponentManager rootViewFrameDidChange:] + 204
-- | --
1 WeexSDK | -[WXComponentManager rootViewFrameDidChange:] + 204
2 WeexSDK | __26-[WXSDKInstance setFrame:]_block_invoke_2 + 64
3 WeexSDK | +[WXComponentManager _performBlockOnComponentThread:] + 224
4 Foundation | ___NSThreadPerformPerform + 340
5 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
6 CoreFoundation | ___CFRunLoopDoSource0 + 88
7 CoreFoundation | ___CFRunLoopDoSources0 + 204
8 CoreFoundation | ___CFRunLoopRun + 1048
9 CoreFoundation | CFRunLoopRunSpecific + 436
10 Foundation | -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
11 WeexSDK | -[WXComponentManager _runLoopThread] + 264
12 Foundation | ___NSThread__start__ + 996
13 libsystem_pthread.dylib | __pthread_body + 308
14 libsystem_pthread.dylib | __pthread_body

I can't reproduce this crash,please check this,thx

**Comment by mahaiyannn** [comment]
Please update to the newest release 0.20.0  and check again.
