### ISSUE TITLE
list中多个video,控制条位置异常

### ISSUE THREAD

**Issue by yikwing** [apache/incubator-weex#1679]
weex-version :0.18.0

应该在视频下方固定位置,现在是呼出控制条,滑动手机控制条就会位置移动

![image](https://user-images.githubusercontent.com/20245290/47700990-55855d80-dc53-11e8-8d70-314cf34c518f.png)

**Comment by yikwing** [comment]
[`gif`](https://s19.aconvert.com/convert/p3r68-cdx67/1yyh0-0tglm.gif)

**Comment by Hanks10100** [comment]
According to the screenshot, I guess this bug happens on the Android platform. Please offer more information about it, such as the live example on http://dotwe.org/vue , steps to reproduce.

**Comment by yikwing** [comment]
http://dotwe.org/vue/8693c53216ac667d482316d0a8212db8

**Comment by YorkShen** [comment]
It seems like there is some problem with the default video which only provide a limited feature. If it is possible, you should use other open source video library instead.  We will look into the problem but there is not a solution yet.

**Comment by YorkShen** [comment]
As described in the [document](https://weex.apache.org/zh/docs/components/video.html), this bug will not be fixed.

> You should consider <video> as demo purpose, and re-implement it your favourite video library.
