### ISSUE TITLE
Gesture event get different value in iOS & Android.

### ISSUE THREAD

**Issue by ssruoyan** [apache/incubator-weex#1681]
## Description
I get a different value in iOS & Android when i bind touch event on an scrollable view.  
And i found difference in iOS and Android source code about touch coordinate calculation: 
In iOS  [Source Code Link](https://github.com/apache/incubator-weex/blob/master/ios/sdk/WeexSDK/Sources/Events/WXComponent%2BEvents.m#L975):
```
CGPoint screenLocation = [touch locationInView:touch.window];
CGPoint pageLocation = [touch locationInView:_component.weexInstance.rootView];
```
In my opinion, weexInstance.rootView will always get a weex container not a touch & scroll view. so i often get a equal value of screenX. Why not use `touch.view`

In Android  [Source Code Link](https://github.com/apache/incubator-weex/blob/master/android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java#L559): 
```
private PointF getEventLocInPageCoordinate(float eventX, float eventY) {
    locEventOffset.set(eventX, eventY);
    locLeftTop.set(0, 0);
    component.computeVisiblePointInViewCoordinate(locLeftTop);

    // here offset scroll length
    locEventOffset.offset(locLeftTop.x, locLeftTop.y);
    return new PointF(WXViewUtils.getWebPxByWidth(locEventOffset.x,component.getInstance().getInstanceViewPortWidth()),
            WXViewUtils.getWebPxByWidth(locEventOffset.y,component.getInstance().getInstanceViewPortWidth()));
  }

 // here computed scrollX， scrollY
 public void computeVisiblePointInViewCoordinate(PointF pointF) {
    View view = getRealView();
    pointF.set(view.getScrollX(), view.getScrollY());
  }
```
In Android, pageX = eventX + scrollX, which is relative to the scroll view.

## Environment

Weex Playground 0.18.0

## Broken Example

Link Address: [http://dotwe.org/vue/a1cb898b0cdfb5044534b1c849e19e66](http://dotwe.org/vue/a1cb898b0cdfb5044534b1c849e19e66)

See difference in iOS & Android.

## Steps to Reproduce
same as above

Thanks

**Comment by ssruoyan** [comment]
Well, i think so.  but `weexInstance.rootView` and `scroller view` are not the same view for iOS,  there is no scroll offset in touch.pageY  calculation.

**Comment by wqyfavor** [comment]
fixed, https://github.com/apache/incubator-weex/pull/2113
