### ISSUE TITLE
toLocaleString显示的时间在安卓上有时会慢一个小时，很奇怪（而且时区是对的）

### ISSUE THREAD

**Issue by noman798** [apache/incubator-weex#1682]
看以下三张截图，时间戳是一样的，时区也一样，但是安卓toLocaleString就快了一个小时。。。
代码
![image](https://user-images.githubusercontent.com/12876555/47770571-db201080-dd1a-11e8-9dbc-5212acbd366a.png)
安卓
![image](https://user-images.githubusercontent.com/12876555/47770562-d3606c00-dd1a-11e8-9b02-00b66898162b.png)
PC浏览器
![image](https://user-images.githubusercontent.com/12876555/47770580-e3784b80-dd1a-11e8-8e8b-0996e4b1e9df.png)

**Comment by zshshr** [comment]
Provide a reproducible example at http://dotwe.org/vue

**Comment by YorkShen** [comment]
Please provide a [demo](http://dotwe.org/vue).

I will close this PR and you can reopen it when your demo is done.

Thanks
