### ISSUE TITLE
Making triangle effect with CSS border failed on android

### ISSUE THREAD

**Issue by AngusFu** [apache/incubator-weex#1683]
## Description

The official demo gives an example of triangle with `<div/>`s and CSS borders, which is intended to make a Vue logo: 

<img src="https://user-images.githubusercontent.com/8180186/47796677-ca45be00-dd5f-11e8-9ae4-75d84ba28426.png" width="50%"/>

However, on my **HUAWEI P20 pro**  and **RedMi**, the result was ——

<img src="https://user-images.githubusercontent.com/8180186/47796611-aaae9580-dd5f-11e8-8cfc-20aa06cb33d0.png" width="50%"/>

## Environment

Weex SDK Version: 0.18.0-beta-3
JS Framework Version: 0.24.5
platform: android
osVersion: 8.1.0
appGroup: WXApp
appName: WXSample
appVersion: 0.18.0-beta-3
deviceModel: CLT-AL01
deviceWidth: 1080
deviceHeight: 2240

Update: Here is another Android phone which also has the same issue ——
<img src="https://user-images.githubusercontent.com/8180186/47798424-4ee60b80-dd63-11e8-8fa3-38b7fd7bbd69.png" width="50%"/>

## Broken Example

Following URL is copied from official playground demo: 

http://dotwe.org/vue/b90dbc5fbecf160a8f6c10b752b44c53

## Steps to Reproduce

1. Download latest playground app from https://weex.apache.org/tools/playground.html.

2. Follow these steps: Exampels > Others > Basic Styles > Triangles

OR just scan the qrcode of the above url:

![image](https://user-images.githubusercontent.com/8180186/47796436-4ee40c80-dd5f-11e8-9850-98337ea2d0a5.png)

**Comment by Hanks10100** [comment]
I wrote that example, but I know it will not render the same result on web and native (both Android and iOS). That's because Weex does not fully support all features of CSS border corners. Maybe I should remove it from the playground app...

This "little" feature will take amount of works to achieve it, because of the platfrom difference between Android, iOS, and Web. We are evaluating it now.

**Comment by YorkShen** [comment]
Not supported yet

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
