### ISSUE TITLE
BoxShadow not working on android phones

### ISSUE THREAD

**Issue by AngusFu** [apache/incubator-weex#1684]
## Description

BoxShadow not working on on **HUAWEI P20 pro**  and **RedMi**.

Expecting:

![image](https://user-images.githubusercontent.com/8180186/47798138-b6e82200-dd62-11e8-91e4-7296886728ef.png)

Result: 

<img src="https://user-images.githubusercontent.com/8180186/47798095-9fa93480-dd62-11e8-8489-6508204406ae.png" width="50%"/>

## Environment

Weex SDK Version: 0.18.0-beta-3
JS Framework Version: 0.24.5
platform: android
osVersion: 8.1.0
appGroup: WXApp
appName: WXSample
appVersion: 0.18.0-beta-3
deviceModel: CLT-AL01
deviceWidth: 1080
deviceHeight: 2240

Update: Here is another Android phone which also has the same issue ——
<img src="https://user-images.githubusercontent.com/8180186/47798424-4ee60b80-dd63-11e8-8fa3-38b7fd7bbd69.png" width="50%"/>

## Broken Example

Following URL is copied from official playground demo: 

dotwe.org/vue/190d8baf578fb7b4efd82f19322a69da

## Steps to Reproduce

1. Download latest playground app from https://weex.apache.org/tools/playground.html.

2. Follow one of these steps: 
   - Exampels > Others > Basic Styles > Box Shaow
   - Exampels > Others > Basic Styles > Watermelon
   - Exampels > Others > Basic Styles > Psudo-classes

**Comment by YorkShen** [comment]
There many box-shadow problem, we will look into it when available. Not sure when we will solve the problem.
* #1720 
* #1988

**Comment by YorkShen** [comment]
As described in the document, [box-shadow](https://weex.apache.org/zh/docs/styles/common-styles.html#%E9%98%B4%E5%BD%B1-box-shadow) is not supported on Android anymore.

The implement of box-shadow relies on a bug of Android, which is fixed by Google. It's time to say goodbye to box-shadow.
