### ISSUE TITLE
Xcode10使用weex create 模板创建使用vue-router之后页面渲染不出来

### ISSUE THREAD

**Issue by allen2437** [apache/incubator-weex#1685]
描述：

weex create 模板创建项目并且使用vue-router，iOS页面白屏

日志信息如下：

2018-11-01 13:17:00.345608+0800 WeexDemo[31830:655950] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
2018-11-01 13:17:00.424978+0800 WeexDemo[31830:656071] <Weex>[info]WXBridgeContext.m:1058, jsLog: START JS FRAMEWORK 0.26.17, Build 2018-06-21 17:37. (Vue: 2.5.13-weex.5, Rax: 0.4.20) START JS FRAMEWORK 0.26.17, Build 2018-06-21 17:37. (Vue: 2.5.13-weex.5, Rax: 0.4.20)
2018-11-01 13:17:00.442631+0800 WeexDemo[31830:656071] <Weex>[info]WXBridgeContext.m:1055, jsLog: Start windmill weex-vue-plugin (0.1.6) framework. Build at 2018-06-21 17:08 __LOG
2018-11-01 13:17:00.498853+0800 WeexDemo[31830:656055] <Weex>[log]WXSDKInstance.m:250, Start rendering page:file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049
2018-11-01 13:17:00.525344+0800 WeexDemo[31830:656071] <Weex>[error]WXMonitor.m:294, [WX_KEY_EXCEPTION_WXBRIDGE] [file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:1369:14] ReferenceError: Can't find variable: process
addRouteRecord@file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:1369:14
file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:1340:19
forEach@[native code]
createRouteMap@file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:1339:17
createMatcher@file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:1560:27
VueRouter@file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:2654:31
file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:211:41
__webpack_require__@file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:22:34
file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:90:33
__webpack_require__@file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:22:34
file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:65:37
global code@file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049:66:12
file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js?random=-1699766049
instanceId:0
options:{
    bundleType = Vue;
    bundleUrl = "file:///Users/ytx/Library/Developer/CoreSimulator/Devices/D5AE179A-B4F0-476D-A495-E41BAABBD7E5/data/Containers/Bundle/Application/142DC4CD-15F2-4864-8194-EEB5C346F851/WeexDemo.app/bundlejs/index.js";
    debug = 1;
    env =     {
        appName = WeexDemo;
        appVersion = "1.8.3";
        deviceHeight = 1334;
        deviceModel = "x86_64";
        deviceWidth = 750;
        logLevel = log;
        osName = iOS;
        osVersion = "12.0";
        platform = iOS;
        scale = 2;
        weexVersion = "0.18.0";
    };
}
data:(null)
(
    service,
    clearTimeout,
    setInterval,
    clearInterval,
    services,
    BroadcastChannel,
    weex,
    setTimeout,
    Vue,
    getJSFMVersion,
    "__WEEX_CALL_JAVASCRIPT__"
)

**Comment by weenta** [comment]
got the same problem

**Comment by allen2437** [comment]
@Hanks10100 使用weex create 模板创建之后使用的WeekSDK是0.19.0的版本会导致页面无法渲染，我在pod中将WeexSDK 改成0.18.0.3之后，页面就能渲染出来了

**Comment by allen2437** [comment]
@weenta 将podfile文件中WeexSDK版本改成pod 'WeexSDK','~> 0.18.0.3'应该就可以

**Comment by weenta** [comment]
果然改了后就可以正常渲染了，多谢了 @allen2437

**Comment by erha19** [comment]
@allen2437 @weenta @weenta see https://github.com/apache/incubator-weex/issues/1686#issuecomment-438207973.

**Comment by erha19** [comment]
@Hanks10100 Duplicate issues can be closed.
