### ISSUE TITLE
新建项目启动白屏，process.env.NODE_ENV找不到

### ISSUE THREAD

**Issue by qzcsgs** [apache/incubator-weex#1686]
运行在 `iPhone X 12.0` ，中启动白屏，经过排查发现是 `bundle/index.js` 中的process.env.NODE_ENV找不到，手动将 `bundlejs` 中的全部 `process.env.NODE_ENV` 替换为字符串就正常了，如何解决？

`macOS v10.13.4`
`weex v1.3.11`
`weexpack : v1.2.7`
`weex-builder : v0.4.0`
`weex-previewer : v1.5.1`

按照官网的教程， 依次执行
`weex create awesome-app`
`cd awesome-app`
`npm install`
`weex platform add ios`
`weex run ios`

**Comment by allen2437** [comment]
@qzcsgs 将podfile文件中WeexSDK版本改成pod 'WeexSDK','~> 0.18.0.3'应该就可以

**Comment by qzcsgs** [comment]
> @qzcsgs 将podfile文件中WeexSDK版本改成pod 'WeexSDK','~> 0.18.0.3'应该就可以

非常感谢，出问题的版本为0.19.0，修改为0.18.0.3就解决了。再次感谢。

**Comment by Hanks10100** [comment]
Same with #1685

**Comment by foyel** [comment]
@Hanks10100 现在IOS的Weex Playground被升级了不能使用，官方除了删打包文件里的process，有没有什么解决方法啊

**Comment by erha19** [comment]
@foyel @qzcsgs The official `webpack` configuration has been updated, and the `process .env.NODE_ENV` variable will be automatically replaced. You can re-run the `weex create` command to create a template and put `configs` folder (which has some webpack config files) into your old project to replace the old configuration.

commit: https://github.com/weex-templates/webpack/commit/f7c7d04d30b734be9e1c2b54df4a8ad723f5b988
