### ISSUE TITLE
新发布的Android 0.19.0.3版本获取能检测到但是编译获取不到

### ISSUE THREAD

**Issue by topcloud-xx** [apache/incubator-weex#1687]
implementation "com.taobao.android:weex_sdk:0.19.0.3"

编译是获取不到这个版本的SDK，旧的“0.18.0”版本就可以正常编译。

iOS版本的“0.19.0”版本：
pod 'WeexSDK', '~> 0.19.0' 也是正常的。

谢谢！

**Comment by juneleaf** [comment]
the aar file name is weex_sdk-0.19.0.4-release.aar
not weex_sdk-0.19.0.4.aar
i guess this is reason
but i dont know how to get 
https://jcenter.bintray.com/com/taobao/android/weex_sdk/0.19.0.4/

**Comment by YorkShen** [comment]
We have fixed this problem by publish a new version named 0.19.0.4

**Comment by myeveryheart** [comment]
implementation "com.taobao.android:weex_sdk:0.19.0.4"
依旧获取不到。

**Comment by myeveryheart** [comment]
@YorkShen

**Comment by topcloud-xx** [comment]
@YorkShen 问题依然存在，依旧获取不到。
https://jcenter.bintray.com/com/taobao/android/weex_sdk/0.19.0.4/目录下的包命名造成的吧
“weex_sdk-0.19.0.4-release.aar”应该是“weex_sdk-0.19.0.4.aar”才合适吧

**Comment by voids** [comment]
implementation 'com.taobao.android:weex_sdk:0.19.0.4:release@aar'

**Comment by myeveryheart** [comment]
@voids 有效，感谢！但同步下来的不是java源码，没办法断点了。

**Comment by myeveryheart** [comment]
release版本会闪退
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
debug可以用。

**Comment by voids** [comment]
@myeveryheart 一样，只能用debug版本

**Comment by YuanClouds** [comment]
> @myeveryheart 一样，只能用debug版本

release版本还不解决吗？有点急

**Comment by YorkShen** [comment]
Sorry for the delay, you can use 0.19.0.7 now. I have checked it.

**Comment by thirtyyuan** [comment]
I got same problem by use 0.19.0.7.
 ![Same Problem at 0.19.07](https://ws4.sinaimg.cn/large/006tNbRwgy1fy4tyu2hwrj31gy07yq4m.jpg)

**Comment by myeveryheart** [comment]
@thirtyyuan It works. Try 
`api 'com.taobao.android:weex_sdk:0.19.0.7'`
And you can use this library for easy.
https://github.com/aygtech/weexbox-android-library

**Comment by thirtyyuan** [comment]
I user `implementation 'com.taobao.android:weex_sdk:0.19.0.7'`, and it's work now. Maybe it's a network error?

**Comment by myeveryheart** [comment]
@thirtyyuan I think it is.
