### ISSUE TITLE
degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

### ISSUE THREAD

**Issue by guozai0806** [apache/incubator-weex#1688]
4.4.2的设备运行weex playground 后 里面显示degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1。

**Comment by Hanks10100** [comment]
页面被降级了，可能是不支持这么低的 Android 版本。

如果还有疑问，欢迎按照 issue 格式提供更多信息。

**Comment by tuoxie007** [comment]
我在 Andriod 9 上也遇到了

```
品牌 HUAWEI
机型 BKL-AL20
分辨率 2040*1080
操作系统 Android 9
```
