### ISSUE TITLE
storage 模块太简陋了，能提供类似web上indexeddb接口的数据库模块吗？

### ISSUE THREAD

**Issue by noman798** [apache/incubator-weex#1689]
storage 模块太简陋了，能提供类似web上indexeddb接口的数据库模块吗？
https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API

**Comment by Hanks10100** [comment]
`IndexedDB` 的确是个很好用的 API，但是相对于 Weex SDK 本身而言可能重了一些，可以写一个独立的模块注册进来。
