### ISSUE TITLE
IOS weex版本19.0和19.1使用weex-UI中的wxc-popup无法正常使用

### ISSUE THREAD

**Issue by joinzhang** [apache/incubator-weex#1690]
在使用weex0.19.0和0.19.1测试时发现，weexUI的wxc-popup弹层组件无法弹出,
老版本的0.18.0可以正常使用。

希望能尽早解决。
谢谢！！

**Comment by Hanks10100** [comment]
Please offer more information according to the issue template.

> 请按照 issue 模板提供更多信息。

**Comment by Hanks10100** [comment]
This issue is closed because of not giving a response for a long time. If you still confused with this question, you can file a new issue according to the issue template with enough information.
