### ISSUE TITLE
0.19.0+ Component 扩展 如何设置组件flex-direction默认值是row左右布局？

### ISSUE THREAD

**Issue by kuaifan** [apache/incubator-weex#1691]
0.19.0+ Component 扩展 如何设置组件flex-direction默认值是row左右布局？
之前0.18.0的时候可以通过WXDomObject修改，但是升级到19以后没有这个了，找到好久没有找到其他方法，希望可以得到解答。

**Comment by kuaifan** [comment]
[https://github.com/apache/incubator-weex/issues/1701](https://github.com/apache/incubator-weex/issues/1701)

**Comment by miomin** [comment]
DomObject is sunk to WeexCore using C++, and the Weex team will update the adaptation document in two days.

**Comment by miomin** [comment]
Please see this document：http://weex-project.io/cn/guide/extend-android.html#0-19-component-kuo-zhan-gua-pei-wen-dang
