### ISSUE TITLE
weex页面在客户端上的刷新问题

### ISSUE THREAD

**Issue by songxing10000** [apache/incubator-weex#1696]
## Description

在使用命令 `npm run dev & npm run serve` 后，保存vue文件，网页里打开的是可以实时自动刷新的。
但是在iOS上展示时，页面没有刷新。通过命令 `npm run dev & npm run serve`，保存后，一直没找到正确的监听方式地址。
```objc
NSString *wsport = queryDict[@"wsport"] ?: @"8082";
    NSURL *socketURL = [NSURL URLWithString:[NSString stringWithFormat:@"ws://%@:%@", url.host, wsport]];
    controller.hotReloadSocket = [[SRWebSocket alloc] initWithURL:socketURL protocols:@[@"echo-protocol"]];
    controller.hotReloadSocket.delegate = controller;
    [controller.hotReloadSocket open];
```
ip是本机调试的ip，端口号从8080到8084都试过了，一直连接失败，报错不是拒绝连接，就是超时。
求解，iOS上能像网页那样实时刷新吗

**Comment by songxing10000** [comment]
目前解决的笨办法，在开发阶段，还是大大提升了效率。
```objc
NSString *ip = @"172.16.69.154";
    NSString *port = @"8081";
    NSURL *socketURL = [NSURL URLWithString:[NSString stringWithFormat:@"ws://%@:%@/sockjs-node/websocket", ip, port]];
    self.hotReloadSocket = [[SRWebSocket alloc] initWithURL:socketURL protocols:@[@"echo-protocol"]];
    self.hotReloadSocket.delegate = self;
    [self.hotReloadSocket open];
```
```objc
- (void)webSocket:(SRWebSocket *)webSocket didReceiveMessage:(id)message
{
    /// 这里暂时用的type hash来区分
    if([message hasPrefix:@"{\"type\":\"hash\""]) {
        [self refreshWeex];
    }
}
```

**Comment by erha19** [comment]
@songxing10000 that's a necessary feature for the weex develop, and we are currently adjusting the code for the playground, and for the manual launch we will also cover this feature on `weex-toolkit@2.x`.

For now, we suggest you using `weex run [ios/android]` command to preview your page on native device, it will support the hot-reload feature.

Also, you can use the weex VSCode extension to do this job, it's easier for you to run the device.

See: https://github.com/weex-cli/vscode-weex.
