### ISSUE TITLE
请教几个问题 安卓上  callback.invoke 是同步还是异步的？ callback.invoke是不是只能调用一次？

### ISSUE THREAD

**Issue by noman798** [apache/incubator-weex#1697]
请教几个问题 

安卓上

1.  callback.invoke 是同步还是异步的？ 

2. callback.invoke是不是只能调用一次？

**Comment by liushengyi** [comment]
多看源码：
public interface JSCallback {
  /**
   * invoke javascript callback method, this method will destoryed after invoke.
   * @param data
   */
  void invoke(Object data);

  /**
   * invoke javascript callback method and keep callback alive for later use.
   * @param data
   */
  void invokeAndKeepAlive(Object data);
}

**Comment by Hanks10100** [comment]
@liushengyi 回答的很正确。

1. 回调都是异步的。
2. 默认回调只触发一次，传递 keepAlive 参数可以触发多次。
