### ISSUE TITLE
升级0.19后WXDomObject找不到

### ISSUE THREAD

**Issue by jasonhe88** [apache/incubator-weex#1701]
如题

还有很多其他Dom相关的类都没有暴露出来，比如 ImmutableDomObject， DOMActionContext，，，
导致以前写的Component编译通不过

iOS里也有一些Component相关的定义和属性不见了，比如CSS_WIDTH定义， 属性 cssNode

为什么不能和前一个版本保持兼容？

**Comment by kuaifan** [comment]
同问啊
[https://github.com/apache/incubator-weex/issues/1691](https://github.com/apache/incubator-weex/issues/1691)

**Comment by topcloud-xx** [comment]
看源码好像是由新的BasicComponentData替换了WXDomObject

**Comment by kuaifan** [comment]
@topcloud-xx  
BasicComponentData只替换了，但是里面只有部分的样式，width、height、flex-direction等都是没有的

**Comment by kuaifan** [comment]
@jasonhe88 找到解决方案了吗？

**Comment by jasonhe88** [comment]
> @jasonhe88 找到解决方案了吗？

没有找到解决方法啊，如果升级的话近十个Component要重写，没法升级，先缓缓

**Comment by miomin** [comment]
DomObject is sunk to WeexCore using C++, and the Weex team will update the adaptation document in two days.

**Comment by miomin** [comment]
Please see this document：http://weex-project.io/cn/guide/extend-android.html#0-19-component-kuo-zhan-gua-pei-wen-dang

**Comment by miomin** [comment]
> 如题
> 
> 还有很多其他Dom相关的类都没有暴露出来，比如 ImmutableDomObject， DOMActionContext，，，
> 导致以前写的Component编译通不过
> 
> iOS里也有一些Component相关的定义和属性不见了，比如CSS_WIDTH定义， 属性 cssNode
> 
> 为什么不能和前一个版本保持兼容？

Please see this document：http://weex-project.io/cn/guide/extend-android.html#0-19-component-kuo-zhan-gua-pei-wen-dang

**Comment by jasonhe88** [comment]
> > 如题
> > 还有很多其他Dom相关的类都没有暴露出来，比如 ImmutableDomObject， DOMActionContext，，，
> > 导致以前写的Component编译通不过
> > iOS里也有一些Component相关的定义和属性不见了，比如CSS_WIDTH定义， 属性 cssNode
> > 为什么不能和前一个版本保持兼容？
> 
> Please see this document：http://weex-project.io/cn/guide/extend-android.html#0-19-component-kuo-zhan-gua-pei-wen-dang

非常感谢！会尝试进行新版本升级。

发现文档里只有Android的升级说明，不知道IOS的API是否也会有文档出来？

**Comment by wqyfavor** [comment]
0.19版本开始我们更换了排版引擎，所以需要一些适配，可以参考文档 http://weex-project.io/cn/guide/extend-ios.html#huo-qu-zu-jian-de-css-yang-shi-xin-xi

**Comment by kuaifan** [comment]
@jasonhe88 兄弟，你按官方的文档解决了吗

**Comment by jasonhe88** [comment]
> @jasonhe88 兄弟，你按官方的文档解决了吗

还没有呢，忙，等有空再弄
