### ISSUE TITLE
iOS。带透明度的渐变色在playGround中显示正常，真机扫码显示不正常

### ISSUE THREAD

**Issue by stvenjobs** [apache/incubator-weex#1703]
在playGround中渐进透明度为从左到右。
而在真机扫码中渐进透明度变为从左到中点从百分0到百分百，再从中点到右百分百到百分0

**Comment by Hanks10100** [comment]
Thanks for your contribution, please offer more information according to the issue template, in particular, provide an example and steps to reproduce it.

> 请提供可复现问题的例子。 http://dotwe.org/vue

**Comment by Hanks10100** [comment]
This issue is closed because of not giving a response for a long time. If you still confused with this question, you can file a new issue according to the issue template with enough information.
