### ISSUE TITLE
weex ios transform 不生效

### ISSUE THREAD

**Issue by KimCongMax** [apache/incubator-weex#1704]
原本是可以的  后来我重新weex run ios 运行项目时 整个项目内的transform就不生效了  我尝试过重新 create 一个新项目 去尝试 发现也是不行，把xcode 卸载重装也是不行。在安卓上跑是没问题的，这是什么问题导致的呢

**Comment by hjhcn** [comment]
@KimCongMax 0.19.* 版本确实有这个问题，
https://github.com/apache/incubator-weex/blob/0.19.0.1/ios/sdk/WeexSDK/Sources/Component/WXTransform.m#L263
可以通过实现WXConfigCenterProtocol绕过，或者依赖master

**Comment by Hanks10100** [comment]
Thanks for your contribution, please offer an example and steps to reproduce it.

> 请提供可复现问题的例子。 http://dotwe.org/vue
