### ISSUE TITLE
white-space & word-break 在安卓8.0手机上不生效

### ISSUE THREAD

**Issue by flameOvO** [apache/incubator-weex#1707]
## Description

给text标签添加了
white-space: nowrap;
word-break: break-all;
在安卓手机上没有生效
## Environment

Android 8.0
## Broken Example

http://dotwe.org/vue/5a3ca73bc45171d3dd3e874cd458b774
## Steps to Reproduce
运行上面的例子然后weex-playground扫

**Comment by YorkShen** [comment]
Not support. The supported style is listed in http://weex-project.io/cn/wiki/text-styles.html.

**Comment by ulivz** [comment]
So how can we make the text do not break into next line?
