### ISSUE TITLE
0.19.0 webpack sockejs.bundle.js document.getElementsByTagName("head")

### ISSUE THREAD

**Issue by michaeldong** [apache/incubator-weex#1714]
启动了Webpack 的hot reload功能后，weex sdk会提示getElementsByTagName is not funtion 错误。
怀疑是js rax runtime里没有桥接这个方法，或者其他的一些DSL转换导致的？

**Comment by Hanks10100** [comment]
Weex 不含 `getElementsByTagName` 这类 DOM 接口。

http://weex-project.io/cn/wiki/platform-difference.html#weex-huan-jing-zhong-mei-you-dom
