### ISSUE TITLE
BoxShadowUtil  方法 draw(Canvas canvas) 行 canvas.clipRect  在android 9.0 报错

### ISSUE THREAD

**Issue by ho2xing** [apache/incubator-weex#1720]
BoxShadowUtil    类 draw 报错

@Override
    public void draw(Canvas canvas) {
      ....
      **canvas.clipRect(newRect,** Region.Op.REPLACE);  //此行报错，
      ...
    }
错误信息："Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed"
原因：
 private static void checkValidClipOp(@NonNull Region.Op op) {
        if (sCompatiblityVersion >= Build.VERSION_CODES.P
                && op != Region.Op.INTERSECT && op != Region.Op.DIFFERENCE) {
            throw new IllegalArgumentException(
                    "Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed");
        }
 }

**Comment by gubaojian** [comment]
may be, you can submit a pull request to fix the problem. and to be an weex committer

**Comment by LazyDemo** [comment]
Does anybody fixed this bug？I use the weex_sdk(018)also has this problem...

**Comment by YorkShen** [comment]
#2279

**Comment by YorkShen** [comment]
Closed by #2545
