### ISSUE TITLE
render eroor: border in <scroller>

### ISSUE THREAD

**Issue by Yhspehy** [apache/incubator-weex#1728]
## Description

Render error: border-top, border-left, border-bottom, border-right in <scroller> is different.

if i use border-top, it get border for four sides. But if i use border-left , border-right or border-bottom, it can't rendered as expected.
## Environment

ios, iphonexs

## Broken Example

[online editor of Weex](http://dotwe.org/vue/8c337a6cae97c0be983d1c00fac56b1b)

**Comment by Hanks10100** [comment]
It works fine for me. http://dotwe.org/vue/539c38f46c2d232009b76e8d6c0ce294

**Comment by Yhspehy** [comment]
@Hanks10100 i mean using border in <scroller> instead of <div>

**Comment by doumafang** [comment]
if u need to use border in scroller, you may need add div as scroller's wrapper.
u can see demo here:http://dotwe.org/vue/1b5c2dd85b197ed683b7038db1bef91d
