### ISSUE TITLE
请问weex如何利用recycle-list实现cell的折叠与展开效果？？？

### ISSUE THREAD

**Issue by LionBuer** [apache/incubator-weex#1735]

**Comment by Hanks10100** [comment]
折叠展开这种效果，在前端里就可以实现。

**Comment by Hanks10100** [comment]
#1736

**Comment by LionBuer** [comment]
@Hanks10100 我是长列表，请问直接使用前端实现，不会出现内存暴增吗？

**Comment by enjoyinwind** [comment]
同问，weex社区就这样解决问题的。。。

**Comment by YorkShen** [comment]
According to [Weex Community guideline](https://weex.io/guide/contribute/how-to-contribute.html#ask-or-answer-questions), Github issue is for bug reporting, not such usage discussion. You may ask this question to the [mailing list](https://weex.io/guide/contribute/how-to-contribute.html#ask-or-answer-questions).
