### ISSUE TITLE
playground 代码运行正常，真机扫码不正常！！！！

### ISSUE THREAD

**Issue by LionBuer** [apache/incubator-weex#1736]
## Description
我在playground编写了一段代码，在playground运行，点击cell会有相应的效果，但是当用真机扫码的时候点击cell的时候没有任何反应

## Environment

$ weex -v
   v1.3.8
 - weexpack : v1.2.5
 - weex-debugger : v1.1.4
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

Weex SDK Version: 0.19.0
DeviceModel: iPhone9,1

## Broken Example

http://dotwe.org/vue/b91a6bcd3a7bdb931798a8bd0054f62a

**Comment by wqyfavor** [comment]
我这边用playground扫码无法复现，应该已经修复了。麻烦用最新版试一下，谢谢。
