### ISSUE TITLE
Weex Playground App中的touch left move示例iOS版本中却没有效果

### ISSUE THREAD

**Issue by topcloud-xx** [apache/incubator-weex#1737]
Weex Playground App 中的示例【其他】--【Touch事件】中的touch left move示例在Android版本中左滑动有效果，但是iOS版本中却没有效果。

两个Weex Playground App都是升级到最新版本，weex SDK version都是0.19.0。

**Comment by doumafang** [comment]
We will fix this bug ASAP.

**Comment by wqyfavor** [comment]
没找到这个示例，麻烦提供一下dotwe的链接。请用最新版先试一下还有没有问题了。谢谢
