### ISSUE TITLE
Android 0.19.0版本引入jacoco  的问题你们不打算解决下了吗，我是服了，牛逼。

### ISSUE THREAD

**Issue by joy2helloworld** [apache/incubator-weex#1738]

**Comment by voids** [comment]
同问，用release版本的aar会直接崩溃，报错如下
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;

**Comment by shushu2013** [comment]
试试把 weex 的 build.gradle 中 release 选项的 testCoverageEnabled 设为 false

```
buildTypes {
        release {
            minifyEnabled false
            testCoverageEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "boolean", "ENABLE_TRACE", "false"
            consumerProguardFiles 'proguard-rules.pro'
        }

        debug {
            buildConfigField "boolean", "ENABLE_TRACE", "true"
            jniDebuggable true
            debuggable true
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
```
[https://github.com/apache/incubator-weex/blob/0.19.0.2/android/sdk/build.gradle](https://github.com/apache/incubator-weex/blob/0.19.0.2/android/sdk/build.gradle)

**Comment by YuanClouds** [comment]
> 同问，用release版本的aar会直接崩溃，报错如下
> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;

@voids 这个问题挺严重的，还不处理么 = =

**Comment by voids** [comment]
@YuanClouds 我不是weex开发组的，我也在等他们处理，不想从源码编译

**Comment by voids** [comment]
@YorkShen  看到testCoverageEnabled true是你加上的，能否去掉？我看到之前的版本这句都在debug里，实在不想从源码编译了，环境弄起来很麻烦

**Comment by zshshr** [comment]
#1779

**Comment by joy2helloworld** [comment]
改了配置后，发布新的办了吗？@zshshr

**Comment by joy2helloworld** [comment]
> @joy2helloworld 我看到还没发，耐心等吧，最后我还是装环境自己编译了aar，用master分支有内存泄漏，checkout到0.19.0.2这个tag编译出来的没问题

好吧，我还是接着用0.18.0吧。。
