### ISSUE TITLE
refresh组件的pullingdown事件中的pullingDistance属性在iOS与Android不一致？？

### ISSUE THREAD

**Issue by sinbadmaster** [apache/incubator-weex#1742]
pullingdown事件中的pullingDistance属性取值在iOS端为负值但是在安卓端为正值

**Comment by fishyumiao** [comment]
确实，我也碰到了，我把ios端的值改为取绝对值了

**Comment by zshshr** [comment]
@sinbadmaster Please provide a reproducible demo on the site of http://dotwe.org/vue/

**Comment by jerryyum** [comment]
文件 WXScrollerComponent.mm
方法 - (void)scrollViewDidScroll:(UIScrollView *)scrollView
下面这一段代码中，REFRESH_PULLINGDISTANCE 下拉时返回的是负值，而在Android中是正值
```
    [_refreshComponent pullingdown:@{
             REFRESH_DISTANCE_Y: @(fabs((scrollView.contentOffset.y - _lastContentOffset.y)/scaleFactor)),
             REFRESH_VIEWHEIGHT: @(_refreshComponent.view.frame.size.height/scaleFactor),
             REFRESH_PULLINGDISTANCE: @(scrollView.contentOffset.y/scaleFactor),
             @"type":@"pullingdown"
    }];
```

**Comment by wqyfavor** [comment]
已修复，https://github.com/apache/incubator-weex/pull/2109

**Comment by sinbadmaster** [comment]
@wqyfavor 多谢修复这个问题。 @jerryyum 也多谢提供了具体问题位置。
