### ISSUE TITLE
IOS  , real device，keyboard stays so close to input

### ISSUE THREAD

**Issue by Yhspehy** [apache/incubator-weex#1745]
## Description

IOS  , real device，keyboard stays so close to input when the input focus.

## Environment

IOS12.1,  IphoneXS

## Broken Example

In weex playground, there is some distance (touchBarHeight).
[Weex Playground](http://dotwe.org/vue/db7833f76a9c7314e21bf6e4ad3296b7)

But in real device, there is null. Can i use a parameter to set this distance to improve the experience.

![image](https://user-images.githubusercontent.com/22761730/48393573-1d9a1200-e74b-11e8-91a4-e118211f80fe.png)

![image](https://user-images.githubusercontent.com/22761730/48393582-238ff300-e74b-11e8-8254-2efe3f1fcb43.png)

**Comment by wqyfavor** [comment]
Which version is WeexSDK?

**Comment by Yhspehy** [comment]
@wqyfavor   0.18

**Comment by wqyfavor** [comment]
we add upriseOffset attribute for input in master.
