### ISSUE TITLE
希望添加麦克风读取功能

### ISSUE THREAD

**Issue by mythbobo** [apache/incubator-weex#1747]
麦克风的使用频率还是很高的。希望能作为基础模块接口调用。非常感谢！

**Comment by Hanks10100** [comment]
这个功能可以用独立的模块来实现，Weex SDK 为了保持精简，未必适合内置此功能。

参考：
+ http://weex-project.io/cn/guide/extend-android.html
+ http://weex-project.io/cn/guide/extend-ios.html
