### ISSUE TITLE
IOS  stream get方法不支持graphql语法

### ISSUE THREAD

**Issue by shawon1220** [apache/incubator-weex#1748]
使用Weex playground app 测试 IOS  stream get方法不支持graphql语法，android可以。

类似请求 '/graphql?query={userInfo{id,userName}}' 返回 {"status":-1,"ok":false}

**Comment by Hanks10100** [comment]
很可能与网络库或者服务端接口有关，请提供例子和复现问题的步骤。

**Comment by shawon1220** [comment]
@Hanks10100  thks, 目前我们都改成POST了，post没问题。另外playground新版本不支持调试了吗？找不到顶部那个小按钮了。

**Comment by zshshr** [comment]
@shawon1220 Please provide a reproducible demo or screenshot
