### ISSUE TITLE
recycle-list里面的cell-slot组件点击问题

### ISSUE THREAD

**Issue by YuanClouds** [apache/incubator-weex#1758]
## Description

recycle-list里面的cell-slot组件点击问题：模板的组件有@click事件，但是发现点击事件不能传递任何参数
，一直是空

## Environment
weex 版本 1.3.8

**Comment by cyabc** [comment]
不支持slot吧

**Comment by YuanClouds** [comment]
> 不支持slot吧

emmm，是slot里面的自定义组件点击

**Comment by Hanks10100** [comment]
请在 http://dotwe.org/ 上提供一个可复现的例子，并且介绍一下复现步骤。

> Weex 目前发布的最高版本是 0.19，还没到 1.x …… 建议再确定一下平台和 SDK 版本

**Comment by snice** [comment]
我也遇到这个问题，示例如下
list:  http://dotwe.org/vue/b062c66787944d15eb63b659f388df90
recycle-list:  http://dotwe.org/vue/43bea46240bba1e4ee34b057a6b818ac

代码：Floor.vue 中click方法

list 可以获取参数
recycle-list 不可以

问题环境：原生平台

**Comment by snice** [comment]
> 请在 http://dotwe.org/ 上提供一个可复现的例子，并且介绍一下复现步骤。
> 
> > Weex 目前发布的最高版本是 0.19，还没到 1.x …… 建议再确定一下平台和 SDK 版本

例子已提供

**Comment by gubaojian** [comment]
可以把里面内容展开试试
