### ISSUE TITLE
 header or sticky in cell and recycle-list is useless

### ISSUE THREAD

**Issue by Yhspehy** [apache/incubator-weex#1766]
## Description

First of all, i have some date like:
```js
data = [
    {
        header: 'need to be rendered as a header',
        list: ['a', 'b', 'c']
    },
    .......
]
```

If i apply it in scroller, it's ok. However the performance is not really perfect especially the data is huge. So i decide to use list or recycle-list. But when i use it in list or recycle-list , it is useless. But in web , it's ok.

Of course, if i use header under the list instead of cell, i works. But i need to write it one by one and i need to know the length of data, it is really ugly.

So i'm really looking forward to using header in cell or recycle-list.

## Environment

iOS, iPhonesXs(12.1)

## Broken Example

[list example](http://dotwe.org/vue/bbde28cf42af89c4d4a2a15cdccdd6dc)
[recycle-list example](http://dotwe.org/vue/79af911f456beaf63cbad0dce6cf8011)

**Comment by doumafang** [comment]
Sorry，recycle-list has not support 'header' and 'sticky'
