### ISSUE TITLE
z-index 最近有没有计划要支持？

### ISSUE THREAD

**Issue by moketao** [apache/incubator-weex#1772]
这个特性还是很重要的，很多特效依赖这个 z-index 。
相关测试链接如下：

http://dotwe.org/vue/c56ea7664afbdcc7ff848950cb2367f4
这个测试，在 web 中有效，但在 ios 的 weex playground 0.19.0 中，无法改变红色方块的层级。

http://dotwe.org/vue/89584de02a16129aa93a511c63b539f7
这个测试，在 web 和 ios 的 weex playground 0.19.0 中都没办法改变红色方块的层级。

**Comment by zshshr** [comment]
There is no plan to support the z-index attribute in the short term. Try a circumvention scheme, such as re-adding and deleting.

**Comment by Hanks10100** [comment]
I think `z-index` is really useful, and can't be achieved by other css styles. I suggest to have a plan to support it.

**Comment by YorkShen** [comment]
Not supported yet.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
