### ISSUE TITLE
video组件能否支持rtsp,rtmp之类的直播流播放？

### ISSUE THREAD

**Issue by mythbobo** [apache/incubator-weex#1783]
如题，目前好像只支持mp4的播放。。能否增加这种直播流的播放功能呢？

**Comment by zshshr** [comment]
There is no plan support in the short term. You are welcome to submit pr

**Comment by mythbobo** [comment]
> There is no plan support in the short term. You are welcome to submit pr

没有android，ios的开发经验。。
