### ISSUE TITLE
Vue.use( plugin ) 全局api在native端没有生效

### ISSUE THREAD

**Issue by weenta** [apache/incubator-weex#1788]
Vue的全局api `Vue.use( plugin )`在web端能正常使用，但是在native端无效，weex有提供类似的接口么？

**Comment by cyabc** [comment]
不支持这种模式的

**Comment by snice** [comment]
我的demo可以支持，https://github.com/snice/easy-weex-demo/blob/master/src/global.bui.js

**Comment by Hanks10100** [comment]
In most cases, Weex is a multiple-page app, not an SPA. It means the `Vue` variable is different in different pages. (http://weex-project.io/cn/guide/use-vue.html#shang-xia-wen)

You should register your plugin in each pages, not just once.
