### ISSUE TITLE
[android] can not read the source code

### ISSUE THREAD

**Issue by myeveryheart** [apache/incubator-weex#1808]
when I use the 0.18.0, I can click into the source code.
But in 0.19.x, it seems that AS can't download the source.
I think is the name problem.
0.18.0:
```
weex_sdk-0.18.0-sources.jar
weex_sdk-0.18.0.aar
```
0.19.5:
```
weex_sdk-0.19.0.5-debug.aar
weex_sdk-0.19.0.5-release.aar
weex_sdk-0.19.0.5-sources.jar
```

**Comment by YorkShen** [comment]
#1694 

Sorry the delay, you can use `compile 'com.taobao.android:weex_sdk:0.19.0.7'`. I have checked, it worked well
