### ISSUE TITLE
list和scroller能否添加支持动态设置禁止滚动

### ISSUE THREAD

**Issue by kang558** [apache/incubator-weex#1809]
## list和scroller能否添加支持动态设置禁止滚动

使用场景还是很多的，比如长按区域拖动，会受到list上下滚动影响，比如K线左右滑动，也会受到影响

**Describe the solution you'd like**
可动态设置禁止滚动，做各种拖动就很好操作了

**Describe alternatives you've considered**
暂无

**Comment by gubaojian** [comment]
scrollable="false"  放到list的属性上面即可
