### ISSUE TITLE
如何动态的移除和添加一个普通 div ？

### ISSUE THREAD

**Issue by moketao** [apache/incubator-weex#1810]
http://dotwe.org/vue/c85357788a5b0d4456b24898304e0ccf
i use remove and append . it work in web , but fall in weex playground.
can you write some example code to show how to readding and deleting？

because z-index is not support for now. i need some funcion like remove and append:
https://github.com/apache/incubator-weex/issues/1772#issue-381927735

**Comment by zshshr** [comment]
http://dotwe.org/vue/ca5ef0dd40e57d3aa6c3ec8f24752a3d
