### ISSUE TITLE
[Android] Official image component dose not trigger @load method On Android

### ISSUE THREAD

**Issue by Bob-huang-gdut** [apache/incubator-weex#1815]
[Android] Official image component dose not trigger @load method On Android
![image](https://user-images.githubusercontent.com/26543174/48997809-213a8980-f18c-11e8-8021-dfbe51b6d5fc.png)
![image](https://user-images.githubusercontent.com/26543174/48997840-34e5f000-f18c-11e8-9bd6-204f369a61a1.png)

**Comment by lucky-chen** [comment]
hi , @Bob-huang-gdut 

i wrote a test demo : http://dotwe.org/vue/7d4f3fb04a31df22632dc3dc21c1d72c
it works for me  (master branch )

check code `_load($event)` 
- method name is right ?
- method  impl has js exception ?

**Comment by YorkShen** [comment]
Work for me, please open another issue if this is reproducible
