### ISSUE TITLE
用了weex被AppStore下架了

### ISSUE THREAD

**Issue by Luis-X** [apache/incubator-weex#1823]
2018年11月27日 上午8:04
发件人 Apple

Hello,

We are writing to let you know about new information regarding your app currently live on the App Store.

Upon re-evaluation, we found that your app is not in compliance with the App Store Review Guidelines. Specifically, we found:

Performance - 2.5.2
Your app, extension, or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with App Store Review Guideline 2.5.2 and section 3.3.2 of the Apple Developer Program License Agreement.

For this reason, your app will be removed from sale on the App Store at this time.

Deliberate disregard of the App Store Review Guidelines and attempts to deceive users or undermine the review process are unacceptable and is a direct violation Section 3.2(f) of the Apple Developer Program License Agreement. Continuing to violate the Terms & Conditions of the Apple Developer Program will result in the termination of your account, as well as any related or linked accounts, and the removal of all your associated apps from the App Store.

Future submissions of this app may require a longer review time, and this app will not be eligible for an expedited review.

If you have any questions about this information, please reply to this message to let us know.

Best regards,

App Store Review

使用了weex动态分发页面，被下架了，有遇到相同情况的吗？

**Comment by zshshr** [comment]
Do you still have other dynamic fixes? Like js patch? Weex did not appear to be removed

**Comment by wqyfavor** [comment]
你们最近有发布改动非常大的页面吗？应用都上架了，怎么会被苹果发现？

**Comment by Luis-X** [comment]
> Do you still have other dynamic fixes? Like js patch? Weex did not appear to be removed

we app not used JSPatch. only use weex

**Comment by wqyfavor** [comment]
可以给苹果回复邮件，说明自己的App并没有在应用审核后，利用任何动态能力修改应用行为。言辞一定要肯定。

**Comment by wqyfavor** [comment]
如果有问题可以留一下电话，详细沟通一下。

**Comment by Luis-X** [comment]
> 可以给苹果回复邮件，说明自己的App并没有在应用审核后，利用任何动态能力修改应用行为。言辞一定要肯定。

已经上架将近1个月的时间了，最近突然被下架了，可能是因为苹果的复查机制

**Comment by zshshr** [comment]
What are you App? @Luis-X

**Comment by TenzeTseng** [comment]
> > 你们最近有发布改动非常大的页面吗？应用都上架了，怎么会被苹果发现？
> 
> > 如果有问题可以留一下电话，详细沟通一下。
> 
> ![image](https://user-images.githubusercontent.com/12946846/49065330-adb27e00-f258-11e8-9c4b-4a3784f219db.png)

参考一下这边文章：   https://www.sohu.com/a/246858026_100180134

**Comment by Luis-X** [comment]
> > > 你们最近有发布改动非常大的页面吗？应用都上架了，怎么会被苹果发现？
> > 
> > 
> > > 如果有问题可以留一下电话，详细沟通一下。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/12946846/49065330-adb27e00-f258-11e8-9c4b-4a3784f219db.png)
> 
> 参考一下这边文章： https://www.sohu.com/a/246858026_100180134

狗年大礼包和我这问题没啥太大关系啊

**Comment by wqyfavor** [comment]
涉及该开发者两个App，与苹果沟通后，其中已经已经恢复上架，另一个正在等待中。Weex团队会继续关注此问题，随时沟通，该Issue先关闭。
