### ISSUE TITLE
You cannot run CocoaPods as root

### ISSUE THREAD

**Issue by haqiaolong** [apache/incubator-weex#1828]
hi
  When I run weex run ios, I report the following error

Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
16:14:16 : Error:Error: Command failed: pod update
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

**Comment by Hanks10100** [comment]
It seems there has an existing issue talk about it https://github.com/weexteam/weex-toolkit/issues/337 , and you already found it. I think you can track the progress there.
