### ISSUE TITLE
有计划支持css key-frame动画吗？

### ISSUE THREAD

**Issue by xiaolanhai228** [apache/incubator-weex#1829]

**Comment by doumafang** [comment]
Currently we have no plans to support it at this time.

**Comment by oikewll** [comment]
![image](https://user-images.githubusercontent.com/244491/49427699-f8933f00-f7de-11e8-81cc-a98a7d4f554a.png)
LOL

**Comment by YorkShen** [comment]
Not supported yet

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
