### ISSUE TITLE
web端，同一个文件中提前声明weex.requireModule()不生效

### ISSUE THREAD

**Issue by qzcsgs** [apache/incubator-weex#1834]
## web端同一个文件中
* undefined is not an object (evaluating 'modal.alert') 
```js
const modal = weex.requireModule('modal')
modal.alert({ message: 'hello' })
```
* success
```js
weex.requireModule('modal').alert({ message: 'hello' })
```

**Comment by Hanks10100** [comment]
Both works for me http://dotwe.org/vue/a315c79279daa474cad354da479ffbda

> If you still think it's a bug, please offer a demo to reproduce it.
