### ISSUE TITLE
如何动态的移除和添加一个普通 div 间接达到 z-index 的效果 (不通过v-if)？

### ISSUE THREAD

**Issue by moketao** [apache/incubator-weex#1841]
可能我没有陈述清楚自己的需求。
这里再做一次详细讨论。
我是希望通过动态的创建、添加一个新的 div，使得多个层之间的**叠加次序改变**，达到 css 中 **z-index** 这个属性的效果。
@zshshr 有写出示范代码，非常感谢，但 **v-if** 并不能在移动端改变层与层之间的叠加次序。

我想举一个应用场景来说明 **z-index** 的重要性：

**单页应用中，一个自定义的 Alert 窗口（就是一个 div）在顶层，此时遇到两个难题：
1、用户打开一个新的层 C ，一个 div 构成的物件，这个时候，如何将 C 覆盖在 Alert 之上？ 
2、即便是已经把 C 覆盖在 Alert 上，此时要再次显示 Alert ，如何调整 Alert 所在层使之回到最顶端？ 如果不能调整，如何创建一个 新的 Alert 层并添加到渲染中？**

这里单独提一下**单页应用** single page web application，SPA（在单页应用中并没有多个 Weex 实例，而是只有一个，weex 不支持 Websocket 在多个实例中共享，关闭 Weex 实例的时候，Websocket也随之销毁，所以只能选择单页应用，否则页面多起来的时候就很麻烦，每个页面要单独开一个 Websocket，关闭页面的时候也要频繁的断开重连 websocket）

所以希望 阿里 要么能解决 Weex 中 Websocket 共享的问题，要么支持一下 z-index，这个特性在游戏引擎中非常常见，在 Web 特效中也非常常见。

_Originally posted by @zshshr in https://github.com/apache/incubator-weex/issues/1810#issuecomment-441946247_

**Comment by zshshr** [comment]
You are welcome to  provide  a pull request to solve the  problem of WebSocket sharing. And we has no plan to support this feature in short term .

**Comment by moketao** [comment]
有尝试过，只是有些地方实在是看不懂，以至于无从下手，比如这个文档：
https://weex.apache.org/cn/references/modules/websocket.html

里面提到：

> **iOS和h5提供 WebSockets 的 protocol 默认实现，安卓使用需要提供自定义 adapter 实现**

安卓不提供默认实现，主要是基于哪方面的考虑？

**Comment by zshshr** [comment]
the WebSockets  module  need the extra dependence of squareup lib , look the [https://github.com/apache/incubator-weex/blob/master/android/playground/app/build.gradle](url)
compile 'com.squareup.okhttp:okhttp:2.3.0'
compile 'com.squareup.okhttp:okhttp-ws:2.3.0'

**Comment by moketao** [comment]
外部库如果直接整合进来，不知道会不会有法律问题，或者道德问题，如果既能兼顾法律，又能整合，那是最好的。
感觉还是 开箱即用 更重要一些，不然有些小团队如果没有安卓程序员，只有 js 程序员，就会比较麻烦。
如果哪天能提供一个类似 Flash 的 IDE 环境就好了。
我这边临时先用 eros 好了，安卓代码对我来说还是太陌生，暂时帮不上忙。
非常感谢 @zshshr 的热心解答，辛苦了。

**Comment by Measy** [comment]
@moketao 你有解决方案了吗？

**Comment by Bijiabo** [comment]
对于 View 层次改变问题，也许可以通过编写一个容器组件来根据配置生成多个叠放的 Alert，需要修改层次的时候更新这个容器组件的配置即可。

对于 WebSocket 的共享问题，也许可以通过跨页面通信的方式来解决，最先启动的 Weex 页面来负责建立连接，然后将消息分发到其他页面....
