### ISSUE TITLE
最新playground app navigator 跳转 问题   直接回退到扫码

### ISSUE THREAD

**Issue by xiaoyuzi1001** [apache/incubator-weex#1842]
我直接扫描官网上navigator的demo也是直接回退扫码    是现在Android协议变了  不能直接也 http://地址了么
我playground app  weex SDK 版本是 0,18,0-beta-3 时是好的   更新到0,19,0出现这问题  望大牛指点 小白一枚

**Comment by erha19** [comment]
@xiaoyuzi1001 I will check it out, wait a second.

**Comment by erha19** [comment]
@xiaoyuzi1001 you can download the latest playground app from [playground.html](http://weex.apache.org/tools/playground.html) or open you playground app now, you will receive an upgrade message.
