### ISSUE TITLE
0.19.0 版本部分样式有问题

### ISSUE THREAD

**Issue by kang558** [apache/incubator-weex#1851]
## Describe the bug
之前APP是0.80样式都好好的，更新到0.19就出问题了。
还有weex-ui也受到影响。

尤其是text组件，使用flex自适应宽高换行和lines不起作用。貌似必须设置固定的宽高，才起作用。
iOS和安卓上的表现还不一致！【安卓是正常的】
## To Reproduce
[代码示例 http://dotwe.org/vue/5446be01fe215af70f5d112baa303325](http://dotwe.org/vue/5446be01fe215af70f5d112baa303325)
## Environment
* Device: [e.g. iPhone7][xiaomi note3]
* OS: [e.g. iOS12.1][Android 8.1.0]
* Version [e.g. 22]
* Build from source [e.g. yes/no]

## Screenshots
iOS：

![screenshot_2018-12-01-12-07-37-089_com alibaba we](https://i.loli.net/2018/12/01/5c020a67d6692.png)

Android：

![screenshot_2018-12-01-12-27-48-417_com alibaba we](https://user-images.githubusercontent.com/22288837/49324222-9202ec80-f564-11e8-8294-ba1fb57175a6.png)

**Comment by mahaiyannn** [comment]
用最新代码编译出来的playground跑起来是正常的，再check下看看？

**Comment by kang558** [comment]
> 用最新代码编译出来的playground跑起来是正常的，再check下看看？

这版本不对吗？ @mahaiyannn 
<img src="https://i.loli.net/2018/12/03/5c0508181a08a.png" width="460">

**Comment by kang558** [comment]
我们的APP使用的是这个版本的 [https://github.com/apache/incubator-weex/releases/tag/0.19.0](https://github.com/apache/incubator-weex/releases/tag/0.19.0)

**Comment by wqyfavor** [comment]
建议试一下0.20.1版本

**Comment by wqyfavor** [comment]
0.20的playground无此问题，先关掉了。谢谢反馈。
