### ISSUE TITLE
希望能将公司产品也加入weex网页

### ISSUE THREAD

**Issue by FateOfKing** [apache/incubator-weex#1852]
公司产品同样使用weex技术开发，请问达到何种条件可以把我公司产品也展示到贵公司的weex官网https://weex.apache.org/cn/who-is-using-weex.html

**Comment by Hanks10100** [comment]
Merged https://github.com/apache/incubator-weex-site/pull/215

**Comment by FateOfKing** [comment]
我发现在网页上依旧不显示我添加的diibee产品图标
https://weex.apache.org/cn/who-is-using-weex.html

**Comment by YorkShen** [comment]
请使用weex国内镜像[站点](http://weex-project.io/who-is-using-weex.html)，由于一些原因，目前https://weex.apache.org 暂时无法更新，国内镜像站点可以正常浏览
