### ISSUE TITLE
recommend to add a reference to the parent component for removeElement

### ISSUE THREAD

**Issue by ts0307** [apache/incubator-weex#1855]
I am trying to adapt weex to work on platforms other than iOS and android. I found some rendering directive definitions not very convenient at work.
If I add a reference to the parent component for removeElement, I can implement this removeElement directive more easily.

After adding the parameters referenced to the parent component, the removeElement directive implementation looks like this:
callRemoveElement(instanceId, parentRef, ref)

**Comment by zshshr** [comment]
Welcome to submit a pull request to add removeElement ，and other question what is the platform that you trying to adapter ？

**Comment by ts0307** [comment]
@zshshr webgl

**Comment by zshshr** [comment]
Can you show us more detail about your  plan ?

**Comment by YorkShen** [comment]
I will close this issue as the conversion happened in https://github.com/apache/incubator-weex/issues/1853
