### ISSUE TITLE
debug功能不能使用

### ISSUE THREAD

**Issue by hshm** [apache/incubator-weex#1858]
工程配置：
weex_sdk_version = "0.19.0.3"//对标github release 标注的版本号，用于标示当前sdk版本号
implementation 'com.taobao.android:weex_inspector:0.18.0'

报下面的错误：
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/taobao/windmill/bridge/IWMLBridge

是sdk 跟 inspector的版本不一致吗，求解？

**Comment by erha19** [comment]
@hshm try to use `com.taobao.android:weex_inspector:0.18.10`

**Comment by miomin** [comment]
> 工程配置：
> weex_sdk_version = "0.19.0.3"//对标github release 标注的版本号，用于标示当前sdk版本号
> implementation 'com.taobao.android:weex_inspector:0.18.0'
> 
> 报下面的错误：
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/taobao/windmill/bridge/IWMLBridge
> 
> 是sdk 跟 inspector的版本不一致吗，求解？

http://weex-project.io/guide/integrate-devtool-to-android.html#version-compatibility
