### ISSUE TITLE
text组件，文字换行时单词被切断，如何设置。

### ISSUE THREAD

**Issue by qzcsgs** [apache/incubator-weex#1862]
text 有些长单词在上一行的末尾， 换到下一行之后被拆成了两部分。

**Comment by qzcsgs** [comment]
<img width="179" alt="2018-12-04 6 51 58" src="https://user-images.githubusercontent.com/38126556/49438078-35b7fb00-f7f8-11e8-8916-b20737e26121.png">
 Successfully被拆成了Success和fully

**Comment by Hanks10100** [comment]
Here is a demo, it works fine on my Android phone http://dotwe.org/vue/11454bbf39f8f3fdf1ab2566b815ef92

**Comment by qzcsgs** [comment]
I'm sorry I can't reproduce it on weex Playground, but I've solved it by adding `word-wrap: break-word`

**Comment by YorkShen** [comment]
Ok, open another issue if there is a problem.
