### ISSUE TITLE
插件市场为什么没有了

### ISSUE THREAD

**Issue by kang558** [apache/incubator-weex#1863]
为什么没有插件市场了 ，打不开了 [https://market.weex-project.io/](https://market.weex-project.io/) 
不维护了吗？
想找插件不知道上哪找去
:joy: :joy: :joy: :joy:

**Comment by Hanks10100** [comment]
That's just a static page to list what plugins Weex has, and this requirement could be supported by the official website of Weex.

We are working the new website of Weex now, it could be release at early 2019. By that time, community developers are able to share their experence and plugins on it, you can also check what plugin is available.

**Comment by kang558** [comment]
good ！

**Comment by kuaifan** [comment]
This is by far weex's largest plug-in market [https://www.jianshu.com/p/1fa669f94f55](https://www.jianshu.com/p/1fa669f94f55)
