### ISSUE TITLE
WXLogLevel与微信SDK重名

### ISSUE THREAD

**Issue by winfredgit** [apache/incubator-weex#1865]
WXLog.h枚举WXLogLevel与微信SDK WXApiObject.h WXLogLevel，重名

**Comment by zshshr** [comment]
WeChat integrates weex?

**Comment by winfredgit** [comment]
微信与weex都定义相同名称的枚举WXLogLevel

**Comment by zshshr** [comment]
#1887

**Comment by coderPChen** [comment]
使用0.20.1版本Weex 编译还是报 enumeration redeclared with different underlying type 'NSInteger' (aka 'long') (was 'NSUInteger' (aka 'unsigned long'))
typedef NS_ENUM(NSInteger,WXLogLevel)重名

**Comment by yubinbin** [comment]
0.20.3编译是这个问题 有人解决没
