### ISSUE TITLE
iOS websocket 无法使用

### ISSUE THREAD

**Issue by skylarLi** [apache/incubator-weex#1868]
为什么最新版weex没有iOS websocket 的实现？

**Comment by zshshr** [comment]
@skylarLi  what's  the version  you use can support？

**Comment by skylarLi** [comment]
是呀 自己在写demo 感觉用不动了发自我的iPhone------------------ 原始邮件 ------------------发件人: quanchaoguo  <notifications@github.com>发送时间: 2018年12月6日 09:23收件人: apache/incubator-weex <incubator-weex@noreply.github.com>抄送: skylarLi <chenhui.li0715@gmail.com>, Author <author@noreply.github.com>主题: 回复：[apache/incubator-weex] iOS websocket 无法使用 (#1868)你们公司还用 weex 么 我感觉真的越来越差了

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-weex","title":"apache/incubator-weex","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-weex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@quanchaoguo in #1868: 你们公司还用 weex 么 我感觉真的越来越差了"}],"action":{"name":"View Issue","url":"https://github.com/apache/incubator-weex/issues/1868#issuecomment-444713640"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-weex/issues/1868#issuecomment-444713640",
"url": "https://github.com/apache/incubator-weex/issues/1868#issuecomment-444713640",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apache/incubator-weex] iOS websocket 无法使用 (#1868)",
"sections": [
{
"text": "",
"activityTitle": "**quanchaoguo**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@quanchaoguo",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apache/incubator-weex\",\n\"issueId\": 1868,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apache/incubator-weex\",\n\"issueId\": 1868\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apache/incubator-weex/issues/1868#issuecomment-444713640"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 420150667\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by zshshr** [comment]
@skylarLi  what's the version you use can support？

**Comment by skylarLi** [comment]
v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.2.5
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

**Comment by skylarLi** [comment]
> @skylarLi what's the version you use can support？
v1.3.11

weexpack : v1.2.7
weex-debugger : v1.2.5
weex-builder : v0.4.0
weex-previewer : v1.5.1

**Comment by stjdydayou** [comment]
我也碰到了同样的问题
ios WeexSDK用的是0.18.0.3，提示WXWebSocketLoader.m:103, No resource request handler found!
我在0.12版本里把SRWebSocket+Weex，WXWebSocketDefaultImpl相关的文件复制到项目里可以运行，但是只能连接与发送消息，无法接收到消息。有什么好的解决方案吗
