### ISSUE TITLE
Weex playground app里面的例子，input输入的内容显示不全。

### ISSUE THREAD

**Issue by leixuesong** [apache/incubator-weex#1870]
![_20181206123340](https://user-images.githubusercontent.com/6357885/49561191-df120480-f950-11e8-8d5f-63e202df6a78.jpg)
abc显示不全。

**Comment by Hanks10100** [comment]
这应该是 input 行高设置的有问题，高度减去 padding 之后太小，放不下一行字。例子有些小问题，稍后更新一下。

**Comment by Hanks10100** [comment]
给 input 框设置一个高度可以解决： http://dotwe.org/vue/fd2266992179ea22a32b25ed864a22ad
