### ISSUE TITLE
crash in [WXComponentManager rootViewFrameDidChange:]

### ISSUE THREAD

**Issue by lixiangsanxun** [apache/incubator-weex#1872]
## crash in  [WXComponentManager rootViewFrameDidChange:] 
我们的项目在APP启动出现首页的时候就会加载2-3个weex界面控制器，偶现crash，从iOS12开始该crash的数量开始增加，目前用的WeexSDK的版本为0.18.0

## Environment
* Device: [e.g. iPhoneX]
* OS: [e.g. iOS12.01]
* Version [e.g. 0.18.0]
* Build from source [e.g. yes/no]

## Additional context
崩溃堆栈如下
0 WeexSDK | -[WXComponentManager rootViewFrameDidChange:] (WXComponentManager.m:163)
-- | --
1 WeexSDK | -[WXComponentManager rootViewFrameDidChange:] (WXComponentManager.m:163)
2 WeexSDK | __26-[WXSDKInstance setFrame:]_block_invoke_2 (WXSDKInstance.m:134)
3 WeexSDK | +[WXComponentManager _performBlockOnComponentThread:] (WXComponentManager.m:130)
4 Foundation | ___NSThreadPerformPerform + 340
5 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
6 CoreFoundation | ___CFRunLoopDoSource0 + 88
7 CoreFoundation | ___CFRunLoopDoSources0 + 204
8 CoreFoundation | ___CFRunLoopRun + 1048
9 CoreFoundation | CFRunLoopRunSpecific + 436
10 Foundation | -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
11 WeexSDK | -[WXComponentManager _runLoopThread] (WXComponentManager.m:122)
12 Foundation | ___NSThread__start__ + 996
13 libsystem_pthread.dylib | __pthread_body + 308
14 libsystem_pthread.dylib | __pthread_body

**Comment by wqyfavor** [comment]
0.21.0和0.19.0版本已发，建议升级看一下。我们大幅提升了component层的稳定性。

**Comment by lixiangsanxun** [comment]
> 0.21.0和0.19.0版本已发，建议升级看一下。我们大幅提升了component层的稳定性。

感谢回复，0.19.0我们已经适配了，只是还没上线，期待新版本的weex
