### ISSUE TITLE
IOS 0.19.0版本启动白屏

### ISSUE THREAD

**Issue by leron1989** [apache/incubator-weex#1874]
你好，0.19.0 在IOS端运行白屏，报错信息如下，请问这个需要怎么处理
instanceId:0
options:{
    bundleType = Vue;
    bundleUrl = "file:///Users/jlr/Library/Developer/CoreSimulator/Devices/8A3BA7D4-0B4F-43C8-9B05-A406798AC47F/data/Containers/Bundle/Application/A4E31FE9-E853-4000-BF40-B928ED67FE4B/WeexDemo.app/bundlejs/index.js";
    debug = 1;
    env =     {
        appName = WeexDemo;
        appVersion = "1.8.3";
        deviceHeight = 1334;
        deviceModel = "x86_64";
        deviceWidth = 750;
        logLevel = log;
        osName = iOS;
        osVersion = "12.1";
        platform = iOS;
        scale = 2;
        weexVersion = "0.19.0";
    };
}
data:(null)
(
    service,
    clearTimeout,
    setInterval,
    clearInterval,
    services,
    BroadcastChannel,
    weex,
    setTimeout,
    Vue,
    getJSFMVersion,
    "__WEEX_CALL_JAVASCRIPT__"
)

**Comment by zshshr** [comment]
Have try it on playground?

**Comment by leron1989** [comment]
> Can you reproduce on Weex playground ?

已经在#1685中找到问题原因了，谢谢哈~~
https://github.com/apache/incubator-weex/issues/1685
