### ISSUE TITLE
Weex Android weex debugx bug

### ISSUE THREAD

**Issue by quanchaoguo** [apache/incubator-weex#1876]
## Describe the bug

weex xbind debugx weex-devtool
weex debugx 
why i do not see  debug  i can see on

<img width="688" alt="2018-12-07 1 54 21" src="https://user-images.githubusercontent.com/32917790/49630187-0556a380-fa28-11e8-8fcb-aca139ca9ef7.png">

 

## Environment
v1.2.9
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6
 - weex-devtool : v0.3.8

**Comment by erha19** [comment]
@quanchaoguo to use the debug command, you can see the document here: http://weex.apache.org/cn/tools/toolkit.html#lian-jie-she-bei, also you can upgrade your `weex-toolkit` by `npm i weex-toolkit@latest -g`.

**Comment by zkj881225** [comment]
我也有这个问题，求官方解答下。

**Comment by zkj881225** [comment]
![image](https://user-images.githubusercontent.com/33045988/50873850-aa381800-13fc-11e9-833b-9f426767d06e.png)
 这是我的版本号

**Comment by erha19** [comment]
duplicate #1867

**Comment by YorkShen** [comment]
I will just close the issue as the discussion happened on other threads.
