### ISSUE TITLE
利用weex控制播放器进度条的时候，会有一个持续增加的数组

### ISSUE THREAD

**Issue by frankLifexg** [apache/incubator-weex#1877]
hello, 请教一个问题，我们在使用weex时候发现了一个现象，就是在利用weex控制播放器进度条的时候，会有一个持续增加的数组，拖慢了性能。这个进度条是一个单利的播放器
![image](https://user-images.githubusercontent.com/7948038/49631363-afd0c580-fa2c-11e8-97aa-3a45a8b1365a.png)

**Comment by zshshr** [comment]
Provide a reproducible example at http://dotwe.org/vue

**Comment by wqyfavor** [comment]
WXTracing这个东西已经干掉了，如果你们的版本不想要的话，可以把WXTracingManager关掉，里面有个方法强行返回NO即可。
