### ISSUE TITLE
ios, build question

### ISSUE THREAD

**Issue by qzcsgs** [apache/incubator-weex#1881]
sorry, my English isn't very good.

* run `npm run build` , `platforms/ios/bundlejs` Not here create `index.js`
* first run `npm run ios` after that `npm run build` create `index.js`

I wonder if this is normal.

**Comment by erha19** [comment]
@qzcsgs It works like our expected now, for the official project, the `npm run build` command will build source to the `dist` folder, while the `npm run ios` command was called, the script will copy files from `dist` to `platforms/ios/bundlejs`, also it will re-run the command `npm run build` command to get the latest products.

**Comment by qzcsgs** [comment]
@erha19 Ok,  thank you very much.
