### ISSUE TITLE
iOS和android的一些bug和建议

### ISSUE THREAD

**Issue by caolizhen997** [apache/incubator-weex#1885]
### 一 ：iOS
1.顶部一个可以换行的textView，下方一个sliderComponent，当textView换行的时候，看你们的源码，会将下方的sliderComponent标记成被污染的组件，并且重绘。重绘结束之后，会调用以下代码。

```
//WXCycleSliderComponent.m （Line：454）
- (void)layoutDidFinish
{
   // _recycleSliderView.currentIndex = _currentIndex;
    _recycleSliderView.currentIndex = _index;
}
当这里调用的时候_index是0（我看到的好像永远都是0），就会造成滑动的错乱，比如我由index=3滑到index=4的时候，恰好上方的textView换行了，下方重绘，那么这个时候slider的表现就是，从3到4，然后从4到0。
注释的地方是我修改的，可以规避这个问题，但是不确定是否会引起什么别的bug。这里最好可以帮忙看一下。

```

2. 渲染出来的weexView和weexView的subView（sliderView or other）不存在尺寸上的任何关联？当我给instance.frame设置高度为200，发现js渲染出来的view的尺寸不受200的限制，可以比200要长，这就导致了超出的部分无法响应任何事件，为了规避该问题，我们新增了接口，让前端同学调用新增的接口来拿到instance.frame的尺寸，才得以解决该问题。请问这里的这种设计是基于什么样的考量？

### 二：android

1.带下拉刷新与上拉加载更多的列表无法响应与其父控件的父控件滑动嵌套（如CoordinatorLayout）。

**Comment by zshshr** [comment]
Provide a reproducible example at http://dotwe.org/vue

**Comment by caolizhen997** [comment]
> Provide a reproducible example at http://dotwe.org/vue

http://dotwe.org/vue/1718e6d406b20c5c94a96a81139d3c7f 
iPhone 扫码之后一直滑动直到换行问题就可以复现，这个是iOS的问题1。
剩下的iOS问题2，和android的问题需要打包成apk才可以。因为我们的项目某个界面是native+weex。

**Comment by wqyfavor** [comment]
iOS问题1已经修复了，可以试试最新代码。第二个问题不太明白，slider的实现就是把内容并排排列，可能超出instance的。

**Comment by YorkShen** [comment]
Can you give a demo for problem 2?

**Comment by caolizhen997** [comment]
Sorry,I cannot describe problem 2 clearly.. 

 

Unfortunately, our application had removed Weex component because some of our businesses could’t be realized.

 

If I have time,I will give a demo  for problem2..

 

Thanks for your contribution

 

发件人: YorkShen <notifications@github.com>
答复: apache/incubator-weex <reply@reply.github.com>
日期: 2019年2月20日 星期三 下午6:01
收件人: apache/incubator-weex <incubator-weex@noreply.github.com>
抄送: caolizhen997 <464514962@qq.com>, Author <author@noreply.github.com>
主题: Re: [apache/incubator-weex] iOS和android的一些bug和建议 (#1885)

 

Can you give a demo for problem 2?

**Comment by YorkShen** [comment]
In that case, I will just close the issue.

Feel free to reopen it when your demo is done.

Thanks for your cooperation.
