### ISSUE TITLE
WXLogLevel枚举名冲突

### ISSUE THREAD

**Issue by GL-Wen** [apache/incubator-weex#1887]
WechatOpenSDK和WeexSDK两个组件，有相同的枚举名称WXLogLevel

**Comment by linmowang** [comment]
我也遇到了， 然后ios开发把WXLogLevel =》 改成了WXXLogLevel

**Comment by zshshr** [comment]
There is no good way to solve this problem，you can refer to the method of @linmowang

**Comment by hponiang** [comment]
> There is no good way to solve this problem，you can refer to the method of @linmowang

现在并没有解决啊
