### ISSUE TITLE
Animation problem on ios, and borderRadius problem when it bigger then width/height

### ISSUE THREAD

**Issue by jerryyum** [apache/incubator-weex#1899]
## Describe the bug
1. Animation has no effect on ios, but it works fine on android & web
1. When width/height < borderRadius, there has wrong cornerRadius on ios.

## To Reproduce

http://dotwe.org/vue/594d43b10d8fb9847d8122bbd429f48b
http://dotwe.org/vue/e787a4a04b3cc33807e2d083ca3f3793

## Environment
* Device: iPhone X
* OS: ios 11
* Version 0.19.0

**Comment by wqyfavor** [comment]
已修复，https://github.com/apache/incubator-weex/pull/2112

**Comment by wqyfavor** [comment]
这个问题在master上直接按照2112来修改有风险，所以我们决定回滚掉了，再想办法解决这个问题。
如果你们自己的app，可以按照2112的改法临时修改。
