### ISSUE TITLE
如何添加 Promise onunhandledrejection 自定义处理

### ISSUE THREAD

**Issue by warlock1024127** [apache/incubator-weex#1903]
- [ ] Review the documentation: https://weex.apache.org/index.html
  - [ ] Search for existing issues: https://github.com/apache/incubator-weex/issues
  - [x] Use the latest Weex release: https://github.com/apache/incubator-weex/releases

## Describe the bug
Unhandled promise rejection 错误在安卓上通过 weex-js-framework 中的console.error('Unhandled promise rejection', value); 这行代码在LogCat中输出，ios上好像不行。请问怎么自定义捕获这类错误，从而添加一些处理方式。

**Comment by biwoodfengs** [comment]
分析下weex-js-runtime/index.js， 如下可以
global.onunhandledrejection = (res,value)=>{
        
};

**Comment by warlock1024127** [comment]
@biwoodfengs 请教一下，怎么在外面取到runtime 中的global

**Comment by wqyfavor** [comment]
如果是iOS的Log方法的问题，麻烦另建一个issue并提供demo，这个问题先关掉了。谢谢反馈。
