### ISSUE TITLE
关于ios版本0.20.1 weexsdk meta.setViewport  bug

### ISSUE THREAD

**Issue by FateOfKing** [apache/incubator-weex#1906]
http://dotwe.org/vue/2754bb29c9225c0d097eab94ebbeb5e6 
这是我的demo，在sdk 0.19.0.2中  设置了meta.setViewport 用来适配ipad屏幕，升级了sdk版本发现失效了。具体视频请查看https://pan.baidu.com/s/1UaZqu8ATo_7P8paLou8GPg

**Comment by zhaozheyu** [comment]
android这边，0.20.0-release，WXSDKInstance.setInstanceViewPortWidth无效

**Comment by wqyfavor** [comment]
谢谢反馈，这个bug iOS已经修复。https://github.com/apache/incubator-weex/pull/2107

**Comment by FateOfKing** [comment]
I noticed that this bug is still not fixed in pod 0.20.3.0-beta, may I ask when it can be fixed

**Comment by gubaojian** [comment]
android 2周后版本修复，目前内部功能已经在开发中。
