### ISSUE TITLE
transition not working on weex-sdk 0.19+ 

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#1908]
## Describe the bug
transition not working on weex-sdk 0.19+ ,i use the latest playground app。

## To Reproduce

demo 
http://dotwe.org/vue/825827b22050004ed6d101b1de9208af

## Environment
* Device: [XIAOMI MI5]
* OS: [android 8.0]
* Build from source [no]

**Comment by Hanks10100** [comment]
You demo seems incorrect, here is the new one http://dotwe.org/vue/9a25405b1283b6dfd9ee7d56907d50e1

1. The root `<div>` is will be rendered to the whole screen by default, do not animate the size of it.
2. The `width` style should contain a unit, such as `px`.
3. Your `transition-property` is `left`, but you are changing the `width`.

**Comment by chenzefeng09** [comment]
so sorry for the mistakes in my demo !
But transition seems still not working in new demo,I try it on the new android playground app.

@Hanks10100
