### ISSUE TITLE
weex_sdk从0.18.0升级到0.20.0.1，开启debug模式程序崩溃，像是so文件引发

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#1913]
1.js打包后在项目中运行没问题，旧版与新版皆正常
2.开启debug
`       String host = "192.168.2.236";
        WEEXURL = "http://192.168.2.236:8088/weex/";
        WXEnvironment.sDebugServerConnectable = true;
        WXEnvironment.sRemoteDebugMode = true;
        WXEnvironment.sRemoteDebugProxyUrl = "ws://" + host + ":8088/debugProxy/native/";`
0.18.0正常：
gradle配置为：
` compile 'com.taobao.android:weex_inspector:0.13.4'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'`
![image](https://user-images.githubusercontent.com/36951996/49990889-3e5bbe80-ffba-11e8-9bc5-89a0fc43ca9f.png)

0.20.0.1崩溃：
gradle配置为：
` compile 'com.taobao.android.weex_inspection:urlconnection_interceptor:1.0.0'
    compile 'com.taobao.android:weex_inspector:0.18.10'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-ws:2.3.0'
    compile 'com.squareup.okio:okio:1.0.1'`
![image](https://user-images.githubusercontent.com/36951996/49991119-07d27380-ffbb-11e8-9e36-d5fac15e71b7.png)
机型：华为
系统：8.0.0

**Comment by fanlvwen** [comment]
weex_sdk0.20.0.1，相同配置下，app的gradle配置为
`compile 'com.taobao.android:weex_inspector:0.18.68'`
不闪退了，但是debug的浏览器页面上，仍然没有显示设备列表

**Comment by miomin** [comment]
请提供你的weex toolkit中weex debuger的版本号

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/49996346-bbdafb00-ffc9-11e8-8912-ab35c1ab9b4c.png)
但是我并未使用debugger，我仍然使用的weex-devtool
`$ weex xbind debugx weex-devtool
$ weex debugx`

**Comment by fanlvwen** [comment]
weex项目中启动debug使用的是
'weex debugx src -e index.vue'

terminal:
![image](https://user-images.githubusercontent.com/36951996/49996587-5cc9b600-ffca-11e8-8b80-af95596c2380.png)

**Comment by erha19** [comment]
@fanlvwen you'd better using `weex debug` command, but not the `weex debugx` command which source the old `weex-devtool` module.

**Comment by fanlvwen** [comment]
> @fanlvwen you'd better using `weex debug` command, but not the `weex debugx` command which source the old `weex-devtool` module.

1.我这个是多页面应用，调试的是整个文件夹，需要类似'weex debugx src -e index.vue'这样的命令，weex debug没有这个命令，只有weex debug src，这个命令打开的debug，比如说index.js超级大，而且index.vue中稍微改一个字，热更新都需要1分钟左右才在chrome上刷新页面

**Comment by erha19** [comment]
@fanlvwen I will check the compilation problem, and I also suggest you using `weex debug` command to debug your page,  if you want to compile pages more quickly, I suggest you using `weex create [projectname]` to create an official project, then put your source into the `src` (do not delete `entry.js`), then running `npm start`, it will open an browser for you to preview your page, you can also modify the configuration on `config` folder.

As a temporary solution, you can also using `weex-devtool` for build, `weex-debugger` for debug.

The built-in module on `weex-debugger` or `weex-devtool` will be removed soon as it can compile very limited content. Wait patiently for the new version of the `weex` debug tool, it will coming soon.

**Comment by fanlvwen** [comment]
> @fanlvwen I will check the compilation problem, and I also suggest you using `weex debug` command to debug your page, if you want to compile pages more quickly, I suggest you using `weex create [projectname]` to create an official project, then put your source into the `src` (do not delete `entry.js`), then running `npm start`, it will open an browser for you to preview your page, you can also modify the configuration on `config` folder.
> 
> As a temporary solution, you can also using `weex-devtool` for build, `weex-debugger` for debug.
> 
> The built-in compile module on `weex-debugger` or `weex-devtool` will be removed soon as it can compile very limited content. Wait patiently for the new version of the `weex` debug tool, it will coming soon.

谢谢回答！
新建项目，把自己项目的src拷贝过来，保留新的entry.js，运行npm run start 报错如下：
![image](https://user-images.githubusercontent.com/36951996/50130708-ebd01a00-02b9-11e9-9ce1-e6a956804382.png)

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/50131580-cd6c1d80-02bd-11e9-8b9d-d8c3a725667a.png)
这个命令卡了十分钟了。。。

**Comment by fanlvwen** [comment]
新建项目，直接npm run build:prod,没问题
加入10+vue文件，没问题，逐渐加入vue文件，当加到70+页面（包括子组件），这时候就会卡住不动了。

**Comment by erha19** [comment]
@fanlvwen You can filter out some files that are temporarily unavailable，see config file on `configs/config.js`, you can modify the `entryFilter` as you like.

**Comment by fanlvwen** [comment]
是这样的，本身我已经有一个线上项目，而且是多页面的（加上子组件估计100+vue文件），按照你说的weex create一个新项目，
运行任何命令都正常。

然后，把线上项目的src整个拷过来。这是前提。

1. 然后运行npm run start，报错如上面的一个图

2. npm run build:prod无响应

3. 猜测是src下vue文件太多，于是逐步拷贝到src下，当文件比较多的时候，出现情况2

**Comment by erha19** [comment]
@fanlvwen use filter config makes files which are necessary to be compiled.

**Comment by fanlvwen** [comment]
不好意思不太明白，src里所有的文件肯定都是要编译的啊

**Comment by erha19** [comment]
@fanlvwen the files you develop now should be one or more than one, but should not be all of the files on `src` folder.

**Comment by fanlvwen** [comment]
或者你能给我一个config参考吗？
我本意是把整个项目打包，用npm run buid可以，用npm run build:prod就不行。
![image](https://user-images.githubusercontent.com/36951996/50195481-416bfb80-037a-11e9-94be-509926185b50.png)
这是用run build打出来的文件，然后压缩好放到android原生assets下运行

**Comment by YorkShen** [comment]
It seems this issue is resolved, I will just close it.

Feel free to reopen it if you have other questions.
