### ISSUE TITLE
iOS 0.19.0 版本toast队列无法清空的问题

### ISSUE THREAD

**Issue by heiby** [apache/incubator-weex#1915]
## Description

当weex页面销毁时，如果toast队列不为空，则队列里面的toast无法展示，并且不会被清理，有可能造成下次调用toast时，把旧的toast展示出来。

## Environment

版本：weex sdk 0.19.0

## Steps to Reproduce

在页面中创建多个toast并在toast没展示完时，退出页面。

## reason

产生此bug的关键代码如下：

当weex页面销毁时，weakself是nil，所以这个递归调用不下去了，无法清除队列数据

![img](https://user-images.githubusercontent.com/4581299/50008362-e25f5d00-ffee-11e8-8473-f10dd2a233c9.png)

**Comment by wqyfavor** [comment]
谢谢反馈，已经修复。https://github.com/apache/incubator-weex/pull/2106
