### ISSUE TITLE
iOS端initSDKEnvironment的初始化方法有成功或失败的回调嘛？

### ISSUE THREAD

**Issue by stvenjobs** [apache/incubator-weex#1917]
- [ ] Review the documentation: https://weex.apache.org/index.html
  - [ ] Search for existing issues: https://github.com/apache/incubator-weex/issues
  - [ ] Use the latest Weex release: https://github.com/apache/incubator-weex/releases

## To Reproduce
Steps to reproduce the behavior.  Include a MCVE using http://dotwe.org/vue , crash stacktrace or  share your app project. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

## Environment
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Version [e.g. 22]
* Build from source [e.g. yes/no]

**Comment by wqyfavor** [comment]
initSDKEnvironment里其实就是要执行一个js脚本，但是会切到js线程执行，具体执行成功还是失败不好判断了。如果只是判断weex-main-jsfm.js这个文件存不存在，意义不大了。谢谢反馈。
