### ISSUE TITLE
weex项目运行后，内存占用太大！如何优化这个问题呢？

### ISSUE THREAD

**Issue by zhuzhuxingtianxia** [apache/incubator-weex#1928]
内存占用220M~290M,占用太大！有时候会因为内存太大crash!
希望能解决这个问题

**Comment by lucky-chen** [comment]
hi, 请提供下测试用例、使用场景，正常页面不会有这么夸张的
比如：https://github.com/apache/incubator-weex/issues/1931

另外，请检查页面，是否使用的大图、大视频之类的

**Comment by CoderQifly** [comment]
播放远程音视频,内存巨大....不释放
