### ISSUE TITLE
小米4初始化GCanvas崩机

### ISSUE THREAD

**Issue by dxwt** [apache/incubator-weex#1933]
## Describe the bug

小米4初始化GCanvas崩机

## Environment

* Device: 小米4
* OS: Android 6.0.1 
* Version [weex sdk 0.20.0.2]
* Build from source [no]

## Expected behavior

调用
WXSDKEngine.registerModule("gcanvas" , GCanvasWeexModule::class.java , true) 
APP崩溃

## Screenshots

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/cancro/cancro:6.0.1/MMB29M/8.4.26:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 25594, tid: 25724, name: WeexJSBridgeThr  >>> xxx.xxxx.xxxx <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa8
    r0 00000000  r1 00001000  r2 00000003  r3 00000000
    r4 9a6c9934  r5 00000000  r6 00000003  r7 00000000
    r8 00000000  r9 ab5a1e00  sl 9a6c9990  fp ab5a1e00
    ip 00000000  sp 9a6c990c  lr b6f75bd3  pc b6f7581e  cpsr 000f0030

backtrace:
    #00 pc 0000681e  /system/bin/linker (__dl__ZL13soinfo_unloadP6soinfo+5)
    #01 pc 0000dc14  /dev/ashmem/dalvik-LinearAlloc (deleted)

**Comment by YorkShen** [comment]
You may ask this question in [GCanvas community](https://github.com/alibaba/GCanvas), thanks.
