### ISSUE TITLE
weex在android上的渲染速度如何优化

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#1935]
weex项目build到原生android中，一个activity从onCreate到renderSucc的耗时：
简单页面，只有一个空div需要1秒左右
复杂一些的，比如列表+子组件的 就要2.5秒+

那么问题来了，从打开activity到页面渲染完成，这中间的几秒空白页，大家是如何处理的呢？

**Comment by chenzefeng09** [comment]
你这包括网络时间吗？有做一些预缓存之类的处理吗

**Comment by fanlvwen** [comment]
就一个空的页面，不包含任何控件，js文件是放在android项目本地的，所以没有网络时间，也没有缓存

**Comment by lvfen** [comment]
这个问题我们也很关注，不过一个空的div耗时1s有点过分了，之前我trace过整个weex的渲染性能问题，性能主要是下面两点：
1. 低端机器上性能热点主要表现在jscore执行js的耗时
2. 高端机器上的性能热点主要表现在core抛出虚拟dom到java层执行的时间，虚拟dom到真正执行时抛的一个个message执行的，而且是单线程，很容易出现不同页面之间的操作相互干扰的现象。之前测试过，单独加载一个页面只需要1s，同时加载2个一样的页面，两个都需要1.5s。

我们根据渲染性能的问题提了这样一个pr，希望对你有帮助：
https://github.com/apache/incubator-weex/pull/1978

**Comment by fanlvwen** [comment]
> 这个问题我们也很关注，不过一个空的div耗时1s有点过分了，之前我trace过整个weex的渲染性能问题，性能主要是下面两点：
> 
> 1. 低端机器上性能热点主要表现在jscore执行js的耗时
> 2. 高端机器上的性能热点主要表现在core抛出虚拟dom到java层执行的时间，虚拟dom到真正执行时抛的一个个message执行的，而且是单线程，很容易出现不同页面之间的操作相互干扰的现象。之前测试过，单独加载一个页面只需要1s，同时加载2个一样的页面，两个都需要1.5s。
> 
> 我们根据渲染性能的问题提了这样一个pr，希望对你有帮助：
> #1978

谢谢，关注中。

**Comment by WangXiZhu** [comment]
> > 这个问题我们也很关注，不过一个空的div耗时1s有点过分了，之前我trace过整个weex的渲染性能问题，性能主要是下面两点：
> > 
> > 1. 低端机器上性能热点主要表现在jscore执行js的耗时
> > 2. 高端机器上的性能热点主要表现在core抛出虚拟dom到java层执行的时间，虚拟dom到真正执行时抛的一个个message执行的，而且是单线程，很容易出现不同页面之间的操作相互干扰的现象。之前测试过，单独加载一个页面只需要1s，同时加载2个一样的页面，两个都需要1.5s。
> > 
> > 我们根据渲染性能的问题提了这样一个pr，希望对你有帮助：
> > #1978
> 
> 赞
> 感觉0.19重构之后渲染性能不如0.18版本（Android，主观感受）

渲染性能不如0.18，这个有数据对比吗？麻烦帖一下，公司正打算升级

**Comment by YorkShen** [comment]
According to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. 

You may discuss the performance issue on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).

Thanks.
