### ISSUE TITLE
@appear 事件不能执行，WeexPlayground 同样不执行；请问如何解决？

### ISSUE THREAD

**Issue by haicuan139** [apache/incubator-weex#1953]
@appear 事件不能执行，WeexPlayground 同样不执行；请问如何解决？
Android 和 ios 平台都不能执行；

**Comment by wqyfavor** [comment]
麻烦给个demo

**Comment by wqyfavor** [comment]
先关掉了，有问题麻烦提供个demo。我们测试appear是没问题的，不知道你说的是加到什么元素上的appear不能执行。
