### ISSUE TITLE
WXSDKInstance类有必要暴露IWXRenderListener和IWXStatisticsListener两个属性

### ISSUE THREAD

**Issue by wangguanquan** [apache/incubator-weex#1954]
RT:
  mRenderListener和mStatisticsListener两个属性都没有get方法，如果要对线上项目监听加逻辑需要打开每个类然后添加相同逻辑，比较麻烦并且容易出错
  如果暴露了get方法可以在一个类进行包装，原逻辑不需要修改。
```
WXSDKInstance wxsdkInstance = WXSDKManager.getInstance().getSDKInstance(instanceId)
if (wxsdkInstance != null) {
    // get rander listener
    final IWXRenderListener listener = wxsdkInstance.getRenderListener(); // TODO
    // wrapper listener
    if (listener != null) {
            wxsdkInstance.registerRenderListener(new WXRenderListenerWrapper(listener));
    } else {
            wxsdkInstance.registerRenderListener(new WXRenderListenerWrapper());
    }
}

WXRenderListenerWrapper implements IWXRenderListener {
    @Override public void onException(WXSDKInstance instance, String errCode, String msg) {
        if (listener != null) {
            listener.onException(instance, errCode, msg);
        }
        // do ...
    }
    ....
}
```

**Comment by wangguanquan** [comment]
补充：以上问题在android sdk

**Comment by zshshr** [comment]
感谢提问，可以提PullRequest上来，我们会评估你的改动

**Comment by wangguanquan** [comment]
对线上项目进行修改时比较有用。
比如我需要在render错误的时候统一将错误信息提交到服务器，如果没有暴露此监听则需要打开原文件然后在onException的时候添加上报代码，相反则只需要添加一个新的类然后通过`WXSDKInstance.getWXRenderListener`拿到此监听，对此监听做一次包装就可以实现此功能，并且对源代码没有侵入性。
PS. 虽然也可以通过反射获得，但暴露出来应该不会有危险

**Comment by YorkShen** [comment]
> 比如我需要在render错误的时候统一将错误信息提交到服务器，如果没有暴露此监听则需要打开原文件然后在onException的时候添加上报代码

* 如果Render出错 *如网络错误、JS执行错误*，sdk底层一定会调用 `RenderListener.onException`。你是在什么场景下，遇到Render出错，且`RenderListener.onException`没有被调用
* 这个接口没有暴露是为了避免weex的Native端使用者错误的调用RenderListener的生命周期函数，如`onException`，导致生命周期被错误的触发。

**Comment by wangguanquan** [comment]
>你是在什么场景下，遇到Render出错，且RenderListener.onException没有被调用

可能是我没有描述清楚，并不是sdk底层没有触发`RenderListener#onException`，是我想在已有项目中添加Render出错时的逻辑。
比如我们线上项目在Render错误时显示一个默认画面，我现在需要在Render错误时显示默认错误并上报错误信息到服务器供开发人员及时修复。
我不想改现有工程代码，想直接通过Application#registerActivityLifecycleCallbacks注册并在onActivityResumed方法中统一通过WXSDKInstance#getRenderListener获得原有的监听，然后再写一个包装类，并在onException方法里实现上报的功能。
伪代码如下：
```
@Override public void onActivityResumed(Activity activity) {
if (activity instanceof IWXRenderListener) {
    // FIXME 在这里获得监听
    final IWXRenderListener listener = wxsdkInstance.getWXRenderListener();
     wxsdkInstance.registerRenderListener(new WXRenderListenerWrapper(listener));
}

//----Render wrapper
public class WXRenderListenerWrapper implements IWXRenderListener {
    private IWXRenderListener listener;
    public WXRenderListenerWrapper (IWXRenderListener listener) {
        this.listener = listener;
    }
...
   
    @Override public void onException(WXSDKInstance instance, String errCode, String msg) {
        // 执行原有逻辑显示默认画面
        if (listener != null) {
            listener.onException(instance, errCode, msg);
        }
        // Track weex render error.
        JSONObject payload = new JSONObject();
        payload.put("className", instance.getContext().getClass().getName());
        payload.put("errCode", errCode);
        payload.put("message", msg);

        // 上报详细信息到服务器通知开发者
        Tracker.track("WEEX_RENDER_ERROR", payload);
    }
}
```

**Comment by YorkShen** [comment]
> 我不想改现有工程代码，想直接通过Application#registerActivityLifecycleCallbacks注册并在onActivityResumed方法中统一通过WXSDKInstance#getRenderListener获得原有的监听，然后再写一个包装类，并在onException方法里实现上报的功能。

依然没有理解，按照给出的代码实例，你添加了一个WXRenderListenerWrapper来执行异常上传逻辑，这个也是改了代码的啊。添加一个新的`WXRenderListenerWrapper`和修改已有的`IWXRenderListener`，本质上没啥区别吧

**Comment by wangguanquan** [comment]
对于修改点来说区别不大，都是加相同逻辑。对于某些应用场景还是比较有用的，比如我们android项目都引用一个common module，我的应用场景就是修改common module在此处添加勾子，对于业务开发部门是无感的，他们仅需升级公共模块的版本，对于非业务功能他们并不需要关心。
我了解你们未暴露此监听的出发点，也赞同你们的顾虑。
目前我们通过反射解决，仅进入画面时反射一次并不会影响速度。
![](https://user-images.githubusercontent.com/16704088/51425213-fe6ca480-1c13-11e9-85fd-fa4ab5aff3e8.png)

**Comment by YorkShen** [comment]
如果是这个场景，建议你们使用Java中的动态代理机制实现`IWXRenderListener`。
