### ISSUE TITLE
0.20.0Demo运行错误

### ISSUE THREAD

**Issue by yxmp** [apache/incubator-weex#1961]
12-25 10:30:01.119 6397-6416/com.alibaba.weex E/WeexCore: failed find class WMBridge
12-25 10:30:01.119 6397-6416/com.alibaba.weex W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bridge.WMLBridge" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/base.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/lib/arm, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/base.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.alibaba.weex-QvB9wLc59ZOVbNcnfgrzJg==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Runtime.nativeLoad(Native Method)
12-25 10:30:01.120 6397-6416/com.alibaba.weex W/System.err:     at java.lang.Runtime.doLoad(Runtime.java:1099)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:140)
        at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:226)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by miomin** [comment]
真正的错误日志应该不是这里，这是打印的警告日志，不会导致程序异常

**Comment by YorkShen** [comment]
This is just a warning, we will remove it in the future release.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow.

**Comment by yxmp** [comment]
好的 谢谢你的回复

在 2019-01-10 11:56:59，"莫绪旻" <notifications@github.com> 写道：


真正的错误日志应该不是这里，这是打印的警告日志，不会导致程序异常
