### ISSUE TITLE
Android scroller  component ,loadmore event  would not be triggered in horizontal  mode 

### ISSUE THREAD

**Issue by leanhunter** [apache/incubator-weex#1962]
- [x] Review the documentation: https://weex.apache.org/index.html
  - [x] Search for existing issues: https://github.com/apache/incubator-weex/issues
  - [x] Use the latest Weex release: https://github.com/apache/incubator-weex/releases

## Describe the bug
Please check dotwe demo below, loadmore event won't be triggered in horizontal mode on Android phones, while it acts well on iOS.

## To Reproduce

http://dotwe.org/vue/343721bb5b5b5a81f7d7bfdb3bc00dcd

## Environment
* Device: [坚果 pro OC105 and maybe on other android phones ]
* OS: [android 7.1.2]
* Version [weex 0.18 +]
* Build from source [no]

**Comment by cnryb** [comment]
fixed by #3025
