### ISSUE TITLE
Android-weex 0.20.x，在插件化框架中强转 PathClassLoader 报错

### ISSUE THREAD

**Issue by joy2helloworld** [apache/incubator-weex#1973]
![image](https://user-images.githubusercontent.com/8622657/50462833-d26a5480-09c2-11e9-8536-68bb62dbc3b0.png)

在部分插件化框架中，classloder是自己构造的，不能强转为PathClassLoader.
我看代码使用PathClassLoader来查找so库地址，是否可开个口子 从外部设置，或者设置classloder。

**Comment by YorkShen** [comment]
This is not supported yet, you can give a PR if you want this feature.
