### ISSUE TITLE
有计划支持v-show吗

### ISSUE THREAD

**Issue by farwolf2010** [apache/incubator-weex#1976]
实际使用发现，v-if会造成闪烁现象，体验不好，另外v-if切换的时候，设置的样式随机性的失效，只有强制绑定样式上去才可以避免，总之是各种bug，我们特别想要v-show这样不占位但是又不会重新创建元素的隐藏

**Comment by kang558** [comment]
+1

**Comment by myeveryheart** [comment]
+1

**Comment by metooweb** [comment]
加上key就好了

**Comment by IDBAI** [comment]
> 加上key就好了

怎么加key？

**Comment by metooweb** [comment]
> > 加上key就好了
> 
> 怎么加key？

就是在 vue element 上面 加上 key 属性呀

**Comment by Hanks10100** [comment]
在 Web 端本身就支持 http://dotwe.org/vue/4adaccbc9820d39cbe4430eab5390653

在客户端支持 `v-show` 依赖底层渲染器支持 `display: none`, 前端框架里本身就支持 v-show 的逻辑， @zshshr 可以评估一下客户端如何支持。

**Comment by YorkShen** [comment]
Not supported yet.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).

**Comment by yuangu** [comment]
@metooweb 怎么加key 啊？在v-if的属性标签上加么？

**Comment by lytasky** [comment]
@zshshr   请问下客户端有支持v-show的计划吗？
