### ISSUE TITLE
[iOS]<refresh> 执行@refresh时,@pullingdown的方法会一直执行,Android不会有这个问题

### ISSUE THREAD

**Issue by Hasten50** [apache/incubator-weex#1979]
如题目:
iOS : 当<refresh>组件执行refresh方法的时候,pullingdown的方法也会一直执行
Andriod不会有这个问题.
Playground :  
http://dotwe.org/vue/dd90b709da081883039d37b0ec7726c4

## Environment
iOS : 
* Device: iPhone 7
* OS: 11.2.5
* Version 0.20.0

Andriod :
* Device: 魅蓝note2
* OS: 5.1
* Version 0.20.0.1

**Comment by wqyfavor** [comment]
已修复https://github.com/apache/incubator-weex/pull/2109
