### ISSUE TITLE
transition not working on weex-sdk 0.19+

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#1980]
Sorry for open a new issue for the same question #1908 ，but the old one is closed and no response anymore.

**Describe the bug**
transition not working on weex-sdk 0.19+ ,i use the latest playground app http://appdownload.alicdn.com/publish/weex_playgroud/latest/weex_playgroud_10006024.apk。

**To Reproduce**
demo
http://dotwe.org/vue/9a25405b1283b6dfd9ee7d56907d50e1

**Environment**
Device: [XIAOMI MI5]
OS: [android 8.0]
Build from source [no]

**Comment by gubaojian** [comment]
![image](https://user-images.githubusercontent.com/2258481/50809456-7bf40300-133e-11e9-8b46-0a59fe88ef5d.png)

**Comment by gubaojian** [comment]
@YorkShen  when update styles, the map is empty

**Comment by chenzefeng09** [comment]
it's partially fixed on 0.24-rc1, this demo show the current problem:http://dotwe.org/vue/b36d0bc8d0d90e8638edf8137c1aedf1

with palyground app build from branch  `release-0.24`

**Comment by chenzefeng09** [comment]
i just notice that `margin-left` is not on the doc, so, it works fine for me now on branch `release-0.24` Thanks for your work! @YorkShen

**Comment by YorkShen** [comment]
It seems this issue is fixed, I will just close it.
