### ISSUE TITLE
ios sdk20.0  profile添加use_frameworks!之后，weex_core的头文件找不到

### ISSUE THREAD

**Issue by farwolf2010** [apache/incubator-weex#1982]
因为业务需求集成了一个swift第三方库，需要在profile中添加use_frameworks!，重新pod install之后，weex_core的头文件全都报找不到
'core/data_render/ast.h' file not found

**Comment by jianhan-he** [comment]
你好，WeexSDK你是源码引用的吗

**Comment by farwolf2010** [comment]
是源码引用的，因为自己改了

**Comment by jianhan-he** [comment]
如果是源码引用，你可以在你工程里的weexsdk.xcconfig文件里，在USER_HEADER_SEARCH_PATHS =  这个后面加入  weex代码路径目录/weex_core/Source

**Comment by wqyfavor** [comment]
谢谢反馈，先关掉了。

**Comment by RicardoYJ** [comment]
同样的问题 并不能解决。。求助

**Comment by RicardoYJ** [comment]
>  同样的问题 并不能解决。。求助

pod引用的 sdk

**Comment by jianhan-he** [comment]
你xcconfig文件里怎么指定头文件路径的

**Comment by RicardoYJ** [comment]
> 你xcconfig文件里怎么指定头文件路径的

${PODS_ROOT}/Headers/Public/WeexSDK/core/**

**Comment by jianhan-he** [comment]
我之前有回复过 USER_HEADER_SEARCH_PATHS = 这个后面加入 weex代码路径目录/weex_core/Source

**Comment by RicardoYJ** [comment]
我的理解是改成这个  ${PODS_ROOT}/WeexSDK/weex_core/Source 然而并不能成功 ，而且pods下面的weex_core文件夹名称也是 WeexCore 我不知道是不是哪里理解错了 谢谢~~

**Comment by jianhan-he** [comment]
就是你实际代码存放weex的路径，把全路径写上去试试看是否可以，应该可以解决问题的
