### ISSUE TITLE
babel compiler 没有弹出询问

### ISSUE THREAD

**Issue by shenmiaoling** [apache/incubator-weex#1983]
## Description
weex create projectname 
弹出的引导没有询问使用哪个 babel 编译器

## Environment

```
$ weex -v
   v1.3.11
 - weexpack : v1.2.7
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```

## Broken Example
 
![2018-12-30 10 48 01](https://user-images.githubusercontent.com/17367714/50543973-01cacc80-0c22-11e9-85cb-4f4f5d748a62.png)

**Comment by erha19** [comment]
@shenmiaoling This issue has been fixed a long time ago, re-create the project would be fixed, that caused by one of the version using babel 7 instead of babel 6, so there were no babel-plugin selections.

Can be close now @zshshr
