### ISSUE TITLE
render error with box-shadow at list   

### ISSUE THREAD

**Issue by cococa** [apache/incubator-weex#1988]
the code  http://dotwe.org/vue/99ff08ce3e0ca3e53f0ad1f812472580

![1546485641260](https://user-images.githubusercontent.com/5626430/50622635-aeba8780-0f49-11e9-838c-7ca9b7313ac3.jpg)

using HUAWEI Android 8.1  Weex Playground App

**Comment by YorkShen** [comment]
We will look into it, not sure when to solve.

**Comment by YorkShen** [comment]
Ref #1684
