### ISSUE TITLE
Android:  the return of method "getRealView" in WXScroller should be 'mRealView'

### ISSUE THREAD

**Issue by or0fun** [apache/incubator-weex#1989]
- [ ] Review the documentation: https://weex.apache.org/index.html
  - [ ] Search for existing issues: https://github.com/apache/incubator-weex/issues
  - [ ] Use the latest Weex release: https://github.com/apache/incubator-weex/releases

## Describe the bug
The return of method "getRealView" in WXScroller should be 'mRealView', which is mScrollerView now.
When I reduce the children of scroller view,  it has no effect now.

## To Reproduce
```vue
<template>
  <div class="wrapper">
    <scroller class="scroller" v-for="(row) in rows" scroll-direction="horizontal">
      <text>{{row.length}}</text>
      <div v-for="(item, index) in row" class="item">
        <text>{{index + item.name}}</text>
      </div>
    </scroller>
    <div @click="changeData" class="button">
      <text>点击</text>
    </div>
  </div>
</template>
```
I reduces item of row in function 'changeData', the length of row changed, but the number of children which displayed didn't change.

## Environment
* Device:  Vivo X9
* OS: Android
* Version  7.1.2
* Build from source  no

## Expected behavior
The number of children in Scroller view should be reduces on the screen when I reduces the number of items.

**Comment by gubaojian** [comment]
you can add one more div in scroller root. which can avoid the bug. the bug has been fixed in the pull request:  https://github.com/apache/incubator-weex/pull/2005
