### ISSUE TITLE
【bug】waterfall瀑布流组件不能动态改变column-count的值

### ISSUE THREAD

**Issue by hulinNeil** [apache/incubator-weex#1995]
问题描述：waterfall瀑布流组件不能动态改变column-count的值，从3列变为2列后就不能变回去了，可重新问题的dotwe地址：[http://dotwe.org/vue/96fcc3687dcfe91f6c5094e482936cc0](http://dotwe.org/vue/96fcc3687dcfe91f6c5094e482936cc0)

**Comment by zshshr** [comment]
@gubaojian please handle this issue

**Comment by gubaojian** [comment]
the bug has been fixed: https://github.com/apache/incubator-weex/pull/2105

**Comment by lyloou** [comment]
The same problem happened on iOS.
