### ISSUE TITLE
刷新组件在不满足条件时，刷新条不会消失

### ISSUE THREAD

**Issue by xiaohp** [apache/incubator-weex#2006]
## Describe the bug
下拉组件的处理函数 `onrefresh`  中，如果` return` 了，页面顶部的刷新条不会消失。
使用的场景：需要控制刷新的频率

## To Reproduce
http://dotwe.org/vue/602447ef81f540a42c114e7c537d5e7b

## Environment
网页版和安卓端 Weex playground app 

## Expected behavior
下拉刷新时，如果不满足条件，释放后页面回弹
只有满足以下条件时才显示刷新条
```js
this.refreshing = true
```

## Screenshots
![image](https://user-images.githubusercontent.com/23056320/50679958-a42ee980-1040-11e9-828f-ed8e4bc265ab.png)

**Comment by julonglu** [comment]
回弹是由refreshing = true和false控制的
需先refreshing=true,然后refreshing=false回弹
状态改变间需要有一定间隔，建议
this.refreshing = true
setTimeout(()=>{this.refreshing=false},10)

**Comment by xiaohp** [comment]
> 回弹是由refreshing = true和false控制的
> 需先refreshing=true,然后refreshing=false回弹
> 状态改变间需要有一定间隔，建议
> this.refreshing = true
> setTimeout(()=>{this.refreshing=false},10)

谢谢
