### ISSUE TITLE
Not able to validate WeexSDK.podspec

### ISSUE THREAD

**Issue by brahmapaytm** [apache/incubator-weex#2018]
- [ ] Review the documentation: https://weex.apache.org/index.html
  - [ ] Search for existing issues: https://github.com/apache/incubator-weex/issues
  - [ ] Use the latest Weex release: https://github.com/apache/incubator-weex/releases

## Describe the bug
I am trying to fork your repo to do some changes. If i am trying to validate WeexSDK.podspec file, it is throwing an error **fatal error: 'core/data_render/vnode/vnode_render_context.h' file not found**

## To Reproduce
use command **pod lib lint WeexSDK.podspec --allow-warnings**.
I also cloned your repo incubator-weex and tried validating podspec file, but it is throwing same error.

Can you please help me here ?

**Comment by jianhan-he** [comment]
The file of weexsdk.xcconfig  ，USER_HEADER_SEARCH_PATHS = " your weex code path/weex_core/Source"

**Comment by wqyfavor** [comment]
谢谢反馈，先关掉了。
