### ISSUE TITLE
toast - 稍快点击时， IOS延迟显示，Android不显示

### ISSUE THREAD

**Issue by xufuping** [apache/incubator-weex#2022]
## Describe the bug
toast - 稍快点击时， IOS延迟显示，Android不显示

Toast - When clicked a little faster, IOS was delayed and Android was not displayed

## To Reproduce
http://dotwe.org/vue/c21e12c72f9833bc1edf3e8868f1d15a

## Environment
[iPhone6]、[Android9.0]

## Expected behavior
Whether the click speed is fast or slow, when the user clicks on it, Toast will display normally.
不管点击速度多块多慢，每一次点击都正常显示toast。

**Comment by zshshr** [comment]
toast是系统行为，可以设置延迟来优化一下，用户展示的体验；

**Comment by wqyfavor** [comment]
toast有delay，duration等控制，本身就不能支持连续显示。

**Comment by Z-Janp** [comment]
Android 9遇到了同样的问题，toast完全不显示。
设备机型: 联想Z5s(L78071)
@wqyfavor

**Comment by DorisOu** [comment]
@wqyfavor 问题解决了吗
