### ISSUE TITLE
想请教关于解决WeexSDK deadlock的思路

### ISSUE THREAD

**Issue by lixiangsanxun** [apache/incubator-weex#2035]
hello,我在WeexSDK的提交记录里找到了解决因为[WXSDKInstance dealloc]和[WXJSCoreBridge dealloc]偶现死锁的两个commit
https://github.com/apache/incubator-weex/commit/d25ed7af3b3527310336d0d2308e7dec8a5fca12#diff-b93d75ed1315a84c9300d2afc84e24a8

https://github.com/apache/incubator-weex/commit/78b887ce8256d3e13c3cfa0294c286db05efccb9

通过这个两个commit的修改内容，也解决我遇到的死锁问题。不过我看了代码后还是有些疑问，
第一是为什么在WXThreadSafeMutableDictionary  removeObjectForKey加锁期间，WXSDKInstance delloc会触发死锁；
第二是为什么WXJSCoreBridge在主线程释放会造成死锁。
查了一下资料，还是不怎么明白，WeexSDK项目组的研发大大们能否指点迷津，不胜感激

**Comment by AntiMoron** [comment]
原意是加了一个远程配置，实验性测试在非主线程removeInstance能性能效果。你这样只是把配置项改为不生效强制在主线程removeInstance了。死锁详情还要从整体机制判断

**Comment by wqyfavor** [comment]
最新版本已经修复这些问题了，不会死锁了，也没有之前的那些配置。

**Comment by wqyfavor** [comment]
WXThreadSafeMutableDictionary的removeObjectForKey引发死锁是因为在WXThreadSafeMutableDictionary的锁里面对象被释放，之后一些逻辑导致又调用到WXThreadSafeMutableDictionary的方法里了导致死锁。现在WXThreadSafeMutableDictionary里被移除的对象被临时变量持有一下，在锁外面释放了。

**Comment by wqyfavor** [comment]
WXJSCoreBridge在主线程释放会死锁是因为JSC里面的锁导致的，比如在主线程释放时进入了JSC的锁，但此时在js线程里有callNative什么的调用，就有可能死锁。现在WXJSCoreBridge也改到JS线程释放了。
