### ISSUE TITLE
我的sdk为0.20.3.0-beta，debug会报错

### ISSUE THREAD

**Issue by zkj881225** [apache/incubator-weex#2041]
修改gradle：compile 'com.taobao.android:weex_inspector:0.18.10'
然后启动app，成功。

但是启动debug页面的remoteDebug后，出现错误，而且app也打不开了。
![image](https://user-images.githubusercontent.com/33045988/51024875-9b509180-15c5-11e9-9260-4280747141da.png)

如上图所示：
我之前用的sdk为0.18.0的时候可以正常调试，现在求指教怎么能成功调试。

**Comment by erha19** [comment]
@zkj881225 try `weex update weex-debugger@latest`.

**Comment by zkj881225** [comment]
仍然不行，我的 weex-debugger版本是1.2.8，运行命令更行后，还是1.2.8，还是会报上面的错误

**Comment by zkj881225** [comment]
@erha19  还有别的解决方式吗？大佬

**Comment by erha19** [comment]
@zkj881225 change your gradle dependence like this
```
weex_sdk: 0.20.3.0-beta
weex_inspector: 0.20.3.0-beta
```

**Comment by zkj881225** [comment]
我改回0.18了,这个解决方案等项目弄完了再测试。。
