### ISSUE TITLE
集成阿里安全组件securityguardaar后渲染报错wx_create_instance_error

### ISSUE THREAD

**Issue by julonglu** [apache/incubator-weex#2042]
组件集成
compile 'com.taobao.android:securityguardaar3:5.1.81@aar
报错类  com.taobao.weex.bridge.WXBridgeManager
行数1523 
报错代码 mWXBridge.initFramework(framework, assembleDefaultOptions())
weex版本 0.16.0 
换 0.20.0测试没问题，升级估计要改好多扩展

**Comment by zshshr** [comment]
版本跨度太大，请升级吧
