### ISSUE TITLE
https://market.dotwe.org/ 打不开为何官方一直不处理

### ISSUE THREAD

**Issue by Ivorzk** [apache/incubator-weex#2045]
https://market.dotwe.org/  此url已经失效，为何官方一直挂在官网上，多少人看到这个会心寒？
请问是认真的吗？

**Comment by jianhan-he** [comment]
你好，请问官网哪里有写这个网址，能否发个链接，我们修改下文档

**Comment by Ivorzk** [comment]
http://weex.apache.org/cn/resources.html  这个地址里面 "组件和模块" 部分 有market的入口，
官方market的入口，我一直没找到，能把入口放出来么，百度也搜不到

**Comment by zshshr** [comment]
最新文档已经更新一波，近期会切换过去，关注 http://weex.io

**Comment by taichen** [comment]
插件市场还是没有，想使用svg插件跟扫描插件
