### ISSUE TITLE
希望能支持图表插件

### ISSUE THREAD

**Issue by ibutterfly** [apache/incubator-weex#2054]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chenzefeng09** [comment]
买
http://weex.io/zh/community/biz-component-map.html

**Comment by ibutterfly** [comment]
> 买
> http://weex.io/zh/community/biz-component-map.html
多少钱

**Comment by chenzefeng09** [comment]
看看这个能不能给你些灵感
https://github.com/alibaba/GCanvas/issues/46

**Comment by zshshr** [comment]
Welcome community contribution

**Comment by YorkShen** [comment]
Not supported officially, maybe some third-party plugin supports it

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list)
