### ISSUE TITLE
indicator需要支持样式自定义

### ISSUE THREAD

**Issue by otakuXv** [apache/incubator-weex#2057]
目前indicator的选中状态样式只支持item-selected-color,包括为选中状态支持item-color。
期望样式可以支持自定义

**Comment by AntiMoron** [comment]
你这个issue感觉提问太笼统，什么是indicator？ 是你们自己写的组件吗？ 那这个应该跟组件作者去讲不是weex框架本身。

**Comment by YorkShen** [comment]
暂未列入排期

欢迎提PR，我们来Review

Pull Request is welcomed

**Comment by YorkShen** [comment]
Not supported yet.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
