### ISSUE TITLE
Android WXImage组件在可见状态和隐藏状态会自动刷新

### ISSUE THREAD

**Issue by leonWenAYG** [apache/incubator-weex#2058]
## Describe the bug
Android WXImage组件在加载完图片后，如果进入下一个界面，再退回来，WXImage组件在可见状态和隐藏状态切换时会刷新图片，在恢复可见状态时，会触发 autoRecoverImage()方法来重新加载图片，这样浪费资源而且还体验不好，我看到这个方法里有一句
if(mAutoRecycle) {
      setSrc(mSrc);
 }
而 WXImage的方法中 有一个setProperty(String key, Object param) 方法，可以设置该属性
mAutoRecycle = WXUtils.getBoolean(param, mAutoRecycle);
所以我想知道，如何调用setProperty方法，来设置我的weex image不自动刷新图片

## Environment
* Device: 华为p20
* OS: Android 8.1
* Version 0.19.0
* Build from source yes

**Comment by seewhy163** [comment]
给image标签加个  `auto-bitmap-recycle="false"`属性

**Comment by YorkShen** [comment]
图片在不见的时候自动回收，在可见的时候重新加载，这个主要是为了节省内存考虑，毕竟图片不可见了，还占着内存也不太合理。如果不需要这个特性，可以设置`auto-bitmap-recycle="false"`
