### ISSUE TITLE
【iOS】使用animation.transition修改image宽高crash

### ISSUE THREAD

**Issue by winfredgit** [apache/incubator-weex#2064]
## Describe the bug
下载完远程图片后，使用animation.transition修改image宽高，在iOS端WXTransition类会发生crash。

## To Reproduce
多张图片从网络请求下载，load事件后使用animation.transition修改image宽高，在iOS设备运行，一次没崩溃，返回进入多试几次，必崩溃。
*** -[WXTransition transitionOptions]: message sent to deallocated instance 0x600001915d00

## Environment
* Device: [iPhone7、iPhone X、模拟器]
* OS: [iOS12]
* Version [0.20.1、0.20.3.0-beta]

## Screenshots
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/8896273/51370966-ba09d780-1b33-11e9-9f8e-35ea7351985d.png">

**Comment by wqyfavor** [comment]
已修复，谢谢反馈。https://github.com/apache/incubator-weex/pull/2111

**Comment by winfredgit** [comment]
> 已修复，谢谢反馈。#2111

但cocoapods还没有发布修复后的版本是吗？
