### ISSUE TITLE
安装weex create成功后，weex debug可以启动，但是点击二维码提示“模拟器调试暂不可使用”

### ISSUE THREAD

**Issue by hponiang** [apache/incubator-weex#2065]
## Description
安装weex create成功后，weex debug可以启动，但是点击二维码提示“模拟器调试暂不可使用”

## Environment

50-1-61-231:awesomeapp apple$ weex -v
   v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.2.8
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

50-1-61-231:awesomeapp apple$ npm -v
-6.5.0

**Comment by erha19** [comment]
@hponiang 如页面提示，请使用真机使用Playgroound APP进行扫码调试，文档见 [如何链接](http://weex-project.io/cn/tools/toolkit.html#lian-jie-she-bei)

**Comment by hponiang** [comment]
有使用真机测试，后面发现了问题，使用ifconfig查看IP地址如下：
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	inet 10.6.6.6 netmask 0xff000000 
	nd6 options=201<PERFORMNUD,DAD>
```
系统默认使用了10.6.6.6 作为服务器地址，当使用手机的app扫描时，虽然在同一局域但是手机是无法访问10.6.6.6，后面使用
`weex debug --host 172.168.1.23 `
可以正常使用

**Comment by hponiang** [comment]
建立官方开启debug时使用en0的地址
