### ISSUE TITLE
textarea的高度能自适应吗

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#2067]
目前textarea的高度只能通过rows明确指定。但输入框场景交互经常是多行输入根据输入内容的长度，控件高度自适应调整，目前用weex没发实现。

**Comment by YorkShen** [comment]
Not supported yet

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).

**Comment by YorkShen** [comment]
Not supported yet.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list).
