### ISSUE TITLE
richtext中文字在ios端显示不出来

### ISSUE THREAD

**Issue by qzcsgs** [apache/incubator-weex#2068]
下面这段代码在ios端一个字都显示不出来
```html
<richtext :style="{'border-width': '1px', height: '100px', 'background-color': 'red'}">
    sdsdfss
    <span :style="{color: '#333', 'font-size': '30px'}">asdasd</span>
    <a :style="{color: '#333', 'font-size': '30px'}">asdasd</a>
</richtext>
```
macOS v10.13.4
weex v1.3.11
weexpack : v1.2.7
weex-builder : v0.4.0
weex-previewer : v1.5.1

**Comment by wqyfavor** [comment]
你的代码试过了，可以显示出来，但是样式不对，估计前端编译时有问题。

用下面代码是正常的，且iOS与Android一致，麻烦再试一下。
<richtext style="border:1px;height:100px;background-color:red">
    sdsdfss
    <span style="color:#333;font-size:30px">asdasd</span>
    <a style="color:#333;font-size:50px">asdasd</a>
</richtext>

**Comment by qzcsgs** [comment]
@wqyfavor 谢谢，我还没有找到失效的原因，但是我已经放弃使用 `richtext` 了
