### ISSUE TITLE
weex如何使用worker 多线程呢

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#2073]
网路请求使用async await（使用promise+then也是会卡住） 导致页面渲染也会被卡住，有什么方式实现请求在子线程呢

**Comment by Darin726** [comment]
请提供一个 demo 哈, 我们排查一下

**Comment by fanlvwen** [comment]
> 请提供一个 demo 哈, 我们排查一下

页面上只有一个list，有两个接口请求数据源，谁先拿到数据用哪个接口，这是背景
` <div class="wrapList">
            <list ref="listt" style="flex: 1" v-if="!showNoData && !isShowTransferEntranceView"
                  @loadmore="loadMoreEvent"
                  @scroll="onScroll" @scrollstart="onScrollstart" @scrollend="onScrollend">
                <cell v-for="item in itemList" v-if="!showNoData">
                    <s_item :s='item' ></s_item>
                </cell>
            </list>
        </div>`

js:
`  queryList() {
                let self = this;
                this.refreshing = true;
                tip.showLoading('查询中');
                let t1 = new Date().getTime()
                console.log('开始请求时间11：',new Date().getTime())
                getTrainList(xxx, (list) => {
                        let t2 = new Date().getTime()
                        console.log("列表拿到数据耗时：", t2 - t1, 'ms')
                        console.log("tList:", list.length);
                        self.dealList(list);
                    });
            },`

`getTrainList(){
 // setTimeout(() => {
        mobileTicketService.queryTrainList(xxx).then(ticketList => {
            let t2 = new Date().getTime()
            console.log('接口返回数据时间111：',new Date().getTime())
            if (!isListEmpty(ticketList)) {
                loaded(ticketList, callBack, true);//此处拿到数据
            }
        });
    // }, 1)
    // setTimeout(() => {
        ticketQueryService.queryTicket(xxx).then(ticketList => {
            loaded(ticketList, callBack);//此处拿到数据
        });
    // }, 1)
}`
`mobileTicketService.queryTrainList()里面是一个async/await,
ticketQueryService.queryTicket()里面有两个await
现象就是list会在ticketQueryService.queryTicket()的第一个await返回数据之后才渲染，而在这之前ticketQueryService.queryTicket()已经拿到数据了
`

**Comment by fanlvwen** [comment]
weex能不能类似java一样，有开启线程方法呢？
我这边多次测试发现，网络请求应该是阻塞了渲染的。

**Comment by YorkShen** [comment]
目前worker特性还不支持，js只能运行在单线程上。
