### ISSUE TITLE
【iOS bug】0.20.1 版本 iconfont 无法显示

### ISSUE THREAD

**Issue by xiaohuapunk** [apache/incubator-weex#2074]
**iOS 0.20.1版本sdk iconfont 无法显示 测试例子：** http://dotwe.org/vue/4641bfd0ab806674d62cb00a9ad2dddb 

初步判断是 WXUtility.m 文件中的 `+ (UIFont *)fontWithSize:(CGFloat)size textWeight:(CGFloat)textWeight textStyle:(WXTextStyle)textStyle fontFamily:(NSString *)fontFamily scaleFactor:(CGFloat)scaleFactor useCoreText:(BOOL)useCoreText` 方法有问题，将0.18.0 版本的实现代码拿过来是可以正常显示的，期待官方修复此问题

**Comment by wqyfavor** [comment]
因为这个demo里的iconfont字体名（存储在font file里）都是"iconfont"，所以显示不出来。请参考文档：http://weex.io/zh/docs/components/text.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AD%97%E4%BD%93
