### ISSUE TITLE
[iOS]iOS weex 在WXCoreBridge类中子线程做了UI操作

### ISSUE THREAD

**Issue by fanglinwei** [apache/incubator-weex#2078]
1.Your development environment（weex、weex-toolkit、system and more).

iOS weex 0.20.1
iOS weex 在WXCoreBridge类中子线程做了UI操作

2.Expected behavior and actual behavior.

![](https://user-images.githubusercontent.com/16839723/51009924-00d45c00-158d-11e9-97fc-41d82a68bdf6.png)

**Comment by wqyfavor** [comment]
已修复，iOS其实不需要这个变量。https://github.com/apache/incubator-weex/pull/2108
