### ISSUE TITLE
swift动态库问题

### ISSUE THREAD

**Issue by fanglinwei** [apache/incubator-weex#2082]
* weex 0.20.1

在oc中采用的静态库编译 ,  但是swift集成pod必须使用use_frameworks!动态库集成
因此拿不到WXComponent+Events.h里面的函数, 希望可以兼容swift把一些需要的头文件提供出来

**Comment by zshshr** [comment]
需要什么头文件，可以提 pr 上来， @wqyfavor 帮忙review

**Comment by wqyfavor** [comment]
WXComponent+Events.h这个头文件里没什么东西，不知道你为什么需要这个头文件。
Swift集成我试了，没什么问题，你可以把需要的头文件整理出来，重新提个issue。我们评估一下。
这个问题先关闭了。
