### ISSUE TITLE
weex version = "0.20.0.1"，android崩溃

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#2086]
weex version = "0.20.0.1"；
debugger：
    compile 'com.taobao.android:weex_inspector:0.18.10'
    compile 'com.github.shenyuanqing.zxing:zxing-simplify:1.0.5'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-ws:2.3.0'

启动app闪退，错误日志如下：
![image](https://user-images.githubusercontent.com/36951996/51810956-b9b4cd80-22e5-11e9-93e2-0db9f292e5c9.png)

**Comment by fanlvwen** [comment]
weex_inspetor升级成最新版
 compile 'com.taobao.android:weex_inspector:0.18.68'
不崩溃了，但是debugger连不上，
![image](https://user-images.githubusercontent.com/36951996/51817008-0b6c5080-2304-11e9-8ab1-d4b94ce25422.png)

**Comment by erha19** [comment]
@fanlvwen please use `weex-debugger` but not `weex-devtool`, you can upgrade your `weex-toolkit` via `npm i weex-toolkit@latest -g`, also you can use the alpha version via `npm i weex-toolkit@alpha -g`.

To integrate devtool SDK, you can use the version below:
```
weex_sdk: 0.20.3.0-beta
weex_inspector: 0.20.3.0-beta
```
That's the devtool SDK which playground app using now.

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/52529319-9993fe00-2d2a-11e9-9dbe-49dac51c9fd8.png)
开启weex项目的debugger就爆内存了，所以才用的devtool
内存溢出之后，尝试使用网上的解决方案都无效
@erha19

**Comment by erha19** [comment]
@fanlvwen 这个主要是由于文件数太多导致的编译期内存泄露问题，一般我们建议通过weex-debugger去编译单个或少数文件来进行便捷的编译服务，weex-debugger中只会提供基础的编译配置，这意味着一旦文件数量增多，编译耗时会随之增加，编译的过程也可能由于某些文件的错误被中断，让问题边的更难以定位。

你这种情况我建议你不要使用weex-debugger中的编译能力进行项目编译（或者指定粒度更小的文件夹，如src/component/xxx）, 更加良好的方式是建立项目内的构建体系，通过本地的webpack配置你的项目构建流程，具体的项目可参考 weex create 命令创建出的项目。

**Comment by fanlvwen** [comment]
> @fanlvwen 这个主要是由于文件数太多导致的编译期内存泄露问题，一般我们建议通过weex-debugger去编译单个或少数文件来进行便捷的编译服务，weex-debugger中只会提供基础的编译配置，这意味着一旦文件数量增多，编译耗时会随之增加，编译的过程也可能由于某些文件的错误被中断，让问题边的更难以定位。
> 
> 你这种情况我建议你不要使用weex-debugger中的编译能力进行项目编译（或者指定粒度更小的文件夹，如src/component/xxx）, 更加良好的方式是建立项目内的构建体系，通过本地的webpack配置你的项目构建流程，具体的项目可参考 weex create 命令创建出的项目。

感谢回答，还是想再请问为什么devtool@v0.3.2-beta.7 是可以正常的debug呢？

**Comment by erha19** [comment]
@fanlvwen 编译问题按道理不会影响调试流程，只是在后续的`weex-debugger`设计中，把编译逻辑作为前置的判断，编译失败->导致工具无法启动，所以你才调试不了，这块在新的工具里会进行调整。

**Comment by fanlvwen** [comment]
@erha19 好的谢谢，那我等weex-debugger升级

**Comment by YorkShen** [comment]
It seems like this issue has been resolved.

I will close this issue, feel free to reopen if there is anything need to update.
