### ISSUE TITLE
改动的一些建议

### ISSUE THREAD

**Issue by julonglu** [apache/incubator-weex#2092]
- (void)_checkPageName
{
    if (nil == self.pageName || [self.pageName isEqualToString:@""]) {
        NSURLComponents *components = [[NSURLComponents alloc] initWithString:self.scriptURL.absoluteString];
        [components.queryItems enumerateObjectsUsingBlock:^(NSURLQueryItem * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            if([obj.name isEqualToString:@"pageName"]){
                self.pageName  = obj.value;
            }
            NSLog(@"%@=%@",obj.name,obj.value);
        }];
//        self.pageName = [self.scriptURL isFileURL] ? self.scriptURL.path.lastPathComponent: self.scriptURL.absoluteString;
    }
    if (nil == self.pageName || [self.pageName isEqualToString:@""]) {
//        self.pageName = NSStringFromClass(self.viewController.class)?:@"unkonwPageCauseUnsetNameAndUrlAndVc";
        self.pageName = @"indexpage";
    }
}

以上改为将路径中所携带的参数pageName作为页面名称，避免出现一长串的URL路径作为页面名称

[self fireGlobalEvent:WX_APPLICATION_DID_BECOME_ACTIVE params:nil];
[self fireGlobalEvent:WX_APPLICATION_WILL_RESIGN_ACTIVE params:nil];

以上两处为何不改为以下这样处理，以下这种方式可以知道前后台切换时，当前用户正在浏览哪一个页面，可以作出细致的处理

NSDictionary *params = @{@"pageName": self.pageName};
[self fireGlobalEvent:WX_APPLICATION_DID_BECOME_ACTIVE params:params];
[self fireGlobalEvent:WX_APPLICATION_WILL_RESIGN_ACTIVE params:params];

**Comment by wqyfavor** [comment]
pageName这个东西在淘宝里改动影响可能比较大，所以暂时不能改了。如果在你的app里要定制，可以给WXSDKInstance加个category，覆盖这个方法好了。
