### ISSUE TITLE
市场打不开 https://market.dotwe.org/

### ISSUE THREAD

**Issue by tianliang211** [apache/incubator-weex#2094]
市场打不开 https://market.dotwe.org/
相同的issue：[https://github.com/apache/incubator-weex/issues/2045]
这个issue被 @zshshr 关闭并要求访问[http://weex.io] ，但是这个站点又没备案。要不要给个ip访问。

尊敬的用户，您好

很抱歉，该网站暂时无法访问，可能由以下原因导致：

原因一：未备案或未接入；根据《非经营性互联网信息服务备案管理办法》，网站需要完成备案或接入。

原因二：网站内容与备案信息不符或备案信息不准确；根据《非经营性互联网信息服务备案管理办法》，网站内容需要与备案信息一致，且备案信息需真实有效。建议网站管理员尽快修改网站信息。

**Comment by wqyfavor** [comment]
市场页面我们会尽快建立，先用https://weex.io访问，谢谢反馈。
