### ISSUE TITLE
weex.io   https://market.dotwe.org/ 无法打开

### ISSUE THREAD

**Issue by Ivorzk** [apache/incubator-weex#2100]
上次我已经反馈过，到现在应该2个星期过去了，官方对外开放的链接能不能弄好一点啊，随便开，随便关，
我上次反馈打不开的时候，官方让我关注 weex.io  好我关注这个，新的官网很不错，比http://weex.apache.org 这个好看多了，也更方便阅读了，但是过了2个星期 weex.io 又打不开了，大家都是成年人，能弄点靠谱的事情不？既然你对外开放，这个就相当于你的产品身份证，别人也只能通过这些入口来了解贵公司的产品，但是这样一会打得开，一会打不开，会让人对weex很失望的，即使你功能做的差一点也没关系，但是要保证稳定啊，这样真的让人感觉开发weex的这些哥们,就像闹着玩似的，说不一定那一天脑子一热又去搞别的了，然后weex又不维护了。

要换地址可以，要做好善后处理好吧！程序员大哥们能用产品的心态去对待工作和生活么？

**Comment by erha19** [comment]
@Ivorzk 前两天由于阿里云针对.io域名的备案限制，网站的访问被过滤了，目前只有https站点可以访问，你可以访问  https://weex.io，后续针对http的网站会有对应策略处理。

**Comment by wqyfavor** [comment]
谢谢反馈，先用https://weex.io。市场页面我们会尽管建立。
