### ISSUE TITLE
[iOS] webpack.common.conf.js 没有初始化 process.env ,渲染页面失败

### ISSUE THREAD

**Issue by Hasten50** [apache/incubator-weex#2101]
当升级了WeexSDK-> 19.0.2后,没有初始化 process.env会直接白屏
看到很多同学都说降级回18是没有事
但是我想说,遇到问题不应该是提供解决方案吗,而不是首先采取降级方案吧
开源代码,可以尝试让用户先在源码上考虑处理吧?

* Device: [iPhone7]
* OS: [iOS11.2.5]
* Version [19.0.2]

**Comment by wqyfavor** [comment]
没理解具体什么问题，麻烦提供个demo，或描述得更详细一些。

**Comment by YorkShen** [comment]
As this thread is not updated for a month, I will just close it.

Feel free to reopen it with a demo.
