### ISSUE TITLE
weex debug 不能用了

### ISSUE THREAD

**Issue by farwolf2010** [apache/incubator-weex#2102]
weex debug 不能用了
sdk 20.0 wxdevtool 20.1 weex debugger 1.2.8 
ios 扫描二维码，打开debug之后，没有出现js代码，再把网络打开，app直接崩溃

**Comment by erha19** [comment]
@farwolf2010 please provide more detail about this issue, it can help me or other people know how you encountered this problem. like the sdk version  (suorce code or cocopod), crash stack and so on.

Thanks.

**Comment by farwolf2010** [comment]
ios sdk0.20 weex-debugger 1.2.8  wxdevtool 20.1 扫描debug的二维码，点击开启debug，不能显示出js代码，继续点击网络的开关，app崩溃

**Comment by erha19** [comment]
@farwolf2010 The WXDevtool 0.20.1 doesn't published, maybe you are using source code on `weex-devtool-iOS/#release/0.21.0` and the latest WeexSDK code on the master branch.

I use the source code below, it works on my iphone 7 plus,  maybe you can check if you have use correct code
1. [Playground demo source](https://github.com/apache/incubator-weex/tree/master/ios/playground).
2. [iOS Devtool SDK source](https://github.com/weexteam/weex-devtool-iOS/tree/release/0.21.0).
3. [Weex SDK]((https://github.com/apache/incubator-weex/).

**Comment by farwolf2010** [comment]
我使用上面提供的地址，试了，还是不行，1和3不是重复的吗，使用的是iphone8,xcode10.1

**Comment by erha19** [comment]
@farwolf2010 that's the podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', '0.20.0'
    pod 'WXDevtool', '0.20.1'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1',:configurations => ['Debug']
    pod 'BindingX', '1.0.3'
    
    # WeexGcanvas is added by Weex Plugin, more info at https://market.dotwe.org/ext/list.htm
    #pod 'WeexGcanvas'
end

target 'WeexDemo' do
    common
end

target 'WeexUITestDemo' do
    common
end

```

**Comment by erha19** [comment]
@wqyfavor This is due to the wrong SDK integration version, can be closed now.
