### ISSUE TITLE
Screen orientation problem with iPad version of our app

### ISSUE THREAD

**Issue by ginuim** [apache/incubator-weex#2103]
## Description

Our latest version of app works well on the iPad in portrait, but the page size cannot be recalculated when changed to landscape.

How can we resize the instance view when screen orientation change?

Thank you～

![](http://img.reaidea.com/ipad0.jpg)
![](http://img.reaidea.com/ipad.jpg)

**Comment by MappleHero** [comment]
The way we try to solve this problem is very complicated.
In two steps
In the first step, the Native side hooks the viewDidLoad method of the WXBaseViewController of the Weex page, adding a monitor for screen rotation.

```
[[NSNotificationCenter defaultCenter] addObserver:self 
                              selector:@selector(onDeviceOrientationChange) 
                              name:UIDeviceOrientationDidChangeNotification object:nil];
```



``` 
- (void)onDeviceOrientationChange {
    if (UIDeviceOrientationIsLandscape([UIDevice currentDevice].orientation)) {
//        不起作用
//        [self.view setNeedsLayout];
//        [self.view layoutIfNeeded]; 
//        [self.view.subviews[0] layoutIfNeeded];
//        [self.view.subviews[0] setNeedsLayout];
        self.view.subviews[0].frame = CGRectMake(self.view.subviews[0].frame.origin.x, self.view.subviews[0].frame.origin.y, GKT_SCREEN_WIDTH, GKT_SCREEN_HEIGHT);
        self.view.subviews[0].subviews[0].frame = CGRectMake(self.view.subviews[0].subviews[0].frame.origin.x, self.view.subviews[0].subviews[0].frame.origin.y, GKT_SCREEN_WIDTH, GKT_SCREEN_HEIGHT);
    } else {
        self.view.subviews[0].frame = CGRectMake(self.view.subviews[0].frame.origin.x, self.view.subviews[0].frame.origin.y, GKT_SCREEN_WIDTH, GKT_SCREEN_HEIGHT);
        self.view.subviews[0].subviews[0].frame = CGRectMake(self.view.subviews[0].subviews[0].frame.origin.x, self.view.subviews[0].subviews[0].frame.origin.y, GKT_SCREEN_WIDTH, GKT_SCREEN_HEIGHT);
    }
}
```

![wechatimg2](https://user-images.githubusercontent.com/4251420/52160767-181ee900-26f6-11e9-8296-ad2a5f1be02f.jpeg)

Because Weex can't dynamically update the page frame，native side manual update the WXRootView and WXView frame.

The second step is to listen to the notification on the Weex side and modify the page frame.

But this method is not elegant, I hope there is a better way.

**Comment by wqyfavor** [comment]
最新PR里修复了setViewport 方法，并提供了修改WeexCore计算时使用的屏幕宽度的方法。
https://github.com/apache/incubator-weex/pull/2107

文档待更新，可以先看：

## 6. 在 iPad 中使用 Weex

当页面渲染完成后，屏幕再旋转，页面不会自动适配。所以，如果你的 App 允许屏幕旋转，务必在页面渲染前更新屏幕宽度。

前端样式中指定的坐标在渲染时会根据 **屏幕宽度** 和 **当前页面的 view-port-width** 进行换算。

修改 view-port-width 的方法，会影响前端代码，通常不要设置，默认为 750px。
```javascript
beforeCreate(){
    const meta = weex.requireModule('meta');
    meta.setViewport({
        width: 1536
    });
}
```

监听 UIDeviceOrientationDidChangeNotification 通知，并调用下面方法修改屏幕尺寸（假设已经旋转完成，[UIScreen mainScreen].bounds.size.width 就是当前宽度）
```Objective-C
[WXCoreBridge setDeviceSize:[UIScreen mainScreen].bounds.size];
```

**Comment by frankLifexg** [comment]
@wqyfavor 下边WXCoreBridge的原生方法没有合到分支里

**Comment by ginuim** [comment]
@wqyfavor 新春快乐！我们现在最大的问题就是要页面渲染完成之后用户还可能随时旋转屏幕切换横竖屏，页面要自适应屏幕尺寸。

我们的 App 有大量的视频课程，用户可能会竖屏看完文章再横屏看视频课，尤其是 iPad Pro 用户往往会配置一个外接键盘，在各种场景下随意切换我们的 App 横竖屏状态。

不知道有没有什么好办法解决渲染完成后旋转屏幕页面重新适应屏幕尺寸？

**Comment by wqyfavor** [comment]
> @wqyfavor 新春快乐！我们现在最大的问题就是要页面渲染完成之后用户还可能随时旋转屏幕切换横竖屏，页面要自适应屏幕尺寸。
> 
> 我们的 App 有大量的视频课程，用户可能会竖屏看完文章再横屏看视频课，尤其是 iPad Pro 用户往往会配置一个外接键盘，在各种场景下随意切换我们的 App 横竖屏状态。
> 
> 不知道有没有什么好办法解决渲染完成后旋转屏幕页面重新适应屏幕尺寸？

这个需要想一下怎么办。因为元素styles里的宽、高、top、left等信息是创建时根据屏幕宽度和view-port计算的，当旋转后，并不是简单的重新触发排版就可以，需要根据js里的原始的style信息重新计算。如果页面已经发生变化，就很不好办了。

**Comment by ginuim** [comment]
> > @wqyfavor 新春快乐！我们现在最大的问题就是要页面渲染完成之后用户还可能随时旋转屏幕切换横竖屏，页面要自适应屏幕尺寸。
> > 我们的 App 有大量的视频课程，用户可能会竖屏看完文章再横屏看视频课，尤其是 iPad Pro 用户往往会配置一个外接键盘，在各种场景下随意切换我们的 App 横竖屏状态。
> > 不知道有没有什么好办法解决渲染完成后旋转屏幕页面重新适应屏幕尺寸？
> 
> 这个需要想一下怎么办。因为元素styles里的宽、高、top、left等信息是创建时根据屏幕宽度和view-port计算的，当旋转后，并不是简单的重新触发排版就可以，需要根据js里的原始的style信息重新计算。如果页面已经发生变化，就很不好办了。

感谢回复！这个难度确实很大，深表理解。

我们之前也确实没有考虑过这种问题，最近好多用户哭着喊着要 iPad 版本，方便他们观看视频课程，我们适配了一下才发现坑太多了……

**Comment by aixiaoxiang** [comment]
期待Weex 团队解决这个问题。

**Comment by dseeker** [comment]
was having the same issue and addressed it without going into the OS specific code, just by forcing a refresh on a component. here's how:
1. bind some global variable to a component's key
```
<template lang="pug">
.wrapper
    router-view(:key="store.resetView") # store.resetView initializes as integer = 0
</template>
```
2. Install Nat.js Library _(maybe it can be done without, but I need it anyway for other things)_
3. create orientation variable in store and set interval polling of Nat.screen.orientation.status every 500ms
4. compare current orientation value with the one in store, if different, add 1 to resetView
```
<script lang="coffee">
module.exports =
    methods:
        initialize: ->
            Nat.screen.orientation.status (err, ret) =>
                if @orientation != ret.orientation
                    ++@store.resetView
</script>
```

this will force the component to refresh every time a screen rotation is detected by the Nat component
