### ISSUE TITLE
0.20.1 版本为什么会含有 alipay 相关字段

### ISSUE THREAD

**Issue by hanl001** [apache/incubator-weex#2104]
![image](https://user-images.githubusercontent.com/20555225/52159408-2b728a00-26df-11e9-8fdc-6b9a6d741c43.png)
请问一下，这个会不会被机器扫描到认为含有3方支付？

**Comment by Hanks10100** [comment]
这部分代码相当于是一份模块“白名单”之类的东西，并不涉及 alipay 相关的逻辑。

**Comment by YorkShen** [comment]
I will close this as it seems resolved, feel free to reopen it.

**Comment by userjustdoit** [comment]
项目包含IAP,确实因为这个alipay 字符串被拒了
