### ISSUE TITLE
TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by joedan0104** [apache/incubator-weex#2118]
加载JS页面时候，发生错误，导致页面加载失败，提示 “render error:-2013”：

## Description

02-12 16:31:33.898 13789-13809/com.weex.app D/weex: callJS >>>> instanceId:1function:createInstance
02-12 16:31:34.147 13789-13809/com.weex.app E/jsengine:  ReportException : Exception: TypeError: Attempted to assign to readonly property.
    (global function):2933:15
    __webpack_require__@(global function):24:34
    (global function):7757:35
    __webpack_require__@(global function):24:34
    (global function):3906:32
    __webpack_require__@(global function):24:34
    (global function):10755:31
    __webpack_require__@(global function):24:34
    (global function):11486:38
    __webpack_require__@(global function):24:34
    (global function):20182:31
    __webpack_require__@(global function):24:34
    (global function):20122:38
    __webpack_require__@(global function):24:34
    (global function):67:37
    (global function):68:12
    anonymous@(global function):20377:4
    a@(weex framework):3:30112
    (weex framework):8:22648
02-12 16:31:34.147 13789-13809/com.weex.app E/weex: reportJSException >>>> instanceId:1, exception function:createInstance, exception:Exception: TypeError: Attempted to assign to readonly property.
    (global function):2933:15

## Environment

设备：华为P8
WeexSDK: 0.20.0.2
Android 版本：6.0

**Comment by YorkShen** [comment]
As shown in the log, this is a JS error, you should check your js file whether there is a `assign to readonly property`

`02-12 16:31:34.147 13789-13809/com.weex.app E/jsengine: ReportException : Exception: TypeError: Attempted to assign to readonly property.`

**Comment by peng0398** [comment]
nstanceId:14, exception function:createInstanceContext, exception:Exception: TypeError: Attempted to assign to readonly property.
    weex createInstanceContext:3:29029
    weex createInstanceContext:3:30445
    t@weex createInstanceContext:3:105
    weex createInstanceContext:3:481
    global code@weex createInstanceContext:3:491
