### ISSUE TITLE
git clone 下来 pod lib lint  发现有头文件找不到 验证不过

### ISSUE THREAD

**Issue by afeng159** [apache/incubator-weex#2129]
## Describe the bug
git clone最新代码 ,pod lib lint  本地验证不过

## Screenshots
![image](https://user-images.githubusercontent.com/15241025/52837355-5c17e200-3129-11e9-99c8-c4ef6eac77f4.png)

**Comment by afeng159** [comment]
![image](https://user-images.githubusercontent.com/15241025/52837177-b3698280-3128-11e9-92f3-7593f9dfeb8d.png)

**Comment by jianhan-he** [comment]
你好，多谢反馈。可以先在weexsdk.xcconfig里加上类似路径：/Users/jianhan/Documents/Work/Code/WeexProject/weex/weex_core/Source，这样就能编译过。我们后续会修复这个问题

**Comment by afeng159** [comment]
![image](https://user-images.githubusercontent.com/15241025/52844882-9771db00-3140-11e9-9267-eea885268486.png)
大佬  是修改这个吗？ weexsdk.xcconfig

**Comment by afeng159** [comment]
![image](https://user-images.githubusercontent.com/15241025/52845212-7bbb0480-3141-11e9-98f5-1aa1e81a7fe3.png)
是改这个吗

**Comment by afeng159** [comment]
大佬

**Comment by jianhan-he** [comment]
是的，你试下可以吗

**Comment by afeng159** [comment]
嗯 可以了 谢谢大佬

**Comment by YorkShen** [comment]
It seems this problem is solved.

I will just close it. Feel free to reopen if you have appending questions.
