### ISSUE TITLE
[Android]failed find class WMBridge

### ISSUE THREAD

**Issue by joedan0104** [apache/incubator-weex#2130]
## Describe the bug

02-15 10:39:33.046 15491-15491/? I/art: Late-enabling -Xcheck:jni
02-15 10:39:33.070 15491-15491/? D/ActivityThread: ActivityThread,attachApplication
02-15 10:39:33.099 15491-15505/com.weex.app E/HAL: load: id=gralloc != hmi->id=gralloc
02-15 10:39:33.100 15491-15491/com.weex.app D/HwCust: Create obj success use class android.content.res.HwCustHwResourcesImpl
**02-15 10:39:33.182 15491-15509/com.weex.app E/WeexCore: failed find class WMBridge
02-15 10:39:33.182 15491-15509/com.weex.app W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bridge.WMLBridge" on path: DexPathList[[zip file**
"/data/app/com.weex.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.weex.app-2/lib/arm, /data/app/com.weex.app-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.Runtime.doLoad(Runtime.java:447)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:382)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.System.loadLibrary(System.java:1086)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:140)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:226)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at android.os.Handler.handleCallback(Handler.java:743)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at android.os.Looper.loop(Looper.java:150)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
**02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:   Suppressed: java.lang.ClassNotFoundException: com.taobao.windmill.bridge.WMLBridge
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.Class.classForName(Native Method)**
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:     ... 12 more
02-15 10:39:33.183 15491-15509/com.weex.app W/System.err:   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
02-15 10:39:33.184 15491-15509/com.weex.app D/SimpleComponentHolder: Generate Component:WXText

## Environment

Device: 华为P8
OS：安卓6.0
WeexSDK：0.20.0.2

**Comment by YorkShen** [comment]
This is a warning, we will fix this soon
