### ISSUE TITLE
[Android] webview中嵌入文件上传点不出文件选择

### ISSUE THREAD

**Issue by littleseven007** [apache/incubator-weex#2134]
## Describe the bug
使用web标签嵌入了一个html页面，html页面中有文件上传功能，在andriod中点击添加图片没有任何反应，也就是说<input type="file">点击没有任何反应

## Environment
* Device: [Android *]

**Comment by YorkShen** [comment]
Please Provide a demo on http://dotwe.org/vue , we will look into it.

**Comment by littleseven007** [comment]
> Please Provide a demo on http://dotwe.org/vue , we will look into it.



> Please Provide a demo on http://dotwe.org/vue , we will look into it.

**Comment by littleseven007** [comment]
> Please Provide a demo on http://dotwe.org/vue , we will look into it.

![image](https://user-images.githubusercontent.com/21102773/53156805-1cef0280-35fb-11e9-80ed-7431b5122b50.png)
打包为android app后点击添加图片无响应调不出手机相册
weex 代码：`<template>
  <web :src="webUrl" class="web-class"></web>
</template>
<script>
  export default{
    data(){
      return {
        webUrl: `http://www.51tanwo.com/phone/#upload?code=123&token=123`
      }
    }
  }
</script>`

**Comment by littleseven007** [comment]
> Please Provide a demo on http://dotwe.org/vue , we will look into it.
![image](https://user-images.githubusercontent.com/21102773/53156985-84a54d80-35fb-11e9-896b-de3c10bcfebe.png)

打包为android app后点击红色框中加号无响应，调不出手机图片浏览
weex简易代码：
```
`<template>
  <web :src="webUrl" class="web-class"></web>
</template>
<script>
  export default{
    data(){
      return {
        webUrl: `http://www.51tanwo.com/phone/#upload?code=123&token=123`
      }
    }
  }
</script>`
```

**Comment by YorkShen** [comment]
If it works fine in Weex playground, I think you should check your app environment first.

**Comment by littleseven007** [comment]
> If it works fine in Weex playground, I think you should check your app environment first.

Thank you for your answer, I confirm that there is no response in Android, so I rewrote there based on natjs, now my problem is solved.

**Comment by cheerful-li** [comment]
点击上传文件没得反应 +1
