### ISSUE TITLE
[iOS] image 无法显示中文链接的图片

### ISSUE THREAD

**Issue by kang558** [apache/incubator-weex#2135]
## Describe the bug
【iOS版本】image 无法显示中文链接的图片

## To Reproduce
在线示例： [http://dotwe.org/vue/f1975a64161d86f26c88cad76d21bd76](http://dotwe.org/vue/f1975a64161d86f26c88cad76d21bd76)

## Environment
Weex Playground weex-SDK：0.19.0 
* Device: [e.g. iPhone6]
* OS: [e.g. iOS12.1.2]
* Version [e.g. 22]
* Build from source [e.g. yes/no]

**Comment by wqyfavor** [comment]
Thanks
