### ISSUE TITLE
大文件 下载，支持断点续传，有类似 的插件或组件 实现吗

### ISSUE THREAD

**Issue by hponiang** [apache/incubator-weex#2136]

**Comment by YorkShen** [comment]
Not supported

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow. You should request features on the [mailing list](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#mailing-list)
