### ISSUE TITLE
0.19.5 应用内部调用/libweexcore.so 出现crash

### ISSUE THREAD

**Issue by gnemgnahz** [apache/incubator-weex#2139]
02-02 10:24:35.239   802   802 I /system/bin/tombstoned: received crash request for pid 4232
02-02 10:24:35.240  4414  4414 I crash_dump32: performing dump of process 3357 (target tid = 4232)
02-02 10:24:35.259  4414  4414 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-02 10:24:35.259  4414  4414 F DEBUG   : Revision: '0'
02-02 10:24:35.259  4414  4414 F DEBUG   : ABI: 'arm'
02-02 10:24:35.259  4414  4414 F DEBUG   : Happend: 'Sat Feb  2 10:24:35 2019
02-02 10:24:35.259  4414  4414 F DEBUG   : '
02-02 10:24:35.260  4414  4414 F DEBUG   : SYSVMTYPE: Maple
02-02 10:24:35.260  4414  4414 F DEBUG   : APPVMTYPE: Art
02-02 10:24:35.260  4414  4414 F DEBUG   : pid: 3357, tid: 4232, name: pool-29-thread-  >>> xxx <<<
02-02 10:24:35.260  4414  4414 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-02 10:24:35.260  4414  4414 F DEBUG   :     r0  00000000  r1  00001088  r2  00000006  r3  00000008
02-02 10:24:35.260  4414  4414 F DEBUG   :     r4  00000d1d  r5  00001088  r6  c266c6e4  r7  0000010c
02-02 10:24:35.260  4414  4414 F DEBUG   :     r8  cb04c2f5  r9  cb0a91cc  r10 f3fe2424  r11 00000059
02-02 10:24:35.260  4414  4414 F DEBUG   :     ip  00000041  sp  c266c6d0  lr  f20e6a6d  pc  f20de796
02-02 10:24:35.312  4414  4414 F DEBUG   : 
02-02 10:24:35.312  4414  4414 F DEBUG   : backtrace:

**Comment by YorkShen** [comment]
Please Update to the latest version.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow.
