### ISSUE TITLE
React Native will support 64 bit for android starting version 0.59, How about weex?

### ISSUE THREAD

**Issue by smoothdvd** [apache/incubator-weex#2140]
React Native will support 64 bit for android starting version 0.59, How about weex?

**Comment by YorkShen** [comment]
I think Weex already supported 64bits years ago.

BTW, according to the [community guideline](https://github.com/apache/incubator-weex-site/blob/draft/docs/guide/contribute/how-to-contribute.md#ask-or-answer-questions), which is voted in the mailing list but not released yet, Github Issues is only for bug report and questions that doesn't get answer on stackOverflow.

**Comment by wuhh2016** [comment]
hi, I cannot find "arm64-v8a" and "x86_64" in the lib folder.

**Comment by hanzhida** [comment]
@YorkShen 这个问题为什么关了，并没有看到 "arm64-v8a"这个目录，只有v7a和arm等。你说的已经支持是什么意思呢？可以把v7a的so直接放到v8a目录？

**Comment by YorkShen** [comment]
1. There is no `arm64-v8a` folders now, but as 64 bit CPU would always fallback to 32 bit if `arm64-v8a` doesn't exist, so there is no problem to run weex on a 64 bit CPU.
2. We are planning to add `arm64-v8a` folders for better performance, but no detail schedule yet.
3. According to [community guideline](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list), Github issues is only for bug report, you should discuss new features in mailing list.

**Comment by smoothdvd** [comment]
@YorkShen Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures. 64-bit CPUs deliver faster, richer experiences for your users. Adding a 64-bit version of your app provides performance improvements, makes way for future innovation, and sets you up for devices with 64-bit-only hardware. [https://developer.android.com/distribute/best-practices/develop/64-bit](url)

**Comment by hanzhida** [comment]
@YorkShen googleplay 2019/8/1强制所有app对应的32位so必须相应提供64位。否则所有海外外发的app都无法在googleplay更新了。google通知这个消息很久了

**Comment by zhou-ting** [comment]
@hanzhida ，解决了吗？一样遇到了，脑壳痛
