### ISSUE TITLE
大家有没有遇到过用appium无法定位和操作weex控件的情况？

### ISSUE THREAD

**Issue by arronhai** [apache/incubator-weex#2146]
如题，我们公司App是用weex技术写的，在如下界面时，可以定位到所有选项，
![image](https://user-images.githubusercontent.com/42204523/53136514-3d4a9d00-35ba-11e9-91e8-094112ac01a1.png)
![image](https://user-images.githubusercontent.com/42204523/53136524-46d40500-35ba-11e9-8aff-5ae62f21fae6.png)
点击状态，优先级和截止时间会有一个弹窗如下
![image](https://user-images.githubusercontent.com/42204523/53136538-58b5a800-35ba-11e9-894b-a38b7c09d9da.png)
在弹出的窗口点击确定或取消后返回到新建任务界面。这时我的driver就失效了，不能定位元素，也不能做任何其他操作。定位元素【任务内容】会报错nosuchelement。我用driver.find_elements_by_xpath('//*')查询当前页面所有元素也一直在加载没有任何反应。
![image](https://user-images.githubusercontent.com/42204523/53136561-6bc87800-35ba-11e9-9462-1d40e827ba02.png)

请问这种情况是什么原因引起的？

**Comment by YorkShen** [comment]
看起来和Appium测试框架有关，我这里也无法推断具体原因。

使用Appium，是想要做哪方面的测试呢

**Comment by arronhai** [comment]
> 
> 
> 看起来和Appium测试框架有关，我这里也无法推断具体原因。
> 
> 使用Appium，是想要做哪方面的测试呢

主要是做跨平台的UI自动化测试，在写测试脚本时发现，Android平台中涉及到上图类型的弹窗控件，一旦我点击了【确定】/【取消】以后，在接下来的界面就无法再定位到元素。只能使用press_keycode()返回首页。（也就是说点击控件中的【确定】/【取消】以后，虽然无法定位到当前页面的元素了，但driver驱动还是能用的）。我咨询过其他人，他们说没有这种情况，因为他们不是用的appium。
