### ISSUE TITLE
[Android][iOS][Dev-tool]  渲染we 文件编译成js  报 Can't find variable: __weex_define__ 

### ISSUE THREAD

**Issue by longios** [apache/incubator-weex#2147]
## Describe the bug
    ios   升级到 0.20.1   we文件编译的js 报 Can't find variable: __weex_define__
    0.19版本没有问题

## Environment

we 文件    最简单的we 测试文件
代码
<template>
    <div style="background-color: red; width: 750;">
    </div>
</template>

<script>
</script>

**Comment by YorkShen** [comment]
Provide a demo, please

**Comment by longios** [comment]
it run well in 0.19sdk   but  report cant find __weex_define in 0.20.    and my weex environment is 
   v1.3.8
 - weexpack : v1.2.3
 - weex-debugger : v1.0.11
 - weex-builder : v0.2.6
 - weex-previewer : v1.5.1

my we code (not vue) is :  

<template>
    <div style="background-color: red; width: 750;">
    </div>
</template>

<script>
</script>

**Comment by longios** [comment]
it run well in sdk 0.19 and cant run in sdk 0.20 it repoart cant find variable __weex_define_
  my .we(not vue  vue can run well) code is : 
<template>
    <div style="background-color: red; width: 750;">
    </div>
</template>
<script></script>

**Comment by longios** [comment]
it run well in sdk 0.19 and cant run in sdk 0.20 it repoart cant find variable __weex_define_
my .we(not vue vue can run well) code is :
//<template>
   // <div style="background-color: red; width: 750;">
   // </div>
//</template>
//<script></script>

**Comment by longios** [comment]
sdk为0.19的时候可以正常运行  为0.20的时候 .we代码编译的js 报cant find variable __weex_define,  .vue代码正常运行
下面是我的  .we 代码 
![image](https://user-images.githubusercontent.com/14165811/53281784-3b730c00-3769-11e9-9488-ab3fc2d40f45.png)

**Comment by YorkShen** [comment]
Please provide a demo in [dot.we](http://dotwe.org/vue), which will make debugging a lot easier. Thanks.
