### ISSUE TITLE
[Android] Package names `com.taobao.*` and `com.alibaba.*`?

### ISSUE THREAD

**Issue by janpio** [apache/incubator-weex#2148]
When looking at PR https://github.com/apache/incubator-weex/pull/2071 I noticed that the Android package names include `com.taobao` and `com.alibaba`. 

Is this here to stay or will this be updated to `org.apache.*`?

**Comment by YorkShen** [comment]
This is a problem I want to solve years ago.

But as there are many util class or base class under `com.taobao` and `com.alibaba` package, such as `com.taobao.weex.ui.component.WXComponent`, which is the base class for almost every UI component.

If we change the package name directly to `org.apache.*`, users with custom plugins that extends the `base` class or uses the `util` class will have many problems to update to the latest version, as such package renaming will cause lots of compiling issue.

Any advice on reduce the cost of renaming for Weex users'?

**Comment by janpio** [comment]
I honestly don't know much about Android development.

Is there a way to maybe rename the real classes but keep an "alias" with the old name around so plugin can keep working?

**Comment by YorkShen** [comment]
> Is there a way to maybe rename the real classes but keep an "alias" with the old name around so plugin can keep working?

Sadly, no.

As there is no way to avoid the tragedy of backwards compatibility now, I think maybe we keep it untouched until have a better solution.

**Comment by cnryb** [comment]
The package name has been changed to `org.apache. *`
