### ISSUE TITLE
关于wxc-ep-slider在ios下,官方demo无法正常运行

### ISSUE THREAD

**Issue by JackChengGZ** [apache/incubator-weex#2149]
我刚开始在自己的项目中做了一个demo,在安卓下是可以的,但是在ios下不行,我的bindingx环境都已经搭建完成,我查看过之前的Issues,然后把官方的demo在weex playround中运行,也不可以,也参考过[https://github.com/alibaba/weex-ui/blob/master/example/ep-slider/index.vue这个的方式](https://github.com/alibaba/weex-ui/blob/master/example/ep-slider/index.vue%E8%BF%99%E4%B8%AA%E7%9A%84%E6%96%B9%E5%BC%8F);
[https://h5.m.taobao.com/trip/wx-detection-demo/ep-slider/index.weex.js这个是编译后的地址,我把生成二维码在weex](https://h5.m.taobao.com/trip/wx-detection-demo/ep-slider/index.weex.js%E8%BF%99%E4%B8%AA%E6%98%AF%E7%BC%96%E8%AF%91%E5%90%8E%E7%9A%84%E5%9C%B0%E5%9D%80,%E6%88%91%E6%8A%8A%E7%94%9F%E6%88%90%E4%BA%8C%E7%BB%B4%E7%A0%81%E5%9C%A8weex) playgound运行,我去滑动元素,总是会跳转到第一个元素

**Comment by YorkShen** [comment]
I will Google Translate your questions first

> I just started to make a demo in my project, it is ok under Android, but not under ios, my bindingx environment has been built, I have looked at the previous Issues, and then put the official demo in weex playround Running in, can't, also refer to [https://github.com/alibaba/weex-ui/blob/master/example/ep-slider/index.vue this way] (https://github.com /alibaba/weex-ui/blob/master/example/ep-slider/index.vue%E8%BF%99%E4%B8%AA%E7%9A%84%E6%96%B9%E5%BC%8F );
> [https://h5.m.taobao.com/trip/wx-detection-demo/ep-slider/index.weex.js This is the compiled address, I will generate the QR code in weex](https:/ /h5.m.tao.com/trip/wx-detection-demo/ep-slider/index.weex.js%E8%BF%99%E4%B8%AA%E6%98%AF%E7%BC%96 %E8%AF%91%E5%90%8E%E7%9A%84%E5%9C%B0%E5%9D%80,%E6%88%91%E6%8A%8A%E7%94%9F% E6%88%90%E4%BA%8C%E7%BB%B4%E7%A0%81%E5%9C%A8weex) playgound runs, I go to slide the element and always jump to the first element

I think The `wxc-ep-slider` component you mentioned is not under this repo, maybe you should ask this question in that repo, Thanks.

**Comment by JackChengGZ** [comment]
yes ,u are right,but[ weex-ui](https://github.com/alibaba/weex-ui/) not reply

**Comment by YorkShen** [comment]
You may contact [tw93](https://github.com/tw93) of weex-ui, I see there is a lot of commit by him.
