### ISSUE TITLE
recycle-list，子组件无法展示，直接写在当前页面没问题

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#2150]
![qq 20190222121436](https://user-images.githubusercontent.com/36951996/53219605-91797e00-369b-11e9-83e5-7997e092e68d.png)
![qq 20190222121443](https://user-images.githubusercontent.com/36951996/53219619-a1915d80-369b-11e9-9cd8-5cc28c86f15c.png)
![2019022201](https://user-images.githubusercontent.com/36951996/53219641-b2da6a00-369b-11e9-8b31-f3174eebd048.png)
代码为官方demo源码
环境为：
 "weex-loader": "^0.7.2",
weex sdk version = "0.18.0"

**Comment by YorkShen** [comment]
1. Prodive a demo in [dot.we](http://dotwe.org/vue) as mentioned in the issue template
2. Update to the latest version and try again

**Comment by fanlvwen** [comment]
http://dotwe.org/vue/9b990bf01a12497d0338ef0b997aff1d
在dot.we上是正常的，但是这个和移动端用的sdk不是一样的吧

官方文档：
该功能部分依赖于编译工具，请确保 weex-loader 的版本升级到最新（v0.7.2+）
使用最新版的 playground app（SDK 版本 0.18.0 及以上）才可以扫码查看原生效果，也可以直接使用dotwe查看Web预览效果

我的环境为：
"weex-loader": "^0.7.2",
weex sdk version = "0.18.0"
weex -v： v1.3.11
条件都是符合的啊

**Comment by fred-ye** [comment]
> http://dotwe.org/vue/9b990bf01a12497d0338ef0b997aff1d
> 在dot.we上是正常的，但是这个和移动端用的sdk不是一样的吧
> 
> 官方文档：
> 该功能部分依赖于编译工具，请确保 weex-loader 的版本升级到最新（v0.7.2+）
> 使用最新版的 playground app（SDK 版本 0.18.0 及以上）才可以扫码查看原生效果，也可以直接使用dotwe查看Web预览效果
> 
> 我的环境为：
> "weex-loader": "^0.7.2",
> weex sdk version = "0.18.0"
> weex -v： v1.3.11
> 条件都是符合的啊

have you run the demo on weex playground app, it seems ok

**Comment by YorkShen** [comment]
As this issue is not updated almost a month, I will just close it.

Feel free to reopen it with a [runnable demo](http://dotwe.org/vue/9b990bf01a12497d0338ef0b997aff1d).

**Comment by ivantree** [comment]
同样的问题升级到最新版本没有解决，banner改成image同样无法显示
