### ISSUE TITLE
[iOS] 不能动态控制border的显示或隐藏 [bug]

### ISSUE THREAD

**Issue by hulinNeil** [apache/incubator-weex#2153]
### 描述
使用 :class 动态控制显示或隐藏 div 的 border 样式，目前现象是只能让其显示，不能让其消失，安卓无此问题，仅iOS有问题。

**可重现此问题的链接：** http://dotwe.org/vue/d51bcf5f483f8ffb02ffebda6914e9e3

**Comment by YorkShen** [comment]
Bug received, we will look into it, not sure when to resolve.

**Comment by wqyfavor** [comment]
Merged, thanks very much.
