### ISSUE TITLE
[iOS] weex+vue，this.$refs.xxx.ref，普通div正常，但在v-for中的div返回undefined

### ISSUE THREAD

**Issue by chenzhaoqi** [apache/incubator-weex#2155]
测试代码如下

> <template>
	<scroller>
		<div class="header" ref="header">Header</div>
		<div v-for="item in ['0']" :key="item">
			<div ref="for">{{item}}</div>
		</div>
		<text>ref={{refValue1}}</text>
		<text>ref={{refValue2}}</text>
		<div class="button" @click="onClick"></div>
	</scroller>
</template>

> <script>
	export default {
		data() {
			return {
				refValue1: "",
				refValue2: ""
			}
		},
		methods: {
			onClick() {
				this.refValue1 = "" + this.$refs.header.ref;
				this.refValue2 = "" + this.$refs.for.ref;
				console.log("123");
			}
		}
	}
</script>

> <style scoped>
	.header {
		padding-top: 50px;
	}
	.button {
		width: 200px;
		height: 100px;
		background-color: #0000FF;
	}
</style>

![dcim](https://user-images.githubusercontent.com/10445666/53312631-c92d3380-38f0-11e9-82f8-b3892a9d732f.jpg)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> [iOS] weex vue, this.$refs.xxx.ref, normal div is normal, but the div in v-for returns undefined

Please provide a complete demo in [dot.we](http://dotwe.org/vue), which debugging so much more easy.

**Comment by Hanks10100** [comment]
Please check the document of Vue.js (https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements).

> When ref is used together with v-for, the ref you get will be an array containing the child components mirroring the data source.

Try `this.$refs.for[0].ref`

**Comment by chenzhaoqi** [comment]
@YorkShen thanks for translating~
@Hanks10100 thanks for the answer~
