### ISSUE TITLE
[Android][iOS][Dev-tool]  Cannot read property 'IOSDevices' of undefined

### ISSUE THREAD

**Issue by BengBu-YueZhang** [apache/incubator-weex#2158]
## Describe the bug

npm run ios, error

## To Reproduce

```shell

TypeError: Cannot read property 'IOSDevices' of undefined
    at Command.run (/Users/zhangyue/.wx/modules/node_modules/_@weex-cli_run@2.0.0-beta.1@@weex-cli/run/commands/run.js:36:34)
    at Runtime.<anonymous> (/Users/zhangyue/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.1@@weex-cli/core/src/runtime/run.ts:62:43)
    at Generator.next (<anonymous>)
    at <anonymous> (/Users/zhangyue/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.1@@weex-cli/core/lib/runtime/run.js:7:71)
    at new Promise (<anonymous>)
    at __awaiter (/Users/zhangyue/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.1@@weex-cli/core/lib/runtime/run.js:3:12)
    at Runtime.run (/Users/zhangyue/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.1@@weex-cli/core/lib/runtime/run.js:23:12)
    at Cli.<anonymous> (/Users/zhangyue/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.1@@weex-cli/core/src/cli/cli.ts:316:44)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zhangyue/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.1@@weex-cli/core/lib/cli/cli.js:4:58)
```

![image](https://i.loli.net/2019/02/25/5c73ad3969255.png)

**Comment by Gitsifu** [comment]
![image](https://user-images.githubusercontent.com/23445650/53330411-5a200100-3929-11e9-89c3-2ea178a3bf6d.png)
Same problem

**Comment by BengBu-YueZhang** [comment]
> ![image](https://user-images.githubusercontent.com/23445650/53330411-5a200100-3929-11e9-89c3-2ea178a3bf6d.png)
> Same problem

Google search failed to find a solution

**Comment by BengBu-YueZhang** [comment]
I am in a state of collapse

**Comment by HelloMrJay** [comment]
I have a same problem

**Comment by humbass** [comment]
the same problem, even I use "weex run web" or "weex run android"

**Comment by BengBu-YueZhang** [comment]
> the same problem, even I use "weex run web" or "weex run android"

Don't use the latest version

**Comment by BengBu-YueZhang** [comment]
> I have a same problem

Don't use the latest version

**Comment by humbass** [comment]
> > the same problem, even I use "weex run web" or "weex run android"
> 
> Don't use the latest version

Thank you gay.

**Comment by erha19** [comment]
@humbass @BengBu-YueZhang @HelloMrJay @Gitsifu 

Fixed https://github.com/weexteam/weex-toolkit/commit/2e0964b73c003aa1df0f84bc9bca1635a8882c17.

Try flowing command to fix this case:

```
$ weex repair @weex-cli/run@latest
```

**Comment by Gitsifu** [comment]
> @humbass @BengBu-YueZhang @HelloMrJay @Gitsifu
> 
> Fixed [weexteam/weex-toolkit@2e0964b](https://github.com/weexteam/weex-toolkit/commit/2e0964b73c003aa1df0f84bc9bca1635a8882c17).
> 
> Try flowing command to fix this case:
> 
> ```
> $ weex repair @weex-cli/run@latest
> ```

The following bug has appeared
![image](https://user-images.githubusercontent.com/23445650/53411689-1e0c9f00-3a02-11e9-8b78-10d08f8e50ac.png)

**Comment by erha19** [comment]
@Gitsifu did you use the project generated by `weex-toolkit` ? looks this project was your personal project.

**Comment by Gitsifu** [comment]
@erha19 I used weex-toolkit, but there is still a problem. The figure below is the version I am using. Is there a conflict in the version?
![image](https://user-images.githubusercontent.com/23445650/53414243-3cc26400-3a09-11e9-9309-8407025c387d.png)

**Comment by erha19** [comment]
@Gitsifu that's my mistakes, try `weex platform update android` then run the `weex run android` command again.

**Comment by Gitsifu** [comment]
@erha19 Successful

**Comment by YorkShen** [comment]
It seems the problem has been solved, I will just close the PR.

Feel free to reopen it.

**Comment by humbass** [comment]
@erha19 

It dost not It doesn't work.

after I run    `weex repair @weex-cli/run@latest`  and  `weex run android`

```
Error: {"ErrorMemory":"ErrorMemory","type":"ANDROID_EMULATOR_NOT_FIND","message":"Not find android emulator!"}
```
