### ISSUE TITLE
怎么替换内置的modal模块

### ISSUE THREAD

**Issue by wslaimin** [apache/incubator-weex#2159]
内置的modal模块，发现有bug，prompt()返回值为页面第一个input元素，如果页面有多个input元素就会有问题。我自己改了，但是怎么替换内置的modal

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The built-in modal module finds a bug, and the prompt() return value is the first input element of the page. If the page has multiple input elements, there will be problems. I changed it myself, but how to replace the built-in modal.

You have two options:
1. Fix the problem based on current `modal` code, and give us a Github PR, which is encouraged.
1. You can implement the modal by yourself, and register a `modal` with the same name using the below [approach](https://weex.apache.org/guide/extend/extend-android.html#module-extend)

**Comment by YorkShen** [comment]
It seems there is no updating for quite a while.

I will just close it. Feel free to reopen it if you have further problems.
