### ISSUE TITLE
Weex Playground App下载地址被篡改

### ISSUE THREAD

**Issue by tenstone** [apache/incubator-weex#2161]
https://weex.apache.org/tools/playground.html

扫码下载时提示404，
下载APK安装后发现是360软件管家

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Https://weex.apache.org/tools/playground.html 404 when scanning code download, download APK after installation found to be 360 software housekeeper

This is because the 404 problem, we will fix it as soon as possible. Meanwhile there is an Android and iOS link, which still works now.

**Comment by YorkShen** [comment]
The problem has been solved, thanks
