### ISSUE TITLE
[Android][iOS][Dev-tool] Weex How do I change the color of StatusBar

### ISSUE THREAD

**Issue by BengBu-YueZhang** [apache/incubator-weex#2164]
```js
const navBar = weex.requireModule("navigationBar");

navBar.setStyle({
    color: 'rgba(255, 255, 255, 1)',
    backgroundColor: 'rgba(0, 129, 255, 1)'
});
```

Seems to be ineffective

**Comment by YorkShen** [comment]
According to the [document](https://weex.apache.org/docs/modules/navigator.html), I don't think this feature is supported.

If you'd like to request a feature, send an email to the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list)

Thanks for you feedback.
