### ISSUE TITLE
ios  v-if没有效果

### ISSUE THREAD

**Issue by mynameissujie** [apache/incubator-weex#2166]
weex 里面定义了v-if，
在mounted里面动态获取到this.type（根据ios注册的module传参来获取的），根据type决定是否隐藏，结果一直没有效果。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Weex defines v-if, dynamically obtains this.type in the mounted (according to the module passed by ios to obtain the parameter), according to the type to determine whether to hide, the result has no effect.

Please provide a [demo](http://dotwe.org/vue), which will make debugging so much easier.

Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by mynameissujie** [comment]
I had made something wrong.
