### ISSUE TITLE
iOS  平台text标签

### ISSUE THREAD

**Issue by zhangtong217** [apache/incubator-weex#2167]
加载大号（比如76px）粗（比如700）字体（比如1234），有的时候出来是斜的，而且显示不全，不必现，不知道你们遇到没？

**Comment by kang558** [comment]
有出现，不知道什么原因。特别是渲染大量数据的时候

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Load large (such as 76px) thick (such as 700) font (such as 1234), sometimes it is oblique, and the display is not complete, do not have to be present, I do not know if you encountered?

Please provide a [demo](http://dotwe.org/vue), which will make debugging so much easier.

Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by YorkShen** [comment]
As there is no update, I will just close the issue. 

Feel free to reopen it with you demo

**Comment by zhangtong217** [comment]
![problem](https://user-images.githubusercontent.com/15995066/54980707-71faab80-4fe1-11e9-9914-358754c3b852.jpg)
![normal](https://user-images.githubusercontent.com/15995066/54980718-74f59c00-4fe1-11e9-851a-211fb23eb7d0.jpg)
Text tags occasionally render problems in bold and large fonts,I uploaded two pictures to show that there was a problem.Please don't close it. There is a high chance of recurrence in the project. I just set up a class selector like this. {
    "fontSize": "72",
    "color": "#FFFFFF",
    "fontWeight": "700"
  },

**Comment by zhangtong217** [comment]
This is before Compilation ：{
    font-size: 72px;
    color: white;
    font-weight: 700;
  }

**Comment by dengp** [comment]
Has the problem been solved?

**Comment by effortcheep** [comment]
同样出现过。text组件在原生端是用 textview做的。没有文本组件吗？ 对应原生的 label不好吗？
