### ISSUE TITLE
weex 怎么判断网络的状态

### ISSUE THREAD

**Issue by ko00wu** [apache/incubator-weex#2170]
## 背景：
查了很多资料，都没有关于weex 如何判断网络状态的内容

## 需求：
需要根据网络是否为wifi状态来进行对应的操作。

**Comment by chenzefeng09** [comment]
需要native端拓展相关功能module
http://weex.apache.org/zh/guide/extend/extend-android.html#module-%E6%89%A9%E5%B1%95

**Comment by YorkShen** [comment]
This is not supported yet.
