### ISSUE TITLE
[Android] weex可以往js中直接注入java对象吗？

### ISSUE THREAD

**Issue by zhaozheyu** [apache/incubator-weex#2173]
## 背景
我们有很多之前的jsbridge，但是不是给weex用的，而想要给weex用又一定要继承WXModule，这样就有一些工作量，所以想问问weex有没有方法直接往js注入一个java对象呢？
## 问题
weex可以往js中直接注入java对象吗？

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> We have a lot of previous jsbridge, but not for weex, but we must inherit WXModule for weex, so there is some work, so I would like to ask if weex has a way to directly inject a java object into js?

Short answer: **NO**

Long Answer: To achieve JS -> Java communication, you need a bridge, which can be `WXModule`, `WXComponent` or event raw JNI method.

Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks
