### ISSUE TITLE
[Android] emoji 显示不正常 where weex version is 0.19.0.7

### ISSUE THREAD

**Issue by warwr1ck** [apache/incubator-weex#2174]
## Describe the bug

服务端获取的emoji字符，在<text>组件中无法正常显示，展示为 ？？？

## Environment

Device: 华为 荣耀 V20
OS： Android 9.0

## Expected behavior
emoji 正常展示

## Screenshots
![11551410732_ pic_hd](https://user-images.githubusercontent.com/14226761/53614391-c4c88980-3c14-11e9-8f4f-468ec158a20b.jpg)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> The emoji characters obtained by the server are not displayed properly in the component. ? ?

1. Please provide a [demo](http://dotwe.org/vue), which will make debugging so much easier.
2. Update to the latest version of weex. 

Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Edit New issue [Android] emoji does not display where weex version is 0.19.0.7

1. Update to the latest version of weex.
2. Please provide a [demo](http://dotwe.org/vue), which will make debugging so much easier.

Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by warwr1ck** [comment]
it's odd that this problem won't show in online editor.
maybe the version of 0.19 cause this problem.
i will try the newest version

**Comment by YorkShen** [comment]
It seems resolved, I will just close it.
