### ISSUE TITLE
[UIApplication statusBarFrame] must be used from main thread only

### ISSUE THREAD

**Issue by loumzy** [apache/incubator-weex#2177]
## Class WXCoreBridge.mm

 Line 861 
 env->AddOption("status_bar_height", std::to_string([[UIApplication sharedApplication] statusBarFrame].size.height));

**Comment by lyle-luan** [comment]
0.20.1版本出现同样的问题。出现两次。
![屏幕快照 2019-04-19 下午4 15 37](https://user-images.githubusercontent.com/1920392/56414837-6e93d080-62be-11e9-812c-39dbffff6a91.png)
在`WXCoreBridge.mm`文件中注释掉`env->AddOption("status_bar_height", std::to_string([[UIApplication sharedApplication] statusBarFrame].size.height));`
