### ISSUE TITLE
WXLogUtils.renderPerformanceLog 报 StringIndexOutOfBoundsException问题

### ISSUE THREAD

**Issue by super1Angle** [apache/incubator-weex#2178]
## Describe the bug

WXLogUtils.renderPerformanceLog方法，报数组越界的问题java.lang.StringIndexOutOfBoundsException

## Environment

品牌:     xiaomi 
OS:     Android-8.1.0 
机型:     MI 6X

## Screenshots

![image](https://user-images.githubusercontent.com/7030784/53636570-a2a62a00-3c5b-11e9-8339-3f4ce178312d.png)

**Comment by YorkShen** [comment]
This problem was solved long times ago. Please update to the latest version.
