### ISSUE TITLE
java.util.ConcurrentModificationException异常

### ISSUE THREAD

**Issue by super1Angle** [apache/incubator-weex#2179]
## Describe the bug

sdk内部 报 java.util.ConcurrentModificationException

## Environment

品牌:     OPPO 
OS:     Android-8.1.0 
机型:     PACM00

## Screenshots

![image](https://user-images.githubusercontent.com/7030784/53636720-13e5dd00-3c5c-11e9-905a-c27b0a859e5e.png)

**Comment by YorkShen** [comment]
The problem has been solved, you may compile from source on the master branch or wait for next release
