### ISSUE TITLE
[Android][iOS][Dev-tool] 怎么引入JS,用混入在web端可以在手机上就不能用

### ISSUE THREAD

**Issue by wdwhai198532** [apache/incubator-weex#2182]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question: How to introduce JS, you can use it on the mobile phone when you mix it on the web.
Please provide a [demo](http://editor.weex.io/), which will make debugging so much easier.

Github issue is only for reporting bugs, you should ask question in [Mailing List](https://weex.io/guide/contribute/how-to-contribute.html#mailing-list), thanks

Thanks
