### ISSUE TITLE
[Android][iOS]WXStreamModule Timeout is unreasonable

### ISSUE THREAD

**Issue by tonyyls** [apache/incubator-weex#2183]
Hi, I found that WXStreamModule timeout param is different between iOS and android platform.
iOS:  timeout  60s
android: timeout 3s
And I can't find this param in the document,  please make sure that. 

It looks a little casual,  recommand that it should be the same!  15s or 30s ?

thanks.

**Comment by YorkShen** [comment]
Please provide a [demo](http://dotwe.org/vue), which will make debugging so much easier.

Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by YorkShen** [comment]
As there is no update of this thread, I will just close it.
