### ISSUE TITLE
[Android][iOS][Dev-tool]The behavior of new Date in weex and h5 is inconsistent

### ISSUE THREAD

**Issue by BengBu-YueZhang** [apache/incubator-weex#2185]
```js
new Date('2019-01') 

```

The results returned by weex and h5 are inconsistent

**Comment by YorkShen** [comment]
Please provide a [demo](http://editor.weex.io/), which will make debugging so much easier.

Also, please follow the issue [template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by YorkShen** [comment]
As this issue is not updated for quite a while, I will just close it.

Feel free to reopen it if you have further problems.
