### ISSUE TITLE
代码实例-Online Editor 运行按钮点击后不起作用

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex#2186]
Windows 10 LTSC
Google Chrome 版本 72.0.3626.119（正式版本） （64 位）

在线编辑点击“运行”按钮后报js错误，请参照下图：
![79398688-73a1-4d0e-91e6-2bbd1e601d29](https://user-images.githubusercontent.com/41984848/53738759-097d4a80-3ecb-11e9-9a36-ef52380aee9f.jpg)
![0275a5f0-068b-4a84-86ee-f7305e341323](https://user-images.githubusercontent.com/41984848/53738766-0da96800-3ecb-11e9-8adf-6de546012a4b.jpg)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Code Instance - Online Editor does not work after clicking the button

Please provide a [demo](http://editor.weex.io), which will make debugging so much easier.

Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by YorkShen** [comment]
As there is no update of this thread, I will just close it.
