### ISSUE TITLE
iOS weex-sdk 0.20.1 waterfall中refresh不能加载bug

### ISSUE THREAD

**Issue by FateOfKing** [apache/incubator-weex#2188]
使用weexplayground （weexsdk0.20.1） ios版本扫描下面两个二维码 
第一个不可以下拉，第二个可以下拉
http://dotwe.org/vue/1d4bce6a5a3c455918fd2cb8c710d658  
http://dotwe.org/vue/579e9bf06f53af66edff1c9f99a58cbd
而两者的差别 仅仅在于数据源数量不同。
第一个cell元素没有超过屏幕，第二个cell超过了屏幕。希望能尽快修复。
安卓上并没有发现这个bug

**Comment by FateOfKing** [comment]
我自己找到了解决办法，在sdk源码WXRecyclerComponent.mm中 
_collectionView.delegate = self;下方添加一句 _collectionView.alwaysBounceVertical = self;即可解决

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: I found a solution myself, add a _collectionView.alwaysBounceVertical = self in the sdk source WXRecyclerComponent.mm _collectionView.delegate = self; can be solved but not rigorous, if the landscape can not be written this way, I hope the official can Fix it as soon as possible.

Please give us a PR, we will review it.

**Comment by FateOfKing** [comment]
Scan the following two two two-dimensional codes using weexplayground (weexsdk0.20.1) IOS version
The first can not be pulled down, the second can be pulled down.
Http://dotwe.org/vue/1d4bce6a5a3c455918fd2cb8c710d658
Http://dotwe.org/vue/579e9bf06f53af66edff1c9f99a58cbd
The only difference between the two is the number of data sources.
The first cell element does not exceed the screen, and the second cell does. I hope it can be repaired as soon as possible.
Android did not find this bug
For the project, just use the official weexplay group.
The modification method can use the method I mentioned above to modify the WXRecyclerComponent. mm file in weexsdk

**Comment by wqyfavor** [comment]
WXRecyclerComponent继承自WXScrollerComponent
WXScrollerComponent支持alwaysScrollableHorizontal和alwaysScrollableVertical两个属性。

**Comment by wqyfavor** [comment]
参考这个demo http://dotwe.org/vue/df57d60ff368acc4e62b9f97c3e7c033
