### ISSUE TITLE
[iOS] navigator模块无法跳转本地bundlejs

### ISSUE THREAD

**Issue by littleseven007** [apache/incubator-weex#2189]
## Environment
苹果app

navigator模块无法跳转本地bundlejs

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question: Apple app navigator module can't jump to local bundlejs

Please provide a [demo](http://editor.weex.io/), which will make debugging so much easier.

Also, please follow the issue [template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.

Thanks

**Comment by littleseven007** [comment]
> 感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。
> 
> > [iOS] navigator module can't jump to local bundlejs
> 
> Please provide a [demo](http://dotwe.org/vue), which will make debugging so much easier.
> 
> Also, please follow the [issue template](https://github.com/apache/incubator-weex/issues/new) when you report a bug. The more information you give, the faster issue will be resolved.
> 
> Thanks

I want to use navigator to jump local bundlejs instead of remote resources in IOS applications.
```
navigator.push({
  url: 'How to write here in IOS',  // TODO
  animated: "true"
}
```
I tried to use the local scheme and relative path,but it didn't work

**Comment by YorkShen** [comment]
Please provide a [runnable demo](http://dotwe.org/vue), not just code snippet.

I will close the issue now. Feel free to reopen it with you demo.
