### ISSUE TITLE
Excuse me, how should I use this method to load GIF picture

### ISSUE THREAD

**Issue by LovelyAeline** [apache/incubator-weex#2192]
- (void)setImageViewWithURL:(UIImageView*)imageView
                        url:(NSURL *)url
           placeholderImage:(UIImage *)placeholder
                    options:(NSDictionary*)options
                   progress:(void(^)(NSInteger receivedSize, NSInteger expectedSize))progressBlock
                  completed:(void(^)(UIImage *image, NSError *error, WXImageLoaderCacheType cacheType, NSURL *imageURL))completedBlock;

**Comment by wqyfavor** [comment]
WeexSDK does not contain image downloader. You should adapt WeexSDK to a picture library such as SDWebImage. If you want to support GIF, you should make sure that your picture library supports GIF by UIImage.
