### ISSUE TITLE
[iOS] Can`t find variable:global

### ISSUE THREAD

**Issue by maoyu** [apache/incubator-weex#2196]
weex SDk 从1.18.0.3升级到。0.20.1 运行报错。升级前是没有问题的。谢谢。
![1552122700397](https://user-images.githubusercontent.com/1551269/54069057-7196ac80-428e-11e9-83c3-b82d4322c40a.jpg)

**Comment by maoyu** [comment]
errorCode:-9700 functionName:func: createInstance arg:start exception:[WX_KEY_EXCEPTION_WXBRIDGE]

**Comment by YorkShen** [comment]
As it said, it is a JavaScript Exception. Check your JS code first.

BTW: We just enabled the error prompt in 0.20.xx, it doesn't mean everything of your JS code is fine in 1.18.xx

**Comment by maoyu** [comment]
I tracked the code and found that if import {Buffer} from'buffer' was added to the interface, the error would be reported. This file is a file under node_modules.
