### ISSUE TITLE
请问Weex Studio在mac上为什么不能输入大写字母？

### ISSUE THREAD

**Issue by HZRZCW** [apache/incubator-weex#2197]
为什么不能呢？是我的电脑的按键设置有问题导致的吗？

**Comment by littleseven007** [comment]
> 为什么不能呢？是我的电脑的按键设置有问题导致的吗？

Android Studio？编辑器的问题吧 与weex没啥关系

**Comment by janpio** [comment]
Is this about https://weex.apache.org/tools/ide.html @HZRZCW ?

**Comment by HZRZCW** [comment]
Mac 的 weex studio https://weex.apache.org/tools/ide.html ，按住 'shift+任意字母' 才能输入大写的字母。换一台macbook pro电脑就不会了，可以直接按caps lock就可以切换大小写。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: hy can't Weex Studio enter uppercase letters on mac?

I think this problem has no relation to Apache, you should ask the developers of Weex IDE. I will just close the issue.
