### ISSUE TITLE
Androiod 按照官方集成weex，0.20.0.2版本  报错error code -1001

### ISSUE THREAD

**Issue by dashuaicomputer** [apache/incubator-weex#2200]
可以render本地加载js文件，但是通过renderByUrl 加载网络js  就会报错，网络js没有问题 ，在本地浏览器可以显示  报错如下
degradeToH5|createInstance fail|wx_create_instance_error, reportJSException >>>> instanceId:2, exception function:createInstance, exception:Exception: SyntaxError: Unexpected token '<'
at (global function):6
Function@[native code]
Function@[native code]
(weex framework):1:151029
ni@(weex framework):1:151047
createInstance@(weex framework):1:154254
(weex framework):1:178788

 getTemplateInfo== template md5 14c4640548672e671a291804871cc642 length 1763 base64 md5 FMRkBUhnLmcaKRgEhxzGQg== response header {null:["HTTP/1.1 200 OK"],"Transfer-Encoding":["chunked"],"templateSourceBase64MD5":["FMRkBUhnLmcaKRgEhxzGQg=="],"Connection":["keep-alive"],"templateSourceMD5":["14c4640548672e671a291804871cc642"],"X-Android-Received-Millis":["1552289937082"],"Date":["Mon, 11 Mar 2019 07:38:55 GMT"],"Accept-Ranges":["bytes"],"X-Android-Selected-Protocol":["http/1.1"],"ETag":["W/\"6e3-c7IMxZSLa3w+fV2F2CPE7TB9WsY\""],"X-Android-Response-Source":["NETWORK 200"],"Vary":["Accept-Encoding"],"X-Android-Sent-Millis":["1552289937074"],"Content-Type":["text/html; charset=UTF-8"],"X-Powered-By":["Express"]}, extInitTime:23869ms, extInitErrorMsg:| weex JS framework from assets, isSandBoxContext: true | pieSupport:true

**Comment by zshshr** [comment]
please  check the js bundle you download from network，
this error message means the download  js bundle is not javascript！

**Comment by YorkShen** [comment]
The content-type should be `application/javascript`
