### ISSUE TITLE
0.20.1 error

### ISSUE THREAD

**Issue by maoyu** [apache/incubator-weex#2203]
I tracked the code and found that if import {Buffer} from'buffer' was added to the interface, the error would be reported. This file is a file under node_modules.

![Simulator Screen Shot - iPhone XR - 2019-03-12 at 10 05 14](https://user-images.githubusercontent.com/1551269/54169619-6fab3400-44ae-11e9-935d-d34c40bc2904.png)

**Comment by maoyu** [comment]
0.18.0.3 is good

**Comment by YorkShen** [comment]
Please follow the issue template and provide your demo.

I will just close the issue, feel free to reopen with your demo.
