### ISSUE TITLE
Module parse failed: Unexpected character '@'

### ISSUE THREAD

**Issue by lilianjin** [apache/incubator-weex#2204]
My`.postcssrc.js` config:
```json

// https://github.com/michael-ciniawsky/postcss-load-config

module.exports = {
    'plugins': [
        require('tailwindcss')(require('./tailwind.js')),
        require('autoprefixer')(),
    ]
}

```

Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @tailwind components;
| @tailwind utilities;

**Comment by YorkShen** [comment]
Please follow the issue template and provide your demo

I will just close the issue, feel free to reopen it with your demo.
