### ISSUE TITLE
[Android][iOS][Dev-tool] Unexpected behavior when xx where weex version is 0.aa.bb.cc

### ISSUE THREAD

**Issue by LionBuer** [apache/incubator-weex#2205]
iOS WeexSDK 0.20.1
weex_core的头文件全都报找不到
'core/data_render/ast.h' file not found

**Comment by jianhan-he** [comment]
可以在WeexSDK.xcconfig文件里的USER_HEADER_SEARCH_PATHS变量加上weex的路径，比如USER_HEADER_SEARCH_PATHS =/Users/jianhan/Documents/Work/Code/WeexProject/weex/weex_core/Source

**Comment by LionBuer** [comment]
> 可以在WeexSDK.xcconfig文件里的USER_HEADER_SEARCH_PATHS变量加上weex的路径，比如USER_HEADER_SEARCH_PATHS =/Users/jianhan/Documents/Work/Code/WeexProject/weex/weex_core/Source

是用的pod自动引入的

**Comment by YorkShen** [comment]
The problem is solved now, we will launch next release soon.
