### ISSUE TITLE
weex报错：{"message":"statuscodeerror."}

### ISSUE THREAD

**Issue by liguotal** [apache/incubator-weex#2208]
_instance.onFailed = ^(NSError *error) {
}
方法中打印日志发现weex报错，code为564，message: statuscodeerror

具体如下：
{"code":564,"map":{"type":"WXErrorDomain","user":{"message":"statuscodeerror."},"code":564},"type":"WXErrorDomain","user":{"message":"statuscodeerror."}}

请问一下是什么原因，如何解决？

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Weex gives an error: {"message":"statuscodeerror."}

Please follow the issue template and provide your [runnable demo](http://dotwe.org/vue).

I will just close the issue, feel free to reopen with your demo.
