### ISSUE TITLE
android 0.20.0.1 component扩展设置自定义属性时，部分属性不生效

### ISSUE THREAD

**Issue by liuxinyea** [apache/incubator-weex#2211]
## Describe the bug
android 0.20.0.1 component扩展设置自定义属性时，部分属性不能响应式更新数据，只能在组件初始化时获取，在android studio中打了断点，没有走到断点处。
## Environment
* Device: [HAWEI P20]
* OS: [ android 9.0]
* Version [ 0.20.0.1]
* Build from source [ yes] 

## Expected behavior
自定义component中的属性可以正常响应

## Screenshots

![image](https://user-images.githubusercontent.com/31365524/54269000-6ce83600-45b7-11e9-9624-be27254d0604.png)
![image](https://user-images.githubusercontent.com/31365524/54269094-a02ac500-45b7-11e9-9d16-a4e871be25bf.png)
![image](https://user-images.githubusercontent.com/31365524/54269297-162f2c00-45b8-11e9-991f-d886ce2b036c.png)

![image](https://user-images.githubusercontent.com/31365524/54269250-fa2b8a80-45b7-11e9-8510-7e317361e947.png)

initComponentHostView中可以获取到，但是得到的是字符串。之后无法改变index的值了

**Comment by liuxinyea** [comment]
在小米8SE上表现是正常的

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Android 0.20.0.1 component extension set custom properties, some properties can not respond to the update data, can only be obtained when the component is initialized, hit a breakpoint in android studio, did not go to the breakpoint.

If I am right, the index in your java code is String, but this is not true in your JS code. 

You can override `component.setProperty(String key, Object param)` to solve the problem.

Ref [WXText](https://github.com/apache/incubator-weex/blob/5a52f042acd357d763d76c88a5a993e9c33e43ad/android/sdk/src/main/java/com/taobao/weex/ui/component/WXText.java#L136
) for detail.

**Comment by YorkShen** [comment]
It seems there is no update about this issue.

I will just close it. Feel free to reopen.

**Comment by lovederh** [comment]
我在ios中遇到同样问题我的weex sdk 是0.18.0的，我在initWithRef就无法获取到绑定属性的值
