### ISSUE TITLE
[Android] Weex 0.20.3.0-beta版里WXComponent的onRenderFinish方法不执行

### ISSUE THREAD

**Issue by wanghan1470** [apache/incubator-weex#2212]
如题：
        [Android] Weex 0.20.3.0-beta版里WXComponent的onRenderFinish方法不执行，同样的代码自定义的Component在0.18.0-beta-3版本里会执行。
        本意是想在所有属性读取完毕后做一些特殊处理。请问现在的版本onRenderFinish不执行了吗？

**Comment by fanlvwen** [comment]
请问你用的是
`compile 'com.taobao.android:weex_sdk:0.20.3.0-beta'
compile 'com.taobao.android:weex_inspector:0.20.3.0-beta'`
吗？

有使用js debug吗？ 真心请教js debug问题
