### ISSUE TITLE
[Android] One Cause for Weex Can't render on a Vivo phone

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#2213]
## Describe the bug
can't render weex page on a vivo phone(Vivo V3Max A)，page just show blank。
every time this phone visit a weex page, code will go throuth this part(sdk version 0.18)
![image](https://user-images.githubusercontent.com/7556537/54329088-4378ea00-464b-11e9-9c27-499f6ae96c94.png)
![image](https://user-images.githubusercontent.com/7556537/54329128-65726c80-464b-11e9-9d86-ce551e1c3725.png)
Which means weex reinit framewok everytime, even it's successed before。

Here is the logcat err msg below:
![image](https://user-images.githubusercontent.com/7556537/54329282-0c570880-464c-11e9-8ffa-5153631693a5.png)

More device info about Vivo V3MAX A:
![image](https://user-images.githubusercontent.com/7556537/54329416-8ab3aa80-464c-11e9-95e9-5faf1e73387b.png)

## Environment
* Device: [VIVO V3MAX A]
* OS: [android 5.1]
* Weex Version:[0.18]
* Build from source [yes] 

## Screenshots
page just shows blank

**Comment by YorkShen** [comment]
Please follow the issue template and provide your runnable demo.

1. Update to the latest version of Weex
2. Please provide a [runnable demo](http://dotwe.org/vue)

I will just close the issue, feel free to reopen it with your demo.
