### ISSUE TITLE
请教：工程下ios目录改变了weex run ios不成功，怎么修改路径？

### ISSUE THREAD

**Issue by byczd** [apache/incubator-weex#2218]
Start setting native config - this may take a few secondsError: ENOENT: no such file or directory, open '/Users/chenzhidong/project.Lg5/weexSource/CaodandeWeex/caodanWeex/platforms/ios/WeexDemo/WeexDemo-Info.plist'
因为我把WeexDemo等文件放到了ios/playground下，所以现在WeexDemo-Info.plist路径为ios/playground /WeexDemo/WeexDemo-Info.plist
然后执行地weex run ios时就提示找到不到WeexDemo-Info.plist，不移动文件(夹)目录的情况下怎么在weex run ios时指定到新的文件路径呢？
请指教！谢谢！

**Comment by erha19** [comment]
@byczd weex-toolkit 中创建的项目为demo项目，用于前端开发者快速进行代码预览，需要你使用命令行或配置文件的方式去更改项目配置，否则对应的手动修改将会导致功能不可用，目前开放的配置项比较少，你可以通过根目录下的`ios.config.json`查看，建议通过你们的客户端同学搭建自己的app进行修改。

**Comment by byczd** [comment]
哇，阿里“哥哥”回我了，谢谢！

**Comment by YorkShen** [comment]
It seems like this problem has been solved.

I will close it.
