### ISSUE TITLE
安卓横竖屏切换，不会重新渲染

### ISSUE THREAD

**Issue by warlock1024127** [apache/incubator-weex#2219]
从原生页面，先跳到一个weex竖屏页面，返回，再跳到一个weex横屏页面，横屏布局就会好像是竖屏的放大版。反过来，先进横屏，再进竖屏，竖屏页面就会好像是横屏的缩小版。推测是weex页面第一次加载过后，就不会再重新渲染框架的布局

**Comment by warlock1024127** [comment]
也不用返回原生页面，直接横竖屏切换就会这样

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: From the native page, first jump to a weex vertical screen, return, and then jump to a weex horizontal screen, the horizontal screen layout will appear to be a magnified version of the vertical screen. In turn, advanced horizontal screen, and then into the vertical screen, the vertical screen will appear to be a reduced version of the horizontal screen. It is speculated that after the first time the weex page is loaded, the layout of the frame will not be re-rendered.

Please follow the issue template and provide your runnable [demo](http://dotwe.org/vue).

I will just close the issue, feel free to reopen it with your demo.
