### ISSUE TITLE
安卓横屏状态translateX的距离不准确

### ISSUE THREAD

**Issue by warlock1024127** [apache/incubator-weex#2220]
安卓横屏状态translateX的距离不准确，不同机型上的差别也不一样，有的比设定的多，有的比设定的少，没找到规律

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The distance of the Android horizontal screen status translateX is not accurate. The difference between different models is different. Some are more than the settings, some are less than the settings, and no rules are found.

Please read the [document](https://weex.apache.org/docs/modules/meta.htm) you will find all the distance is web based and `viewport:750px` related.
