### ISSUE TITLE
[Android] x86的cpu无法加载页面。WeexSDK的x86模式缺少libJavaScriptCore.so,版本号：0.20.0.2

### ISSUE THREAD

**Issue by ccbuildpro** [apache/incubator-weex#2221]
x86的cpu无法加载页面。
查看了下现象：
解压weex_sdk-0.20.0.2的aar之后，在jni目录下，有三个文件夹：
armeabi，armeabi-v7a，x86
其中x86比其他两个文件夹缺少libJavaScriptCore.so和libweexjst.so，这是核心原因。

**Comment by zshshr** [comment]
weex don‘t support x86
