### ISSUE TITLE
recycle-list怎么添加分割线？是直接写在item的布局文件里面么？

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#2222]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: How does the recycle-list add a split line? Is it written directly in the layout file of the item?

You may try use a div as a divider, but Github issue is only for bug report and I don't think this is bug report. If you have feature request, you should ask in the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list).

I will just close the issue.
