### ISSUE TITLE
[Android][iOS][Dev-tool] Android Scroller cannot remove child with v-if

### ISSUE THREAD

**Issue by venuson** [apache/incubator-weex#2223]
private FrameLayout mScrollerView was added in WXScroller, in function getRealView,  mScrollerView is returned, but all children's parent is actually mRealView, so we can not remove scroller's child in function public void remove(WXComponent child,boolean destory)

**Comment by YorkShen** [comment]
What's your point, I can't get you.

Could please update the code format and we can discuss based on code snippet.

**Comment by YorkShen** [comment]
As this problem is not updated for a while, I will just close it.

Feel free to reopen it if you have further problems.
