### ISSUE TITLE
[Android]When the weex 0.20.0 interface is revisible, the interface is re-rendered and refreshed.

### ISSUE THREAD

**Issue by BatterMan-Li** [apache/incubator-weex#2227]
Hello weex engineer
At present, after the project upgrades the weex version to 0.20.0, the interface (which is not visible outside the screen area) will be re-rendered as a whole. The previous version of 0.17.0 will not render the entire screen area.
The situation found is that the picture URL will be re-read in the image loading adaptation. How can I modify it without re-rendering, is the v-once attribute a feasible solution?

**Comment by BatterMan-Li** [comment]
Added: I also checked the autoBitmapRecycle tag attribute in the document (<image> is used to display a single image in your interface.), but the interface re-visible image is also reloaded (eg, the application returns to the background, halfway) Minutes back to the program again, the current interface image will re-read the image URL loading), how to solve this problem?

**Comment by YorkShen** [comment]
If `autoBitmapRecycle:false` doesn't solve your question, I think you could rewrite the [imageAdatper](https://github.com/apache/incubator-weex/blob/29c3c80d3e03fd913716ec803c2244b946521dcf/android/commons/src/main/java/com/alibaba/weex/commons/adapter/ImageAdapter.java) and make a memory cache of the image using Picasso, Fresco or any other image library you like

**Comment by YorkShen** [comment]
As this problem is not updated for a while, I will just close it.

Feel free to reopen it if you have further question.
