### ISSUE TITLE
官方示例的demo中video标签无法正常播放啊

### ISSUE THREAD

**Issue by LazyDemo** [apache/incubator-weex#2229]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The video tag in the demo of the official example does not play properly.

Please follow the issue template and provide your [runnable demo](http://dotwe.org/vue).

I will just close the issue, feel free to reopen it with your demo.
