### ISSUE TITLE
集成sdk源码报错：More than one file was found with OS independent path 'lib/armeabi/libweexjsb.so'

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#2232]
使用weex sdk源码依赖，代码为incubator-weex下最新sdk，
version = project.hasProperty('weexVersion')? project.getProperty('weexVersion') : "0.20.0.1"

安卓项目运行报错：
More than one file was found with OS independent path 'lib/armeabi/libweexjsb.so'

debug配置为： compile 'com.taobao.android:weex_inspector:0.20.3.0-beta'
okhttp:  compile 'com.squareup.okhttp:okhttp:2.3.0'
             compile 'com.squareup.okhttp:okhttp-ws:2.3.0'
系统环境：
![image](https://user-images.githubusercontent.com/36951996/54744746-b31a4680-4c02-11e9-89ae-9f99bd198555.png)

**Comment by fanlvwen** [comment]
项目gradle改成2.3.3，不报上面的错了，但是启动app直接崩溃
![image](https://user-images.githubusercontent.com/36951996/54747164-18713600-4c09-11e9-90a3-43d4f0042308.png)

依赖源码和直接gradle：compile 'com.taobao.android:weex_sdk:0.20.3.0-beta'
都是这个崩溃

**Comment by fanlvwen** [comment]
补充：启用debug会崩，直接用打包出来的js没问题

**Comment by fanlvwen** [comment]
包括incubator-weex 主分支下的项目，直接硬编码开启debug，也是崩溃,日志和上面我自己的项目一样
![image](https://user-images.githubusercontent.com/36951996/54747810-d6e18a80-4c0a-11e9-916e-9659cdcdf060.png)

**Comment by Darin726** [comment]
能否用 arm-linux-androideabi-addr2line  -piCfe  /path/libweexcore.so  00xxxxx 解开看看具体的代码文件在发上来看下

**Comment by fanlvwen** [comment]
> 能否用 arm-linux-androideabi-addr2line -piCfe /path/libweexcore.so 00xxxxx 解开看看具体的代码文件在发上来看下

能麻烦描述具体一点吗？ 对so文件不熟悉怎么操作

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/54748817-b23ae200-4c0d-11e9-91f4-d7f05d08095e.png)
还有这个n你看一下，文档上说cmake要3.9+，但是我这个报错，切换成3.6那个才行

**Comment by Darin726** [comment]
可以参考 https://stackoverflow.com/questions/5314036/how-to-use-addr2line-in-android 这个去解开堆栈.

在 Android 目录下 使用  find ./ -iname libweexcore.so -exec ls -lah {} \; 找到对应带堆栈的 libweexcore.so

**Comment by fanlvwen** [comment]
> 可以参考 https://stackoverflow.com/questions/5314036/how-to-use-addr2line-in-android 这个去解开堆栈.
> 
> 在 Android 目录下 使用 find ./ -iname libweexcore.so -exec ls -lah {} ; 找到对应带堆栈的 libweexcore.so

![image](https://user-images.githubusercontent.com/36951996/54794096-b81ddb00-4c80-11e9-8382-3a0470f8554d.png)
你好，帮忙看一下

**Comment by Darin726** [comment]
> 补充：启用debug会崩，直接用打包出来的js没问题

启用 debug 是指 weex 的 debug 吗, 还是 Androidstudio 的 debug

**Comment by fanlvwen** [comment]
> > 补充：启用debug会崩，直接用打包出来的js没问题
> 
> 启用 debug 是指 weex 的 debug 吗, 还是 Androidstudio 的 debug

![image](https://user-images.githubusercontent.com/36951996/54798220-94fc2700-4c92-11e9-84e3-b2507522d735.png)
是指直接在application中启动weex 的debug，androidstudio只是run了app，没有其他操作

**Comment by fanlvwen** [comment]
@Darin726 请问能定位吗？ 一直卡在这里了，不开application里不开debug就没事，开了就崩溃

**Comment by fanlvwen** [comment]
我找出一个规律，
![image](https://user-images.githubusercontent.com/36951996/54808976-cc7fc900-4cbc-11e9-8e3a-ab83da30132b.png)
这个WXEnvironment.sRemoteDebugMode 一开始就置为true的话，就崩溃。
置为false的话，app启动后浏览器会打开
![image](https://user-images.githubusercontent.com/36951996/54809018-f507c300-4cbc-11e9-8c6a-7c895474dcfa.png)
c此时jsDebug为关闭状态 需手动开启，但是开启之后，app页面空白
![image](https://user-images.githubusercontent.com/36951996/54809062-19fc3600-4cbd-11e9-959a-1e462f835987.png)

android studio报错日志如下：
![image](https://user-images.githubusercontent.com/36951996/54809078-2aacac00-4cbd-11e9-86b8-d70c6c6ddc68.png)

![image](https://user-images.githubusercontent.com/36951996/54809092-34ceaa80-4cbd-11e9-8637-ddcea87968db.png)

代码环境为incubator-weex-0.20.3.0-beta分支下源码

**Comment by pdrsnow** [comment]
导入这俩个依赖WXEnvironment.sRemoteDebugMode=true时不会崩溃，
api 'com.taobao.android.weex_inspection:urlconnection_interceptor:1.0.0'
api 'com.taobao.android.weex_inspection:protocol:1.0.2'
但是debug界面依旧空白，开启网络调试后，在浏览器上网络监控模块可以看到加载了当前js文件

**Comment by fanlvwen** [comment]
> 导入这俩个依赖WXEnvironment.sRemoteDebugMode=true时不会崩溃，
> api 'com.taobao.android.weex_inspection:urlconnection_interceptor:1.0.0'
> api 'com.taobao.android.weex_inspection:protocol:1.0.2'
> 但是debug界面依旧空白，开启网络调试后，在浏览器上网络监控模块可以看到加载了当前js文件

你的weex sdk和interceptor版本是什么  是最新的0.20.3.0-beta吗

**Comment by pdrsnow** [comment]
![TIM截图20190322181722](https://user-images.githubusercontent.com/37689690/54816337-f80baf00-4cce-11e9-9796-5c49984ecbe6.png)
![TIM截图20190322181745](https://user-images.githubusercontent.com/37689690/54816343-fa6e0900-4cce-11e9-8dbb-a9f622af39a2.png)
问题依旧

**Comment by fanlvwen** [comment]
> ![TIM截图20190322181722](https://user-images.githubusercontent.com/37689690/54816337-f80baf00-4cce-11e9-9796-5c49984ecbe6.png)
> ![TIM截图20190322181745](https://user-images.githubusercontent.com/37689690/54816343-fa6e0900-4cce-11e9-8dbb-a9f622af39a2.png)
> 问题依旧

唉  新版debug玩不起来

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Weed sdk problem under branch 0.20.3.0-beta

Again, I think this is a bug about dev-tool, you should ask it in the [weex-toolkit](https://github.com/weexteam/weex-toolkit), not this repos.

But as you discussion happened here for a while, I think you could continue this time, but ask question about dev-tool in [weex-toolkit](https://github.com/weexteam/weex-toolkit) next time.

Thanks

**Comment by YorkShen** [comment]
It seems there is no updating about this question.

I will just close it, feel free to reopen it.
