### ISSUE TITLE
[Android][iOS][Dev-tool] Unexpected behavior when xx where weex version is 0.aa.bb.cc

### ISSUE THREAD

**Issue by xinglai-orange** [apache/incubator-weex#2233]
weex官网的实例页面经常挂掉，打不开啊~特别是下午四五点~‘等待dotwe.org的响应~’

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The example page of the weex official website often hangs, can't open, especially at 4 or 5 in the afternoon ‘waiting for the response from dotwe.org~’

You may try http://editor.weex.io/, but I don't think this problem is about Apache Weex.

I will just close the issue.
