### ISSUE TITLE
[Android] web组件 无法监听 spa的url变化

### ISSUE THREAD

**Issue by heymalio** [apache/incubator-weex#2235]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Web component can't listen to spa url changes

Please follow the issue template and provide your [runnable demo](http://dotwe.org/vue).

* If this is a feature request, you should ask it in the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list)
* If this is a bug report, please provide a [runnable demo](http://dotwe.org/vue).

Either case, I will just close the issue, feel free to reopen it with your demo or send an email to the mailing list.
