### ISSUE TITLE
android sometime The display control is not displayed

### ISSUE THREAD

**Issue by 1043276584** [apache/incubator-weex#2237]
when open weex page in android ,The display control is not displayed, when you quit the page open it again it's ok

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The fonts of the various controls are the same, even if the existing control fonts become larger

Please follow the issue template and provide your demo.

I will just close the issue, feel free to reopen it with your demo.
