### ISSUE TITLE
[Android] arm64-v8a support for requirments of google 

### ISSUE THREAD

**Issue by sdlu1992** [apache/incubator-weex#2238]
Due to the [requirements of google](https://developer.android.com/distribute/best-practices/develop/64-bit), We must support android arm64-v8a before **August 1 2019**. So do you have any plan to support it? 
If you cant support it timely, We will consider remove weex sdk in our app because we cant let our app ban by Google Play.

**Comment by YorkShen** [comment]
Problems received, I don't think this is a bug. 

Instead, I think this is a feature request, in which cause you should send an email to the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list)

I will just close the issue.

**Comment by Victoriayangx** [comment]
I think you should consider re-opening this. This is indeed a blocker for us. And About React Native,this issue had been started about two years ago. And about seventeen days ago, React Native  had released 0.59.0 version to  solve the 64 bits issue. And i also had sent an email to dev@weex.incubator.apache.org to feedback this issue. Looking forward to your Reply, Thanks.

**Comment by YorkShen** [comment]
#2389 

We will solve the problem in the early of June.

Thanks

**Comment by duqian291902259** [comment]
Please update weex-sdk to support arm64-v8a，otherwise we maybe in trouble to publish app to google play.
