### ISSUE TITLE
[Android] 0.19.0 crash when use recycler-list

### ISSUE THREAD

**Issue by lvfen** [apache/incubator-weex#2239]
## Describe the bug
we use recycler-list on a simple page, we find lots of crash report on lastest version of our app, there is crash stack:

`#00 pc 00075900 /data/app/***/lib/arm/libweexcore.so [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#01 pc 0005eeb1 /data/app/***/lib/arm/libweexcore.so (_ZN12JStringCache3putEP7_JNIEnvSsP8_jobject+176) [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#02 pc 0005ef3f /data/app/***/lib/arm/libweexcore.so (_ZN12JStringCache9GetStringEP7_JNIEnvSs+82) [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#03 pc 00061a0b /data/app/***/lib/arm/libweexcore.so (_Z15getKeyFromCacheP7_JNIEnvPKc+34) [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#04 pc 00060399 /data/app/***/lib/arm/libweexcore.so (_ZN8WeexCore19Bridge_Impl_Android16callNativeModuleEPKcS2_S2_S2_iS2_i+128) [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#05 pc 00068f79 /data/app/***/lib/arm/libweexcore.so (_callNativeModule+88) [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#06 pc 00068481 /data/app/***/lib/arm/libweexcore.so [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#07 pc 00067d39 /data/app/***/lib/arm/libweexcore.so (_ZNSt17_Function_handlerIFSt10unique_ptrI9IPCResultSt14default_deleteIS1_EEP12IPCArgumentsEPS7_E9_M_invokeERKSt9_Any_dataS6_+8) [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#08 pc 0006dc21 /data/app/***/lib/arm/libweexcore.so [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#09 pc 0006d1df /data/app/***/lib/arm/libweexcore.so [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#10 pc 00065ff7 /data/app/***/lib/arm/libweexcore.so (_ZN8WeexCore9WeexProxy6execJSEP7_JNIEnvP8_jobjectP8_jstringS6_S6_P13_jobjectArray+438) [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#11 pc 000610a1 /data/app/***/lib/arm/libweexcore.so [armeabi-v7a::d2c9fe0768d4758c11e4333e26a57bb6]`
`#12 pc 005ad5d5 /data/app/***/oat/arm/base.odex (oatexec+5952981) [armeabi::d498b40ca30921b06bf6e4042f4c2eef]`

And there is addr2line result:
`aarch64-linux-android-addr2line -e /**/libweexcore.so -f 00075900 0005eeb1 0005ef3f 00061a0b 00060399 00068f79 00068481 00067d39 0006dc21 0006d1df 00065ff7 000610a1`
`_ZNSt8__detail15_List_node_base7_M_hookEPS0_`
`/usr/local/google/buildbot/src/android/master-ndk/toolchain/gcc/gcc-4.9/libstdc++-v3/src/c++98/list.cc:132`
`_ZNSt4listISt4pairISsP8_jobjectESaIS3_EE9_M_insertIJS3_EEEvSt14_List_iteratorIS3_EDpOT_`
`/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_list.h:1689`
`_ZN12JStringCache9GetStringEP7_JNIEnvSs`
`/incubator-weex/weex_core/Source/android/base/string/jstring_cache.cpp:56 (discriminator 1)`
`_Z15getKeyFromCacheP7_JNIEnvPKc`
`/incubator-weex/weex_core/Source/android/bridge/impl/weexcore_impl_android.cpp:82 (discriminator 4)`
`_ZN8WeexCore19Bridge_Impl_Android16callNativeModuleEPKcS2_S2_S2_iS2_i`
`/incubator-weex/weex_core/Source/android/bridge/impl/bridge_impl_android.cpp:225`
`_callNativeModule`
`/incubator-weex/weex_core/Source/android/jsengine/api/WeexJSCoreApi.cpp:75`
`_ZL22handleCallNativeModuleP12IPCArguments`
`/incubator-weex/weex_core/Source/android/jsengine/multiprocess/ExtendJSApi.cpp:277`
`_ZNSt17_Function_handlerIFSt10unique_ptrI9IPCResultSt14default_deleteIS1_EEP12IPCArgumentsEPS7_E9_M_invokeERKSt9_Any_dataS6_`
`/Users/longquan/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/functional:2025 (discriminator 1)`
`_ZNKSt8functionIFSt10unique_ptrI9IPCResultSt14default_deleteIS1_EEP12IPCArgumentsEEclES6_`
`/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/functional:2439 (discriminator 1)`
`_ZN12_GLOBAL__N_113IPCSenderImpl4sendEP9IPCBuffer`
`/incubator-weex/weex_core/Source/IPC/IPCSender.cpp:80 (discriminator 1)`
`_ZN8WeexCore9WeexProxy6execJSEP7_JNIEnvP8_jobjectP8_jstringS6_S6_P13_jobjectArray`
`/incubator-weex/weex_core/Source/android/jsengine/multiprocess/WeexProxy.cpp:432 (discriminator 1)`
`_ZL6ExecJSP7_JNIEnvP8_jobjectP8_jstringS4_S4_P13_jobjectArray`
`/incubator-weex/weex_core/Source/android/bridge/impl/weexcore_impl_android.cpp:328`

Through the stack we found the problem appearing in the code below:
// jstring_cache.cpp
![image](https://user-images.githubusercontent.com/8586486/54898699-43f56880-4f08-11e9-8d22-6720e53434f9.png)

**Comment by YorkShen** [comment]
Please update to the latest version of Weex.

Feel free to reopen after you updated to the latest version.
