### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by pengwangpengwang** [apache/incubator-weex#2240]
后台请求文本中包含中文和英文，使用lines:1，在ios中可以正常显示一行，在安卓中仍然自动换行，未显示一行，设置超出显示省略号不对

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The background request text contains Chinese and English. With lines:1, one line can be displayed normally in ios, and it still wraps automatically in Android. No line is displayed. The setting exceeds the display ellipsis.

Please follow the issue template and provide your demo.

I will just close the issue, feel free to reopen with your **demo**.

**Comment by pengwangpengwang** [comment]
http://dotwe.org/vue/a3bf4eba5c55f021d2dbfbe7480d9717

**Comment by niannianer** [comment]
Is the problem solved?

**Comment by pengwangpengwang** [comment]
> Is the problem solved?

no solved
