### ISSUE TITLE
[iOS] 0.19.0偶现字体变大的问题

### ISSUE THREAD

**Issue by lixiangsanxun** [apache/incubator-weex#2244]
## Describe the bug
各个控件字体是相同的，偶现有的控件字体变大的情况

## Environment
* Device: [e.g. iPhone6s]
* OS: [e.g. iOS11]
* Version [0.19.0]
* Build from source [e.g. yes/no]

## Screenshots
正常的

![image](https://user-images.githubusercontent.com/16277917/54968122-7fe60780-4fb4-11e9-8ef0-e8185df64817.png)

字体发生变换的，应该显示“即将开始”，现在只显示了“即将开”
![image](https://user-images.githubusercontent.com/16277917/54967898-c6873200-4fb3-11e9-8497-ffa3d9397ed5.png)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

Question Description: The fonts of the various controls are the same, even if the existing control fonts become larger

1. Please follow the issue template and provide your demo
2. Please update to the latest version.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
