### ISSUE TITLE
[Android][Weex Devtools] 0.20.3.0-beta环境下连上Weex Devtools Android Module函数返回的值类型错误

### ISSUE THREAD

**Issue by selpro** [apache/incubator-weex#2246]
## Describe the bug
在 0.20.3.0-beta环境下连接Weex Devtools工具进行js debug，在Android机器上出现 module中的函数返回值(Map)在js代码中变成string类型的情况，如果断开Devtools连接，又会恢复正常。

## Environment
Device: [华为mate10]
OS: [emui 9.0]
WEEX SDK版本
0.20.3.0-beta
weex inspector版本
0.20.3.0-beta

### 代码
测试代码如下：

#### Android module 
![TIM截图20190326163358](https://user-images.githubusercontent.com/8252922/54982128-fb5fad00-4fe4-11e9-9db9-68361b7e3b36.png)

#### weex 测试代码
![TIM截图20190326163336](https://user-images.githubusercontent.com/8252922/54982136-00246100-4fe5-11e9-9f79-e8bcb4db7520.png)

#### 不连 Weex Devtools
![TIM截图20190326163218](https://user-images.githubusercontent.com/8252922/54982048-cc493b80-4fe4-11e9-96b8-e8f912f2c09d.png)

#### 连上Weex Devtools
![TIM截图20190326163204](https://user-images.githubusercontent.com/8252922/54982049-cce1d200-4fe4-11e9-9ade-2f0fc41ca5ba.png)

#### 环境
![TIM截图20190326161905](https://user-images.githubusercontent.com/8252922/54982493-eb949880-4fe5-11e9-8784-e31e7b3c55a7.png)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Error value type returned by Weex Devtools Android Module function in 0.20.3.0-beta environment

I think this is a bug about dev-tool, you should ask it in the [weex-toolkit](https://github.com/weexteam/weex-toolkit), not this repos.

**Comment by ken-iheha** [comment]
> 感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。
> 
> > Question Description: Error value type returned by Weex Devtools Android Module function in 0.20.3.0-beta environment
> 
> I think this is a bug about dev-tool, you should ask it in the [weex-toolkit](https://github.com/weexteam/weex-toolkit), not this repos.

This problem only found in 0.20.3.0-beta version. Are you sure the problem is from weex-toolkit?

**Comment by YorkShen** [comment]
You are using weex-toolkit, and it only happens when you enable weex toolkit. So, yes, I think there is maybe something wrong with weex-toolkit.
