### ISSUE TITLE
[Android]Android-0.20.0不支持richtext组件

### ISSUE THREAD

**Issue by shadowGdNf** [apache/incubator-weex#2256]
我下载了Android-0.20.0 release包发现里面没有richtext源码，导致<richtext>组件无效，但是我看master上有richtext相关代码...是忘记打包进0.20.0了？

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: I downloaded the Android-0.20.0 release package and found that there is no richtext source, which causes the component to be invalid, but I see the richtext related code on the master... Is it forgotten to package into 0.20.0?

`richtext` is created after 0.20.0 is released.
