### ISSUE TITLE
[Android][iOS] input组件不能输入负数

### ISSUE THREAD

**Issue by topcloud-xx** [apache/incubator-weex#2270]
项目中需要使用input接收用户输入的数据，设置type='number'. 但是不能输入负号。
iOS和Android的都存在这个问题。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

Question Description: The fonts of the various controls are the same, even if the existing control fonts become larger

1. Please follow the issue template and provide your demo
2. Please update to the latest version.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
