### ISSUE TITLE
weex create awesome-app doesn't work

### ISSUE THREAD

**Issue by EasyValley** [apache/incubator-weex#2274]
Weex cli version is 2.0.0-beta.16, nodejs version is v9.1.0.  When I use **"weex create awesome-project"** command to create project terminal response  **"Sorry, didn't recognize that command! Type weex help to view common commands."** and nothing is created. I use **"weex -h"** command to find usage , it shows **"create <template-name> [project-name] | Create a weex project. "**.  I want to know what template-name can I use.

**Comment by YorkShen** [comment]
I think this is a problem about weex-cli, you should ask problems in [weex-cli](https://github.com/weexteam/weex-toolkit) reop, not there.

Thanks for your bug reporting.
