### ISSUE TITLE
[Android][iOS][Dev-tool] Vue.mixin cannot work

### ISSUE THREAD

**Issue by xuchao622** [apache/incubator-weex#2275]
I create a index.js for mixins and import it in entry.js, It can work on Web, but it cannot work on IOS and Android (use Weex Playground).

//index.js
`export default {
  methods: {
    test () {
      return 'mixins'
    }
  }
}`

//entry.js
`import Vue from 'vue'`
`import mix from '@/mixins/index'`
`import weex from 'weex-vue-render'`

`Vue.mixin(mix)`
`weex.init(Vue)`

//HelloWorld.vue
`<template>`
`<text class="message">{{test()}}</text>`
`</template>`

**Comment by YorkShen** [comment]
Please follow the issue template and provide your [runnable demo](http://dotwe.org/vue).

I will just close the issue, feel free to reopen it with your demo.

**Comment by HaloZhou** [comment]
me too
