### ISSUE TITLE
SDK动画事件有概率为Nil导致APP崩溃

### ISSUE THREAD

**Issue by LWDM** [apache/incubator-weex#2276]
在SDK中，如果有动画事件的话，_targetComponent会有几率为nil然后导致崩溃
WXPerformBlockOnMainThread(^{
        [_targetComponent _updateViewStyles:dupStyles];
    });

**Comment by YorkShen** [comment]
Please follow the issue template and provide a [demo](http://dotwe.org/vue).

I will close the issue, feel free to reopen it with your demo.
