### ISSUE TITLE
[iOS]Swift Xcode10.2  Cocoapod集成问题

### ISSUE THREAD

**Issue by BMMax** [apache/incubator-weex#2278]
## Describe the bug

 ``pod 'WeexSDK'``, 桥接后,在release模式下可以编译成功, 而在debug下,编译失败, 提示:'WeexSDK/WeexSDK.h' file not found

## Screenshots

<img width="1094" alt="WeChat07e37625fbe5d3317ad8bb0a306f5435" src="https://user-images.githubusercontent.com/13166040/55546163-483c3580-5701-11e9-87fe-663e5f87a733.png">

**Comment by wqyfavor** [comment]
建议检查自己的工程，如果不能解决，可以把安装好依赖的工程压缩发给我们
