### ISSUE TITLE
There is likely additional logging output above.

### ISSUE THREAD

**Issue by hsutimes** [apache/incubator-weex#2288]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\ProgramFile\\nodejs\\node.exe',
1 verbose cli   'E:\\ProgramFile\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle irmall@1.0.0~prestart: irmall@1.0.0
6 info lifecycle irmall@1.0.0~start: irmall@1.0.0
7 verbose lifecycle irmall@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle irmall@1.0.0~start: PATH: E:\ProgramFile\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\程序文件\WebStorm\Gitee\irmall\node_modules\.bin;C:\Program Files (x86)\NetSarang\Xshell 6\;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;E:\ProgramFile\JetBrains\Python36-32\Scripts\;E:\ProgramFile\JetBrains\Python36-32\;.;E:\ProgramFile\JDK\Java\jdk-10.0.1\bin;E:\ProgramFile\JDK\Java\jdk-10.0.1\lib;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;E:\ProgramFile\SQL\SQL Server\Microsoft SQL Server 2017\140\Tools\Binn\;E:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;E:\ProgramFile\SQL\SQL Server\Microsoft SQL Server 2017\140\DTS\Binn\;E:\ProgramFile\SQL\SQL Server\Microsoft SQL Server 2017\Client SDK\ODBC\130\Tools\Binn\;E:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;E:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;E:\ProgramFile\nodejs\;E:\Program Files\IBM\SPSS\Statistics\22\JRE\bin;C:\Program Files (x86)\MySQL\MySQL Utilities 1.6\;E:\Program Files\MATLAB\R2018b\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Live\Shared;E:\ProgramFile\Android\sdk\platform-tools\;E:\ProgramFile\Git\cmd;C:\Program Files (x86)\Lua\5.1;C:\Program Files (x86)\Lua\5.1\clibs;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;E:\ProgramFile\Android\flutter\bin;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\WebStorm 2018.3\bin;;C:\Program Files\JetBrains\DataGrip 2018.3\bin;;C:\Program Files\JetBrains\IntelliJ IDEA 2018.3\bin;;C:\Program Files\Huawei FastApp IDE\bin
9 verbose lifecycle irmall@1.0.0~start: CWD: E:\程序文件\WebStorm\Gitee\irmall
10 silly lifecycle irmall@1.0.0~start: Args: [ '/d /s /c', 'npm run serve' ]
11 silly lifecycle irmall@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle irmall@1.0.0~start: Failed to exec start script
13 verbose stack Error: irmall@1.0.0 start: `npm run serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\ProgramFile\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (E:\ProgramFile\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid irmall@1.0.0
15 verbose cwd E:\程序文件\WebStorm\Gitee\irmall
16 verbose Windows_NT 10.0.17763
17 verbose argv "E:\\ProgramFile\\nodejs\\node.exe" "E:\\ProgramFile\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error irmall@1.0.0 start: `npm run serve`
22 error Exit status 1
23 error Failed at the irmall@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by YorkShen** [comment]
What' your point? I don't get it. If there is something wrong, please follow the issue template provide a demo.

I will just close it, feel free to reopen it with a demo.
