### ISSUE TITLE
[Android] erroecode -1001 degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

### ISSUE THREAD

**Issue by Mrhejunjie** [apache/incubator-weex#2291]
我这边在集成weex库的时候，初始化报

> erroecode -1001 degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

后面仔细看来一下，是因为我这边架构打开的是'armeabi-v7a', 'armeabi', 'arm64-v8a'；然后在一看weex提供的so包架构'armeabi-v7a', 'armeabi'；没有arm64-v8a；我使用的0.20.3.0-beta版，希望官方能提供arm64-v8a架构的so包

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Look carefully behind it, because the architecture I opened here is 'armeabi-v7a', 'armeabi', 'arm64-v8a'; then look at the so package architecture 'armeabi-v7a', 'armeabi' provided by weex There is no arm64-v8a; I use the 0.20.3.0-beta version, I hope the official can provide the so package of arm64-v8a architecture.

We are working on it, and we may solve the problem before June. Thanks for your report.

**Comment by nothing-important** [comment]
Is there a solution to this problem now?
