### ISSUE TITLE
[Web] 编译很慢

### ISSUE THREAD

**Issue by aixiaoxiang** [apache/incubator-weex#2293]
使用 npm start 编译超级慢
   
一直卡在 
 
94% asset optimization                                                                   

## Environment

* Device: [e.g. iPhone 8 Plus]
* OS: [e.g. iOS 12.3 ]
* Version 
    2.0.0-beta.18
      - @weex-cli/generator : v2.0.0-beta.16
      - @weex-cli/run : v2.0.0-beta.17
      - @weex-cli/device : v2.0.0-beta.2
      - @weex-cli/doctor : v2.0.0-beta.10

* Build from source [e.g. yes/no]

**Comment by gaoshu883** [comment]
可能是因为启动的时候，需要给每个页面都生成一个web preview页。

**Comment by liushengyi** [comment]
是不是一次编译的页面比较多？  我们这边一般10几个页面同时编译就会卡很久。

**Comment by aixiaoxiang** [comment]
使用 weex preview 会快些

**Comment by YorkShen** [comment]
If you have question about dev-tool, you should ask in [weex dev tool](https://github.com/weexteam/weex-devtool-iOS) repo, not here. Thanks

**Comment by aowuR** [comment]
所以大哥最后咋解决的  我这边文件太多了 编译直接 94% Asset Optimization 卡死住了
