### ISSUE TITLE
[iOS]ios原生如何实现pop weex中的上一个页面

### ISSUE THREAD

**Issue by ZhangHJ1002** [apache/incubator-weex#2294]
现在项目中遇到一个问题 
weex push到一个新的页面  然后ios底层要控制进入到这个页面以后 pop回上一个页面
这个功能是可以全部由weex实现的 但是现在要用ios原生去实现一下 后面要用这个交互做其他的功能  
请问如何实现呢？我原生的调用    [rootVC.navigationController popViewControllerAnimated:YES]; 会报错
![image](https://user-images.githubusercontent.com/22254492/55805530-313a8080-5b11-11e9-9a8f-7cb50cca427c.png)

**Comment by wqyfavor** [comment]
从log看没有问题，只要保证instance的destroyInstance方法被调用，并且instance对象dealloc即可。关于一些jsLog: Error错误已经在新版修复，可以试一下。谢谢
