### ISSUE TITLE
[Android]找不到WeexURLConnectionManager

### ISSUE THREAD

**Issue by QiaoYang0923** [apache/incubator-weex#2296]
Android找不到 com.taobao.weex.urlconnection包

在集成到Android上

**Comment by YorkShen** [comment]
Please add `com.taobao.android.weex_inspection:urlconnection_interceptor` to your build.gradle.

`com.taobao.weex.urlconnection` is for debug purpose, no need to bundle it in your release app. I will just close the issue.
