### ISSUE TITLE
<web>标签设置source为html5内容片段（内容不确定） 高度怎么设置

### ISSUE THREAD

**Issue by gmgw0909** [apache/incubator-weex#2308]
因为html5片段是接口返回的 内容是不确定的 所以web的高度不能确定 这个问题怎么解决

**Comment by gmgw0909** [comment]
<web> 标签 嵌套在<scroller>里面

**Comment by gmgw0909** [comment]
web 标签 嵌套在 scroller标签内

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Because the content returned by the html5 fragment is undefined, the height of the web cannot be determined. How to solve this problem?

The height of the `web` must be specified. Thanks.
