### ISSUE TITLE
[Android]Weex SDK 0.18.0 升级到 0.20.3.0-beta后，weex-ui的组件闪动问题

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex#2309]
2.0.0-beta.20 (Core 2.0.0-beta.18)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.17
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/run : v2.0.0-beta.17
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.17
- @weex-cli/lint : v2.0.0-beta.2
该问题的实际情况请参见以下视频：
“wxc-tab-bar”组件闪动现象，该组件闪动是因文本框输入或删除内容。
![86702ab5f5ea8845e811389a1f5e0649_20190412155958](https://user-images.githubusercontent.com/41984848/56021831-ff0d6680-5d3c-11e9-9e83-05b20a40fbc4.gif)
“wxc-popup”组件闪动现象，该组件闪动是因主页面有个时钟的定时器。
![d05454ee2464c670d1acfe3c91e47472_20190412160308](https://user-images.githubusercontent.com/41984848/56021906-295f2400-5d3d-11e9-9bbb-ccc58eaccd0b.gif)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Weex-ui component flashing issue after Weex SDK 0.18.0 is upgraded to 0.20.3.0-beta

1. Please follow the issue template and provide your demo

I will just close the issue first. Feel free to reopen it with your demo. Thanks for your interest.
