### ISSUE TITLE
weex 可视化工具有哪些？

### ISSUE THREAD

**Issue by Drowned-fish** [apache/incubator-weex#2310]
如题

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: What are weex visual chemicals?

Github issue is only for bug reporting, if you have something to discuss, please use [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list)
