### ISSUE TITLE
how can I get the data by stream.fetch in android

### ISSUE THREAD

**Issue by nikojxie** [apache/incubator-weex#2314]
when I use post method in android, I can't get the response data
========request'log=======
    method : POST
    url : https://******/api/login
    headers : appType: android
    Content-Type: application/json
    user-agent: Android SDK built for x86(Android/8.1.0) (atjia-busi/1.1.2) Weex/0.18.0 1440x2416
========response'log=======
    url : https://*****/api/login
    code : 200
    protocol : http/1.1

But it's effective in IOS😭
Thanks for your help

**Comment by zshshr** [comment]
give us a demo of dotwe

**Comment by YorkShen** [comment]
As this issue is not update for a while, I will just close it. Feel free to reopen it if you have further questions.
