### ISSUE TITLE
[Android]自定义WXVContainer时使用fireEvent自定义事件weex页面不响应事件，用fireGlobalEventCallback可以

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#2317]
Android 代码
@Component(lazyload = false)
public class WXRefreshLayout extends WXVContainer<DCRefreshLayout> {
    private LinearLayout refreshLl;

    public WXRefreshLayout(WXSDKInstance instance, WXVContainer parent, BasicComponentData basicComponentData) {
        super(instance, parent, basicComponentData);
    }

    @Override
    protected DCRefreshLayout initComponentHostView(@NonNull Context context) {
        DCRefreshLayout linearLayout = (DCRefreshLayout) View.inflate(context, R.layout.weex_refresh_layout, null);
        refreshLl = linearLayout.findViewById(R.id.refresh_ll);

        linearLayout.setOnRefreshAndLoadMoreListener(new OnRefreshAndLoadMoreListener() {
            @Override
            public void onRefresh(@NonNull RefreshLayout refreshLayout) {
                getInstance().fireGlobalEventCallback("onRefresh",null);
            }

            @Override
            public void onLoadMore(@NonNull RefreshLayout refreshLayout) {
                fireEvent("onLoadMore");
            }
        });
        return linearLayout;
    }
}

weex 代码：<refresh-layout ref="refresh"  @onLoadMore="onLoadMore"/>
onLoadMore事件不响应

**Comment by CaptainHuangsh** [comment]
问题解决了吗，什么原因呢

**Comment by YongshengLuan** [comment]
请问你是用的这个 来实现 weex调用安卓原生刷新吗
