### ISSUE TITLE
weex 0.20.0  android 环境 当键盘输入值后，有些页面会一直闪动。

### ISSUE THREAD

**Issue by yejunrong** [apache/incubator-weex#2318]
我将weex_sdk 0.20 源码导入工程后，出现的问题。之前用weex 0.18是没有问题的
日志里面可以看到，在不停的调用WXComponent.setLayout
![image](https://user-images.githubusercontent.com/3793569/56119183-29119380-5f9e-11e9-94fe-022767a92b95.png)

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: I have problems after importing the weex_sdk 0.20 source code into the project. Before using weex 0.18 is no problem
You can see in the log, call WXComponent.setLayout non-stop

Please follow the issue template and provide your demo.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
