### ISSUE TITLE
[iOS][Dev-tool] Memory issue

### ISSUE THREAD

**Issue by brahmapaytm** [apache/incubator-weex#2324]
We are using weex sdk 0.18.0. On every push there is an amount of memory is captured and not being released on pop weex screen.
There may be some memory leak. 
Same issue is there in weex sample as well. When you push pop continuously and observe the memory consumption, it is continuously increasing by some amount.

**Comment by wqyfavor** [comment]
Please try using latest Weex, we believed we have fixed most leaks.
