### ISSUE TITLE
 stream 模块

### ISSUE THREAD

**Issue by nongchangzhu** [apache/incubator-weex#2331]
为什么不支持cookie 机制呢？有什么更好的方法来实现登录状态手机端保存呢？

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Why not support the cookie mechanism? Is there any better way to implement login status on the mobile side?

It just doesn't support, feel free to give us a PR.
