### ISSUE TITLE
【Android】 After the source code of weex 0.17.0 was upgraded to 0.20.0, the list previously used was not as smooth as the original version

### ISSUE THREAD

**Issue by BatterMan-Li** [apache/incubator-weex#2332]
The weex version used in the previous application was 0.17.0, but after the recent upgrade to 0.20.0, the list sliding changed to a carton, and the code did not change. Is there a big difference between the architecture after the upgrade and the previous one? How?

Also, there is transparency in the RGB color value used by border-color in the general style, but there is obvious jagged edges in the rounded corners. Can this be solved?

**Comment by YorkShen** [comment]
Please follow the issue template and provide your [demo](http://dotwe.org/vue)

I will just close the issue, feel free to reopen with your demo.
