### ISSUE TITLE
[Android] emoji表情显示不全 0.20.0-rc1

### ISSUE THREAD

**Issue by fsxiaoke** [apache/incubator-weex#2334]
![微信图片_20190417194611](https://user-images.githubusercontent.com/19701356/56285359-9a417a00-6149-11e9-81e2-c4edac556df3.png)
在输入emoji时，从js传过来的字符少一位，导致最后一个emoji表情显示不出来
比如
输入2个emoji时，第2个显示不出来，
但是紧接着再输入第3个时，第二个就能显示出来了，第三个显示不出来，总是最后一个无法显示

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: When I type emoji, there is one less character from js, which causes the last emoji expression to not be displayed. For example, when 2 emoji is input, the second one cannot be displayed, but then the third one is entered, the second one Can be displayed, the third one does not show up, always the last one can not be displayed

1. Please follow the issue template and provide your demo
2. Please update to the latest version.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
