### ISSUE TITLE
[iOS] webSocket demo is connecting all the time, without any error or succes prompts

### ISSUE THREAD

**Issue by Clarence-pan** [apache/incubator-weex#2335]
## Describe the bug
In weex playground APP, the webSocket demo is connecting all the time, without any error or succes prompts.

## To Reproduce

Demo: <http://dotwe.org/vue/abdcc5c77ab823a85ec66e4de571ad35>
It is the official webSocket demo of weex from <https://weex.apache.org/docs/modules/websockets.html#onerror>.
The demo works in my PC Chrome browser. But it cannot work in the Weex playground APP in the same WIFI network.
I also tried Taobao APP and Dingding APP. It did not work in them.

## Environment

* Device:  iPhone7
* OS: iOS 12.2
* Weex Playground APP Version: 4.0
* Weex SDK Version: 0.20.0
* JS Framework: 0.29.0
* Build from source : no

## Expected behavior

When I click the "connect" button, the websocket should be connected. 

## Screenshots

![image](https://user-images.githubusercontent.com/8750132/56333787-1aa6c000-61c8-11e9-88ba-95374d3f12f0.png)

**Comment by azamat-sharapov** [comment]
Same on android.

**Comment by wqyfavor** [comment]
这个是服务端的问题，建议做代码参考，不用在意能否连上。之后我们有时间会再看一下这个demo。谢谢

**Comment by Clarence-pan** [comment]
@wqyfavor 如果是服务端的问题，为啥PC浏览器上能连上呢？
