### ISSUE TITLE
[Android][Dev-tool] open debug in application at the beginning,then app crashed

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#2338]
https://weex.apache.org/zh/guide/debug/integrate-devtool-to-android.html#android%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%

my environment:
`
C:\Users\flw>weex -v
2.0.0-beta.25 (Core 2.0.0-beta.25)
- @weex-cli/preview : v2.0.0-beta.1
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/generator : v2.0.0-beta
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/debug : v2.0.0-beta.25

`

1. weex create myApp & add android, then run it in android studio,it seems well

2.weex debug  --port 8888 --channelid 1,chrome opened

3.in android studio :
![image](https://user-images.githubusercontent.com/36951996/56416794-7fdfdb80-62c4-11e9-9f15-6875c16a05eb.png)

just the same as the official document said,but the app crached,whether enable is true or false

here is the logcat:

![image](https://user-images.githubusercontent.com/36951996/56416922-ed8c0780-62c4-11e9-8624-620c7830ec4a.png)

**Comment by YorkShen** [comment]
If you have question about dev-tool, you should ask in [weex dev tool](https://github.com/weexteam/weex-devtool-iOS) repo.
