### ISSUE TITLE
textarea 无法移除焦点吗？只能通过软键盘移除？

### ISSUE THREAD

**Issue by pidogc** [apache/incubator-weex#2340]
input组件的方法报错undefined

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Can't textarea remove focus? Can only be removed via the soft keyboard?
> 1. Please follow the issue template and provide your demo
> 2. Please update to the latest version.

If it doesn't list in the document, it just doesn't support.
