### ISSUE TITLE
[Android]再viewappear里面使用 globalEvent.addEventListener接收不到app传过去的值

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#2343]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: [Android] Then viewappear uses globalEvent.addEventListener to receive the value passed by the app.

1. Please follow the issue template and provide your demo
2. Please update to the latest version.

I will just close the issue, feel free to reopen with your demo and the latest of Weex.
