### ISSUE TITLE
iOS 当有个人热点状态栏的时候，底部导航栏显示不全

### ISSUE THREAD

**Issue by chenhuocan** [apache/incubator-weex#2346]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: iOS When there is a personal hotspot status bar, the bottom navigation bar is incomplete.

1. Please follow the issue template and provide your demo
2. Please update to the latest version.

I will just close the issue, feel free to reopen with your demo and the latest of Weex.
