### ISSUE TITLE
[Android][Dev-tool] Unexpected behavior when 轮播图，最后一张到第一张的时候，会闪屏 where weex version is 0.20.0.2

### ISSUE THREAD

**Issue by wujianqiang6** [apache/incubator-weex#2351]
轮播图，最后一张到第一张的时候，会闪屏。。什么问题，有人遇到过吗

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Carousel map, the last one will flash when the first one

1. Please follow the issue template and provide your demo
2. Please update to the latest version.

I will just close the issue, feel free to reopen with your demo and the latest of Weex.
