### ISSUE TITLE
[iOS] iOS 的怎么查看Log啊？？

### ISSUE THREAD

**Issue by Yinlujia** [apache/incubator-weex#2357]
## Describe the bug
iOS 上看不到console.log打印的日志啊，iOS 原生的也看不到，
用weex run ios 运行的，xcode 上没有打印的，mac的控制台也看不到打印的log，要疯了，
哪位大神棒棒忙啊。

## Environment
simulator 6s  iOS 12.2

**Comment by hponiang** [comment]
打开xcode直接在里面看， 或者你可以将输出重定向到log文件

**Comment by Yinlujia** [comment]
@hponiang 用weex run ios 运行起来的，xcode的控制台看不到log，不知道咋回事儿，什么输出都没有的

**Comment by hponiang** [comment]
weex run ios后需要 重新再用xcode run起来

或者参考 
https://www.jianshu.com/p/ae1d7a2b0a8a
最下面的内容

**Comment by Yinlujia** [comment]
Thanks
