### ISSUE TITLE
[Android] weex scroller @scrollend can't support  

### ISSUE THREAD

**Issue by 1kr** [apache/incubator-weex#2358]
[ios] can support scrollend

**Comment by YorkShen** [comment]
If it doesn't list on the document, then it just doesn't support.

**Comment by fund-iconfont** [comment]
The document has listed that "The component `scroller` support `scrollstart` & `scrollend` " , but the actual is not supported.

**Comment by YorkShen** [comment]
Without a demo, I don't think there is anyone could help you.
