### ISSUE TITLE
[iOS] xcode run project throw library not found for -lSDWebImage

### ISSUE THREAD

**Issue by Yinlujia** [apache/incubator-weex#2359]
## Describe the bug

When I run project use xcode, it throw an error: library not found for -lSDWebImage.
How can i fix it??
## Environment

* Device: simulator iPhone6
* OS:  iOS 12.2

**Comment by YorkShen** [comment]
Could please provide more detail, stacktrace would be help.

**Comment by YorkShen** [comment]
The issue is closed due to no update.

Feel free to reopen it if you have further questions.
