### ISSUE TITLE
[Android][Dev-tool] weex_sdk:0.20.0.2 WCAG 无障碍读取异常

### ISSUE THREAD

**Issue by Moycks** [apache/incubator-weex#2360]
当使用weex_sdk:0.20.0.2 时，Android 使用无障碍会读出奇怪的数字，IOS正常。回退到0.17 0.18发现可以正常读出。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description:  When using weex_sdk:0.20.0.2, Android uses accessibility to read strange numbers, IOS is normal. Falling back to 0.17 0.18 found that it can be read normally.

Please follow the issue template and provide your demo.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
