### ISSUE TITLE
[Android] Unexpected behavior when canvas.clipRect(newRect, Region.Op.REPLACE),where weex version is 0.20.0.2

### ISSUE THREAD

**Issue by panic-java** [apache/incubator-weex#2361]
java.lang.IllegalArgumentException
Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
com.taobao.weex.utils.BoxShadowUtil$OverflowBitmapDrawable.draw(SourceFile:402)

android 9,level 28，崩溃处：
com.taobao.weex.utils.BoxShadowUtils 402行，

canvas.clipRect(newRect, Region.Op.REPLACE);

应做版本兼容
 if(Build.VERSION.SDK_INT >= 26){
     canvas.clipRect(mClipBounds);
 }else {
     canvas.clipRect(mClipBounds, Region.Op.UNION);
 }

**Comment by YorkShen** [comment]
Actually, it is not that easy. The behavior of Android system is inconsistent.

Ref #2279 for detail

**Comment by YorkShen** [comment]
Fixed by #2545
