### ISSUE TITLE
预览input标签无法输入

### ISSUE THREAD

**Issue by wangyunlong0418** [apache/incubator-weex#2362]
在预览页面输入框无法输入内容

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description:  Cannot enter content in the preview page input box

Please follow the issue template and provide your demo.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
