### ISSUE TITLE
an issue when packing android apk

### ISSUE THREAD

**Issue by nikojxie** [apache/incubator-weex#2372]
The error is here:
What went wrong: Could not resolve all files for configuration ':sdk:releaseCompileClasspath'. Could not find com.android.support:recyclerview-v7:25.3..
Searched in the following locations: file:/Users/mac/Library/Android/sdk/extras/m2repository/com/android/support/recyclerview-v7/25.3./recyclerview-v7-25.3..pom file:/Users/mac/Library/Android/sdk/extras/m2repository/com/android/support/recyclerview-v7/25.3./recyclerview-v7-25.3..jar file:/Users/mac/Library/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/25.3./recyclerview-v7-25.3..pom file:/Users/mac/Library/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/25.3./recyclerview-v7-25.3..jar file:/Users/mac/Library/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/25.3./recyclerview-v7-25.3..pom file:/Users/mac/Library/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/25.3./recyclerview-v7-25.3..jar

I tried many ways but still couldn't solve it..... Thanks for your help

**Comment by YorkShen** [comment]
I think this problems has nothing to do with Weex, it is about normal Android development.
