### ISSUE TITLE
[Android]Security Issue: 任意命令执行和目录遍历漏洞

### ISSUE THREAD

**Issue by tuhaolam** [apache/incubator-weex#2376]
### 问题1
以下api可通过webview对象向页面javascript导出java本地接口，可能导致任意命令执行
> https://github.com/apache/incubator-weex/blob/15e8df0a1aeddbb6a41afcccee373944e68914a9/android/sdk/src/main/java/com/taobao/weex/ui/view/WXWebView.java
### 建议1
建议禁用危险接口addJavascriptInterface导出Java类及方法；移除系统webkit内置的searchBoxJavaBridge_和accessibility和accessibilityTraversal这三个危险接口；

### 问题2
以下文件中的ZipEntry.getName()方法未过滤"../"，可导致目录遍历: 
> https://github.com/apache/incubator-weex/blob/a0222dbefad18e7d1fb0e75a6cf5f52e887e66d3/android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
### 建议2
ZipEntry.getName()该方法的返回值中如果包含有../跳转符，会存在目录遍历漏洞，请过滤../跳转符。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用英语回答你的问题。

I will remove your comment as it may damage our user, please report security related issue through private@weex.apache.org.  Thanks for your cooperation.
