### ISSUE TITLE
[Android 8] modal.alert不显示oktitle

### ISSUE THREAD

**Issue by XuedaoYuan** [apache/incubator-weex#2377]
![image](https://user-images.githubusercontent.com/14260107/56874804-f58b3a80-6a6e-11e9-9467-c2c5fdcc945c.png)
android8 下modal组件不显示okTitle和cancelTitle。 可以点击但是字体颜色貌似丢失了

**Comment by XuedaoYuan** [comment]
"weex-loader": "^0.7.2",
 "weex-vue-precompiler": "^0.1.17"
 "weex-ui": "^0.6.7",  
 "weex-vue-render": "^1.0.17"

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The modal component of android8 does not display okTitle and cancelTitle. Can click but the font color seems to be missing

Please follow the issue template and provide your demo as I really can't help you with such little information.

I will just close the issue, feel free to reopen with your demo and the latest of weex.

**Comment by XuedaoYuan** [comment]
thanks a lot!
