### ISSUE TITLE
[Android] text组件中文和长串英文发生换行

### ISSUE THREAD

**Issue by niannianer** [apache/incubator-weex#2379]
[Android]手机上， 几个中文，之后是长串英文字母，英文会换行，设置word-break: keep-all;也不管用

http://dotwe.org/vue/c25eec077761b5200be5fd6d74d27011

**Comment by qgmzhna** [comment]
汉字和英文之间加空格就换行了。
It works when add a space after the Chinese character

**Comment by niannianer** [comment]
> 汉字和英文之间加空格就换行了。
> It works when add a space after the Chinese character

中文和英文之间没有加空格，我希望整个内容不换行，满一行再换行

**Comment by YorkShen** [comment]
This is undefined behaviour, ref [link](https://weex.apache.org/zh/docs/components/text.html#%E5%85%B6%E4%BB%96) for more information

**Comment by niannianer** [comment]
> This is undefined behaviour, ref [link](https://weex.apache.org/zh/docs/components/text.html#%E5%85%B6%E4%BB%96) for more information
http://dotwe.org/vue/c25eec077761b5200be5fd6d74d27011
请用安卓手机和ios手机分别看效果，ios手机中英文连在一起，满一行才换行，安卓中英文发生折行
