### ISSUE TITLE
[iOS]input设置maxlength，获取到的内容比最大长度多一位

### ISSUE THREAD

**Issue by niannianer** [apache/incubator-weex#2380]
input设置maxlength，比如3，输入1234，input的内容显示的是123，但是获取到的变量值实际是1234

请在weex playground上扫二维码，在input中输入内容看效果

http://dotwe.org/vue/f149d8caf693178d14cf0d036d2684f5

**Comment by YorkShen** [comment]
We will look into that.

**Comment by jianhan-he** [comment]
你好，该问题已经修复，非常感谢你的反馈。你可以用最新的代码进行验证。
