### ISSUE TITLE
[Android][iOS] Regarding the inconsistency of refresh on ios on Android, how can I solve it?

### ISSUE THREAD

**Issue by pidogc** [apache/incubator-weex#2381]
![image](https://user-images.githubusercontent.com/42857270/56889086-62301600-6a2a-11e9-859d-e517090f58d4.png)
![image](https://user-images.githubusercontent.com/42857270/56889131-7a079a00-6a2a-11e9-9331-0035f58d8822.png)

**Comment by pidogc** [comment]
The elements wrapped in the refresh component on Android appear directly, and I found that ios has some error in positioning px on Android.

**Comment by YorkShen** [comment]
Please follow the issue template and provide your demo as I really can't help you with such little information.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
