### ISSUE TITLE
[Android]Unexpected behavior with android app bundle and dynamic feature from varsion gradle 3.3.0 where weex version is 0.20.0.2@aar

### ISSUE THREAD

**Issue by vikasrathore** [apache/incubator-weex#2386]
## Describe the bug
1- Enabled Android app bundle with gradle version 3.3 and weex pages stopped working. We could see that the .so files were not getting loaded.
2- Contacted google- they have asked to load SO file by System.load or System.loadlobrary, since they have made changes in compression of .so files. For time being, they have asked to add a temporary fix by adding a flag in gradle **android.bundle.enableUncompressedNativeLibs=false** this thread you can access here [**https://issuetracker.google.com/issues/125164369**](url).
The above URL contains complete details.
3-The weex pages started loaded on gradle 3.3.0 after that 
4-We have enabled dynamic delivery of android features. You can find the details in below links. 
[https://developer.android.com/studio/projects/dynamic-delivery](url)
[https://developer.android.com/guide/app-bundle/playcore](url)

5-In our app, we are trying to add the weex library as a dynamic feature modules and delivery it to users as dynamic download module. In dynamic delivery guideline the so files needed to  by **SplitInstallHelper.loadLibrary(Context context, String libName)**. You can find that from below link. 

[https://developer.android.com/guide/app-bundle/playcore#load_native_libs](url)

6-When we install a fresh version of app, when we try to load the weex page it gives following error.
**onExceptionerrCode -1001 msg degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1**
7- we checked **WXEnvironment.sApplication is not null** and on render it gives above error first time .
8- If we push the update to the existing install app, then weex pages start working and load .js file from assets folder 
Here is repo [https://github.com/prankulg/DynamicDeliveryDemo/](url) checkout branch **weexsdk**

**Comment by shreyagarwal** [comment]
@vikasrathore Were you able to get any remarks from weex team for this ?

**Comment by lucky-chen** [comment]
> When we install a fresh version of app, when we try to load the weex page it gives following error.
> onExceptionerrCode -1001 msg degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

works fine on pixel2(Android 9.0)

> onExceptionerrCode -1001 msg degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

 in your  case , check `SoLoader.doLoadLibrary()`, may be the so load failed

**Comment by vikasrathore** [comment]
@lucky-chen Thanks for the help. I have did multiple tests. 

1) Fully qualified name : I have given the fully qualified name for the so file and tried to load via custom SO loader

String fullPath= ”/data/data/" + pkgName + "/lib/" + shortName;

SplitInstallHelper.loadLibrary(mContex, fullPath);

It does not work at both debug(Android studio build) and release(play store build)

2) When I have given the so name, eg “weexcore” and tried the custom so loader

SplitInstallHelper.loadLibrary(mContex, shortPath);

It also does not work when you download from play store.

The issue is happening if we move the weex lib to the dynamic feature module and trying to initialise it. To check this, you need to install this sample app. If you can share your email address, we can add you in the internal test track of this app. Then you will be able to download and check it.

**Comment by lucky-chen** [comment]
@veightz show log here , or debug source code `WXSoInstallMgrSdk.initSo() ` , check `InitSuc` flag

```
    boolean InitSuc = false;
//    if (checkSoIsValid(libName, BuildConfig.ARMEABI_Size) ||checkSoIsValid(libName, BuildConfig.X86_Size)) {

      /**
       * Load library with {@link System#loadLibrary(String)}
       */
      try {
        // If a library loader adapter exists, use this adapter to load library
        // instead of System.loadLibrary.
        if (mSoLoader != null) {
          mSoLoader.doLoadLibrary(libName);
        } else {
          if ("weexcore".equalsIgnoreCase(libName)){
            File newFile = new File("/data/local/tmp/libweexcore.so");
            if (newFile.exists()){
              File cacheFile = new File(WXEnvironment.getApplication().getCacheDir(),"libweexcore.so");
              WXFileUtils.copyFile(newFile,cacheFile);
              System.load(cacheFile.getAbsolutePath());
            }else {
              System.loadLibrary(libName);
            }
          }
        }


     // true ??????
        InitSuc = true;
      } catch (Exception | Error e2) {
        if (cpuType.contains(ARMEABI) || cpuType.contains(X86)) {
          WXExceptionUtils.commitCriticalExceptionRT(null,
                  WXErrorCode.WX_KEY_EXCEPTION_SDK_INIT,
                  "initSo", "[WX_KEY_EXCEPTION_SDK_INIT_CPU_NOT_SUPPORT] for android cpuType is " +cpuType +
                          "\n Detail Error is: " +e2.getMessage(),
                  null);
        }
       //false ??????
        InitSuc = false;
      }
```

**Comment by krissGit** [comment]
@lucky-chen Thanks for your Help. 
we are using SDk version 0.20.0.2 , In this version WXSoInstallMgrSdk.initSo()  doesn't have check  against "weexcore" lib name condition( if ("weexcore".equalsIgnoreCase(libName)) ) but in your reply its there ,can you tell us your SDK version ?
 


<img width="1469" alt="Screen Shot 2019-05-08 at 2 21 14 PM" src="https://user-images.githubusercontent.com/16849695/57362584-ca09fd80-719c-11e9-8c11-315fcd7131e1.png">

**Comment by vikasrathore** [comment]
We found the exact path where .so files are placed in fresh install(dynamic deliver first time) and 
update app first time.

**In fresh install** - 
Here is path of so files absolute path  -
    : File Absolute path  : /data/data/com.test.dynamictest/files/splitcompat/90/native-libraries/weexsdk.config.armeabi_v7a/libJavaScriptCore.so
    : File Absolute path  : /data/data/com.test.dynamictest/files/splitcompat/90/native-libraries/weexsdk.config.armeabi_v7a/libweexjss.so
   : File Absolute path  : /data/data/com.test.dynamictest/files/splitcompat/90/native-libraries/weexsdk.config.armeabi_v7a/libweexjsb.so
    : File Absolute path  : /data/data/com.test.dynamictest/files/splitcompat/90/native-libraries/weexsdk.config.armeabi_v7a/libweexjst.so
    : File Absolute path  : /data/data/com.test.dynamictest/files/splitcompat/90/native-libraries/weexsdk.config.armeabi_v7a/libweexcore.so

in Custom so loader we tried with Sytstem.load(absPath) it does not work.

**In First update** 
Here is path of so files absolute path  -
    : File Absolute path  : /data/data/com.test.dynamictest/lib/libJavaScriptCore.so
    : File Absolute path  : /data/data/com.test.dynamictest/lib/libweexjsb.so
    : File Absolute path  : /data/data/com.test.dynamictest/lib/libweexcore.so
    : File Absolute path  : /data/data/com.test.dynamictest/lib/libweexjst.so
    : File Absolute path  : /data/data/com.test.dynamictest/lib/libweexjss.so

in Custom so loader we tried with Sytstem.load(absPath) it does not work.

after that we tried to copy .so file from  **/data/data/com.test.dynamictest/files/splitcompat/90/native-libraries/weexsdk.config.armeabi_v7a/**    to  **/data/data/com.test.dynamictest/lib/**

but did not work throws an exception 

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.paytm.ddtest/files/splitcompat/106/native-libraries/weexsdk.config.armeabi_v7a/libweexcore.so" is 32-bit instead of 64-bit
       at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.test.dynamictest.MainActivity.copyFile(MainActivity.java:323)
       at com.test.dynamictest.MainActivity.copySoFiles(MainActivity.java:297)
       at com.test.dynamictest.MainActivity.lambda$onCreate$2(MainActivity.java:130)
       at com.test.dynamictest.-$$Lambda$MainActivity$3xLwvPeKh80p6MkuBh4_ajkgmUI.onClick(Unknown Source:2)
       at android.view.View.performClick(View.java:6302)
       at android.view.View$PerformClick.run(View.java:24782)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**WeexSdk has 32 bit .so files and because of that it fails to copy in /data/data/com.test.dynamictest/lib/.**
Please update on this.

**Comment by krissGit** [comment]
Hi @lucky-chen we observed that Weex sdk version 0.20 is creating only 32 bit of .so files for ARM and x86 Platform.
<img width="166" alt="Screen Shot 2019-05-10 at 10 53 30 AM" src="https://user-images.githubusercontent.com/16849695/57504488-58ec5680-7312-11e9-940e-3dbce7ab2164.png">

Suppose it should create some more folder like **lib/arm64-v8a and lib/x86_64** to support 64 bit libraries .
As per Google we need to support 64 bit Starting August 1, 2019 
ref link : https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by lucky-chen** [comment]
@vikasrathore the issue is .so load failed, loos like `SoLoader` impl has bug in appbundle.

1. for 32/64 bit .so

 64bit so will be support  before  the  Google’s deadline . we are working at

2. about solultion:
```
after that we tried to copy .so file from /data/data/com.test.dynamictest/files/splitcompat/90/native-libraries/weexsdk.config.armeabi_v7a/ to /data/data/com.test.dynamictest/lib/
```
does it is official recommendation for `appbundle`？

check appbundle's official doc both you and me, google should have solution there

**Comment by vikasrathore** [comment]
It's not official recommendation. we tried this because it expects .so files to be in '/data/data/com.test.dynamictest/lib/' .

**Comment by krissGit** [comment]
@lucky-chen Thanks for your reply.
In 32 bit Device with same SoLoader its working fine.

But in case of 64 bit device its not working with below Exception
"/data/data/com.paytm.ddtest/files/splitcompat/106/native-libraries/weexsdk.config.armeabi_v7a/libweexcore.so" is 32-bit instead of 64-bit

**Comment by lucky-chen** [comment]
@krissGit 
same issue of 64bit  : https://github.com/apache/incubator-weex/issues/2389 
and check process on dev mail list  ：https://lists.apache.org/thread.html/bc2be5495bfe47df0fcbfcbf16299023e24a7ec8e254120e60d553ec@%3Cdev.weex.apache.org%3E

**Comment by lucky-chen** [comment]
#2389

**Comment by Darin726** [comment]
OK, I got this issue And I am working on making weex support 64-bit cpu, I think you may fix your problem through this way temporarilly.

`Remove all your app's 64-bit so file, And load 32-bit so file in all devices.`

```gradle
android {
    ...
    defaultConfig {
        ...
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }

        packagingOptions {
            exclude "lib/arm64-v8a/xxx.so"
        }
    }
}
```

**Comment by vikasrathore** [comment]
ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        packagingOptions {
            exclude "lib/arm64-v8a/weexcore.so"
        }

added above  and got below response 

05-20 14:02:24.554 30691 30691 W ResourceType: For resource 0x7f0d0047, entry index(71) is beyond type entryCount(58)
05-20 14:02:24.555 30691 30691 D SplitCompat: FileStorage: initializing (files directory = /data/user/0/com.test.dynamictest/files, versionCode = 98)
05-20 14:02:24.558 30691 30691 D SplitCompat: NativeLibraryExtractor: split 'weexsdk.config.armeabi_v7a' has native library 'libJavaScriptCore.so' for ABI 'armeabi-v7a'
05-20 14:02:24.558 30691 30691 D SplitCompat: NativeLibraryExtractor: split 'weexsdk.config.armeabi_v7a' has native library 'libweexcore.so' for ABI 'armeabi-v7a'
05-20 14:02:24.558 30691 30691 D SplitCompat: NativeLibraryExtractor: split 'weexsdk.config.armeabi_v7a' has native library 'libweexjsb.so' for ABI 'armeabi-v7a'
05-20 14:02:24.558 30691 30691 D SplitCompat: NativeLibraryExtractor: split 'weexsdk.config.armeabi_v7a' has native library 'libweexjss.so' for ABI 'armeabi-v7a'
05-20 14:02:24.558 30691 30691 D SplitCompat: NativeLibraryExtractor: split 'weexsdk.config.armeabi_v7a' has native library 'libweexjst.so' for ABI 'armeabi-v7a'
05-20 14:02:24.558 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI arm64-v8a
05-20 14:02:24.558 30691 30691 D SplitCompat: NativeLibraryExtractor: there are native libraries for supported ABI armeabi-v7a; will use this ABI
05-20 14:02:24.559 30691 30691 D SplitCompat: NativeLibraryExtractor: using library libweexjsb.so for ABI armeabi-v7a
05-20 14:02:24.559 30691 30691 D SplitCompat: NativeLibraryExtractor: using library libweexcore.so for ABI armeabi-v7a
05-20 14:02:24.559 30691 30691 D SplitCompat: NativeLibraryExtractor: using library libweexjst.so for ABI armeabi-v7a
05-20 14:02:24.559 30691 30691 D SplitCompat: NativeLibraryExtractor: using library libJavaScriptCore.so for ABI armeabi-v7a
05-20 14:02:24.559 30691 30691 D SplitCompat: NativeLibraryExtractor: using library libweexjss.so for ABI armeabi-v7a
05-20 14:02:24.559 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI armeabi
05-20 14:02:24.561 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI arm64-v8a
05-20 14:02:24.561 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI armeabi-v7a
05-20 14:02:24.561 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI armeabi
05-20 14:02:24.563 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI arm64-v8a
05-20 14:02:24.563 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI armeabi-v7a
05-20 14:02:24.563 30691 30691 D SplitCompat: NativeLibraryExtractor: there are no native libraries for supported ABI armeabi
05-20 14:02:24.565 30691 30691 D SplitCompat: addAssetPath completed with 7
05-20 14:02:24.565 30691 30691 D SplitCompat: addAssetPath completed with 8
05-20 14:02:24.566 30691 30691 D SplitCompat: addAssetPath completed with 9
05-20 14:02:24.566 30691 30691 D SplitCompat: Split 'weexsdk.config.armeabi_v7a' installation emulated

**Comment by vikasrathore** [comment]
@Darin726 tried with this too  
ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        packagingOptions {
            exclude "lib/arm64-v8a/weexcore.so"
            exclude "lib/arm64-v8a/weexjst.so"
            exclude "lib/arm64-v8a/JavaScriptCore.so"
            exclude "lib/arm64-v8a/weexjss.so"
        }

not worked .. by adding both in feature module and base app.

**Comment by lucky-chen** [comment]
@vikasrathore  
maybe found the tmp soultion on [google's doc](https://codelabs.developers.google.com/codelabs/your-first-dynamic-app/index.html#3)
open app/build.gradle and add the following inside the android {} block:
```
bundle {
   language {
       enableSplit = true
   }
   density {
       enableSplit = true
   }
   abi {
       enableSplit = true
     //change to false
   }
}
```

if still not work , wait 64bit support （will be completed at the middle of June.）
 check process on [dev mail list ](https://lists.apache.org/thread.html/bc2be5495bfe47df0fcbfcbf16299023e24a7ec8e254120e60d553ec@%3Cdev.weex.apache.org%3E)

and this issue will be closed ， all 64bit issue be merged to #2389

**Comment by vikasrathore** [comment]
@lucky-chen please update

**Comment by NithinJohn** [comment]
@lucky-chen We have tested the weex loading issue with android app bundle in .26 version of weex. We could see that it is still present. We have tested it with custom .so loader, still its not working. 

https://issuetracker.google.com/issues/125164369

Without using the below flag in android the pages are not getting loaded. 
android.bundle.enableUncompressedNativeLibs=false
