### ISSUE TITLE
对于<cell>组件, 使用v-for时, 是否需要写key?

### ISSUE THREAD

**Issue by DevWhan** [apache/incubator-weex#2388]
在Android0.18.0上, 写了key=index 会造成cell数据错误(随机缺少cell),iOS未发现
查阅了iOS(0.19.0)源码中的<cell>组件 未发现有关"key"的使用
在官方文档也没有找到这方面的说明
请问只针对于Android和iOS来说, 在<cell>组件使用v-for时 是否有必要写key, 其中的缓存机制是怎样的? 如果可以麻烦告知下相关原理, 感谢

**Comment by zshshr** [comment]
Give an example of how to reproduce this problem. http://dotwe.org/vue

**Comment by zsmjhtn** [comment]
我们团队使用weex2年多，偶现 线上页面 元素缺失不展示的问题，列表出现率更高。一直没找到原因，昨天线上遇到一个 离奇的 布局不展示问题，可以能稳定的重现 一个没有被 v-if 控制的布局，居然会受到影响而消失！
我觉得这和之前我们线上偶现的元素不展示问题、DevWhan提到的Android写了key=index 会造成cell数据错误(随机缺少cell)的问题、以及我稳定复现提出的issue，这3者有强烈关系。
ios在0.18未出现，但之前我们用0.1版本时，ios也会偶现部分元素不展示问题。
猜测是 js传递到安卓原生，原生构建虚拟Dom树 至 虚拟DOM树 渲染为 原生布局，这个过程中出了问题，导致元素丢失。
不知道是 构建虚拟Dom树时丢失的？还是render时机丢失的？
麻烦官方人员抽点时间，试试我 issue中的 demo，解释下这种现象的原因。
谢谢了🙏

**Comment by zsmjhtn** [comment]
#2391

**Comment by Felix8029** [comment]
同问题，挺严重的，希望官方解决

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: On Android0.18.0, writing key=index will cause cell data error (randomly missing cell), iOS did not find the components in the iOS (0.19.0) source code and found no use of "key" in the official documentation. Find instructions for this. Is it only for Android and iOS, is it necessary to write a key when the component uses v-for, what is the caching mechanism? If you can trouble tell the relevant principles, thank you

Please follow the issue template and provide your demo as I really can't help you with such little information.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
