### ISSUE TITLE
Need armeabi-v7a, arm64-v8a and x86_64 architectures support in Android Weex SDK

### ISSUE THREAD

**Issue by nikkulshrestha** [apache/incubator-weex#2389]
## Describe the bug
Currently, Android Weex SDK doesn’t support armeabi-v7a, arm64-v8a and x86_64 architectures. From August 2019 onwards Google will not allow apps on Playstore which does not have support for these architectures. So we need these architectures to support in Weex SDK.

## Expected behavior
Weex SDK should support x64 architectures eg. armeabi-v7a, arm64-v8a and x86_64.

## Additional context
For more info please check the following link:
https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by YorkShen** [comment]
We are working on this issue now, and I think we will solve the problem in the early of June.

Thanks.

**Comment by Darin726** [comment]
I'm working on this issue, and arm64-v8a so has been built out now.  As YorkShen said,  it will be released with Weex 0.26

**Comment by YorkShen** [comment]
ARM 64 is supported now.

#2561

**Comment by ginuim** [comment]
so it released with Weex 0.26?

YorkShen <notifications@github.com> 于2019年6月18日周二 下午8:49写道：

**Comment by yanghuaxiong** [comment]
What is the latest arm64-v8a version?

**Comment by YorkShen** [comment]
Please subscribe the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list). According to ASF's [policy](https://apache.org/legal/resolved.html#category-x), Weex 0.26 will not be release until the [LGPL issue](https://issues.apache.org/jira/browse/LEGAL-464) is solved. The information will be updated in the mailing list, not there.

**Comment by ginuim** [comment]
Ok，Thank you very much!

YorkShen <notifications@github.com> 于2019年6月24日周一 下午7:50写道：

**Comment by yanghuaxiong** [comment]
When will version 26 be available? I can download the SDK reference directly, but it didn't work
