### ISSUE TITLE
模拟器无法运行

### ISSUE THREAD

**Issue by chengsan** [apache/incubator-weex#2390]
使用WEEX_SDK 0.20.01版本，在模拟器上无法运行，NDK配置为：
ndk {
            abiFilters "x86"
            abiFilters "armeabi"
            abiFilters "armeabi-v7a"
        }
但是使用官网的Weex Playground是可以在模拟器上运行的，并且我看了版本也是0.20.01，这是什么原因？

**Comment by zsmjhtn** [comment]
weex sdk的so只支持armeabi/x86，armeabi-v7a的手机架构怕是 initWeexFramework就抛错崩溃了吧

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: With WEEX_SDK 0.20.01, it can't run on the emulator. The NDK is configured as: ndk { abiFilters "x86" abiFilters "armeabi" abiFilters "armeabi-v7a" } But the Weex Playground using the official website can be run on the emulator. And I saw the version is also 0.20.01, what is the reason?

Please follow the issue template and provide stacktrace as I really can't help you with such little information.

I will just close the issue, feel free to reopen with more information.
