### ISSUE TITLE
[Android]Unexpected behavior when I control v-if where weex version is 0.18

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex#2391]
## Describe the bug

just look the code:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/18029210/57190488-3f7f8f00-6f4d-11e9-9e9b-9dc17845c9ee.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/18029210/57190500-663dc580-6f4d-11e9-8752-f9d30c4bcd17.png">
<img width="446" alt="image" src="https://user-images.githubusercontent.com/18029210/57190504-6d64d380-6f4d-11e9-925b-18e977436f97.png">

when the **data** back from network, **both params**  are changing from **Visiable** to **Gone**,which named **is201904** && **isSubscribeWX** for controlling UI。
In my opinion, only the **image** && **the second div** will disappear，and weex always work like this。
To my surprise,
`<text style="font-size:24px;color:#999;" >{{currentMonth}}月已收收益(元)</text>`
this text will disappear, too !!!
I know both use v-if && v-else will **reuse** the layout without a **key** in **Vue**.But I remind  Vue will not reuse layout  when I only use **v-if**。
I have found two ways to solve / avoid this problem:
1. Set a key for the disappear text.Tell Vue not reuse this text.And text will not be gone . But I don not know why **Weex/Vue** thought this text should be reuse !?? 
2. Not change both params at the time.Set one param at the front of another. For example, 
`setTimeout(()=> this.is201904 = ..., 3000)
 setTimeout(()=> this.isSubscribeWX = ...., 3000)
`
## Environment

weex 0.18  
all android device behaviour it
ios is ok！👌
## Expected behavior

The text which without v-if control will not disappear 。I don not think it is a right behaviour in Android ！

**Comment by zsmjhtn** [comment]
@zshshr @YorkShen 
BTW, we have found  some elements will disappear out of mind  in WeexActivity  at online APP sometimes. It is a stubborn problem, and  we have no way to  reappear it stablely.
Associate with this problem, we think maybe something going wrong in Weex Android  SDK , between V-Dom converting to Render Layout。 
Please spend sometime for this problem。
Thanks！

**Comment by YorkShen** [comment]
@zsmjhtn Could please provide a demo in [dot.we](http://dotwe.org/vue), which make my life so much easy

**Comment by zsmjhtn** [comment]
`<template>
  <com :dto="dto" :current-month="3"></com>
</template>
<style>
</style>
<script>
const _ = require("./../async/_Vue.js");
const ENHANCE = require("../enhance-vue");
const NATIVE = require('../module/wjsNative.js')
export default {
  components: {
    com: require("../components-vue/test-com.vue")
  },
  data: () => ({
    dto: {}
  }),
  created() {
    ENHANCE.enhance(this);
    NATIVE.stopLoading()
    this.$initDate = _.create()
      .fetch("/app/wealthbill/getCustProfitBill", () => ({
        month: 4,
        year: 2019
      }))
      .toastOnCode("all")
      .map(rsp => ({
        dto: rsp
      }))
      .assign(this)
      .invoke();
  }
};
</script>
`
`<template>
  <div class="main">
    <scroller class="main-scroll">
      <div class="div-card">
        <image v-if="isSubscribeWX == '0'" class="img-wx" :src="'img/bill_wx.png'"> </image>
        <div class="div-card-header">
          <text style="font-size:24px;color:#999;" >{{currentMonth}}月已收收益(元)</text>
          <image style="width:24;height:24;margin-left:8" src="img/icon_tips.png"></image>
        </div>
        <div v-if="is201904 == '0'"  class="div-card-bottom">
          <text :style="{'font-size':24,color:'#333'}">比上月</text>
        </div>
      </div>
    </scroller>
  </div>
</template>
<style>
.main {
  width: 750;
  justify-content: flex-start;
  align-items: center;
  background-color: #ffffff;
}
.main-scroll {
  flex: 1;
  width: 750;
  justify-content: flex-start;
  align-items: center;
   padding-bottom: 40;
}
.img-wx{
  position: absolute;
  right: 0;
  top: 28;
  width: 150;
  height: 44;
}
.img-bg {
  position: absolute;
  left: 0;
  top: 0;
  bottom:0;
  right:0;
  width: 750;
  height: 1402;
}
.div-center {
  margin-top: 24;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  background-color: #ffffff;
  box-shadow:0 6px 20px 0 rgba(0,0,0,0.06);
  border-radius:16px;
}

.div-card {
  margin-top: 24px;
  background-color: #ffffff;
  box-shadow: 0 6px 20px 0 rgba(0, 0, 0, 0.06);
  border-radius: 16px;
  width: 700px;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
}
.div-card-header {
  margin-top: 32px;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}
.div-card-bottom {
  margin-top: 16px;
  margin-bottom: 40px;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}

.div-profit {
  margin-top: 40px;
  margin-bottom: 54px;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
</style>
<script>
const _ = require("./../async/_Vue.js");
const ENHANCE = require("../enhance-vue");
export default {
  props:{
    dto:{
      type:Object,
      default:{},
    },
    currentMonth:{
      type: Number,
      default: undefined,
    }
  },
  watch: {
    dto: {
      handler: function(x) {
        this.buildViewModule(x)
      },
      immediate: true
    },
  },
  data: () => ({
    totalProfit: 0,//总收益
    is201904:0,//'1'是，‘0’不是
    isSubscribeWX:0,//'1'是，‘0’不是
  }),
  created() {
    ENHANCE.enhance(this);
   
  },
  methods: {
    buildViewModule(dto){
      this.totalProfit = dto.totalProfit
      setTimeout(()=>{
           this.isSubscribeWX = dto.isSubscribeWX || '0';
           this.is201904 = dto.is201904 || '0';
      }, 3000)
    }
  }
};
</script>

`

**Comment by zsmjhtn** [comment]
main Page:
`<template>
  <com :dto="dto" :current-month="3"></com>
</template><script>
const _ = require("./../async/_Vue.js");
const ENHANCE = require("../enhance-vue");
const NATIVE = require('../module/wjsNative.js')
export default {
  components: {
    com: require("../components-vue/test-com.vue")
  },
  data: () => ({
    dto: {}
  }),
  created() {
    ENHANCE.enhance(this);
    NATIVE.stopLoading()
    this.$initDate = _.create()
      .fetch("/app/wealthbill/getCustProfitBill", () => ({
        month: 4,
        year: 2019
      }))
      .toastOnCode("all")
      .map(rsp => ({
        dto: rsp
      }))
      .assign(this)
      .invoke();
  }
};
</script>`

**Comment by zsmjhtn** [comment]
```javascript
<template>
  <div class="main">
    <scroller class="main-scroll">
      <div class="div-card">
        <image v-if="isSubscribeWX == '0'" class="img-wx" :src="'img/bill_wx.png'"> </image>
        <div class="div-card-header">
          <text style="font-size:24px;color:#999;" >{{currentMonth}}月已收收益(元)</text>
          <image style="width:24;height:24;margin-left:8" src="img/icon_tips.png"></image>
        </div>
        <div v-if="is201904 == '0'"  class="div-card-bottom">
          <text :style="{'font-size':24,color:'#333'}">比上月</text>
        </div>
      </div>
    </scroller>
  </div>
</template>
<style>
.main {
  width: 750;
  justify-content: flex-start;
  align-items: center;
  background-color: #ffffff;
}
.main-scroll {
  flex: 1;
  width: 750;
  justify-content: flex-start;
  align-items: center;
   padding-bottom: 40;
}
.img-wx{
  position: absolute;
  right: 0;
  top: 28;
  width: 150;
  height: 44;
}
.img-bg {
  position: absolute;
  left: 0;
  top: 0;
  bottom:0;
  right:0;
  width: 750;
  height: 1402;
}
.div-center {
  margin-top: 24;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  background-color: #ffffff;
  box-shadow:0 6px 20px 0 rgba(0,0,0,0.06);
  border-radius:16px;
}

.div-card {
  margin-top: 24px;
  background-color: #ffffff;
  box-shadow: 0 6px 20px 0 rgba(0, 0, 0, 0.06);
  border-radius: 16px;
  width: 700px;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
}
.div-card-header {
  margin-top: 32px;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}
.div-card-bottom {
  margin-top: 16px;
  margin-bottom: 40px;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}

.div-profit {
  margin-top: 40px;
  margin-bottom: 54px;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
</style>
<script>
const _ = require("./../async/_Vue.js");
const ENHANCE = require("../enhance-vue");
export default {
  props:{
    dto:{
      type:Object,
      default:{},
    },
    currentMonth:{
      type: Number,
      default: undefined,
    }
  },
  watch: {
    dto: {
      handler: function(x) {
        this.buildViewModule(x)
      },
      immediate: true
    },
  },
  data: () => ({
    totalProfit: 0,//总收益
    is201904:0,//'1'是，‘0’不是
    isSubscribeWX:0,//'1'是，‘0’不是
  }),
  created() {
    ENHANCE.enhance(this);
   
  },
  methods: {
    buildViewModule(dto){
      this.totalProfit = dto.totalProfit
      setTimeout(()=>{
           this.isSubscribeWX = dto.isSubscribeWX || '0';
           this.is201904 = dto.is201904 || '0';
      }, 3000)
    }
  }
};
</script>
```

**Comment by YorkShen** [comment]
Not sure what's your problem. I am the same behaviour with you [demo](http://dotwe.org/vue/ed3c7bb018740f01ad003bff7dafb19d) and `weex 0.24`

**Comment by zsmjhtn** [comment]
> Not sure what's your problem. I am the same behaviour between android and iOS with you [demo](http://dotwe.org/vue/ed3c7bb018740f01ad003bff7dafb19d) and `weex 0.24`
> 
> I will just close the issue, feel free to reopen it if you have further question. (_I only response to issues that are opened_)

Maybe it is OK in weex 0.24. but my problem was found  in weex 0.18.
We will update Weex Version in second half of year. I will reopen it if the problem still existing.

**Comment by YorkShen** [comment]
It seems like things are solved.

I will just close the issue, feel free to reopen it if you have further question. (I only response to issues that are opened)
