### ISSUE TITLE
[iOS][WeexSDK] weex升级到最新版本 push界面有的正常，有的会崩溃，安卓是正常的

### ISSUE THREAD

**Issue by youfeng77** [apache/incubator-weex#2392]
weex升级到最新版本 push界面有的正常，有的会崩溃，安卓是正常的
![image](https://user-images.githubusercontent.com/50291405/57192485-c6d7fd00-6f63-11e9-8ee0-a24622a55fac.png)

![image](https://user-images.githubusercontent.com/50291405/57192512-fbe44f80-6f63-11e9-8f3d-443d48fb2e1b.png)

**Comment by youfeng77** [comment]
![image](https://user-images.githubusercontent.com/50291405/57192520-0ef71f80-6f64-11e9-9803-00787c7dbd14.png)

**Comment by wqyfavor** [comment]
加个异常断点，看看具体抛出来的异常是什么

**Comment by wqyfavor** [comment]
看你的截图我感觉是instanceId为空

**Comment by wqyfavor** [comment]
Close for now. If you still have problem please create another issue.
