### ISSUE TITLE
[Android]CMake Error: Could not create named generator Android Gradle - Ninja

### ISSUE THREAD

**Issue by swkfx** [apache/incubator-weex#2395]
## Environment
  NDK： r16
  cmake: 3.10+ 
  AS ：3.4
## Describe the bug
 下载Master分支直接编译报错如下错误,虽然文档说用 cmake 3.9+ 但是新的 As 3.4 是SDKManager 只能获取到 3.10 和 3.6 两个版本都试了 还是无法编译通过，尝试删除build 等cache文件及文件夹 还是同样的错误。 虽然有找到cmake 3.9 但是找不到As如何制定Cmake 版本编译。希望能指点一下。

SIMPLE: Build command failed.

SIMPLE: Error while executing process /home/jt/Android/Sdk/cmake/3.10.2.4988404/bin/cmake with arguments {-H/home/jt/dev/incubator-weex/weex_core -B/home/jt/dev/incubator-weex/android/sdk/.externalNativeBuild/cmake/release/armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=/home/jt/Android/Sdk/android-ndk-r16b -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/jt/dev/incubator-weex/android/sdk/build/intermediates/cmake/release/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/home/jt/Android/Sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/home/jt/Android/Sdk/android-ndk-r16b/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-14 -DANDROID_PLATFORM=android-19 -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DCMAKE_BUILD_TYPE=Release -DENABLE_ASAN=false}

SIMPLE: CMake Error: Could not create named generator Android Gradle - Ninja

SIMPLE: Generators

SIMPLE:   Unix Makefiles               = Generates standard UNIX makefiles.

SIMPLE:   Ninja                        = Generates build.ninja files.

SIMPLE:   Watcom WMake                 = Generates Watcom WMake makefiles.

SIMPLE:   CodeBlocks - Ninja           = Generates CodeBlocks project files.

SIMPLE:   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.

SIMPLE:   CodeLite - Ninja             = Generates CodeLite project files.

SIMPLE:   CodeLite - Unix Makefiles    = Generates CodeLite project files.

SIMPLE:   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.

SIMPLE:   Sublime Text 2 - Unix Makefiles

SIMPLE:                                = Generates Sublime Text 2 project files.

SIMPLE:   Kate - Ninja                 = Generates Kate project files.

SIMPLE:   Kate - Unix Makefiles        = Generates Kate project files.

SIMPLE:   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.

SIMPLE:   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

SIMPLE:   KDevelop3                    = Generates KDevelop 3 project files.

SIMPLE:   KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.

SIMPLE: Build command failed.

SIMPLE: Error while executing process /home/jt/Android/Sdk/cmake/3.10.2.4988404/bin/cmake with arguments {-H/home/jt/dev/incubator-weex/weex_core -B/home/jt/dev/incubator-weex/android/sdk/.externalNativeBuild/cmake/debug/armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=/home/jt/Android/Sdk/android-ndk-r16b -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/jt/dev/incubator-weex/android/sdk/build/intermediates/cmake/debug/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/home/jt/Android/Sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/home/jt/Android/Sdk/android-ndk-r16b/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-14 -DANDROID_PLATFORM=android-19 -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DCMAKE_BUILD_TYPE=Release -DENABLE_ASAN=false}

SIMPLE: CMake Error: Could not create named generator Android Gradle - Ninja

SIMPLE: Generators

SIMPLE:   Unix Makefiles               = Generates standard UNIX makefiles.

SIMPLE:   Ninja                        = Generates build.ninja files.

SIMPLE:   Watcom WMake                 = Generates Watcom WMake makefiles.

SIMPLE:   CodeBlocks - Ninja           = Generates CodeBlocks project files.

SIMPLE:   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.

SIMPLE:   CodeLite - Ninja             = Generates CodeLite project files.

SIMPLE:   CodeLite - Unix Makefiles    = Generates CodeLite project files.

SIMPLE:   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.

SIMPLE:   Sublime Text 2 - Unix Makefiles

SIMPLE:                                = Generates Sublime Text 2 project files.

SIMPLE:   Kate - Ninja                 = Generates Kate project files.

SIMPLE:   Kate - Unix Makefiles        = Generates Kate project files.

SIMPLE:   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.

SIMPLE:   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

SIMPLE:   KDevelop3                    = Generates KDevelop 3 project files.

SIMPLE:   KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.

**Comment by YorkShen** [comment]
Make sure you have deleted `weex/android/sdk/build`

**Comment by swkfx** [comment]
@YorkShen 已经确定删除  weex/android/sdk/build  以及 sdk/.externalNativeBuild 
还是报同样的错误啊

**Comment by zsmjhtn** [comment]
同样的问题，一搜issue还以为找到解决方法了，进来一看还是一贯的作风，回句话&&close～～

**Comment by aleisurelypioneer** [comment]
> 同样的问题，一搜发行还以为找到解决方法了，进来一看还是一贯的作风，回句话&&Close~~

你现在解决了吗?我也遇到了同样的问题，怎么都没有解决。
