### ISSUE TITLE
[iOS][WeexSDK] 0.20.1版本实现renderFinish方法但方法不会调用

### ISSUE THREAD

**Issue by mahailin** [apache/incubator-weex#2396]
- (WXSDKInstance *)instance
{
    if (!_instance)
    {
        __weak typeof(self) weakSelf = self;
        _instance = [[WXSDKInstance alloc] init];
        _instance.viewController = self;
        _instance.frame = self.view.frame;
        
        _instance.onCreate = ^(UIView *view) {
            
            [weakSelf.weexView removeFromSuperview];
            weakSelf.weexView = view;
            [weakSelf.view addSubview:weakSelf.weexView];
        };
        
        _instance.renderFinish = ^(UIView *view) {
            
            NSLog(@"renderFinish");
        };
    }
    
    return _instance;
}

0.20.1版本，界面渲染后renderFinish方法不会调用?打印不出“renderFinish”。

**Comment by YorkShen** [comment]
Normally, this is caused by a JS Exception.
