### ISSUE TITLE
Does the component contain a switch component? Can be used directly, but I did not find it? Not mentioned in the documentation?

### ISSUE THREAD

**Issue by pidogc** [apache/incubator-weex#2397]
![image](https://user-images.githubusercontent.com/42857270/57281604-303d3600-7060-11e9-81ce-d8aa7e9c6752.png)
![image](https://user-images.githubusercontent.com/42857270/57281672-4cd96e00-7060-11e9-8caf-d64e083d0198.png)

**Comment by zsmjhtn** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/18029210/57293408-43e7ab80-70f7-11e9-9e35-9eb4f4d522b6.png">
BTW, 不好用，两端展示不一致。都是自己给2张图片来回切换

**Comment by pidogc** [comment]
兩端展示不一致的問題，我覺得還是挺嚴重的，很多地方都存在這個問題

**Comment by YorkShen** [comment]
As the `switch` is deprecated, so there is no document for it. Thanks
