### ISSUE TITLE
iOS:TypeError:undefinedisnotanobject(evaluating't.status')native-bundle-main.js

### ISSUE THREAD

**Issue by travelto** [apache/incubator-weex#2403]
## Environment

error info:
errorCode=-9400,functionName=,exception=[WX_KEY_EXCEPTION_WXBRIDGE][undefined:5:9530]TypeError:undefinedisnotanobject(evaluating't.status')native-bundle-main.js:3:30993forEach@[nativecode]p@native-bundle-main.js:3:30892native-bundle-main.js:8:26372,userInfo=jsMainBundleStringContentLength=1050994,jsMainBundleStringContentMd5=de550dac73cddb2c387406d69a0a60b6,,sdkVersion=0.17.0,jsfmVersion=0.22.7"}

**Comment by YorkShen** [comment]
Check your `js` file first, the stacktrack is so clear that there is something wrong with `t.status`.
