### ISSUE TITLE
android error

### ISSUE THREAD

**Issue by yejunrong** [apache/incubator-weex#2406]
多次切换复杂界面后会出现如下错误：

reportServerCrash instanceId:17 crashFile: /crash_dump.log
getCrashFilePath:/data/user/0/com.xxx.xxx/app_crash
[WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
app AvailMemory ---->>>1266
Start JS Framework 0.29.0, Build at 2018-10-02 14:30. (Vue: 2.5.16-weex.5, Rax: 0.4.20)
Start windmill weex-vue-plugin (0.3.2) framework. Build at 2018-09-18 13:06__LOG
ComponentModulesReadyTime 165034

目测看好像内存撑爆。。。

**Comment by zsmjhtn** [comment]
帮你看了下，应该不是内存问题，是 main.js  初始化问题。具体问题要自己找找
<img width="917" alt="image" src="https://user-images.githubusercontent.com/18029210/57429390-8c6da900-725e-11e9-9716-d6839512f089.png">

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: After switching the complex interface multiple times, the following error will occur: reportServerCrash instanceId: 17 crashFile: /crash_dump.log getCrashFilePath:/data/user/0/com.xxx.xxx/app_crash [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized. app AvailMemory - --->>>1266 Start JS Framework 0.29.0, Build at 2018-10-02 14:30. (Vue: 2.5.16-weex.5, Rax: 0.4.20) Start windmill weex-vue-plugin ( 0.3.2) framework. Build at 2018-09-18 13:06__LOG ComponentModulesReadyTime 165034 Visually look like memory explosion. . .

Please follow the issue template and provide your demo as I really can't help you with such little information.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
