### ISSUE TITLE
weexsdk线程警告

### ISSUE THREAD

**Issue by Choulan** [apache/incubator-weex#2414]
Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarFrame]
PID: 2844, TID: 2874840, Thread name: com.taobao.weex.bridge, Queue name: com.apple.root.default-qos.overcommit, QoS: 21
Backtrace:
4   WXDemo                              0x0000000102c40400 __23+[WXCoreBridge install]_block_invoke + 656
5   libdispatch.dylib                   0x0000000104129220 _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000104129f34 dispatch_once_f + 120
7   WXDemo                              0x0000000102c40144 +[WXCoreBridge install] + 92
8   WXDemo                              0x0000000102bc20d8 -[WXBridgeContext registerGlobalFunctions] + 192
9   WXDemo                              0x0000000102bc1edc -[WXBridgeContext jsBridge] + 944
10  WXDemo                              0x0000000102bcbd14 -[WXBridgeContext executeJsFramework:] + 636
11  WXDemo                              0x0000000102bd4504 __38-[WXBridgeManager executeJsFramework:]_block_invoke + 112
12  WXDemo                              0x0000000102bd28fc +[WXBridgeManager _performBlockOnBridgeThread:] + 180
13  Foundation                          0x00000001831c20ec <redacted> + 340
14  CoreFoundation                      0x000000018271f404 <redacted> + 24
15  CoreFoundation                      0x000000018271ec2c <redacted> + 276
16  CoreFoundation                      0x000000018271c79c <redacted> + 1204
17  CoreFoundation                      0x000000018263cda8 CFRunLoopRunSpecific + 552
18  Foundation                          0x00000001830b1674 <redacted> + 304
19  WXDemo                              0x0000000102bd244c -[WXBridgeManager _runLoopThread] + 344
20  Foundation                          0x00000001831c1efc <redacted> + 1040
21  libsystem_pthread.dylib             0x000000018239d220 <redacted> + 272
22  libsystem_pthread.dylib             0x000000018239d110 <redacted> + 0
23  libsystem_pthread.dylib             0x000000018239bb10 thread_start + 4
2019-05-09 09:00:26.757967+0800 WXDemo[2844:2874840] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarFrame]
PID: 2844, TID: 2874840, Thread name: com.taobao.weex.bridge, Queue name: com.apple.root.default-qos.overcommit, QoS: 21
Backtrace:
4   WXDemo                              0x0000000102c40400 __23+[WXCoreBridge install]_block_invoke + 656
5   libdispatch.dylib                   0x0000000104129220 _dispatch_client_callout + 16
6   libdispatch.dylib                   0x0000000104129f34 dispatch_once_f + 120
7   WXDemo                              0x0000000102c40144 +[WXCoreBridge install] + 92
8   WXDemo                              0x0000000102bc20d8 -[WXBridgeContext registerGlobalFunctions] + 192
9   WXDemo                              0x0000000102bc1edc -[WXBridgeContext jsBridge] + 944
10  WXDemo                              0x0000000102bcbd14 -[WXBridgeContext executeJsFramework:] + 636
11  WXDemo                              0x0000000102bd4504 __38-[WXBridgeManager executeJsFramework:]_block_invoke + 112
12  WXDemo                              0x0000000102bd28fc +[WXBridgeManager _performBlockOnBridgeThread:] + 180
13  Foundation                          0x00000001831c20ec <redacted> + 340
14  CoreFoundation                      0x000000018271f404 <redacted> + 24
15  CoreFoundation                      0x000000018271ec2c <redacted> + 276
16  CoreFoundation                      0x000000018271c79c <redacted> + 1204
17  CoreFoundation                      0x000000018263cda8 CFRunLoopRunSpecific + 552
18  Foundation                          0x00000001830b1674 <redacted> + 304
19  WXDemo                              0x0000000102bd244c -[WXBridgeManager _runLoopThread] + 344
20  Foundation                          0x00000001831c1efc <redacted> + 1040
21  libsystem_pthread.dylib             0x000000018239d220 <redacted> + 272
22  libsystem_pthread.dylib             0x000000018239d110 <redacted> + 0
23  libsystem_pthread.dylib             0x000000018239bb10 thread_start + 4

初始化weexsdk时，按照官方文档流程，在0.20.1版本中会出现线程警告，而0.18.0版本中则不会，这是什么原因？

**Comment by YorkShen** [comment]
Thanks for your reporting, we will look into that.

**Comment by jianhan-he** [comment]
你好，请问这个告警在WeexDemo这个工程里可以复现出来吗

**Comment by jianhan-he** [comment]
Thanks for your reporting， this issue has fixed, you can try on the latest code.
