### ISSUE TITLE
waterfall组件的 left-gap 和 right-gap 属性在 Web 端无效

### ISSUE THREAD

**Issue by canvasT** [apache/incubator-weex#2428]
## Describe the bug

waterfall组件的left-gap和right-gap在Web端无效，但是在iOS客户端的playground下有效

## To Reproduce

在官方[demo](http://dotwe.org/vue/b6102e44d1ba03476092be680f9bf779)里，增加
:left-gap="40"
:right-gap="40"
没有效果

## Environment

* Device: Chrome 74.0.3729.131
* OS: maxOS mojave
* Version 10.14.4
* Build from source no

## Expected behavior

按照官方描述
> Weex enables developers to use modern web development skills to build Android, iOS, and Web apps with a single codebase. 

Web端的left-gap和right-gap也应该生效

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: https://ehr.alibaba-inc.com/campus/resumeDetail.htm?resumeId=11521993&applicationId=2374138

Thanks for your reporting, we will look into that.

**Comment by YorkShen** [comment]
Just got response from our developer, `waterfall` doesn't support web, it only supports iOS and Android. I will make sure the document is clear about that.
