### ISSUE TITLE
[Android] NPE in WXUtils and emoji bug, weex version is 0.20.0.2

### ISSUE THREAD

**Issue by zjutkz** [apache/incubator-weex#2429]
Method `getInter` in `WeexUtils` has a NPE in weex sdk version 0.20.0.2
`if (!ret.equals(df)) {
        sCache.put(key, ret);
}`
I saw it fixed in master branch, so just release a version a.s.a.p,please!

Another problem is emoji cannot be shown in Android 8.0+ platforms,please check it too.

**Comment by YorkShen** [comment]
1. Release of Weex need to be voted with at least three `agree` reposone. If you really need it, there are two options:
    * Help to propose a release for Weex. I can guide you the procedure and corresponding issue.
    * Wait for the next release, which may happen in one month later (*Personal opinion, as the we need to vote for a release like any other Apache Project)
2. Please follow the issue template and provide your demo.
