### ISSUE TITLE
文档中的实例都打不开了

### ISSUE THREAD

**Issue by lavender1026** [apache/incubator-weex#2435]
http://dotwe.org/vue/6e3c7fb21976e80c2959f330ddd1b26a?spm=a2c7j.-zh-docs-components-scroller.0.0.449020b6d9BIzq
文档中的实例都打不开了

**Comment by YorkShen** [comment]
The server of dotwe.org crashed, we are looking into that. 

Meanwhile, you can use `editor.weex.io` with your path appended. For example, you can visit http://editor.weex.io/vue/6e3c7fb21976e80c2959f330ddd1b26a to see the page you mentioned.
