### ISSUE TITLE
官网文档示例都无法打开了

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#2437]
似乎dotwe.org/下的各种示例都无法打开了，比如
https://weex.apache.org/zh/docs/events/common-events.html#stoppropagation中的示例
http://dotwe.org/vue/48ddb2f7339d1fb116135900a2dbc8e5?spm=a2c7j.-zh-docs-events-common-events.0.0.2a9220b6a48Esa

**Comment by YorkShen** [comment]
The problem is solved now, thanks for your reporting.
