### ISSUE TITLE
[iOS] In some case WX_EXPORT_METHOD_SYNC not work

### ISSUE THREAD

**Issue by darkThanBlack** [apache/incubator-weex#2445]
## Describe the bug

Some day other team web developer told me a custom weex plugin can't work.
 I notice the method ``get:``works, but method ``get:callback:`` do not work, when web js call this method, weex SDK print log like this:
![11721557915823_ pic](https://user-images.githubusercontent.com/8111265/57773003-91909380-7749-11e9-8a28-4c055b5d4865.jpg)
That means weex not find the method in this plugin. How can this be? 
So I review the code and found the plugin code as follows:

```
@interface WXLocalCacheModel : NSObject<WXModuleProtocol>
- (void)get:(id)sender;
- (void)get:(id)sender callback:(WXModuleKeepAliveCallback)callback;
@end

@implementation WXLocalCacheModel
WX_EXPORT_METHOD_SYNC(@selector(save:))
WX_EXPORT_METHOD_SYNC(@selector(get:))
WX_EXPORT_METHOD_SYNC(@selector(deleteCache:))
WX_EXPORT_METHOD_SYNC(@selector(save:callback:))
WX_EXPORT_METHOD_SYNC(@selector(get:callback:))
WX_EXPORT_METHOD_SYNC(@selector(deleteCache:callback:))
@end
```

## To Reproduce
All things seem perfect. For a brief explanation, if I try code like follows, method ``get:`` and ``get:callback:`` should be called correctly, just add Enter in each line:
```
@implementation WXLocalCacheModel

WX_EXPORT_METHOD_SYNC(@selector(save:))

WX_EXPORT_METHOD_SYNC(@selector(get:))

WX_EXPORT_METHOD_SYNC(@selector(deleteCache:))

WX_EXPORT_METHOD_SYNC(@selector(save:callback:))

WX_EXPORT_METHOD_SYNC(@selector(get:callback:))

WX_EXPORT_METHOD_SYNC(@selector(deleteCache:callback:))

@end

```
Unbelievable,right?

## Some Explanation
How can I find it? I try to review WX_EXPORT_METHOD_SYNC macro definiton, and this is what I see:
```
#ifndef __WX_DEFINE_H__
#define __WX_DEFINE_H__

#define WX_SDK_VERSION @"0.19.0"

#define WX_CONCAT(a, b)   a ## b

#define WX_CONCAT_WRAPPER(a, b)    WX_CONCAT(a, b)

#define WX_EXPORT_METHOD_INTERNAL(method, token) \
+ (NSString *)WX_CONCAT_WRAPPER(token, __LINE__) { \
    return NSStringFromSelector(method); \
}

#define WX_EXPORT_METHOD_SYNC(method) WX_EXPORT_METHOD_INTERNAL(method,wx_export_method_sync_)

```
The ``__LINE__``macro means code line number, this grammar sugar add ``wx_export_method_sync_``, ``__LINE__`` to method behind, weex SDK will try to find method in plugin depend on final method name. 
BUT IS THIS A GOOD DESIGN？
To bind particular method implementation to source code line number? This might lead C macro expansion problem. Holding such doubts, I try to change source code line number in ``WXLocalCacheModel`` such as add Enter, fortunately, it works.
I try to use ``PRINT_MACRO`` print real code after macro expansion to got more information but faild cause ``#`` in macro, I am not good at English, and not good at C language, may be your guys can fix it.
If you need all source code in ``WXLocalCacheModel``, contact me.

## environment
iOS12, Xcode 10.2, weex SDK pod version 0.19.0

===

## 问题描述

前端有一天跑过来跟我讲有一个不常用的插件里的方法不管用了。我看了下代码，问题是``get:``方法会正常调用，``get:callback:``方法没有被调用，同时 weex SDK 会打印类似于下图的信息：
![11721557915823_ pic](https://user-images.githubusercontent.com/8111265/57773003-91909380-7749-11e9-8a28-4c055b5d4865.jpg)
这信息的意思是 weex 没有找到该插件内对应的方法。(脏话)
这个插件里的代码大概是这样子的：

```
@interface WXLocalCacheModel : NSObject<WXModuleProtocol>
- (void)get:(id)sender;
- (void)get:(id)sender callback:(WXModuleKeepAliveCallback)callback;
@end

@implementation WXLocalCacheModel
WX_EXPORT_METHOD_SYNC(@selector(save:))
WX_EXPORT_METHOD_SYNC(@selector(get:))
WX_EXPORT_METHOD_SYNC(@selector(deleteCache:))
WX_EXPORT_METHOD_SYNC(@selector(save:callback:))
WX_EXPORT_METHOD_SYNC(@selector(get:callback:))
WX_EXPORT_METHOD_SYNC(@selector(deleteCache:callback:))
@end
```

## 复现
代码看起来中规中矩，毫无问题。为了简略说明，我先贴上能够正常使用的代码：
```
@implementation WXLocalCacheModel

WX_EXPORT_METHOD_SYNC(@selector(save:))

WX_EXPORT_METHOD_SYNC(@selector(get:))

WX_EXPORT_METHOD_SYNC(@selector(deleteCache:))

WX_EXPORT_METHOD_SYNC(@selector(save:callback:))

WX_EXPORT_METHOD_SYNC(@selector(get:callback:))

WX_EXPORT_METHOD_SYNC(@selector(deleteCache:callback:))

@end

```
加个回车就好了？真的假的？千真万确（脏话）

## 可能的解释
我先说一下我的思路和排查过程，我先看了``WXDefine.h``里面的宏定义，相关代码如下：
```
#ifndef __WX_DEFINE_H__
#define __WX_DEFINE_H__

#define WX_SDK_VERSION @"0.19.0"

#define WX_CONCAT(a, b)   a ## b

#define WX_CONCAT_WRAPPER(a, b)    WX_CONCAT(a, b)

#define WX_EXPORT_METHOD_INTERNAL(method, token) \
+ (NSString *)WX_CONCAT_WRAPPER(token, __LINE__) { \
    return NSStringFromSelector(method); \
}

#define WX_EXPORT_METHOD_SYNC(method) WX_EXPORT_METHOD_INTERNAL(method,wx_export_method_sync_)

```
因为我不会 C 语言，所以查了下资料，发现``__LINE__``这个宏的意思是当前代码的行号，所以
``WX_EXPORT_METHOD_SYNC`` 这个语法糖的意思是将一个固定的字符串``wx_export_method_sync_``与当前这句代码的行号一次拼接到传入的选择子后面，作为这个选择子对应的真正的方法名，在 web js 发起调用的时候，weex SDK 会根据具体参数解析出组件名，方法名，行号进行查找。
理解了这个宏以后，我的第一反应是为什么要将代码的行号与具体的方法实现绑定起来？在源代码里面加入不起作用的代码，例如空方法、注释、回车等会影响到编译后的源码实现，我感觉这是一件很奇怪的事。我知道 C 语言里宏展开很容易出现隐性问题，既然变动行号会影响方法实现，那么我先加个回车试试好了。幸运的是，试了一次就成功了。
我本打算设法打印出把这些宏展开后的对应代码来进一步验证我的猜想，但是因为我不会 C 语言，不知道怎么打印宏展开后的代码，所以。。。
如果你需要这个源文件的全部代码，联系我就好，当然我不保证在你那里能复现，如果还有不信的，我空了录小视频给你看（笑）。

## 环境
iOS12, Xcode 10.2, weex SDK pod version 0.19.0

===

**Comment by YorkShen** [comment]
Thanks for your reporting, we will look into that

**Comment by wqyfavor** [comment]
加不加回车并不影响。这里WX_EXPORT_METHOD_SYNC宏实际是给OC类添加一个特定前缀的方法，至于 __LINE只是为了这些方法selector名字不一致（但是有相同前缀）。这样在初始化weexsdk时，利用oc runtime拿到OC类的所有selectors，然后过滤出带这个前缀的方法们，依次调用这些方法，拿到要注册给前缀的真正接口名称。所以你加回车，也只是这些方法名的行号变了一下，并不影响weexSdk拿到真正要的方法名。只要WX_EXPORT_METHOD_SYNC(xxx)这些代码不在 **同一行** 就可以。

到于方法丢失的问题，是weexsdk的多线程问题。参考这个PR进行修改，或升级到最新版本即可。https://github.com/apache/incubator-weex/pull/2394
