### ISSUE TITLE
weex vue-router跳转闪动，页面加载内容偶尔缺失

### ISSUE THREAD

**Issue by sawadazina** [apache/incubator-weex#2448]
weex vue-router跳转闪动，页面加载内容偶尔缺失

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Weex vue-router jumps flashing, page loading content is occasionally missing

Please follow the issue template and provide your demo as I really can't help you with such little information.

I will just close the issue, feel free to reopen with your demo and the latest of weex.

**Comment by sawadazina** [comment]
Hello, here is the question demo address.：https://github.com/sawadazina/weex-demo
The problem demo video is demo. MP4 in the address.

**Comment by huadon9** [comment]
> Hello, here is the question demo address.：https://github.com/sawadazina/weex-demo
> The problem demo video is demo. MP4 in the address.

Hi, sawadazina
  do you solved this bug, i have the same bug in android mobile

**Comment by sawadazina** [comment]
It is recommended that you use navigator to switch between the Android side. Since a single js file represents an active activity window on the Android side, the vue-router mode switch is to refresh the current window, so there will be flashing, and the page missing problem is not there. Solve, hope to help you a little
