### ISSUE TITLE
[Android][iOS][Dev-tool] Unexpected behavior when xx where weex version is 0.aa.bb.cc

### ISSUE THREAD

**Issue by gmgw0909** [apache/incubator-weex#2450]
degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount
 需要
//        ndk {
//            abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a'
//        }
删除后面 'armeabi-v7a', 'arm64-v8a' 但是项目中其他sdk需要 请问如何解决（版本 0.20.0.2@aar）

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount Requires // ndk { // abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a' // } Remove the following 'armeabi-v7a', 'arm64-v8a' But other sdk in the project need to ask how to solve (version 0.20.0.2@aar)

Weex will support armeabi-v7a in the early of June

#2389
