### ISSUE TITLE
[Dev-tool] Unexpected behavior when create where weex version is 2.0.0-beta

### ISSUE THREAD

**Issue by misakamaiyako** [apache/incubator-weex#2458]
## Describe the bug

i can't use weex-toolkit to create or build a project
## To Reproduce

 for basically,use weex create course in cmd or bash in win10-ubunto
## Environment
OS: win10,win10-ubunto

## Expected behavior

able to create or build
## Screenshots

![{290FA5A7-1476-4A82-899E-DCFAC88BA0CD}_20190519125312](https://user-images.githubusercontent.com/21253592/57977935-1bd04480-7a35-11e9-84a8-f4f6f4691a98.jpg)

**Comment by zsmjhtn** [comment]
看上去是循环引用

**Comment by YorkShen** [comment]
As it is said in [doc](https://weex.apache.org/tools/toolkit.html),
> Weex Toolkit is a third party plugin, and is not developed nor maintained by Apache Weex.
you should ask this question weex_tookit repo, not here.
