### ISSUE TITLE
[ios] weex run ios  at ChildProcess.exithandler (child_process.js:294:12)

### ISSUE THREAD

**Issue by JackgorHJ** [apache/incubator-weex#2465]
when I use 'weex run ios' 

it point out like this

"CpResource /Users/levinli/Desktop/IVC/CWOL-APP/platforms/ios/bundlejs /Users/levinli/Desktop/IVC/CWOL-APP/platforms/ios/build/Build/Products/Debug-iphonesimulator/WeexDemo.app/bundlejs (in target: WeexDemo)
    cd /Users/levinli/Desktop/IVC/CWOL-APP/platforms/ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/levinli/Desktop/IVC/CWOL-APP/platforms/ios/bundlejs /Users/levinli/Desktop/IVC/CWOL-APP/platforms/ios/build/Build/Products/Debug-iphonesimulator/WeexDemo.appError: Command failed: xcodebuild  -scheme WeexDemo -configuration Debug -sdk iphonesimulator -derivedDataPath build -workspace WeexDemo.xcworkspace
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/levinli/Desktop/IVC/CWOL-APP/platforms/ios/build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Script-1E390F7C694E73E70F0885A9.sh
(1 failure)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
"

So i cant continue run ios,Plz help me ,thanks

**Comment by YorkShen** [comment]
As it is said in [doc](https://weex.apache.org/tools/toolkit.html),
> Weex Toolkit is a third party plugin, and is not developed nor maintained by Apache Weex.

you should ask this question [weex_tookit](https://github.com/weexteam/weex-toolkit) repo, not here.
