### ISSUE TITLE
weex在安卓下的报错

### ISSUE THREAD

**Issue by jolun123** [apache/incubator-weex#2468]

**Comment by jolun123** [comment]
reportJSException >>>> exception function:createInstance, exception:Exception: TypeError: undefined is not an object (evaluating 'modules[moduleId].call')
22:14:36.258 10:12.120 16491 16512 E console : __webpack_require__@(global function):4404:30
22:14:36.275 10:12.120 16491 16512 E console : componentsMSearchMSearchCreateComponent@(global function):51559:118
22:14:36.288 10:12.120 16491 16512 E console : __webpack_require__@(global function):4404:35
22:14:36.307 10:12.120 16491 16512 E console : checkDeferredModules@(global function):4361:45
22:14:36.327 10:12.120 16491 16512 E console : (global function):51555:61
22:14:36.347 10:12.120 16491 16512 E console : require@(global function):8:671861
22:14:36.367 10:12.120 16491 16512 E console : (global function):51564:8
22:14:36.387 10:12.120 16491 16512 E console : anonymous@(global function):76814:7
22:14:36.407 10:12.120 16491 16512 E console : (weex framework):1:41074
22:14:36.427 10:12.120 16491 16512 E console : createInstance@(weex framework):1:41085
22:14:36.447 10:12.120 16491 16512 E console : (weex framework):1:177648
22:14:36.467 10:12.120 16491 16512 E console :
22:14:36.487 10:12.120 16491 16512 E console :  getTemplateInfo== template md5 null ,httpHeader:{}

**Comment by YorkShen** [comment]
Check your JS code.

The log is pretty clear, there is something undefined.

> undefined is not an object (evaluating 'modules[moduleId].call')
