### ISSUE TITLE
there is a certain probability that events cannot be triggered automatically on android 9

### ISSUE THREAD

**Issue by imfenghuang** [apache/incubator-weex#2470]
There is a certain probability that events can not be triggered automatically on android 9.

I use `scroller` component. On android 7, the appear event can be triggered automatically when the page is opened and no manual scoll page.

However,  on android 9, sometimes, the appear event can not be triggered automatically, even if use `scrollToElement` to scroll `scroller`. Only use finger to scroll the `scroller`, the appear event is triggered.

weex sdk 0.18

Has anyone encountered the same problem?

**Comment by YorkShen** [comment]
1. First upgrade weex to the latest version (0.24.0)
2. Provide a [demo](http://dotwe.org/vue).

I will close your issue and you are welcomed to reopen it when you have a demo.
