### ISSUE TITLE
Android在fragment中如何使用weex？

### ISSUE THREAD

**Issue by cheng1128feng** [apache/incubator-weex#2471]
文档和Demo中只有weex在application中的初始化，以及在Activity中的加在，现在业务需要在一个fragment中使用weex,如何setView？

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: How to use weex in Android in fragment

You should probably Google "Android Fragment" first.
