### ISSUE TITLE
@appear 事件不触发

### ISSUE THREAD

**Issue by LionBuer** [apache/incubator-weex#2472]
http://dotwe.org/vue/dcac1550b4467965e0251ef7ca1c4222

在Weex Playground中会触发，使用Weex Playground APP 不能触发

**Comment by jianhan-he** [comment]
> http://dotwe.org/vue/dcac1550b4467965e0251ef7ca1c4222
> 
> 在Weex Playground中会触发，使用Weex Playground APP 不能触发

这个是那个平台的，iOS还是Android出现的问题？

**Comment by LionBuer** [comment]
> > http://dotwe.org/vue/dcac1550b4467965e0251ef7ca1c4222
> > 在Weex Playground中会触发，使用Weex Playground APP 不能触发
> 
> 这个是那个平台的，iOS还是Android出现的问题？

iOS平台

**Comment by jianhan-he** [comment]
你好，weex支持的appear事件是在可滚动的组件（scroller）里才会被触发，可以参考文档https://weex.apache.org/zh/docs/events/common-events.html#appear。你的例子里没有scroller组件，所以无法触发。
