### ISSUE TITLE
Android手机微信公众号（QQ浏览器内核）无法触发refresh组件的onrefresh方法

### ISSUE THREAD

**Issue by androidzhangyanhui** [apache/incubator-weex#2473]
Android手机微信公众号（QQ浏览器内核）无法触发refresh组件的onrefresh方法

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Android mobile phone WeChat public number (QQ browser kernel) can not trigger the onrefresh method of refresh component

We have no plan to support browsers other than chrome, safari and firefox. Use it at your own risk.

I will just close the issue, feel free to reopen with your demo and the latest of weex.
