### ISSUE TITLE
Weex Release 0.25 issues

### ISSUE THREAD

**Issue by YorkShen** [apache/incubator-weex#2482]
The following issue need resolved before 0.25 release.
- [x] Solve License issue. (Solve license problem for `weex_core/Source/include/JavaScriptCore` and `weex_core/Source/include/wtf`)
- [x] [Document for the release procedure](https://weex.apache.org/community/release-procedure.html).
- [x] A private page/SVN to host private key for the following:
    * NPM
    * Bintray
    * Cocoapods

**Comment by janpio** [comment]
>     * A private page/SVN to host private key for the following:

Infra can provide something equivalent to `https://svn.apache.org/repos/private/pmc/cordova/` (if this doesn't exist already)

**Comment by YorkShen** [comment]
Thanks, I just submitted a JIRA ticket to INFRA.
