### ISSUE TITLE
WXDevtool 0.24.0 crash

### ISSUE THREAD

**Issue by Ramonfan** [apache/incubator-weex#2496]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/8336766/58601845-39b36a00-82bd-11e9-984d-585671ad3d47.png">
JS-DEBUG 一打开---iOS 端就会出现闪退如下图：
<img width="909" alt="image" src="https://user-images.githubusercontent.com/8336766/58602001-b8100c00-82bd-11e9-8d70-a24afa69e605.png">

**Comment by YorkShen** [comment]
Again, this is about dev-tool and you should ask question in repo of [dev-tool](https://github.com/weexteam/weex-devtool).

As for your problem, just clean your project, everything should go well.
