### ISSUE TITLE
[iOS]Could not find remote branch 0.17.0 to clone

### ISSUE THREAD

**Issue by MichaelWangC** [apache/incubator-weex#2502]
![image](https://user-images.githubusercontent.com/8220697/58690102-5e8e0700-83bb-11e9-9f20-a1fada6a7656.png)

**Comment by jianhan-he** [comment]
We release the versions: 0.24.0 0.20.0 0.19.0 0.12.0. Other release version we have already removed.

The document: https://weex.apache.org/download/download.html
