### ISSUE TITLE
[iOS][Dev-tool]vue is not defined

### ISSUE THREAD

**Issue by HaloZhou** [apache/incubator-weex#2506]
![image](https://user-images.githubusercontent.com/25050405/58773467-bd3bc680-85ef-11e9-9603-56a251f02dc0.png)

用'weex create ***'创建的工程，通过weex studio'开始'按钮运行，报错'vue is not defined'

假设我加上'import Vue from 'vue''，不报错了，但是在手机端加载，则会出现找不到'$t'

而用以前自己手动搭建的项目并没有此问题，难道是你们官方的脚手架出现问题了？？？（难道是我操作的问题？但是我这都是正常操作）

**Comment by HaloZhou** [comment]
我觉得和 #2275 应该是一个问题

**Comment by erha19** [comment]
@HaloZhou `weex studio IDE`只支持IDE自己创建的项目，两个工具项目存在配置上的差异，不能一起使用。

**Comment by HaloZhou** [comment]
> @HaloZhou `weex studio IDE`只支持IDE自己创建的项目，两个工具项目存在配置上的差异，不能一起使用。

那假设我按照现在这种方式，该怎么做？求教

**Comment by erha19** [comment]
@HaloZhou 
可以尝试使用IDE创建项目 -> 替换`src`内容为你原来项目`src`，不行的话就只能靠你自己看代码改了

**Comment by YorkShen** [comment]
I seems the issue is solved, thanks all.

**Comment by HaloZhou** [comment]
@YorkShen 还没有解决
