### ISSUE TITLE
[Android]@click事件，0.20.0的weex sdk上，频繁出现点击之后要等个好几秒才响应

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#2508]
@click事件，0.24的weex sdk上，频繁出现点击之后要等个好几秒才响应

环境：
`
compile 'com.taobao.android:weex_inspector:0.24.2.4'
    compile 'com.taobao.android.weex_inspection:urlconnection_interceptor:1.0.0'
    compile 'com.taobao.android.weex_inspection:protocol:1.1.4.1'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-ws:2.3.0'
    compile 'com.squareup.okio:okio:1.0.1'

`
![image](https://user-images.githubusercontent.com/36951996/58786023-4e736300-8619-11e9-922f-df7a2030dce2.png)

**Comment by fanlvwen** [comment]
测试机型有华为 oppo vivo，均不同概率出现了点击延迟

**Comment by BatterMan-Li** [comment]
请问这个问题解决了吗？如何解决的？
我发现打开应用程序放至息屏一段时间然后回到应用后要等一段时间才能响应点击时间
