### ISSUE TITLE
globalEvent 监听无返回

### ISSUE THREAD

**Issue by aidy-automan** [apache/incubator-weex#2513]
js 
   created(){
        weex.requireModule('globalEvent').addEventListener('barcode_scanner', function(e) {
            this.userNumber = "11111111"
        });
    },

android
    WXSDKInstance mWXSDKInstance = new WXSDKInstance(WXPageActivity.this);
    mWXSDKInstance.fireGlobalEventCallback("barcode_scanner", param);

**Comment by YorkShen** [comment]
1. Please follow the issue template and provide your demo in [dot.we](http://dotwe.org/vue)
2. You can reopen the issue after completed your demo as **I only response to issues that are open**.

**Comment by aidy-automan** [comment]
问题已解决，发现activity 不一样只有把context传值传过去，才行
