### ISSUE TITLE
[iOS][Dev-tool]   White screen flashes back when weex debug is used

### ISSUE THREAD

**Issue by githbq** [apache/incubator-weex#2518]
When I use weex debug to debug the official weex playground app on ios devices, the screen will flash back to ask the authorities to solve the problem

**Comment by YorkShen** [comment]
As it's said clearly in the document, you should ask question in [their repo](https://github.com/weexteam/CLI-for-Apache-Weex), not here.
> weex-toolkit is a third party plugin, and is not developed nor maintained by Apache Weex.
