### ISSUE TITLE
[Android] load page failed in 5.1.1&5.1, where weex version is 0.24.0

### ISSUE THREAD

**Issue by zjutkz** [apache/incubator-weex#2519]
## Describe the bug
If we have an emoji in code,it cannot be loaded properly in 5.1.1&5.1.

## Code
![image](https://user-images.githubusercontent.com/9446934/59008245-83232c80-885c-11e9-8d6c-2733c1c7a544.png)

## Environment
* Device: vivo Xplay5A
* OS: Android 5.1.1

## Stacktrace
`degradeToH5|createInstance fail|wx_create_instance_error[WXBridgeManager] `

## Addition
Exception when executing `WXBridgeManger.invokeCreateInstanceContext`

**Comment by YorkShen** [comment]
Please follow the issue template and provide the demo in [dot.we](http://dotwe.org/vue), a screenshot is not enough.

Feel free to reopen the issue as **I only response to issues that are open**.

**Comment by zjutkz** [comment]
http://dotwe.org/vue/7568b4c5615864967bfc5e22b6808b16
@YorkShen It is the demo ref. It run failed both in my App and Weex Playground
