### ISSUE TITLE
【weex version  0.24.0】 css border-bottom-xxx or border-top-xxx类似写法的样式在iOS不支持，安卓可以

### ISSUE THREAD

**Issue by Ramonfan** [apache/incubator-weex#2527]
【weex version  0.24.0】 css border-bottom-xxx or border-top-xxx类似写法的样式在iOS不支持，安卓可以

**Comment by YorkShen** [comment]
1. Please follow the issue template and provide your demo in [dot.we](http://dotwe.org/vue)
2. You can reopen the issue after completed your demo as **I only response to issues that are open**.
