### ISSUE TITLE
「Weex」input和textarea的disabled属性问题

### ISSUE THREAD

**Issue by HaloZhou** [apache/incubator-weex#2528]
动态控制 input 或者 textarea 的disabled属性的时候，会出现v-model绑定的数据在控件上面突然消失.
工具：weexStudio
版本：3.1.0-emas (3.1.0-emas) 
操作系统：MacOS
示例代码：
```
<template>
    <div>
        <input type="text" v-model="content" :disabled='dis'>
        <input type="button" value="按钮" @click="fn()">
    </div>
</template>
<script>
export default {
    data(){
        return{
            content:'1111',
            dis:true
        }
    },
  methods:{
    fn(){
        this.dis = !this.dis,
        this.content = '2222'
    }
  }
}
</script>

```

**Comment by YorkShen** [comment]
1. Please follow the issue template and provide your demo in [dot.we](http://dotwe.org/vue)
1. Please provide the platform information(Android or iOS) as well.
1. You can reopen the issue after completed your demo as **I only response to issues that are open**.
