### ISSUE TITLE
[Android] Weex page failed to render in Android Q

### ISSUE THREAD

**Issue by wuhh2016** [apache/incubator-weex#2539]
Weex page failed to render in Android Q.
No method of IWXRenderListener is invoked.

**Comment by YorkShen** [comment]
As Android Q is [done](https://github.com/apache/incubator-weex/pull/2336),  and will be published in next release.

**Comment by wuhh2016** [comment]
with https://github.com/apache/incubator-weex/commit/ed9264bb8c2e9c6b32b26187b6a63f71350219e0
this change does not fix the error.

WeexCore: server died
3221228600
