### ISSUE TITLE
[Weex] Is there a bounces property in WebView

### ISSUE THREAD

**Issue by ken-iheha** [apache/incubator-weex#2541]
As mentioned. We'd like to disable the bounce effect in WebView.

**Comment by YorkShen** [comment]
As mentioned in [document](https://weex.apache.org/docs/components/web.html#summary)

> web is only used as a degraded unconventional scenario and is not recommended for a large number of normal Weex pages.

But if you have a PR to fix the problem, I will be happy to review and merge it.
