### ISSUE TITLE
the @scroll event of <scroller> in android

### ISSUE THREAD

**Issue by nikojxie** [apache/incubator-weex#2546]
the @scroll event of <scroller> in android
it triggered only once when  it's offset in android
but it's effective in ios
what will cause this situation？ 

Thanks for your help🙏

**Comment by YorkShen** [comment]
Could you please provide a [demo](http://dotwe.org/vue)

I will just close the issue, feel free to reopen it when you are ready.

**I only response to issues that are open**.
