### ISSUE TITLE
[Android] mounted生命周期钩子函数并不与页面渲染完毕的时机挂钩. weex 0.20.0.2

### ISSUE THREAD

**Issue by chaopei1989** [apache/incubator-weex#2547]
## Environment
Android 4.4
1280*800 平板设备

## Expected behavior
在mounted钩子函数里弹toast, 观察页面元素的展现与toast的时机, toast应该在页面元素全部展现完毕后出现. 

## Current behavior
实际表现为, 页面元素还未完全渲染出现, toast先弹了.

**Comment by YorkShen** [comment]
1. Please follow the issue template and provide your demo in [dot.we](http://dotwe.org/vue)
1. You can reopen the issue after completed your demo as **I only response to issues that are open**.
