### ISSUE TITLE
 android 上  图片显示   属性transform   scale 和 rolate 异常 

### ISSUE THREAD

**Issue by zhaoqigang** [apache/incubator-weex#2553]
## Describe the bug

我播放菜单列表       我通过改变一个图片控件  的url 和  scale  和 rolate  当我播放几个菜单后  发现 scale 和 rolate  显示不对 ， 偶发的不是每个都错误，可能下次显示的时候又正确了。
## To Reproduce

这个是改变  修改属性  菜单的方法  

 if (this.menuData.ext_property && (this.menuData.ext_property.cashId === this.menuTypeId) && this.menuData.ext_property.defaultHeight) {

                    let top = this.format(this.menuData.ext_property.top, this.menuData.ext_property.defaultHeight);
                    let left = this.format(this.menuData.ext_property.left, this.menuData.ext_property.defaultHeight);

                    native.log("this.menuData.ext_property.scale==" + this.menuData.ext_property.scale);
                    this.menuStyle.top = top;
                    this.menuStyle.left = left;
                    this.menuStyle.transform = 'scale(' + this.menuData.ext_property.scale + ')  rotate(' + this.menuData.ext_property.rotateZ + 'deg)'
                }
## Environment

JIULIAN  UNT401H  盒子  
Android 4.4.2

## Expected behavior

希望  图片的旋转和缩放  都正常

**Comment by YorkShen** [comment]
Please update to the latest version of weex and provide a [demo](http://dotwe.org/vue), I really can't help you according to just one sentence . **Please reopen this issue when demo are ready as I only response to issues that are open.**
