### ISSUE TITLE
[iOS] Carthage update failed

### ISSUE THREAD

**Issue by KorolZhu** [apache/incubator-weex#2555]
i want use weex ios sdk in carthage, but when i run carthage update command, the WeexSdk-Dynamic compile failed.

you can clone my project to reproduce the error: https://github.com/KorolZhu/WeexSDKExample.git

![image](https://user-images.githubusercontent.com/1926639/59560415-4cab9580-9044-11e9-9424-c7e928550103.png)

**Comment by wqyfavor** [comment]
有一个文件没有添加到dynamic target里，已经在master分支上修复。
