### ISSUE TITLE
input 組件限制輸入長度實際獲取到的值多一位

### ISSUE THREAD

**Issue by pidogc** [apache/incubator-weex#2562]
![image](https://user-images.githubusercontent.com/42857270/59584117-139a1200-9092-11e9-815f-7e7fb54695d2.png)
![image](https://user-images.githubusercontent.com/42857270/59584142-23b1f180-9092-11e9-8335-51a3f9506bfc.png)

**Comment by jianhan-he** [comment]
谢谢你的反馈，该问题在最新代码上已经解决，你可以直接源码集成试试

**Comment by jianhan-he** [comment]
谢谢你的反馈，该问题在最新代码上已经解决，你可以直接源码集成试试
