### ISSUE TITLE
weex框架的插件市场

### ISSUE THREAD

**Issue by kuaifan** [apache/incubator-weex#2566]
eeui框架是目前唯一一个有插件市场的weex开源框架，欢迎交流https://eeui.app/markets/, github地址：https://github.com/kuaifan/eeui

**Comment by kuaifan** [comment]
![image](https://console.eeui.app/uploads/picture/1/201906/bda148149048397ae895bcbae733c39d_2160x4160-1.png)

**Comment by YorkShen** [comment]
感谢分享，这是一个有趣的想法。如果可能，我希望你能在[邮件列表](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)中分享这个想法，毕竟目前邮件列表是Apache的官方沟通渠道。

PS：*邮件列表中的沟通语言是英语*。

**Comment by kang558** [comment]
6666

**Comment by kuaifan** [comment]
![Image](https://console.eeui.app/uploads/picture/1/201906/5454c90cc1d0e18125951fae938e6188_2160x4160-1.png)
