### ISSUE TITLE
[Android]请添加arm64-v8a的支持，google play要求必须对64位的进行支持

### ISSUE THREAD

**Issue by ha6cc** [apache/incubator-weex#2569]

**Comment by YorkShen** [comment]
ARM64 is supported now.

https://github.com/apache/incubator-weex/pull/2561

**Comment by ha6cc** [comment]
在github的项目上只有libJavaScriptCore.so和libWTF.so有arm64-v8a的，另外四个libweexcore.so，libweexjsb.so，libweexjss.so，libweexjst.so文件好像没有arm64-v8a的，请问怎么才能得到这四个支持arm64的文件
