### ISSUE TITLE
[Android][iOS] 如何实现原生Gone的效果？

### ISSUE THREAD

**Issue by fsxiaoke** [apache/incubator-weex#2572]
sdk：0.24.0
使用visiablity=“gone”的话，并不能达到gone的效果，只是把view隐藏了，仍然在占位
请问如何让view消失并且不占位？

**Comment by YorkShen** [comment]
Please read the document of Weex/Vue, thanks.

[v-if](https://weex.apache.org/guide/use-vue-in-weex.html#supported-features) is what you are looking for.

**Comment by fsxiaoke** [comment]
> Please read the document of Weex/Vue, thanks.
> 
> [v-if](https://weex.apache.org/guide/use-vue-in-weex.html#supported-features) is what you are looking for.

v-if will recreate all the view,that is not what I expected
