### ISSUE TITLE
Can Weex's other operating system support be merged?

### ISSUE THREAD

**Issue by hanagm** [apache/incubator-weex#2573]
Hello,Guys

We are a Chinese operating system company, because most of our operators are front-end engineers, so we plan to support JavaScript development of applications.

Through our in-depth understanding of the current Weex architecture, we should end up running enough for our operations.

At present, we have a concern that if we expand our support for our operating system based on Weex, can we follow up to the master version?

If it may be rejected, we should expand support for Fork Weex, but we are worried that the follow-up will not be compatible with the Weex ecosystem.

If possible, please give a good suggestion, thank you.

My email address.
email: hanamg@hotmail.com

**Comment by YorkShen** [comment]
That's an interesting idea. I suggest you use master branch if ever possible and merge your changes to Weex. IMO, forking Weex is not an good idea as I know some company forked their version of Weex privately and it's almost impossible for them to merge back.

You can discuss the detail in [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list), which is a more appropriate place.

**Comment by hanagm** [comment]
Thank you for your suggestion, follow-up I will discuss through mailing list
