### ISSUE TITLE
click delete in <input>,then app crash

### ISSUE THREAD

**Issue by nikojxie** [apache/incubator-weex#2584]
When using <input> in ios, long press to call the menu ,then click delete, app crash
￼￼
![image](https://user-images.githubusercontent.com/35838595/59813226-58000900-9343-11e9-829d-152b45b5e7d6.png)

![41560996578_ pic_hd](https://user-images.githubusercontent.com/35838595/59813291-8978d480-9343-11e9-8bbd-274cb0d679c9.jpg)

Thanks for your help🙏

**Comment by YorkShen** [comment]
Please update to the latest version of weex and provide a [demo](http://dotwe.org/vue), I really can't help you according to just one sentence . **Please reopen this issue when demo are ready as I only response to issues that are open.**
