### ISSUE TITLE
Weex Rendering failed(must stop callNative)

### ISSUE THREAD

**Issue by zhenghaizhong** [apache/incubator-weex#2590]
06-11 14:19:15.736  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.737  2003  2234 W weex    : destroyInstance :78 JSF must stop callNative
06-11 14:19:15.737  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.737  2003  2234 I chatty  : uid=10024(com.flyme.systemuiex) WeexJSBridgeThr identical 3 lines
06-11 14:19:15.738  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.739  2003  2234 W weex    : destroyInstance :78 JSF must stop callNative
06-11 14:19:15.739  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.739   769   844 D BufferQueueProducer: [StatusBar#0](this:0x70ec3d3000,id:37,api:1,p:2003,c:769) connect(P): api=1 producer=(2003:com.android.systemui) producerControlledByApp=true
06-11 14:19:15.739  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.741  2003  2234 W weex    : destroyInstance :78 JSF must stop callNative
06-11 14:19:15.741  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.743  2003  2234 W weex    : destroyInstance :78 JSF must stop callNative
06-11 14:19:15.743  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.743  2003  2234 W weex    : destroyInstance :78 JSF must stop callNative
06-11 14:19:15.743  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.743  2003  2234 W weex    : destroyInstance :78 JSF must stop callNative
06-11 14:19:15.743  2003  2234 E jsengine: instance destroy JFM must stop callNative
06-11 14:19:15.743  2003  2234 W weex    : destroyInstance :78 JSF must stop callNative
06-11 14:19:15.743  2003  2234 E jsengine: instance destroy JFM must stop callNative

How can I solve it?please help.

**Comment by YorkShen** [comment]
This log implies that you are trying to run some JS/Java code after you leave the page, I don't think it will cause any failure.

Please provide more detail

**Comment by zhenghaizhong** [comment]
[log.zip](https://github.com/apache/incubator-weex/files/3312727/log.zip)



您好.上面是日志文件,看看对您分析有没有帮助 .

**Comment by YorkShen** [comment]
Still, not helpful.

From the log you provided, the only information I got is that you are trying to run some JS/Java code after you leave the page and I don't think it will cause any failure.

I will just close the issue and you can open another issue if you still have problems. 

*I only response the issue that are opened.*
