### ISSUE TITLE
[Help] Can not open https://weex.apache.org/zh/ webside

### ISSUE THREAD

**Issue by darkThanBlack** [apache/incubator-weex#2596]
I can open [https://weex.apache.org/](https://weex.apache.org/)
but can not open  [https://weex.apache.org/zh/guide/introduction.html](https://weex.apache.org/zh/guide/introduction.html)
It's showed ``ERR_TOO_MANY_REDIRECTS`` at 2019.06.20 22:00
Now it's showed ``ERR_CONNECTION_TIMED_OUT``
Tried someone else's computer but not work.

**Comment by YorkShen** [comment]
Fixed now.

Thanks
