### ISSUE TITLE
0.24sdk 在android x86模拟器上跑不起来，出现要降级h5的错误

### ISSUE THREAD

**Issue by farwolf2010** [apache/incubator-weex#2602]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: 0.24sdk can't run on android x86 emulator, there is an error to downgrade h5

Thanks for reporting, we will look into that.

**Comment by kuaifan** [comment]
找到一个解决方案，使用0.18.0版本的so替换就可以
参考：https://bbs.eeui.app/question/7?answer_id=8&single=TRUE#!answer_8

**Comment by YorkShen** [comment]
> 找到一个解决方案，使用0.18.0版本的so替换就可以
> 参考：https://bbs.eeui.app/question/7?answer_id=8&single=TRUE#!answer_8

Yes, this may solve the issue, but it may also cause another crash.

**Comment by YorkShen** [comment]
Thanks , already fixed in master branch
