### ISSUE TITLE
[Android]0.24sdk 加载js文件出错,报9601错误

### ISSUE THREAD

**Issue by pujyzx** [apache/incubator-weex#2604]
reportJSException >>>> instanceId:3, exception function:createInstanceContext, exception:Exception: ReferenceError: Can't find variable: process
    Store@weex createInstanceContext:43341:14
    weex createInstanceContext:43026:43
    __webpack_require__@weex createInstanceContext:22:34
    weex createInstanceContext:47463:33
    __webpack_require__@weex createInstanceContext:22:34
    weex createInstanceContext:65:37
    global code@weex createInstanceContext:66:12

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: 0.24sdk loading js file error, reported 9601 error

Check your JavaScript code with **process**, the stacktrace is pretty clear that it can't find variable named `process`.
