### ISSUE TITLE
[Android][iOS][all the mobile] error behavior when using "v-for" for div in list cell where weex version is 0.18

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex#2605]
## Describe the bug

Can we "v-for" div in cell compoment ?
In WEEX0.18 , i hava a dto like :
```javascript
dto:[
   childdto:[1,1,1],
   childdto:[1,1,1],
   childdto:[1,1,1],
]
```
When I use:
```javascript
<list>
  // <commonrefresh v-on:refresh.native="$refresh.invoke()" :refreshing="refreshing"></commonrefresh>
   <cell v-for="(item , index) in dto" :key="index">
         <div v-for="(item1 , index1) in item.childdto" :key="index1+'child'">               
               <text style="height:200">show Text</text>
         </div>   
   </cell>
</list>
```
The initRender is right.Three data block were shown on Screen.
Then i add a refresh function. Without change data.
Only the first && second  data block are Visible, the third block is absent !!!

At most time, we only repeat arratData in Cell, and it works no problem!
In this case, it works ok if I exchange  both "list" to "scroller", "cell" to "div"
So I think it will go wrong when repeat div in cell.

BTW, I DEBUG it in AndroidStudio.The Domobj is right, even the third block is invisiable, Domobj also hold the object of third block.

**Comment by YorkShen** [comment]
Please add a complete demo, thanks. Code snippet is not helpful.

I will close the issue and you could reopen it with you demo.

* I only response to issues that are open.*
