### ISSUE TITLE
[Android]so库问题 weex version is 0.24.0

### ISSUE THREAD

**Issue by wangtaoT** [apache/incubator-weex#2610]
E/weex: getLibLdPath is /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm:/system/fake-libs:/data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/base.apk!/lib/armeabi-v7a
E/weex: JavaScriptCore's Path is/data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm/libJavaScriptCore.so
    findLibJscRealPath /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm/libJavaScriptCore.so
E/WeexCore: initFromParam is running 
E/weex: getUseSingleProcess is running false
E/WeexCore: g_use_single_process is false 
E/weex: getLibJscPath is running /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm
E/WeexCore: g_jscSoPath is /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm 
E/weex: getLibJssPath is running /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm/libweexjss.so
E/WeexCore: g_jssSoPath is /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm/libweexjss.so 
E/WXParams: getCrashFilePath:/data/user/0/com.wangtao.my/app_crash
E/WeexCore: g_crashFilePath is /data/user/0/com.wangtao.my/app_crash 
E/weex: getLibIcuPath is running /system/usr/icu/icudt60l.dat
E/WeexCore: g_jssIcuPath is /system/usr/icu/icudt60l.dat 
E/weex: getLibLdPath is running /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm:/system/fake-libs:/data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/base.apk!/lib/armeabi-v7a
E/WeexCore: lib_ld_path is /data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/lib/arm:/system/fake-libs:/data/app/com.wangtao.my-XJcC28b0IKgkXC00q4cSOg==/base.apk!/lib/armeabi-v7a 
E/WeexCore: xxx set_core_side is runing and 0xd067f428
    ScriptBridgeInMultiProcess
    MultiProcessAndSoInitializer IS IN init
    WeexJSConnection g_crashFileName: /data/user/0/com.wangtao.my/app_crash/crash_dump.log
E/WeexCore: startupPie :1

**Comment by liuxinyea** [comment]
我也遇到了这个问题
I also have this problem.

**Comment by liuxinyea** [comment]
@wangtaoT 
你是怎么解决的？
How did you solve it?

**Comment by wangtaoT** [comment]
这个问题的原因是没初始化完成，就去调用！

**Comment by wangtaoT** [comment]
在回调方法中延时重新调用
@Override
    public void onException(WXSDKInstance instance, String errCode, String msg) {
//        if ("-1001".equals(errCode)) {
//            new Thread(new Runnable() {
//                @Override
//                public void run() {
//                    try {
//                        Thread.sleep(200);
//                    } catch (InterruptedException e) {
//                        e.printStackTrace();
//                    }
//                    runOnUiThread(new Runnable() {
//                        @Override
//                        public void run() {
//                            prepareWeex();
//                        }
//                    });
//                }
//            }).start();
//        }
    }
