### ISSUE TITLE
[iOS][Dev-tool] waterfall是什么时候出的版本，我这边显示不出来瀑布流的样式

### ISSUE THREAD

**Issue by shiqianren** [apache/incubator-weex#2615]
按照官网demo实现的

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: [When is the waterfall version, I can't show the style of the waterfall here?

I am pretty sure that `weex-0.24` supports it. If you are interesting, you can check out release branch and find out which one include waterfall.
