### ISSUE TITLE
[Android]@click事件，0.24的weex sdk上，频繁出现点击之后要等个好几秒才响应

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex#2620]
![image](https://user-images.githubusercontent.com/36951996/60232909-a62b8400-98d0-11e9-9c42-6e398bb403ac.png)

[点击事件demo在这里](http://dotwe.org/vue/919c5e8501209110db0a07ed6ff88dc4)
不断重复点，点个十几二十次 就没响应了，过个七八秒，刚才的点击事件才开始执行，感觉是队列卡住了

**Comment by YorkShen** [comment]
Duplicated #2599
