### ISSUE TITLE
人脸识别之后怎么，回调callback。 如何将callBack中的base64字符串显示。 image.src 提示错误，应该如何写

### ISSUE THREAD

**Issue by shimminZ** [apache/incubator-weex#2622]
TypeError: null is not an object (evaluating 'this.src = 'https://cdn.dribbble.com/users/179241/screenshots/1829868/nerfwarrior_dribbble.png'')

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: After the face recognition, callback callback. How to display the base64 string in callBack. Image.src prompt error, how should I write

Please read the document and provide a demo. Thanks.

I will close the issue as it not complies the issue template.
