### ISSUE TITLE
[iOS][Dev-tool] Unexpected behavior when open js-debug where weex version is 0.24.0

### ISSUE THREAD

**Issue by 371612143** [apache/incubator-weex#2623]
## Expected behavior

I can not debug js code with devtools
## Screenshots

![image](https://user-images.githubusercontent.com/11910163/60247465-4d211780-98f3-11e9-932a-fe42b0406719.png)

**Comment by YorkShen** [comment]
Please ask question the right [repo](https://github.com/weexteam/CLI-for-Apache-Weex), thanks
