### ISSUE TITLE
[iOS] ios sdk build fails on release/0.26

### ISSUE THREAD

**Issue by c0decafe** [apache/incubator-weex#2673]
ios sdk build fails on release/0.26:
```
In file included from /tmp/incubator-weex/weex_core/Source/core/parser/dom_wson.cpp:24:
/tmp/incubator-weex/weex_core/Source/android/utils/params_utils.h:23:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.

** BUILD FAILED **
```
It is caused by the below:

https://github.com/apache/incubator-weex/blob/486648769934be249c3d942081debde841a20325/weex_core/Source/core/parser/dom_wson.cpp#L24

removing it fixes the ios build.

also it seems to not be necessary as it didn't break the android build.

**Comment by YorkShen** [comment]
As release/0.26 passed two rounds vote and will be published soon, the code on release/0.26 won't be changed.

However, we fixed this issue when merge code into master branch.
