### ISSUE TITLE
Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by peng0398** [apache/incubator-weex#2689]
E/weex: reportJSException >>>> instanceId:14, exception function:createInstanceContext, exception:Exception: TypeError: Attempted to assign to readonly property.
    weex createInstanceContext:3:29029
    weex createInstanceContext:3:30445
    t@weex createInstanceContext:3:105
    weex createInstanceContext:3:481
    global code@weex createInstanceContext:3:491

**Comment by YorkShen** [comment]
Check your code, thanks.

The message is pretty straight-forward. You are **Attempted to assign to readonly property**.
