### ISSUE TITLE
 [Android] weex 0.26 doesn't reset :active style on <text>

### ISSUE THREAD

**Issue by dim0xff** [apache/incubator-weex#2695]
## Describe the bug
Style for :active on <text> element is not being reset ( like in #2657 )

## To Reproduce
http://dotwe.org/vue/76185ea0f5176a878ce474bbf66a1053

## Expected behavior
Style should be reset to it's original state after click on <text> element

## Environment
* OS: Android 9
* Weex SDK Version: 0.26.0
* Build from source: no

**Comment by YorkShen** [comment]
Duplicate with #2657
