### ISSUE TITLE
[Android]loading-indicator's error when set animating true

### ISSUE THREAD

**Issue by tonlion** [apache/incubator-weex#2698]
the animating's default value must be true, when set true,arrow always show. 
when toggle animating's value,arrow disappears.
here is code.
```
<template>
    <div>
      <loading-indicator class="indicator" :animating="animating"></loading-indicator>
    </div>
</template>

<script>
  export default {
    data () {
      return {
        animating: true
      }
    }
  }
</script>

<style scoped>
  .indicator {
    margin-top: 16px;
    height: 50px;
    width: 50px;
    color: black;
  }
</style>
```

**Comment by YorkShen** [comment]
I don't see any problem here.

Change `animating` to false when you finishes the loading in JS.

**Comment by tonlion** [comment]
When setting animating to false and then changing to true, the arrow will disappear after the first turn, and when the initial setting is true, the arrow will always exist.
