### ISSUE TITLE
[Android] 0.26.0 Richtext components filled in Chinese android can not be displayed

### ISSUE THREAD

**Issue by kuaifan** [apache/incubator-weex#2700]
Richtext components filled in Chinese android can not be displayed.

But master normal.

**Comment by kuaifan** [comment]
http://dotwe.org/vue/f748b0cee3991522a66d4376b66a4f2a

**Comment by YorkShen** [comment]
There is a missing commit in `release/0.26` branch.

Due to the time consuming of Apache release procedure, there are three options:
* Wait for next release, which shall be scheduled in August.
* Compile from source of master branch.
* Be the release manager and do a release based on master branch.

**Comment by kuaifan** [comment]
Thanks.
