### ISSUE TITLE
Weex V0.26.0 onException errcode-1001

### ISSUE THREAD

**Issue by Herrick66** [apache/incubator-weex#2716]
When I ran the app on the real machine, I reported an error of 1001, but it worked well on the virtual machine。My Phone is DUK-AL20（荣耀v9),the OS is EMUI9.1.0.188 and the Android OS is 9.
Here are the error details：TestWeexFragment-->onException-->errcode-1001--msg-->degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

**Comment by YorkShen** [comment]
Currently, we have no Android 9 real machine and no plan to do the test before we got the real phone with Android 9.

Also it works well on my Android emulator.
