### ISSUE TITLE
List Scroller下偶现控件丢失不展示

### ISSUE THREAD

**Issue by fengmingye** [apache/incubator-weex#2717]
## Describe the bug

在List Scrollder等容器下面偶现控件丢失不展示的问题

## Environment

weex sdk 版本0.18
Android ,ios都有此问题，退出页面再次进入则恢复正常

## Screenshots

![image](https://user-images.githubusercontent.com/16618626/61344895-7a733c80-a885-11e9-84e4-d9a66455d905.png)

**Comment by fengmingye** [comment]
图中第二个item应该展示预期年化，但是没有展示出来，数据本身是OK的。
页面刷新重新绘制都没有，只有退出页面再次进入才可以。
复现概率偏小

**Comment by YorkShen** [comment]
1. Please upgrade to 0.26. Even if it is a bug, there is nothing we can do on such an old version.
2. Provide a demo. We can't fix a bug before reproduce it.

**Comment by xiaoqi951109** [comment]
@YorkShen  We've had this problem too many times.So we updated to version 26.But I don't know if it will be solved.Sometimes some icons or views don't show up, and sometimes lists repeat.This is a very serious problem. Every day, customers complain about the instability of our system and occasionally show a lack of it. They mistakenly think it's a data problem.The trigger probability is estimated to be about 3%, but there is nothing we can do about it.I'm sure if you open a weex-built software for a whole day, it will appear 2-3 times.

**Comment by xiaoqi951109** [comment]
@YorkShen Today, I try to raise our version to 26. I don't know if it can solve this problem. But 26 has a very serious problem. Another friend raised a question: when the page loads, there will be component jump, sometimes from the top, sometimes from the bottom, about 100 ms later, it will jump back to the target location. The performance of the mobile phone is not questioned. Question, and every cell phone can be reproduced
