### ISSUE TITLE
weex手势密码的源代码在哪里可以找到？

### ISSUE THREAD

**Issue by lieqiang** [apache/incubator-weex#2732]
请问一下下面这个手势密码的源代码在哪里可以找到？目前只看到下面这个页面，并未发现源码https://weex.apache.org/zh/biz-component/biz-comm-PatternLock.html

**Comment by chenzefeng09** [comment]
你看到的不是weex sdk的一部分，算是阿里的一个商业产品的吧http://emas.weex.io/zh/community/biz-emas.html

**Comment by YorkShen** [comment]
`PatternLock` is not a part of weex, I am not sure why the page exsits. I will delete it anyway.

**Comment by YorkShen** [comment]
The page is deleted as expceted.
