### ISSUE TITLE
[Android] 新建weex工程，把SDK升级到0.26后，安装app时报错！

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex#2733]
错误信息如下图所示：
![E91BC3C1-DA62-45b3-8A13-0109636A4EBD](https://user-images.githubusercontent.com/41984848/61507490-77f51c00-aa18-11e9-993d-53f1f2117e44.png)

操作步骤：
1.使用weex create命令项目
2.使用weex platform add android创建安卓工程
3.使用android studio修改weex sdk版本号，相关jar包版本如下图所示：
![QQ截图20190719110906](https://user-images.githubusercontent.com/41984848/61506758-c9e87280-aa15-11e9-98e8-b3ff6d52b34e.png)
![QQ截图20190719110929](https://user-images.githubusercontent.com/41984848/61506776-da005200-aa15-11e9-884f-1a4e09ba301d.png)
![QQ截图20190719110953](https://user-images.githubusercontent.com/41984848/61506784-df5d9c80-aa15-11e9-9817-876a4b200342.png)

**Comment by YorkShen** [comment]
The log is pretty straightforward, you are missing `ABI`. Add your `ABI` first.

FYI, `weex create` is never part of Apache Weex as it explained in the document, you should not ask question in the right place.

I will just close the issue.

**Comment by zhongwang2008** [comment]
同一个工程，SDK降到0.24版本，就不会弹这个错误！
希望能给个具体的解决方法！谢谢！

**Comment by YorkShen** [comment]
As it's said multiple times, we are not responsible for the CLI `weex create` as it is not part of Apache Weex currently.
