### ISSUE TITLE
我在配置week初始化时报错，连接失败，见截图

### ISSUE THREAD

**Issue by qieting** [apache/incubator-weex#2740]
我使用了最新稳定版的npm，设置了代理，下载weex没有问题
但是当我输入weex
![image](https://user-images.githubusercontent.com/29308172/61622859-35e20980-aca8-11e9-902b-399fcb5c62e6.png)
我是win7 64 bit

**Comment by qieting** [comment]
我才用了另外一个链接的配置weex的代理的方法也没有奏效

**Comment by YorkShen** [comment]
Please check your network, we are not able to help fixing your network problem.
