### ISSUE TITLE
[Android]weex 2.0.0-beta.31

### ISSUE THREAD

**Issue by iceading** [apache/incubator-weex#2742]
你好请问为什么我的weex list 和waterfall的滚动条在网页端和安安卓端都无法加载，我已经在环境中配置了<list ref="myheight" show-scrollbar="true">，可是还是无法夹在请问这是普遍的问题吗

**Comment by YorkShen** [comment]
There is certainly no version `2.0.0-beta.31`. All the version we have is listed [here](https://weex.apache.org/download/download.html). If some third-party provides version, ask them, not here.

**Comment by YorkShen** [comment]
There is no such version called `2.0.0-beta.31`. All the version we have currently is listed [here](https://weex.apache.org/download/download.html). If some third-parties provide you the version, ask them, not here.
