### ISSUE TITLE
[iOS]线性渐变 Linear-gradient IOS has bugs

### ISSUE THREAD

**Issue by hilads** [apache/incubator-weex#2748]
* Device: [e.g. iPhone8]
* OS: [e.g. iOS12.3.1]

## Expected behavior

![image](https://user-images.githubusercontent.com/46804595/61773188-a1ea7c00-ae26-11e9-9c9c-34d1ffde6155.png)
but 但是 确是这样的 
![image](https://user-images.githubusercontent.com/46804595/61773257-d5c5a180-ae26-11e9-967c-832c3cfd4cce.png)
![image](https://user-images.githubusercontent.com/46804595/61773230-c5adc200-ae26-11e9-9c93-b24b521d65c7.png)
当不用渐变时 正常 
![image](https://user-images.githubusercontent.com/46804595/61773296-f130ac80-ae26-11e9-84ac-1485146a9758.png)
![image](https://user-images.githubusercontent.com/46804595/61773307-f68df700-ae26-11e9-9648-faf7068a4914.png)
i dont know what happen

**Comment by yp-mon** [comment]
我也遇到类似问题

**Comment by hilads** [comment]
> 我也遇到类似问题

我是打算用层级不同 叠加一个 奈何 不支持 z-index 就很难受

**Comment by Txink** [comment]
Your Weex SDK may be not latest version. This bug has been fixed.

**Comment by hilads** [comment]
> Your Weex SDK may be not latest version. This bug has been fixed.

ok  I'll give it a try.
