### ISSUE TITLE
Can you provide a stable version of the 64-bit SDK? 8.1 is coming soon. Version 0.26 is very unstable and not available at all

### ISSUE THREAD

**Issue by roger2380** [apache/incubator-weex#2749]

**Comment by YorkShen** [comment]
Weex 0.26 already supports 64 bits.

If you are not happy with 0.26, you can 
* Compile from source.
* Host a release under the [procedure](https://weex.apache.org/community/release-procedure.html)

**Comment by roger2380** [comment]
Sorry ,how to compile weex_core  to 64bit ?

**Comment by roger2380** [comment]
or 0.24 weex_core same as  0.26?

**Comment by YorkShen** [comment]
Read the document, everything you need is in there.

**Comment by roger2380** [comment]
tks
