### ISSUE TITLE
[Android] NullPointerExcep when `weex run android` where call gradew.bat [weex2beta3.1]

### ISSUE THREAD

**Issue by dagang007** [apache/incubator-weex#2757]
## Describe the bug
When I run : weex run android
>JSBundle done
>select device of yeshen
>start hotreload server done
>set native config done
>copy js source done
>watch js source done
>Error: command failer: call gradlew.bat clean assembleDebug
>Exception in thread: main java.NullPointerE....

**Comment by YorkShen** [comment]
Again, [weex-cli](https://github.com/weexteam/CLI-for-Apache-Weex) is not part of Apache Weex, you should ask questions in the right place.
