### ISSUE TITLE
请问下可以在weex里面使用 vue render方法吗？

### ISSUE THREAD

**Issue by lieqiang** [apache/incubator-weex#2759]
请问下可以在weex里面使用 vue render方法吗？用模板方法有些功能实现繁琐。

**Comment by dagang007** [comment]
你好，请教一下我按官方的weex create proj 可以启动web项目。
但是weex platform add android -> weex run android 会报错！你执行这些是正常的吗？
（报错的都是各种gradle的配置错误）

**Comment by lieqiang** [comment]
之前刚开始有这些错，按错误提示网上找下方法，或者官网看看，或者问问原生开发的人，基本可以解决哈；

**Comment by mofeisike** [comment]
都要用, render, 用React吧

**Comment by snice** [comment]
Yes,
```js
export default {
    render: function (h) {
    }
}
```

**Comment by YorkShen** [comment]
Thanks for your reply @snice , I will just close the issue.
