### ISSUE TITLE
[iOS] 用scroller时如果有多个textarea 键盘弹出页面偏移计算会有问题

### ISSUE THREAD

**Issue by yqnight** [apache/incubator-weex#2784]
问题：当使用scroller时，如果页面上的textarea有部分被屏幕挡住，点击这个textarea，当键盘弹起时，整个视图会发生错误的偏移
（When using the scroller, if the textarea on the page is partially blocked by the screen, click on the textarea. When the keyboard pops up, the entire view will be incorrectly offset.）

Reproduce：http://dotwe.org/vue/59469ca271eb4e5551c1ce2d3031cd04

*设备：iPhone XR
*操作系统：IOS12.4
*weex版本：0.24
*从源代码构建:是

**Comment by jianhan-he** [comment]
谢谢您的反馈，该问题已经修复
