### ISSUE TITLE
weex create error

### ISSUE THREAD

**Issue by kuangyanit** [apache/incubator-weex#2799]
when i use `weex create weex-demo`， there is a error like ` Error: [.babelrc] Missing helper: "if_eq"`, how can i solve it? 

weex --version

2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.31
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/doctor : v2.0.0-beta.20

**Comment by YorkShen** [comment]
Please ask question in the [right repo](https://github.com/weexteam/CLI-for-Apache-Weex), not here
