### ISSUE TITLE
[Android]transform+box-shadow error on android 7

### ISSUE THREAD

**Issue by zhangleiooo** [apache/incubator-weex#2801]
When using transform and box-shadow at the same time, box-shadow is abnormal on Android 7.

here is code
http://dotwe.org/vue/b9b0bdbc87e5cea76b0dce174c22a2f5

device:redmi note 4X 
android 7.

**Comment by YorkShen** [comment]
As android OS changed its `canvas` behavior, `box-shadow` on Android will not be supported anymore.

**Comment by zhangleiooo** [comment]
How can I solve it?

> As android OS changed its `canvas` behavior, `box-shadow` on Android will not be supported anymore.
