### ISSUE TITLE
[iOS] iOS13 [WXComponent Dealloc] crash in 0.20.1

### ISSUE THREAD

**Issue by lixiangsanxun** [apache/incubator-weex#2804]
## Describe the bug

 iOS13 [WXComponent Dealloc] crash in 0.20.1.

## To Reproduce
When weex page render，this crash happens occasionally.WXTextComponet dealloc also cause this crash.

## Environment

* Device: [e.g. iPhone6]
* OS: [e.g. iOS13]
* Version [e.g. 20]
* Build from source [e.g. yes]

## Additional context

0 UIKitCore | 0x000000019a8c3000 + 15067552
-- | --
1 UIKitCore | 0x000000019a8c3000 + 15067444
2 WeexSDK | -[WXComponent .cxx_destruct] (WXComponent.mm:56)
3 libobjc.A.dylib | 0x0000000196fed000 + 20968
4 libobjc.A.dylib | objc_destructInstance + 88
5 libobjc.A.dylib | _objc_rootDealloc + 48
6 WeexSDK | -[WXComponent dealloc] (WXComponent.mm:272)
7 libsystem_blocks.dylib | _Block_release + 152
8 WeexSDK | __destroy_helper_block_e8_32s40s48s56s (WXAnimationModule.m:185)
9 libsystem_blocks.dylib | _Block_release + 152
10 libsystem_blocks.dylib | _Block_release + 152
11 libdispatch.dylib | 0x0000000196f3d000 + 373196
12 libdispatch.dylib | 0x0000000196f3d000 + 15196
13 libdispatch.dylib | 0x0000000196f3d000 + 12976
14 libdispatch.dylib | 0x0000000196f3d000 + 65680
15 libdispatch.dylib | 0x0000000196f3d000 + 67676
16 libsystem_pthread.dylib | _pthread_wqthread + 212

**Comment by YorkShen** [comment]
Please upgrade to 0.26. 

Even if there is a problem in 0.20, we are not able to fix it.

**Comment by MrBoog** [comment]
hi，guys  any update about this? I met the same problem
