### ISSUE TITLE
How to get CSSNode(like) in weex 0.26 for android?

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex#2811]
How to get CSSNode(like) in weex 0.26 for android?
In weex docs, only tell the way in IOS.
But no suggestions for android, how to replace CSSNode in weex from 0.18 to 0.26.
Could you write more details in docs both Android and iOS?
It is really hard to update from 0.18 to0.26 without exhaustive docs.Thanks!

**Comment by fengmingye** [comment]
The same to me，It is too hard to update without exhanstive docs.

**Comment by YorkShen** [comment]
The `CSSNode` is removed for historical Facebook additional patten reason, read [document](https://weex.apache.org/guide/extend/extend-android.html#component-extension-adaptation) to find out the behaviour.

If this could solve your problem, you can update the documentation of Weex to help others.
