### ISSUE TITLE
[iOS]自定义扩展组件时，属性无法传递给原生使用  weex version is 0.18.0

### ISSUE THREAD

**Issue by lovederh** [apache/incubator-weex#2817]
组件定义方法
`
- (instancetype)initWithRef:(NSString *)ref type:(NSString *)type styles:(NSDictionary *)styles attributes:(NSDictionary *)attributes events:(NSArray *)events weexInstance:(WXSDKInstance *)weexInstance
{
    self = [super initWithRef:ref type:type styles:styles attributes:attributes events:events weexInstance:weexInstance];
    if (self) {
        if(attributes[@"url"]){
            _url = [WXConvert NSString: attributes[@"url"]]; //此处获取不到
        }
        NSLog(@"url is %@", _url); // 打印为空
    }
    return self;
}
- (void) updateAttributes:(NSDictionary *)attributes{
    if(attributes[@"url"]){
        _url = [WXConvert NSString: attributes[@"url"]];
    }
    NSLog(@"url update is %@", _url);
}
`
`<hy-player :url="url" style="width:800px;height: 500px" ></hy-player>`
获取url为空
前端组件代码

**Comment by lovederh** [comment]
前端组件调用``<hy-player :url="url" style="width:800px;height: 500px" ></hy-player>``

**Comment by jianhan-he** [comment]
把attributes整个对象打印出来里面是什么内容？

**Comment by YorkShen** [comment]
No update for a month, I will just close it.
