### ISSUE TITLE
求分享JS service内置包的方案

### ISSUE THREAD

**Issue by tailorsira** [apache/incubator-weex#2839]
JS bundle包越来越大，想把一部分包内置到客户端中，但是包很大了之后，页面的渲染性能随之下降，求分享一个1M的包(gzip之后)，渲染方案

**Comment by zsmjhtn** [comment]
> JS bundle包越来越大，想把一部分包内置到客户端中，但是包很大了之后，页面的渲染性能随之下降，求分享一个1M的包(gzip之后)，渲染方案

单weex文件越来越大？还是weex总文件数量增大？
个人经验单文件一般100kb左右。先打weex包，在apk打包时，将加密后的weex文件copy到apk的asset里面，apk启动时先把asset里的weex文件copy到sd卡，然后加载sd卡里的weex文件。
至于weex文件热更新，在生命周期做个同步，比较本地和远程md5，增量下载到sd卡。

目前没遇到过明显的渲染性能问题。渲染回调不能正确控制等几个小问题一直都有

**Comment by cyabc** [comment]
有解么

**Comment by hponiang** [comment]
直接用文件资源的形式加载不就可以了，比如安卓 file://assets/dist/+路径  ios WeexDemo.app加路径

**Comment by YorkShen** [comment]
It seems like this problem is solved, I will just close it.
