### ISSUE TITLE
weex安卓应用的字体类型能不能与手机的字体类型一致

### ISSUE THREAD

**Issue by Hzhxi9** [apache/incubator-weex#2845]
H5页面字体应该与系统字体一直，需评估是否可以完成；

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Can the font type of the weex Android app be the same as the font type of the phone?

First of all, there is no font called system font. If you don't specify a font-family, the fallback/default rule of font is undefined behavior.

So, specify a [font-family](https://weex.apache.org/docs/styles/text-styles.html#font-family) will make your life easier.
