### ISSUE TITLE
[iOS] XCode11打包，iOS13系统手机，使用<text>组件，字体非苹果默认的苹方字体

### ISSUE THREAD

**Issue by jiqimao3528** [apache/incubator-weex#2859]
## Describe the bug
[iOS] XCode11打包，iOS13系统手机，使用<text>组件，字体非苹果默认的苹方字体

## Environment
<!-- 
* Device: iPhone
* OS: iOS13 beta7
* WeexSDK: 0.22.0.6
* 编译器：XCode11

## Expected behavior
使用XCode11编译，运行在iOS13手机上时，weex页面中，使用<text>标签的文字字体默认不显示系统字体。单独设置coretext="false"之后，可以正常显示。
使用XCode10编译或者不是iOS13系统的手机，无此问题。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> [iOS] XCode11 package, iOS13 system phone, use <text> component, font is not Apple's default apple font

Change it to whatever you want by using [font-family](https://weex.apache.org/docs/styles/text-styles.html#font-family)

**Comment by krimeshu** [comment]
> 感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。
> 
> > [iOS] XCode11 package, iOS13 system phone, use  component, font is not Apple's default apple font
> 
> Change it to whatever you want by using [font-family](https://weex.apache.org/docs/styles/text-styles.html#font-family)

你好，请问具体怎么设置 font-family 呢？
判断 iOS 原生环境，然后给每个 text 组件都设置一遍 font-family: PingFang; 吗？好像效率很低，还不确定是否能生效，多封装一层组件似乎没必要。
请问推荐的详细解决方案是什么样呢？

Hello, what's the value be setted to `font-family`? 
Check if in the iOS native environment, and set `font-family: PingFang;` to every `<text>` or wrap an component (e.g. `<my-text>`) to replace all `<text>`? It seems ugly, and not sure it'll work.
Could you mind offer an more detail and effective solution?

**Comment by krimeshu** [comment]
关联问题：
https://segmentfault.com/q/1010000020611504

**Comment by YorkShen** [comment]
@wqyfavor Have a look?

**Comment by krimeshu** [comment]
尝试了以下 `font-family` 属性，或者设置 `style` 属性样式，但都无效：

All attemps below not working, help please~

求助～

```css
.test-1 {
    font-family: 'PingFang', sans-serif;
}
.test-2 {
    font-family: 'PingFang';
}
.test-3 {
    font-family: 'PingFangSC';
}
```

**Comment by krimeshu** [comment]
Help~

**Comment by QC-L** [comment]
@YorkShen This issue has a wide range of impact on iOS. More obvious is that the text is centered vertically.

**Comment by YorkShen** [comment]
> @YorkShen This issue has a wide range of impact on iOS. More obvious is that the text is centered vertically.

@QC-L Sorry, I am not an iOS developer. Maybe @jianhan-he @wqyfavor could have a look.

**Comment by jianhan-he** [comment]
@QC-L can you try like as :   font-family: PingFang SC

**Comment by krimeshu** [comment]
Tried, but still not work.

jianhan-he <notifications@github.com> 于2019年11月25日周一 下午5:25写道：

**Comment by krimeshu** [comment]
There are lots of log like this:

```
CoreText note: Client requested name ".SFUI-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].
```

**Comment by jianhan-he** [comment]
@krimeshu which version of weexsdk do you use?   pr: https://github.com/apache/incubator-weex/pull/2936  has already fix this bug.

**Comment by krimeshu** [comment]
> @krimeshu which version of weexsdk do you use? pr: #2936 has already fix this bug.

0.24.0

**Comment by jianhan-he** [comment]
you can try the version of 0.28.0. It has already fixed. @krimeshu

**Comment by krimeshu** [comment]
> you can try the version of 0.28.0. It has already fixed. @krimeshu

Upgraded to 0.28.0, bug resolved, thank you!
