### ISSUE TITLE
有富文本编辑组件吗？

### ISSUE THREAD

**Issue by bestprize999** [apache/incubator-weex#2860]
请问支持richedit吗？

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Is there a rich text editing component?

Nope, and you're welcomed to give us PR.
