### ISSUE TITLE
[Android] wx_create_instance_error, reportJSException >>>> instanceId:3, exception function:createInstance, exception:Exception: ReferenceError: Can't find variable: window

### ISSUE THREAD

**Issue by wangfengzxz** [apache/incubator-weex#2863]
A little of users encounted this problem.
error trace:
java.lang.RuntimeException: degradeToH5|createInstance fail|wx_create_instance_error, reportJSException >>>> instanceId:1, exception function:createInstance, exception:Exception: ReferenceError: Can't find variable: window
(global function):6:4636
anonymous@(global function):9:3
(weex framework):1:151036
ni@(weex framework):1:151047
createInstance@(weex framework):1:154254
(weex framework):1:178788

This trance is the same type below
java.lang.RuntimeException: degradeToH5|createInstance fail|wx_create_instance_error, reportJSException >>>> instanceId:3, exception function:createInstance, exception:Exception: ReferenceError: Can't find variable: document
(global function):6:10
anonymous@(global function):9:3
(weex framework):1:151036
ni@(weex framework):1:151047
createInstance@(weex framework):1:154254
(weex framework):1:178788

The version I used is 'com.taobao.android:weex_sdk:0.20.0.2@aar'

**Comment by YorkShen** [comment]
The log is pretty straight-forward, there is an undefined variable called `window` in your JS file.
