### ISSUE TITLE
weex image src not support Ternary expression

### ISSUE THREAD

**Issue by chenjuyu** [apache/incubator-weex#2871]
weex 的 image 组件 :src="[img?img:error.jpg]" src 属性不支持三元表达式 ，当img 有值时，图片组件显示不出来

**Comment by zsmjhtn** [comment]
> weex 的 image 组件 :src="[img?img:error.jpg]" src 属性不支持三元表达式 ，当img 有值时，图片组件显示不出来

支持的，至少我用的0.18版本是支持的。
这种没理由做不到支持，查查自身原因吧，绝大概率是自己问题

**Comment by zsmjhtn** [comment]
:src="Cond ? 'img1' : 'img2' "。
你看看你传的是 图片地址 还是 一个引用？图片地址要用单引号包起来

**Comment by chenjuyu** [comment]
去掉[]号可以了，谢谢了
