### ISSUE TITLE
[Android]有谁能联系到作者吗，跪求0.27.0的发布呀，我们周一上线google play。

### ISSUE THREAD

**Issue by hechangpeng** [apache/incubator-weex#2872]
[Android]有谁能联系到作者吗，跪求0.27.0的发布呀，我们周一上线google play，要支持64位，但是0.26.0太多BUG了，测试不通过呀。

**Comment by LwLuna** [comment]
我看他0.26.0版本修改的特征不是写的支持64位arm吗

**Comment by hechangpeng** [comment]
> 我看他0.26.0版本修改的特征不是写的支持64位arm吗

太多BUG了，部分手机插件启动白屏。
error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

**Comment by LwLuna** [comment]
> 
> 
> > 我看他0.26.0版本修改的特征不是写的支持64位arm吗
> 
> 太多BUG了，部分手机插件启动白屏。
> error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

这个错应该就是库没对应上，我这边也马上要发布Google play呢，之前在ERos上写的，没有64位库，就想转到这个上面算了，没想到weex也存在这个问题，这怎么办 啊

**Comment by hechangpeng** [comment]
> > > 我看他0.26.0版本修改的特征不是写的支持64位arm吗
> > 
> > 
> > 太多BUG了，部分手机插件启动白屏。
> > error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
> 
> 这个错应该就是库没对应上，我这边也马上要发布Google play呢，之前在ERos上写的，没有64位库，就想转到这个上面算了，没想到weex也存在这个问题，这怎么办 啊
唉

**Comment by hechangpeng** [comment]
> > > 我看他0.26.0版本修改的特征不是写的支持64位arm吗
> > 
> > 
> > 太多BUG了，部分手机插件启动白屏。
> > error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
> 
> 这个错应该就是库没对应上，我这边也马上要发布Google play呢，之前在ERos上写的，没有64位库，就想转到这个上面算了，没想到weex也存在这个问题，这怎么办 啊

可以试试编译0.24.0的版本，看下能不能搞出个64位版本，或者最新源码拉下来自己编译。有结果分享一个。

**Comment by LwLuna** [comment]
好的

**Comment by YorkShen** [comment]
Master branch support 64 bit, you can build from master branch.

**Comment by LwLuna** [comment]
你是怎么升级到0.26.0的我这边升级报错

**Comment by hechangpeng** [comment]
> 你是怎么升级到0.26.0的我这边升级报错

报啥错？weex新旧版本api有变化，不兼容。

**Comment by LwLuna** [comment]
> 
> 
> > 你是怎么升级到0.26.0的我这边升级报错
> 
> 报啥错？weex新旧版本api有变化，不兼容。

WXDomObject 这个找不到了，  WXSDKEngine.switchDebugModel(true, debug_url);也找不到了，IWXDebugProxy这个也找不到了。我把他们都去掉报res=-113错误了又 ，能不能加个QQ：1053419668

**Comment by LwLuna** [comment]
> 
> 
> > 你是怎么升级到0.26.0的我这边升级报错
> 
> 报啥错？weex新旧版本api有变化，不兼容。

可以了。升级了weex 重新创建的项目，你那边什么手机白屏

**Comment by zsmjhtn** [comment]
我拉新源码替换，0.24报了个cmake的c++空指针的异常，编译不过，0.26编译过但是weex一直报错：error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

**Comment by hechangpeng** [comment]
> 我拉新源码替换，0.24报了个cmake的c++空指针的异常，编译不过，0.26编译过但是weex一直报错：error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

我也是这个错误，插件打不开。

**Comment by hechangpeng** [comment]
> > > 你是怎么升级到0.26.0的我这边升级报错
> > 
> > 
> > 报啥错？weex新旧版本api有变化，不兼容。
> 
> 可以了。升级了weex 重新创建的项目，你那边什么手机白屏

低端机，32位cpu

**Comment by zsmjhtn** [comment]
> > 我拉新源码替换，0.24报了个cmake的c++空指针的异常，编译不过，0.26编译过但是weex一直报错：error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
> 
> 我也是这个错误，插件打不开。

这种错误抛出来，无从下手，不知道哪里的问题，怎么解决

**Comment by hechangpeng** [comment]
> > > 我拉新源码替换，0.24报了个cmake的c++空指针的异常，编译不过，0.26编译过但是weex一直报错：error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
> > 
> > 
> > 我也是这个错误，插件打不开。
> 
> 这种错误抛出来，无从下手，不知道哪里的问题，怎么解决

史前棘手的问题，我怕是要成背锅侠了。唉。

**Comment by LwLuna** [comment]
> 
> 
> > > > 你是怎么升级到0.26.0的我这边升级报错
> > > 
> > > 
> > > 报啥错？weex新旧版本api有变化，不兼容。
> > 
> > 
> > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> 
> 低端机，32位cpu
我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的

**Comment by zsmjhtn** [comment]
> > > > 你是怎么升级到0.26.0的我这边升级报错
> > > 
> > > 
> > > 报啥错？weex新旧版本api有变化，不兼容。
> > 
> > 
> > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> 
> 低端机，32位cpu
> 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的

你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两种问题。

**Comment by LwLuna** [comment]
> 
> 
> > > > > 你是怎么升级到0.26.0的我这边升级报错
> > > > 
> > > > 
> > > > 报啥错？weex新旧版本api有变化，不兼容。
> > > 
> > > 
> > > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> > 
> > 
> > 低端机，32位cpu
> > 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的
> 
> 你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
> 我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两


是的，我就是从0.16.0=》0.26.0 升级失败所以重新装的工具重新创建的项目

**Comment by zsmjhtn** [comment]
> > > > > > 你是怎么升级到0.26.0的我这边升级报错
> > > > > 
> > > > > 
> > > > > 报啥错？weex新旧版本api有变化，不兼容。
> > > > 
> > > > 
> > > > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> > > 
> > > 
> > > 低端机，32位cpu
> > > 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的
> > 
> > 
> > 你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
> > 我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两
> 
> 是的，我就是从0.16.0=》0.26.0 升级失败所以重新装的工具重新创建的项目

这种方式感觉比较片面，讲道理不应该和项目结构挂钩。况且混合开发不一定只用weex。比如要加入flutter的话，原生项目还要依赖flutter的环境。flutter官方是有提供了其他引入方式的文档。而不需要你必须新疆一个flutter项目

**Comment by LwLuna** [comment]
> 
> 
> > > > > > > 你是怎么升级到0.26.0的我这边升级报错
> > > > > > 
> > > > > > 
> > > > > > 报啥错？weex新旧版本api有变化，不兼容。
> > > > > 
> > > > > 
> > > > > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> > > > 
> > > > 
> > > > 低端机，32位cpu
> > > > 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的
> > > 
> > > 
> > > 你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
> > > 我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两
> > 
> > 
> > 是的，我就是从0.16.0=》0.26.0 升级失败所以重新装的工具重新创建的项目
> 
> 这种方式感觉比较片面，讲道理不应该和项目结构挂钩。况且混合开发不一定只用weex。比如要加入flutter的话，原生项目还要依赖flutter的环境。flutter官方是有提供了其他引入方式的文档。而不需要你必须新疆一个flutter项目


我这也是真的没办法了，先能正常用起来再说吧，公司催着发布呢
我这也是没办法了

**Comment by hechangpeng** [comment]
> > > > > > 你是怎么升级到0.26.0的我这边升级报错
> > > > > 
> > > > > 
> > > > > 报啥错？weex新旧版本api有变化，不兼容。
> > > > 
> > > > 
> > > > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> > > 
> > > 
> > > 低端机，32位cpu
> > > 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的
> > 
> > 
> > 你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
> > 我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两
> 
> 是的，我就是从0.16.0=》0.26.0 升级失败所以重新装的工具重新创建的项目

“0.16.0=》0.26.0”  和 “升级失败所以重新装”，这两种操作有什么不一样吗？你们是Android还是IOS啊

**Comment by LwLuna** [comment]
> 
> 
> > > > > > > 你是怎么升级到0.26.0的我这边升级报错
> > > > > > 
> > > > > > 
> > > > > > 报啥错？weex新旧版本api有变化，不兼容。
> > > > > 
> > > > > 
> > > > > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> > > > 
> > > > 
> > > > 低端机，32位cpu
> > > > 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的
> > > 
> > > 
> > > 你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
> > > 我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两
> > 
> > 
> > 是的，我就是从0.16.0=》0.26.0 升级失败所以重新装的工具重新创建的项目
> 
> “0.16.0=》0.26.0” 和 “升级失败所以重新装”，这两种操作有什么不一样吗？你们是Android还是IOS啊



Android啊

**Comment by zsmjhtn** [comment]
> > > > > > > 你是怎么升级到0.26.0的我这边升级报错
> > > > > > 
> > > > > > 
> > > > > > 报啥错？weex新旧版本api有变化，不兼容。
> > > > > 
> > > > > 
> > > > > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> > > > 
> > > > 
> > > > 低端机，32位cpu
> > > > 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的
> > > 
> > > 
> > > 你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
> > > 我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两
> > 
> > 
> > 是的，我就是从0.16.0=》0.26.0 升级失败所以重新装的工具重新创建的项目
> 
> “0.16.0=》0.26.0” 和 “升级失败所以重新装”，这两种操作有什么不一样吗？你们是Android还是IOS啊

aos和ios差不多。第一种升级方式是copy sdk源码+依赖文件，手动替换升级。第二种是根据一个非官方维护的cli工具，生成一个“weex”的项目结构，然后更改里面的sdk依赖版本

**Comment by LwLuna** [comment]
> 
> 
> > > > > > > > 你是怎么升级到0.26.0的我这边升级报错
> > > > > > > 
> > > > > > > 
> > > > > > > 报啥错？weex新旧版本api有变化，不兼容。
> > > > > > 
> > > > > > 
> > > > > > 可以了。升级了weex 重新创建的项目，你那边什么手机白屏
> > > > > 
> > > > > 
> > > > > 低端机，32位cpu
> > > > > 我重新升级了 weex-toolkit 重新创建项目，加上64位的包了，运行没问题，在64位手机也可以运行，只试了个华为和三星的可以运行正常的
> > > > 
> > > > 
> > > > 你是根绝doc的唯一步骤，用toolkit创建的demo项目，然后在gradle里依赖weexsdk，编译跑起来的吗？
> > > > 我觉得实际开发情况大部分是，自家项目+ copy weexsdk源码（有bug自己可以部分修复/自定义扩展能力强）。在这种项目结构下，已经实行了多次替换升级。0.1=》0.18没问题，0.18=〉0.24/0.26就会遇到上面提到的两
> > > 
> > > 
> > > 是的，我就是从0.16.0=》0.26.0 升级失败所以重新装的工具重新创建的项目
> > 
> > 
> > “0.16.0=》0.26.0” 和 “升级失败所以重新装”，这两种操作有什么不一样吗？你们是Android还是IOS啊
> 
> aos和ios差不多。第一种升级方式是copy sdk源码+依赖文件，手动替换升级。第二种是根据一个非官方维护的cli工具，生成一个“weex”的项目结构，然后更改里面的sdk依赖版本

对的

**Comment by shenhuniurou** [comment]
> 我看他0.26.0版本修改的特征不是写的支持64位arm吗

目前只支持arm64-v8a，但是还不支持x86_64

**Comment by LwLuna** [comment]
> 
> 
> > 我看他0.26.0版本修改的特征不是写的支持64位arm吗
> 
> 目前只支持arm64-v8a，但是还不支持x86_64

是的

**Comment by LwLuna** [comment]
0.26.0版本你们有没有遇到过点击事件突然就不能用了，重新打开APP就又可以用了

**Comment by hechangpeng** [comment]
> 0.26.0版本你们有没有遇到过点击事件突然就不能用了，重新打开APP就又可以用了

不是不能用，而是新旧api不兼容。weex的源码新旧不兼容，导致插件js里面报错了，间接报了weex_js_connect.cpp server died，然后表现出来就是界面卡主了。。。

**Comment by LwLuna** [comment]
> 
> 
> > 0.26.0版本你们有没有遇到过点击事件突然就不能用了，重新打开APP就又可以用了
> 
> 不是不能用，而是新旧api不兼容。weex的源码新旧不兼容，导致插件js里面报错了，间接报了weex_js_connect.cpp server died，然后表现出来就是界面卡主了。。。

你怎么解决的这个问题

**Comment by hechangpeng** [comment]
> > > 0.26.0版本你们有没有遇到过点击事件突然就不能用了，重新打开APP就又可以用了
> > 
> > 
> > 不是不能用，而是新旧api不兼容。weex的源码新旧不兼容，导致插件js里面报错了，间接报了weex_js_connect.cpp server died，然后表现出来就是界面卡主了。。。
> 
> 你怎么解决的这个问题

改插件代码，让插件同事定位报错信息。或者你可以试试改改weex源码。

**Comment by hechangpeng** [comment]
> > > > 0.26.0版本你们有没有遇到过点击事件突然就不能用了，重新打开APP就又可以用了
> > > 
> > > 
> > > 不是不能用，而是新旧api不兼容。weex的源码新旧不兼容，导致插件js里面报错了，间接报了weex_js_connect.cpp server died，然后表现出来就是界面卡主了。。。
> > 
> > 
> > 你怎么解决的这个问题
> 
> 改插件代码，让插件同事定位报错信息。或者你可以试试改改weex源码。

**Comment by LwLuna** [comment]
> 
> 
> > > > 0.26.0版本你们有没有遇到过点击事件突然就不能用了，重新打开APP就又可以用了
> > > 
> > > 
> > > 不是不能用，而是新旧api不兼容。weex的源码新旧不兼容，导致插件js里面报错了，间接报了weex_js_connect.cpp server died，然后表现出来就是界面卡主了。。。
> > 
> > 
> > 你怎么解决的这个问题
> 
> 改插件代码，让插件同事定位报错信息。或者你可以试试改改weex源码。

你改的源码吗

**Comment by YorkShen** [comment]
@shenhuniurou 目前 Weex 有能力支持 x86-64(需要对CMakeList进行修改与适配)。目前我的工作重点不在这里，如果你需要的话，请在[邮件列表](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)中发起讨论，我会协助你进行 CMakeList 与PR的提交。

目前， Weex 0.28 已经发布，你也可以试试 Weex 0.28

**Comment by YorkShen** [comment]
@shenhuniurou 目前 Weex 有能力支持 x86-64(需要对CMakeList进行修改与适配)。目前我的工作重点不在这里，如果你需要的话，请在[邮件列表](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)中发起讨论，我会协助你进行 CMakeList 与PR的提交。

目前， Weex 0.28 已经发布，你也可以试试 Weex 0.28
