### ISSUE TITLE
weex 的indicator组件能不能设置宽高以及背景颜色

### ISSUE THREAD

**Issue by Hzhxi9** [apache/incubator-weex#2874]
weex 的indicator组件能不能设置宽高以及背景颜色

**Comment by zsmjhtn** [comment]
> indicator

直接设置一下属性看看效果咯...

**Comment by Hzhxi9** [comment]
不行 文档是只给出了颜色，选中的颜色以及指示点大小

**Comment by zsmjhtn** [comment]
> 不行 文档是只给出了颜色，选中的颜色以及指示点大小

那就改原生。自己在WXBaseCircleIndicator类里加一个设置背景色的方法。在WXIndicator的setHostLayoutParams里，你也可以控制帧布局的宽高。
都能改，改后添加到property，交由weex控制

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Weex's indicator component can set the width and height as well as the background color

You're welcomed to give a PR. Please remember that in Apache Community, the relationship between users and committers are not employer and employee.  Participant is always encouraged and you can be Apache committer if you make enough contribution.
