### ISSUE TITLE
[Android] Unexpected crash when app is in profiler started state where weex version is 0.26.2

### ISSUE THREAD

**Issue by thh0613** [apache/incubator-weex#2881]
## Describe the bug
My app is using weex sdk in source integration. We have used for half of year when the version is 0.21.0, but now we update  weex sdk version to 0.26.2. And when I want to monitor  the memory and cpu in android studio's profiler. The app is crashed. 

## To Reproduce
just open the profiler ,and open a weex page. 

## Environment

* Device: [android sumung galaxy s8 plus and huawei P20]
* Version [0.26.2]
* Build from source [ yes] 

## Additional context
when my app crashed, I just have little crash information:
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1f in tid 8314 (WeexJSBridgeThr)`

**Comment by YorkShen** [comment]
If the crash only happens during profile, it's probably because the profiler tools. There is nothing I can do with such tools.

**Comment by monkeycraps** [comment]
it seem to be cause by android studio 3.5 
i open debug mode, it crash too
```
    
    --------- beginning of crash
09-23 21:26:52.360 2677-2695/com.weex.app A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 2695 (WeexJSBridgeThr)
```
