### ISSUE TITLE
为什么Android 升级到weex0.26的时候，之前的项目里面的console.log日志再AndroidStudio打印不出来了

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#2888]

**Comment by wangxiongtao** [comment]
0.24的也不行

**Comment by snice** [comment]
需要用https://weex.apache.org/zh/docs/modules/console-log.html#switchloglevel

**Comment by zsmjhtn** [comment]
确定这demo能跑？
![image](https://user-images.githubusercontent.com/18029210/66987913-3138c000-f0f4-11e9-90be-f7c03ba9b8e7.png)
Safari，Chorme直接run就抛错，能不能再用点心维护

**Comment by YorkShen** [comment]
在这里，每个人都是无偿在为社区做贡献，请记住，你并没有付钱给我们。

I am sorry, but everyone here is doing this job for free, and you don't pay I or anyone else money, or do you?

**Comment by YorkShen** [comment]
I'd like to close the issue accroding to our [code of conduct](https://github.com/apache/incubator-weex/blob/master/CODE_OF_CONDUCT.md).

> Examples of unacceptable behavior by participants include:
> * Trolling, insulting/derogatory comments, and personal or political attacks
> * Public or private harassment

**Comment by YorkShen** [comment]
If you find something wrong, something unexpected, please describe your questions politely and try to figure it out by yourself.
