### ISSUE TITLE
[Android]  The cell/cell-slot in the list/recycle-list component of weex cannot be used with vue :is dynamic component usage, not in the list component is normal

### ISSUE THREAD

**Issue by Jackhu9018** [apache/incubator-weex#2893]
### The cell/cell-slot in the list/recycle-list component of weex cannot be used with vue :is dynamic component usage

The cell/cell-slot in the list/recycle-list component of weex cannot be used with vue :is dynamic component usage, while not in the list component is normal

## Environment
android 

## demo
```xml
<template>
    <list >
        <cell  v-for="(rowdata, i) in handleDataSet" :key="i"  >
            <div class="panel" >
                <text class="text">test{{rowdata.rowData.name}}</text>
            <lm-list-row-test
                            :list_data="rowdata">
            </lm-list-row-test>
                <component
                :is="lm-list-row-test"
                :list_data="rowdata">
                </component>
            </div>
        </cell>
    </list>
</template>
```
When i use <lm-list-row-test>, it was useful ,but when it change to <component :is="lm-list-row-test"> , it can't work well ,  i hope someone can explain this situation
###  dotwe address
http://editor.weex.io/p/Jackhu9018/test_is/commit/c99079b80e64209551c08fae36417767

**Comment by Hanks10100** [comment]
The `:is` property is equal with `v-bind:is` which takes a js variable as its value, not the string literal of component name.

Remove the `:` or binding it with a js variable can solve it.

```html
<component
  is="lm-list-row-test"
  list_data="rowdata">
</component>
```
