### ISSUE TITLE
[Android]点击事件0.26.0

### ISSUE THREAD

**Issue by LwLuna** [apache/incubator-weex#2895]
我用的0.26.0版本点击事件有时候会突然不能点击整个页面卡死，退出APP，在进去又可以了

**Comment by shenhuniurou** [comment]
> 我用的0.26.0版本点击事件有时候会突然不能点击整个页面卡死，退出APP，在进去又可以了

master分支已经解决这个bug了，你可以拉取master分支的代码自己打包sdk。

**Comment by LwLuna** [comment]
![图片](https://user-images.githubusercontent.com/52556048/64673535-01691d80-d4a1-11e9-916e-cf6aff5cae54.png)
官网的这个源码下下来重新生成SDK就可以了吗

**Comment by LwLuna** [comment]
> 
> 
> > 我用的0.26.0版本点击事件有时候会突然不能点击整个页面卡死，退出APP，在进去又可以了
> 
> master分支已经解决这个bug了，你可以拉取master分支的代码自己打包sdk。

https://user-images.githubusercontent.com/52556048/64673535-01691d80-d4a1-11e9-916e-cf6aff5cae54.png这个官网的下下来打包就可以了吗

**Comment by shenhuniurou** [comment]
> ![图片](https://user-images.githubusercontent.com/52556048/64673535-01691d80-d4a1-11e9-916e-cf6aff5cae54.png)
> 官网的这个源码下下来重新生成SDK就可以了吗

不是0.26的源代码，是master分支的代码。

**Comment by LwLuna** [comment]
> 
> 
> > ![图片](https://user-images.githubusercontent.com/52556048/64673535-01691d80-d4a1-11e9-916e-cf6aff5cae54.png)
> > 官网的这个源码下下来重新生成SDK就可以了吗
> 
> 不是0.26的源代码，是master分支的代码。

有没有打包好的分享一下啊

**Comment by fengmingye** [comment]
同问，有没有打好的包，我们自己打包so总算有不同机子的兼容问题导致页面白屏，create instance failed,errcode=-1001

**Comment by fengmingye** [comment]
同问，有没有打好的包，我们自己打包so总是有不同机子的兼容问题导致页面白屏，create instance failed,errcode=-1001

**Comment by YorkShen** [comment]
Try Weex 0.28, it just released a week ago.
