### ISSUE TITLE
support <flutter as render> & <jsCore engine>

### ISSUE THREAD

**Issue by tzh-goon** [apache/incubator-weex#2904]
support <flutter as render> & <jsCore engine>

**Comment by chenzefeng09** [comment]
flutter as render  +1 
new features are supposed discuss in the apache mailing list

**Comment by cubemoon** [comment]
flutter as render +1

**Comment by YorkShen** [comment]
Good idea, it would be great if you could discuss your proposal with detail in [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list).

If the `JSCore` you mentioned is `JavaScriptCore`, then yes, Weex is currently using it (JavaScriptCore of 2017).
