### ISSUE TITLE
[iOS] the default font-family in text component is different between iOS12 and iOS13

### ISSUE THREAD

**Issue by xuchao622** [apache/incubator-weex#2954]
when I use text component and don't set font-family, the default value is different between iOS12 and iOS13.
On iOS12, the default is Arial, and on iOS13, is Times New Roman

**Comment by zhangyanan151** [comment]
I have the same problem. Here's a screenshot of ios13.1.2, and this default font-family is different of  other ios's version 
![181570506223_ pic_hd](https://user-images.githubusercontent.com/16643246/66472468-e26da380-eabf-11e9-8bb9-e012cb87d971.jpg)

**Comment by shenhuniurou** [comment]
[https://github.com/apache/incubator-weex/pull/2936](https://github.com/apache/incubator-weex/pull/2936)

**Comment by Joy-Wang** [comment]
the same thing

**Comment by YorkShen** [comment]
Ref #2936, thanks
