### ISSUE TITLE
[Android] weex version 0.24.0

### ISSUE THREAD

**Issue by XMWP** [apache/incubator-weex#2961]
weex version 0.18版本SDK就不会报错正常显示，升级weex version 0.24.0 GCanvas报错，效果也显示不出来！报错/weex: WXComponentFactory Exception type:[gcanvas] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/taobao/weex/dom/WXDomObject;

**Comment by zsmjhtn** [comment]
0.24 已经删除WXDomObject这个类了

**Comment by XMWP** [comment]
> 0.24已经删除WXDomObject这个类了

这类已经删除了，那是否代表0.24版本用不了gcanvas这个插件了呢？因为gcanvas一用就报错也显示不出应有的功能效果！

**Comment by XMWP** [comment]
> 0.24 已经删除WXDomObject这个类了
因为我要用gcanvas做一个类似于折线图的效果，现在在0.24版本线是显示不出来的，是否0.24版本有其他插件可以实现这类似的效果么？0.18版本gcanvas没有问题可以达到先过，可是版本过低其他功能又实用不了。。。

**Comment by zsmjhtn** [comment]
> > 0.24 已经删除WXDomObject这个类了
> > 因为我要用gcanvas做一个类似于折线图的效果，现在在0.24版本线是显示不出来的，是否0.24版本有其他插件可以实现这类似的效果么？0.18版本gcanvas没有问题可以达到先过，可是版本过低其他功能又实用不了。。。

看了下gcanvas 2019年的修改，只是修改一些bug/so/编译的问题，没有针对WXDomObject相关的修改。你要自己改下 WXComponentFactory 了

**Comment by XMWP** [comment]
> > > 0.24 已经删除WXDomObject这个类了
> > > 因为我要用gcanvas做一个类似于折线图的效果，现在在0.24版本线是显示不出来的，是否0.24版本有其他插件可以实现这类似的效果么？0.18版本gcanvas没有问题可以达到先过，可是版本过低其他功能又实用不了。。。
> 
> 看了下gcanvas 2019年的修改，只是修改一些bug/so/编译的问题，没有针对WXDomObject相关的修改。你要自己改下 WXComponentFactory 了
如何修改呢？WXComponentFactory - -不会修改

**Comment by snice** [comment]
see [GCanvas#43](https://github.com/alibaba/GCanvas/issues/43)
