### ISSUE TITLE
[iOS] There is different behavior when use default font between IOS12 and IOS13 where weex version is 0.17

### ISSUE THREAD

**Issue by Joy-Wang** [apache/incubator-weex#2962]
I have not set font-family, It‘s different in default font when upgraded to IOS 13, and font-weight and font-style is invalid.
![image](https://user-images.githubusercontent.com/16829479/66693557-c6931900-ecdc-11e9-95cd-00dd2e43fba3.png)
![image](https://user-images.githubusercontent.com/16829479/66693590-2984b000-ecdd-11e9-965c-313d81fd05db.png)

**Comment by snice** [comment]
Please read [#2936](https://github.com/apache/incubator-weex/pull/2936)
