### ISSUE TITLE
Curiosity how do u develop project by using V0.26/0.24?

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex#2972]
First: console.log in Js is in vain. 
Weex throw error is so obscure that I can only depend on Console.log for finding bugs.Now it useless, i can not understand the change of  Console.

Second: Error log is so chaos。
Even a little Js errors，u can see a lot of useless logs。Example

```java
2019-10-17 15:47:10.646 26175-26201/com.ifaex_aos E/WeexCore: script_side_in_multi_process.cpp:314,futex lock pi failed: No such process, 80006682 26201 (0 0 0 80006682)
2019-10-17 15:47:10.647 26175-26201/com.ifaex_aos E/WXBridge: reportServerCrash instanceId:1 crashFile: /crash_dump.log
2019-10-17 15:47:10.647 26175-26201/com.ifaex_aos E/WXParams: getCrashFilePath:/data/user/0/com.ifaex_aos/app_crash
2019-10-17 15:47:10.647 26175-26201/com.ifaex_aos D/jsengine: callReportCrashReloadPage crashFile:/data/user/0/com.ifaex_aos/app_crash/crash_dump.log
2019-10-17 15:47:10.664 26175-26201/com.ifaex_aos E/WeexCore: wx_bridge.cpp:1138,class Name is com/taobao/weex/bridge/WXBridge
2019-10-17 15:47:10.664 26175-26201/com.ifaex_aos E/WeexCore: WXBridge_jni.h:1198,Java_WXBridge_reset_clazz class Name is com/taobao/weex/bridge/WXBridge
2019-10-17 15:47:10.684 26175-26201/com.ifaex_aos W/weex: app AvailMemory ---->>>1634
2019-10-17 15:47:10.702 26175-26304/com.ifaex_aos D/ReportCrash:  commitJscCrashAlarmMonitor errMsg SIG: SIGSEGV (11), fault addr: 0x0
    maps:
    b73d4000-b73d5000 r-xp 00000000 fd:06 231600                             /data/app/com.ifaex_aos-Eypc1EKUSA-6G84DkfJYkQ==/lib/arm/libweexjsb.so
    b73d5000-b73d6000 r--p 00000000 fd:06 231600                             /data/app/com.ifaex_aos-Eypc1EKUSA-6G84DkfJYkQ==/lib/arm/libweexjsb.so
    b73d6000-b73d7000 rw-p 00000000 00:00 0 
    ea700000-eac00000 rw-p 00000000 00:00 0                                  [anon:libc_malloc]
    eac15000-eac16000 ---p 00000000 00:00 0                                  [anon:thread stack guard page]
    eac16000-ead12000 rw-p 00000000 00:00 0 
    ead12000-ead13000 ---p 00000000 00:00 0                                  [anon:thread stack guard page]
    ead13000-eae0f000 rw-p 00000000 00:00 0 
    eae0f000-eae10000 ---p 00000000 00:00 0                                  [anon:thread stack guard page]
    eae10000-eaf0c000 rw-p 00000000 00:00 0 
    eaf0c000-eaf0d000 ---p 00000000 00:00 0                                  [anon:thread stack guard page]
    eaf0d000-eb009000 rw-p 00000000 00:00 0 
    eb009000-eb00a000 ---p 00000000 00:00 0                                  [anon:thread stack guard page]
    eb00a000-eb106000 rw-p 00000000 00:00 0 
    eb106000-eb107000 ---p 00000000 00:00 0                                  [anon:thread stack guard page]
    eb107000-eb203000 rw-p 00000000 00:00 0 
    eb203000-eb204000 ---p 00000000 00:00 0                                  [anon:thread stack guard page]
    eb204000-eb300000 rw-p 00000000 00:00 0 
    eb300000-eb680000 rw-p 00000000 00:00 0 
```
Maybe the reason is the error using/import of:
```javascript
onst logModule = weex.requireModule('sdk-console-log')
	const toastModule = weex.requireModule('modal')
......
..... invoke above code....
```
When I delete those  relativition code, the chaos errors is dismiss.
Through chaos logs , I don not what error happen to me and how to solve it.

I confirm  weex_group  take great pains on this project.
But the new version is more  difficult to use , compare to early version。

**Comment by YorkShen** [comment]
I'd suggest you verify whether it works on branch `release/0.28` and you can build binary from source. If everything works well on `release/0.28`, then perhaps you can wait for that version.

As for the log you printed, it's a Linux SIGSEGV error. There is very little things we could do to make Linux SIGSEGV error more clear.

**Comment by snice** [comment]
Now, console.log need switch, please see [console-log](https://weex.apache.org/docs/modules/console-log.html)

**Comment by zsmjhtn** [comment]
> Now, console.log need switch, please see [console-log](https://weex.apache.org/docs/modules/console-log.html)

The web Demo throws: Failed to compile current project!
Can u fix the error?

**Comment by zsmjhtn** [comment]
> I'd suggest you verify whether it works on branch `release/0.28` and you can build binary from source. If everything works well on `release/0.28`, then perhaps you can wait for that version.
> 
> As for the log you printed, it's a Linux SIGSEGV error. There is very little things we could do to make Linux SIGSEGV error more clear.

When i develop my project, i can not mark mine error through  console log.
I hava to annotate code step by step, and rebuild weex bundle for confirm  it works correctly.
For example, i use  "let bus = new Vue()" as   EventBus for Weex-Vue-Template, and it works right in V0.18.
In V0.26, the same Weex-page throw chaos error, When i annotate the code of inject "$bus = new Vue()", Weex-page render successfully.
The log have little message about Vue, only tell the weex_js_xxxx  died/error/xxxx

It is to hard to find where the bug is.

I  remeber the error log about Vue  in .we file(the old weex version)，Console log  is clearly both in compile-file and run-weex-bundle.

I will try more with new version, even if  looks like first meet with Weex.😢

**Comment by zsmjhtn** [comment]
> Now, console.log need switch, please see [console-log](https://weex.apache.org/docs/modules/console-log.html)

 It really works. BTW, How can i use console.log() in V0.26 ? I can only read the weex-self log, without my customize  log

**Comment by YorkShen** [comment]
Thanks all. Let me explain something. 

`Console.log()` is disable by default as it has a very bad performce impact. One can use it by enabling debug level in [console-log](https://weex.apache.org/docs/modules/console-log.html).

@zsmjhtn Could you please write a document for Weex, so that other developers won't suffer from it anymore.

**Comment by zsmjhtn** [comment]
It works all right。只是print log方式有点“变化”
安卓0.28 Js log 是在独立进程打印的。
IDE 搜索log时，需要注意filter规则，不能选 show only selected application。要选择 NO filters
这样就能找到Js log
