### ISSUE TITLE
[Android] Unsupported localeCompare in chinese

### ISSUE THREAD

**Issue by ArrayDC** [apache/incubator-weex#2980]
string sort in chinese as follows:
` 
    var arr = ['南京', '北京', '上海', '杭州', '深圳'];
    arr = arr.sort(function(item1, item2) {
        return item1.localeCompare(item2, 'zh-CN');
    });
    console.log(arr); //arr not change 
`

**Comment by YorkShen** [comment]
For Weex 0.28, It ues a stripped [JavaScript interpreter](https://www.npmjs.com/package/jsc-android/v/245459.0.0), some function may be stripped. You could change the JavaScript interpreter if you could or [check whether the extend arguement is supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Check_browser_support_for_extended_arguments) before you call it.
