### ISSUE TITLE
[Android]weex 0.20.3.0-beta版本以后使用Console.log打印日志再AndroidStudio打印不出来，是要做什么处理么

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#2986]

**Comment by zsmjhtn** [comment]
https://weex.apache.org/docs/modules/console-log.html

**Comment by wangxiongtao** [comment]
> https://weex.apache.org/docs/modules/console-log.html

<script>
  const logModule = weex.requireModule('sdk-console-log');
  const toastModule = weex.requireModule('modal')
  export default {
    name: "TestDemo",
    created() {
      logModule.switchLogLevel("all",  ()=> {
        toastModule.toast({ message: 'Success' })
        console.log("==weex==>>>>>>>>>>>>>")
      });

    }
  }
</script>

这么使用的么

**Comment by zsmjhtn** [comment]
> > https://weex.apache.org/docs/modules/console-log.html
> 
> <script> const logModule = weex.requireModule('sdk-console-log'); const toastModule = weex.requireModule('modal') export default { name: "TestDemo", created() { logModule.switchLogLevel("all", ()=> { toastModule.toast({ message: 'Success' }) console.log("==weex==>>>>>>>>>>>>>") }); } } </script>
> 这么使用的么

这module只能打出weex-log，我在想要怎么打出我自定义的log....

**Comment by wangxiongtao** [comment]
> > > https://weex.apache.org/docs/modules/console-log.html
> > 
> > 
> > <script> const logModule = weex.requireModule('sdk-console-log'); const toastModule = weex.requireModule('modal') export default { name: "TestDemo", created() { logModule.switchLogLevel("all", ()=> { toastModule.toast({ message: 'Success' }) console.log("==weex==>>>>>>>>>>>>>") }); } } </script>
> > 这么使用的么
> 
> 这module只能打出weex-log，我在想要怎么打出我自定义的log....

所以是不是要自定义一个log的module调用原生的log

**Comment by YorkShen** [comment]
Duplicate with #2972

**Comment by YorkShen** [comment]
@zsmjhtn 自定义的log是指什么。

**Comment by wmlgl** [comment]
需要加上这个
var logModule = weex.requireModule('sdk-console-log');
logModule.switchLogLevel("debug");

**Comment by YorkShen** [comment]
android的log级别分为v,d,i,w,e，这些log级别分别可以和console.verbose, console.debug 等映射。

然而console.log并无法映射到标准的android的log中

**Comment by shenhuniurou** [comment]
> 需要加上这个
> var logModule = weex.requireModule('sdk-console-log');
> logModule.switchLogLevel("debug");
> 
> 然后只能用console.info输出日志，console.log用不了，应该是bug

为什么我加上了还是无法打印出来

**Comment by YorkShen** [comment]
@shenhuniurou Please try Weex 0.28.

I just checked, it works fine.

**Comment by zsmjhtn** [comment]
it works fine. “console.debug” works fine.
安卓0.28 js log是打印在独立进程的。
IDE搜索log时，filter设置为 No Filters。即可看到log

**Comment by Ryan-Shz** [comment]
> it works fine. “console.debug” works fine.
> 安卓0.28 js log是打印在独立进程的。
> IDE搜索log时，filter设置为 No Filters。即可看到log

确实如此，这样其实不是很方便

**Comment by wangxiongtao** [comment]
> > it works fine. “console.debug” works fine.
> > 安卓0.28 js log是打印在独立进程的。
> > IDE搜索log时，filter设置为 No Filters。即可看到log
> 
> 确实如此，这样其实不是很方便

我已经再原生自己写了个module，调用原生的日志LogUtil来打印日志了
