### ISSUE TITLE
[Android] 升级0.26.0后 WXDomTask WXDomHandler没有找到类，应该怎么处理或者用什么方法替代？

### ISSUE THREAD

**Issue by caikaitao** [apache/incubator-weex#2991]

**Comment by YorkShen** [comment]
1. Read the [document](https://weex.apache.org/zh/guide/extend/extend-android.html#component-%E6%89%A9%E5%B1%95)
2. 2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8).
