### ISSUE TITLE
Unexpected behavior when Android where weex version is 0.28.0 java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path

### ISSUE THREAD

**Issue by xcyoung** [apache/incubator-weex#2993]
When weex upgrades to 0.28, the initialization prints out the stack.
![image](https://user-images.githubusercontent.com/32295159/67914632-a6fc5b80-fbcb-11e9-8d61-877be76605d3.png)
The package build without proguard，the page of weex can load normally，but build with proguard, page can not load and show weex uninitialized exception.Occasionally crashes during initialization！！！

**Comment by YorkShen** [comment]
The screenshot you provided is just a warning, and we intend to remove it in the future.

As for progurad, there is a proguard file in sdk.aar or sdk_legacy.aar, please checkout whether the proguard file take effects.

If this still bothers you and you find a solution, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8).

**Comment by limingwei** [comment]
+1 也遇到这个问题
