### ISSUE TITLE
[Android]Unexpected crash behavior when update to  weex version  0.28.0, the log shows that couldn't find "libc++_shared.so" caught  the crash

### ISSUE THREAD

**Issue by Jackhu9018** [apache/incubator-weex#3006]

**Comment by YorkShen** [comment]
As it's said in the [documentation](https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html), Weex only supports `x86`, `armeabi-v7a` and `arm64-v8a`. No `armeabi` support.

**Comment by Jackhu9018** [comment]
So , what can i do to deal with armabi ?  The previous  version has no problem

**Comment by Jackhu9018** [comment]
> As it's said in the [documentation](https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html), Weex only supports `x86`, `armeabi-v7a` and `arm64-v8a`. No `armeabi` support.

So , what can i do to deal with armabi ? The previous version has no problem

**Comment by YorkShen** [comment]
Yes, from 0.28, armabi is not supported any more, as Google depracted and stopped the support for `armeabi`. There is nothing we can do here.

**Comment by Jackhu9018** [comment]
> Yes, from 0.28, `armabi` is not supported any more, as Google depracted and stopped the support for `armeabi`. There is nothing we can do here.

Is there any compatibility scheme ?  I want to update , but this problem have to be settled

**Comment by YorkShen** [comment]
1. Weex will not provide `armeabi` considering Google's insturction.
2. You could copy files from `armeabi-v7` of `weex` to your app's `lib/armeabi`. This may work, you could give it a try.

**Comment by Jackhu9018** [comment]
> 1. Weex will not provide `armeabi` considering Google's insturction.
> 2. You could copy files from `armeabi-v7` of `weex` to your app's `lib/armeabi`. This may work, you could give it a try.

Thanks, i will try it

**Comment by YorkShen** [comment]
Also remember copy the JavaScript Interpreter to `lib/armeabi`.

`https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle` doesn't support `armeabi`, either.

**Comment by Jackhu9018** [comment]
> Also remember copy the JavaScript interpreter to `lib/armeabi`.
> 
> `https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle` doesn't support `armeabi`, either.

Just now, i have tried several times , 
1.First , i build a new jni directory in jniLibs .
2.Next , i copy the so file to the directory , contains armeabi-v7 files in sdk and libjsc.so file ,
  but in the buid process, it was deleted automatic , it was the jsc script that worked ?  So i can't 
  continue it , i don't know what todo now

**Comment by Jackhu9018** [comment]
> > Also remember copy the JavaScript interpreter to `lib/armeabi`.
> > `https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle` doesn't support `armeabi`, either.
> 
> Just now, i have tried several times ,
> 1.First , i build a new jni directory in jniLibs .
> 2.Next , i copy the so file to the directory , contains armeabi-v7 files in sdk and libjsc.so file ,
> but in the buid process, it was deleted automatic , it was the jsc script that worked ? So i can't
> continue it , i don't know what todo now

And the ndk config also the "ndk {
            abiFilters "x86"
            abiFilters "armeabi"
        }"

**Comment by YorkShen** [comment]
**Don't add `apply from https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle`**.

Just copy all the so(jsc.so and weex related so) files to `libs/armeabi`.

FYI: I am sure about `compile org.apache.weex:sdk:0.28` will not cause deleting your files. You might figure out yourself.

**Comment by Jackhu9018** [comment]
> **Don't add `apply from https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle`**.
> 
> Just copy all the so(jsc.so and weex related so) files to `libs/armeabi`.
> 
> FYI: I am sure about `compile org.apache.weex:sdk:0.28` will not cause deleting your files. You might figure out yourself.

OK, i will have a try , thanks very much !

**Comment by Jackhu9018** [comment]
> **Don't add `apply from https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle`**.
> 
> Just copy all the so(jsc.so and weex related so) files to `libs/armeabi`.
> 
> FYI: I am sure about `compile org.apache.weex:sdk:0.28` will not cause deleting your files. You might figure out yourself.

I have tried yesterday and it works well

**Comment by hponiang** [comment]
![image](https://user-images.githubusercontent.com/8768585/69390551-8e82eb00-0d0a-11ea-9956-a11fd77da198.png)
Please check if your jnilibs configuration is normal

**Comment by FightingForDevelop** [comment]
> **Don't add `apply from https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle`**.
> 
> Just copy all the so(jsc.so and weex related so) files to `libs/armeabi`.
> 
> FYI: I am sure about `compile org.apache.weex:sdk:0.28` will not cause deleting your files. You might figure out yourself.

Hi,I have a similar error."java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[[zip file "/data/app/com.zhaopin.ihr-QAevaKfoDUkl0I0jJ00_0w==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhaopin.ihr-QAevaKfoDUkl0I0jJ00_0w==/lib/arm, /data/app/com.***-QAevaKfoDUkl0I0jJ00_0w==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]",
dependencies just like this:
    //bindingX
    implementation 'com.alibaba.android:bindingx-core:1.0.1'
    implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.1'
   //weex
api 'org.apache.weex:sdk_legacy:0.28.0'

Please tell me how to resolve it.
