### ISSUE TITLE
[Android]degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1 升级到0.28加载以前的weex页面报错，这是so文件配置不对么

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#3007]

**Comment by wangxiongtao** [comment]
onRenderError -1001,degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

**Comment by YorkShen** [comment]
1. There is nothing we can do with such little information.
2. Maybe you could give it a try https://github.com/apache/incubator-weex/issues/3006
