### ISSUE TITLE
[Android]JS运算效率问题

### ISSUE THREAD

**Issue by st-dc** [apache/incubator-weex#3008]
测试发现 weex 0.21.0版本执行加密JS运算需要大概100毫秒左右的时间。相同代码在0.26.0版本就变为300毫秒左右了。
http://editor.weex.io/compiled/833c2884882a03f33aba35b92fd4bbac/bundle.weex.js 这是示例js 运行点击test按钮。

**Comment by YorkShen** [comment]
This dependends on the JavaScript Interpreter itselft, there is nothing we can do.

In Weex 0.28, you are free to use whatever JavaScript Interpreter you like, it's unbundled from Apache Weex for good.
