### ISSUE TITLE
[Android]代码如下，横向布局拼接时，2个view中间会有一条缝隙。

### ISSUE THREAD

**Issue by xiongtingjin** [apache/incubator-weex#3010]
<template>
  <div class="wrapper">
    <div class="c1">
      <div class="d1">111</div>
    </div>
    
    <div class="c1">
      <div class="d1">111</div>
    </div>
    
    <div class="c1">
      <div class="d1">111</div>
    </div>
    
    <div class="c1">
      <div class="d1">111</div>
    </div>
    
    <div class="c1">
      <div class="d1">111</div>
    </div>
 
  </div>
</template>
<style scoped>
  .wrapper {
    height:60px;
    flex-direction: row;
    background-color:#ff0000;
  }
  .c1 {
    height:60px;
    flex-direction: row;
    background-color:#ff00ff;
  }
  .d1 {
    width: 120px;
    height:60px;
    background-color:#0000ff;
  }
</style>

如图显示：
![TIM截图20191107104116](https://user-images.githubusercontent.com/18025569/68355750-2dc0b380-014b-11ea-8bf3-8ad75ecf4fb8.png)

**Comment by YorkShen** [comment]
The inaccuracy is caused by `float to int` conversion, there is nothing we can do now.
