### ISSUE TITLE
[Android] Open weex page white screen where weex version is 0.28.0

### ISSUE THREAD

**Issue by bobSir** [apache/incubator-weex#3013]
![image](https://user-images.githubusercontent.com/16300254/68729152-25152500-0604-11ea-8f9e-db1e1c25dccd.png)
![image](https://user-images.githubusercontent.com/16300254/68729170-32321400-0604-11ea-898e-2323b4d8c07b.png)

E/weex: onRenderError -1001,degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

Very frequently encountered after the upgrade。
If you have time, take a look。ths

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/68737943-e68d6380-061f-11ea-8a20-e2d523f3ba59.png)

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/68739707-6c131280-0624-11ea-8b32-a5195f17fe08.png)

**Comment by YorkShen** [comment]
Please don't use `armeabi` anymore, Google stopped supporting it years ago.

Weex only [supports `armeabi-v7a`, `arm64-v8a` and `x86`](https://weex.apache.org/guide/develop/integrate-to-android-app.html) and we don't test API on `armeabi` anymore. If there is a confusion about what Weex supports and what don't, you could give us a PR to make the documentation better.

**Comment by bobSir** [comment]
Because we are the service provider, Party A wants armeabi. Now I am replacing v7a with armeabi
,Do you have any suggestions? ths

**Comment by YorkShen** [comment]
Maybe you could help us improve the document. I see some pepole complains the error you met, and a document improvement may solve the problems for future users of Weex.

**Comment by bobSir** [comment]
First of all, I have to solve this problem in order to supplement the documentation to help people who have encountered such problems. Now, I don't know how to solve them. Can you give me some advice?

**Comment by YorkShen** [comment]
Have you tried `armeabi-v7a`?

The current NDK 18 Weex using doesn't support `armeabi`, and I can't make Google to support `armeabi` in the furture release of NDK.

**Comment by bobSir** [comment]
All right, I am testing with armeabi-v7a now. I have to replace armeabi with armeabi-v7a, which may be difficult to advance.

**Comment by bobSir** [comment]
I can compile armeabi using your source code, but the new jsc does not provide armeabi so, [https://registry.npmjs.org/jsc-android/-/jsc-android-241213.1.0.tgz], so you know Where can I find armeabi libjsc.so?

**Comment by bobSir** [comment]
I still have a question. Is there any difference between the android-jsc file provided by jsc-android and the android-jsc-intl file? Why is their libjsc.so volume difference? I am using android-jsc libjsc.so to replace android-jsc-intl libjsc.so will have problems? I thought that one of them was a normal version and the other was an international version.

**Comment by YorkShen** [comment]
* `android-jsc-intl` contains ICU, which support various language, like Russian, Greek, or other language you may heard.
* `android-jsc` doesn't have that kinds of language support.

For `armeabi` of jsc-android, there is nothing I can do. I think as Google stopped supporting `armeabi`, libraries in Android wil not provide it either, as time goes.

**Comment by bobSir** [comment]
If you see this and have students who have the same problem. This may be the only way to switch to armeabi-v7a. If any of the students have a good solution, share it, thank you.

**Comment by bobSir** [comment]
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@46e6539
 E/weex: tryUseRunTimeApi ? false
E/WXParams: setCrashFilePath: /data/user/0/com.fund.weex.fundandroidweex/app_crash
E/weex: weexjss's Path is/data/app/com.fund.weex.fundandroidweex-Lmd-9iQybVplTgLxkyw2oA==/lib/arm/libweexjss.so
E/weex: jsc's Path is/data/app/com.fund.weex.fundandroidweex-Lmd-9iQybVplTgLxkyw2oA==/lib/arm/libjsc.so
E/weex: findLibJscRealPath /data/app/com.fund.weex.fundandroidweex-Lmd-9iQybVplTgLxkyw2oA==/lib/arm/libjsc.so
E/weex: enableAlarmSignal:true
E/weex: getUseSingleProcess is running false
E/WeexCore: params_utils.cpp:197,g_use_single_process is false 
E/weex: getLibJscPath is running /data/app/com.fund.weex.fundandroidweex-Lmd-9iQybVplTgLxkyw2oA==/lib/arm
E/WeexCore: params_utils.cpp:232,g_jscSoPath is /data/app/com.fund.weex.fundandroidweex-Lmd-9iQybVplTgLxkyw2oA==/lib/arm 
E/weex: getLibJssPath is running /data/app/com.fund.weex.fundandroidweex-Lmd-9iQybVplTgLxkyw2oA==/lib/arm/libweexjss.so
E/WeexCore: params_utils.cpp:245,g_jssSoPath is /data/app/com.fund.weex.fundandroidweex-Lmd-9iQybVplTgLxkyw2oA==/lib/arm/libweexjss.so 
E/WXParams: getCrashFilePath:/data/user/0/com.fund.weex.fundandroidweex/app_crash
E/WeexCore: params_utils.cpp:257,g_crashFilePath is /data/user/0/com.fund.weex.fundandroidweex/app_crash 
E/weex: getLibIcuPath is running /system/usr/icu/icudt60l.dat
E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
E/WeexCore: params_utils.cpp:270,g_jssIcuPath is /system/usr/icu/icudt60l.dat 
E/weex: getLibJsbPath is running /data/data/com.fund.weex.fundandroidweex/cache/weex/libs/weexjsb/armeabi-v7a/libweexjsb.so
E/WeexCore: setDebugMode  2 
E/libc: Access denied finding property "net.dns1"
E/WeexCore: multi_process_and_so_initializer.cpp:38,MultiProcessAndSoInitializer IS IN init
E/WeexCore: weex_js_connection.cpp:140,WeexJSConnection g_crashFileName: /data/user/0/com.fund.weex.fundandroidweex/app_crash/crash_dump.log
E/[HOTFIX]: [ThreadDexHotfixMonitor]Bind hotfix monitor service fail!
E/fundandroidwee: Invalid ID 0x00000000.
E/weex: idle from create instance cache size is 0
E/weex: onRenderError -1001,degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
E/WeexCore: weex_js_connection.cpp:288,WeexJSConnection catch: spinWaitPeer timeout
E/WeexCore: weex_js_connection.cpp:183,IPCException server died spinWaitPeer timeout
E/WeexCore: multi_process_and_so_initializer.cpp:47,JSFramwork init start sender is null
E/WeexCore: weex_js_connection.cpp:140,WeexJSConnection g_crashFileName: /data/user/0/com.fund.weex.fundandroidweex/app_crash/crash_dump.lo
E/WeexCore: weex_js_connection.cpp:252,startupPie :1
E/weex: initFrameWorkCount :1
E/weex: PerformanceData 
E/memtrack: Couldn't load memtrack module
E/memtrack: Couldn't load memtrack module
 E/weex: PerformanceData 
E/memtrack: Couldn't load memtrack module
E/memtrack: Couldn't load memtrack module

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/68834361-9205e900-06f0-11ea-9b7c-8e8fb3b679f7.png)
![image](https://user-images.githubusercontent.com/16300254/68834386-9d591480-06f0-11ea-8723-0a685a680078.png)

**Comment by bobSir** [comment]
I changed to armeabi-v7a, but still reported the same error, you should check it out.

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/68835885-0b530b00-06f4-11ea-86b2-d37c131e10bb.png)

**Comment by YorkShen** [comment]
It worked fine in Playground, could please provide more infromation.

It seems to me there is a crash and the crash file is printed in the logcat. Maybe you could share the crash file.

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69226865-dcd5a400-0bbb-11ea-8ab6-947cb64f355d.png)
size ==0  the log is empty!

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69227176-65544480-0bbc-11ea-8248-21427087a310.png)

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69227412-b8c69280-0bbc-11ea-83d1-57910879b7d6.png)

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69227463-cb40cc00-0bbc-11ea-80f3-05161f5daee7.png)

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69227745-53bf6c80-0bbd-11ea-92c6-f2a77cac1115.png)

**Comment by bobSir** [comment]
This looks like weexSdkInstance failed to initialize. Is this problem difficult to locate?

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69236770-3bf0e400-0bcf-11ea-8126-f866cb6d38ba.png)
Just output this information

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69237250-3516a100-0bd0-11ea-9d40-157ec6e33740.png)
I compared the versions of 26 and 28. Why did the instance initialization on the 28 version comment this line of code?

**Comment by bobSir** [comment]
I let go of this line of code and it didn't work.
if you have time please checkout。ths

**Comment by bobSir** [comment]
in WxBridgeManager initFramework() method:
![image](https://user-images.githubusercontent.com/16300254/69300865-65e9eb00-0c4f-11ea-8dfa-58f269b27ab7.png)
![image](https://user-images.githubusercontent.com/16300254/69300944-9af63d80-0c4f-11ea-95e1-3e64b4e822b5.png)

I found the problem, the framework initialization is sometimes very slow, my test found that sometimes it takes 40 seconds to initialize. It seems that you have not tested well with the new jsc.

**Comment by YorkShen** [comment]
> I found the problem, the framework initialization is sometimes very slow, my test found that sometimes it takes 40 seconds to initialize. It seems that you have not tested well with the new jsc.

It tooks 40 seconds to execute `nativeInitFrameworkEnv` ? That never happened in my phone, or CI environment. Does it happen in a certain phone, or any phone you have? Could you please provide more detail, like the OS version, phone name, etc.?

**Comment by bobSir** [comment]
I have reproduced on many mobile phones, Huawei p20, xiaomi MIX2, Samsung s8 plus, Huawei p30... The phones I have on hand have been reproduced. The probability of recurring on MIX2 is relatively large.

**Comment by bobSir** [comment]
![image](https://user-images.githubusercontent.com/16300254/69320569-62b92400-0c7c-11ea-8440-243ca5154ecd.png)
Is this call to the jsc api or the weexCore api?

**Comment by CoralXss** [comment]
> Please don't use `armeabi` anymore, Google stopped supporting it years ago.
> 
> Weex only [supports `armeabi-v7a`, `arm64-v8a` and `x86`](https://weex.apache.org/guide/develop/integrate-to-android-app.html) and we don't test Weex on `armeabi` anymore. If there is a confusion about what Weex ABI supports and what don't, you could give us a PR to make the documentation better.

I have the same problem. Is this starting from Weex v0.20 ?

**Comment by bobSir** [comment]
> > Please don't use `armeabi` anymore, Google stopped supporting it years ago.
> > Weex only [supports `armeabi-v7a`, `arm64-v8a` and `x86`](https://weex.apache.org/guide/develop/integrate-to-android-app.html) and we don't test Weex on `armeabi` anymore. If there is a confusion about what Weex ABI supports and what don't, you could give us a PR to make the documentation better.
> 
> I have the same problem. Is this starting from Weex v0.20 ?

I met after 0.28.0, replacing the new jsCore from 0.28.0 weex sdk.

**Comment by YorkShen** [comment]
> ![image](https://user-images.githubusercontent.com/16300254/69320569-62b92400-0c7c-11ea-8440-243ca5154ecd.png)
> Is this call to the jsc api or the weexCore api?

It will invoke a [C++ API](https://github.com/apache/incubator-weex/blob/master/weex_core/Source/android/wrap/wx_bridge.cpp#L331) in WeexCore, and you can view all the C++/Java binding in this  [file](https://github.com/apache/incubator-weex/blob/master/weex_core/Source/base/android/jniprebuild/jniheader/WXBridge_jni.h).

FYI: Have you tried the [Weex Playground](https://github.com/apache/incubator-weex-playground/), which also uses the new JSC. I think there may be a configuration problem in your app with the new JSC.

**Comment by YorkShen** [comment]
If the suggestion I gave is helpful, please upgrade the current documentation so that we could help more users.

**Comment by hponiang** [comment]
确实是libjsc.so的问题，可以对比一下 playground 的libjsc.so位置

**Comment by bobSir** [comment]
> If the suggestion I gave above is helpful, please upgrade the current documentation so that we could help more users.

![image](https://user-images.githubusercontent.com/16300254/69395923-9bf4a100-0d1b-11ea-835f-485a31c481d3.png)
![image](https://user-images.githubusercontent.com/16300254/69395940-aa42bd00-0d1b-11ea-8319-cb74716d6865.png)
As you can see, the framework init takes about 40 seconds.

**Comment by YorkShen** [comment]
@bobSir Does Weex Playground have the same problem on your phone?

**Comment by fund-iconfont** [comment]
I'm in the same corp. with bobSir, and I found something strange. In `multi_process_and_so_initializer.cpp` with function `Init`， the code has jumped into the case 
`if (sender == nullptr)` and throws the Exception `IPCException server died spinWaitPeer timeout` 
and `WeexJSConnection catch: spinWaitPeer timeout`。 

Expecting  to give some advice to us. Thanks any way.

**Comment by YorkShen** [comment]
Maybe you should have a look at  https://github.com/apache/incubator-weex/issues/3030

**Comment by bobSir** [comment]
I solved this problem temporarily, and I found that some time-consuming operations in my application may block the initialization of jsFrameWork. My current approach is to listen for the time-consuming operations after the jsFrameWork initialization is complete.
But the same operation before 0.28.0, the initialization of jsFrameWork is normal. Maybe what weex can do?
If a classmate encounters the same problem as me, you can refer to my approach.

**Comment by YorkShen** [comment]
> But the same operation before 0.28.0, the initialization of jsFrameWork is normal. Maybe what weex can do?

If you suspect this is the problem of the new JSC, you can build Weex from source together with the legacy JSC. For detail of the build comand, you can look at the [travis command line](https://github.com/apache/incubator-weex/blob/master/.travis.yml#L141)

Anyway, I will just close it. Feel free to contact me if there are any other problems.

**Comment by SkunkBoy** [comment]
![Uploading image.png…]()
