### ISSUE TITLE
[iOS][WeexSDK] iconfont can not showed as expected where weex version is 0.26.0

### ISSUE THREAD

**Issue by amiacoder** [apache/incubator-weex#3014]
Loading two iconfont ttf files at the same time, the fonts in one font library are not displayed, and are normal on the browser.

this is the test dotwe address
http://dotwe.org/vue/f378cb6fecaff54b6951326e4a2002a2

## Environment
* Device: [e.g. iPhone X]
* OS: [e.g. iOS13.1]
* Version [e.g. 0.26.0]
* Build from source [e.g. yes]

**Comment by Jackhu9018** [comment]
It seems  normal in the payground .

**Comment by amiacoder** [comment]
> It seems normal in the payground .

this is browser
![image](https://user-images.githubusercontent.com/5467305/68844635-106c8600-0705-11ea-8244-5b18971973d6.png)

and this is weex playground

![image](https://user-images.githubusercontent.com/5467305/68844722-342fcc00-0705-11ea-9571-b43873748f22.png)

**Comment by amiacoder** [comment]
Is there anybody can help me?

**Comment by YorkShen** [comment]
@jianhan-he Have a look?

**Comment by jianhan-he** [comment]
@amiacoder Weex on iOS dont support iconfont. If you want to use iconfont that you can add attribute "coretext=false" on text tag. like as: <text class="title3" coretext=false>http woff: &#xe7cb;</text>

**Comment by jianhan-he** [comment]
@amiacoder You should never use iconfont as family-name. Can you try change another family-name?

**Comment by amiacoder** [comment]
> @amiacoder Weex on iOS dont support iconfont. If you want to use iconfont that you can add attribute "coretext=false" on text tag. Like as

you are right! thx

**Comment by YorkShen** [comment]
The issue seems like solved, I'd like to close it.

Feel free to open a new one if there is other problem.
