### ISSUE TITLE
[Android] recycle-list在使用子组件时卡顿掉帧

### ISSUE THREAD

**Issue by e020120** [apache/incubator-weex#3015]
## Describe the bug

用定义子组件模板的方式使用recycle-list组件，在安卓机型上滚动列表出现卡顿掉帧
## To Reproduce

扫描下面这个weex官方代码示例即可
代码地址：[http://dotwe.org/vue/da72c9150ce2f8bc41bc6ffbf8475fbc](http://dotwe.org/vue/da72c9150ce2f8bc41bc6ffbf8475fbc)（安卓扫这个，苹果没问题）
## Environment

设备：大部分安卓机型
系统：安卓6+
Weex Playground版本：最新版
WeexSDK：0.26，0.28

## Expected behavior

期望能正常在安卓上用定义子组件模板的方式使用recycle-list组件

## Screenshots

![](https://s2.ax1x.com/2019/11/13/MYFOHS.jpg)
![](https://s2.ax1x.com/2019/11/13/MYFjAg.jpg)

## Additional context

之前也有别人遇到过同样的问题，他的issue地址：
https://github.com/apache/incubator-weex/issues/2805

**Comment by YorkShen** [comment]
Try use the release version, not debug version.

The android debug API have serious performance punishement on Weex.

**Comment by e020120** [comment]
> Try use the release version, not debug version.
> 
> The android debug API have serious performance punishement on Weex.

Thanks for your help!
I builded an APP for Android, It's no problem.

**Comment by yjouyang** [comment]
I've tried to run the release version apk, it didn't help. Scrolling a <recycle-list> is so slow

**Comment by yjouyang** [comment]
Android 9.0 and weex version 0.28
