### ISSUE TITLE
weex如何实现这样的文字布局？

### ISSUE THREAD

**Issue by huanghaodong** [apache/incubator-weex#3016]
![image](https://user-images.githubusercontent.com/24872469/68818836-4a1b9d80-06c1-11ea-9752-8b989e8a5118.png)

**Comment by e020120** [comment]
<div>
<text style="position: absolute;left: 0;">个人简历：</text>
<text>{{space}}{{content}}</text>
</div>

个人简历用定位，说明部分内容前面用空格填充，好像用text组件默认会去掉首尾空白，所以建议用变量的方式

**Comment by YorkShen** [comment]
[Richtext](https://weex.apache.org/docs/components/richtext.html)
