### ISSUE TITLE
[Android]Android relies on the weex SDK 0.28 source code

### ISSUE THREAD

**Issue by BatterMan-Li** [apache/incubator-weex#3018]
Android relies on the source code of weex SDK version 0.28. Since the SDK no longer provides libweexcore.so file, I need to implement the work of xiangguang. what should I do

**Comment by YorkShen** [comment]
Well, Weex provides `libweexcore.so` as always. You could check it from the [convience binary of Weex](https://weex.apache.org/download/download.html#_0-28-0).

Weex doesn't provide JavaScript interpreter, and the supproting information is also on the [change log](https://weex.apache.org/download/major_change.html#_0-28).
