### ISSUE TITLE
[Android] Incorrect page zoom happend occasionally. 页面偶尔异常缩放

### ISSUE THREAD

**Issue by krimeshu** [apache/incubator-weex#3021]
## Describe the bug

Page was zoomed on some user's device.

页面在用户设备上异常缩放。

## To Reproduce

普通页面布局，但不同用户反馈会偶然遇到，暂时没有找到必现途径。

Simple page layout, happens occasionally. Reproduce path not found yet.

## Environment

Device: Android
OS: 5
Version: 0.24.0

## Expected behavior

页面期望效果：

This is what the page shold be:

![WechatIMG6.jpeg](https://i.loli.net/2019/11/17/325KsExP4nb7fGm.jpg)

## Screenshots

![WechatIMG7.png](https://i.loli.net/2019/11/17/fDsopFWZ1rRMkdy.png)

某些用户的设备上，偶尔会出现上面的异常放大情况，非必现。此时页面被放大到显示不全，无法通过操作缩放回来。

异常缩放时，页面布局（宽高、位置）被放大，但字体大小、边框圆角半径等属性却没有缩放，导致字体与布局不搭，圆形 `<div>` 变成圆角方块。

This incorrect zoom happens on some user's device occasionlly, but not every times. When happend, user can not get full page content, and can not restore the page by guesture.

And you can see, the page layout (width, height and relate postion) was scaled, but `font-size` and `border-radius` was not. Leads to page content mismatch, round `<div>` becomes round corner block.

## Additional context

后续跟进用户反馈再补充。

Follows by user's further report.

**Comment by YorkShen** [comment]
With the information you provide, it's very likely caused by [viewport](https://weex.apache.org/docs/modules/meta.html). Here is my suggestion:

1. Try to upgrade to Weex 0.28
2. Provide a stable reproducable case.

**Comment by krimeshu** [comment]
@YorkShen 

> 1. Try to upgrade to Weex 0.28
> 

We tried to upgrade to Weex 0.28.0, but app crashed:

> 2. Provide a stable reproducable case.
>

**Comment by YorkShen** [comment]
I still suggest you upgrade to the Weex 0.28. Even if this is a bug and we fix it, you have to upgrade anyway.

> dlopen failed: library "/system/lib/libc++_shared.so" needed
`libc++_shared.so` is missing in your apk for some reason, and I'm sure `weex.aar` contains the file. You should check your build.gradle of your apk.

**Comment by krimeshu** [comment]
> I still suggest you upgrade to the Weex 0.28. Even if this is a bug and we fix it, you have to upgrade anyway.
> 
> > dlopen failed: library "/system/lib/libc++_shared.so" needed
> 
> `libc++_shared.so` is missing in your apk for some reason, and I'm sure `weex.aar` contains the file. You should check your build.gradle of your apk.

Upgraded, bug resolved, thank you!

**Comment by krimeshu** [comment]
Weex 0.28.0 changed the package name: [https://weex.apache.org/download/major_change.html#package-name](https://weex.apache.org/download/major_change.html#package-name)

And we have used BindingX, but it still depending on the old package name, how to fix the conflict between Weex 0.28.0 and BindingX?

**Comment by YorkShen** [comment]
As it explained by the documentation, there are `sdk` and `sdk_legacy` in 0.28. 

* `org.apache.weex:sdk` is the currently stable package of Weex, where all Java files are under the package of org.apache.weex.
* `org.apache.weex:sdk_legacy` is the legacy package of Weex, where all Java files are under the package of com.taobao.weex. This artifact may not be maintained in the future, please upgrade to the new package name when it's possible for you.

Read the document carefully, many solutions are in the document, acutally.

**Comment by krimeshu** [comment]
Some user reported this problem again, seems upgrade the SDK doesn't work now.
