### ISSUE TITLE
[iOS] list 设置bounce='false'，导致list不能滑动

### ISSUE THREAD

**Issue by zhanglinfeng** [apache/incubator-weex#3033]
[iOS] list 设置bounce='false'，导致list不能滑动

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> [iOS] [iOS] list set bounce = 'false', haciendo que la lista no se deslice

There is nothing we can do without a [demo](http://dotwe.org/vue).

**Comment by zhanglinfeng** [comment]
demo is here  http://dotwe.org/vue/b2660683cac82fafe04b5e172fa20d13
