### ISSUE TITLE
[Android] input doesn't support 'font-weight' style. 

### ISSUE THREAD

**Issue by fund-iconfont** [apache/incubator-weex#3036]
The component input does not support the style: font-weight, also textarea has the same bug.

**Comment by YorkShen** [comment]
There is nothing we could do without a [demo](http://dotwe.org/vue).

**Comment by fund-iconfont** [comment]
The demo : http://dotwe.org/vue/7d2c31eca33007f69911d817315d0a6a

**Comment by YorkShen** [comment]
According to the [document](https://weex.apache.org/zh/docs/components/input.html), `font-weight` is not supported by `input`.

However, if you like, you could give us a PR for `font-weight` support in `input` by [adding a switch case for input](https://github.com/apache/incubator-weex/blob/master/android/sdk/src/main/java/org/apache/weex/ui/component/AbstractEditComponent.java#L466).
