### ISSUE TITLE
[Android][iOS][Dev-tool] Unexpected behavior when xx where weex version is 0.aa.bb.cc

### ISSUE THREAD

**Issue by Buddhas** [apache/incubator-weex#3037]
`weex富文本编辑问题：这边通过html-parse-stringify将html解析出来后，将原有的<p>标签替换成weex可用的标签，但是挂载过程中出现问题，我这边是这样挂载的
![image](https://user-images.githubusercontent.com/21301053/69725018-2ee86d80-1158-11ea-8ff6-b86031e4a07f.png)

weex 直接将他解析成html文本
![image](https://user-images.githubusercontent.com/21301053/69722343-cbf3d800-1151-11ea-910c-0ad31a8cedbe.png)
请问我这边应该怎么将已替换的标签挂载到已有的元素下？
对应的dotweDemo：http://dotwe.org/vue/25cd15df5853c3414a82644bfaf68da4

**Comment by YorkShen** [comment]
weex 的富文本只支持有限的子节点类型，具体可参见[文档](https://weex.apache.org/zh/docs/components/richtext.html#%E6%A0%B7%E5%BC%8F)。

`text` 不是富文本支持的子节点。
