### ISSUE TITLE
bindingX for Weex v0.28

### ISSUE THREAD

**Issue by Herrick66** [apache/incubator-weex#3038]
I have upgraded the android SDK to v0.28, but bingx failed。it con`t  find the "com.taobao.weex"
<img width="702" alt="CD97E61A-F4F4-4605-8327-CA29BCD1C68D" src="https://user-images.githubusercontent.com/24795917/69722426-12493700-1152-11ea-8ca7-f1e4da4830a6.png">

**Comment by topcloud-xx** [comment]
bindingX not update，u can use "weex_sdk_legacy" to solve it.

https://github.com/apache/incubator-weex/tree/master/android#build-types

**Comment by YorkShen** [comment]
Just as @topcloud-xx said, you could use `compile 'org.apache.weex:sdk_legacy:0.28.0'`, read the [documentation](https://weex.apache.org/zh/download/download.html#_0-28-0) here.
