### ISSUE TITLE
[Android]在Android端保存图片会在相册产生两张图片

### ISSUE THREAD

**Issue by caixiquan** [apache/incubator-weex#3055]
在Android端保存图片的时候会在weex文件下产生一张图片，然后在pictures文件下产生一张一样的图片，weex文件下的图片是原图，pictures下面的图片是压缩过的，如何解决，iOS没事

**Comment by YorkShen** [comment]
I'm pretty sure about Weex will only [save one file](https://github.com/apache/incubator-weex/blob/7548ba6214ddfe16455cf03c577941f1dfb1ecdc/android/sdk/src/main/java/org/apache/weex/utils/WXViewToImageUtil.java#L90-L126) to your phone.

As for system gallery problem, I think this is the problem of Android system, and there are many similar issue you search in the internet.

Next time, please provide a [demo](dotwe.org).
