### ISSUE TITLE
[Android]list组件和refresh组件配合使用下拉刷新时，对list和refresh单独设置背景颜色时中间有一条白线怎么去掉

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#3060]
## Describe the bug
![1575529363](https://user-images.githubusercontent.com/29773333/70211579-6c5c8480-1770-11ea-9b78-bf1e08424c22.jpg)

**Comment by YorkShen** [comment]
Try use [roundOffDeviation](https://weex.apache.org/zh/docs/modules/meta.html#setviewport)

Please provide a [demo](https://weex.apache.org/zh/docs/modules/meta.html#setviewport) next.

**Comment by wangxiongtao** [comment]
表示不起作用啊 我entry.js这么设置的
import Vue from "vue";
import weex from "weex-vue-render";


const meta = weex.requireModule('meta');
meta.setViewport({
  roundOffDeviation: false
});
weex.init(Vue);

**Comment by wangxiongtao** [comment]
> Try use [roundOffDeviation](https://weex.apache.org/zh/docs/modules/meta.html#setviewport)
> 
> Please provide a [demo](https://weex.apache.org/zh/docs/modules/meta.html#setviewport) next.

表示不起作用啊 我entry.js这么设置的
import Vue from "vue";
import weex from "weex-vue-render";


const meta = weex.requireModule('meta');
meta.setViewport({
  roundOffDeviation: false
});
weex.init(Vue);

**Comment by YorkShen** [comment]
1. A runnable demo, please. Not code snippet.
2. Set the background color of the container to red, which will help you skip the problem. The reason of the problem is also in the document I provided.
