### ISSUE TITLE
[Android/ios] Not Bug！Ask for confirming is Weex  not support “.we” DSL yet in V0.28。

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex#3064]
I tried to load 4 WeexFragment in Activity, contains three "Vue" files, and the last is "We".
All fragments rendered wonderfully but the only "We" fragment . 
Replace  Vue to We, all  fragments showed white screen.
Looks like "We" DSL is not supported in V0.28. Developers can not use "We" DSL any more.

**Comment by YorkShen** [comment]
**Short answer**: `.we` are not supported officially and there is no test case for it anymore, you may use it at your own risk.

**Long answer**: In Weex 0.28, we decoupled javascript interpreter from Weex and used JSC as the default Javascript interpreter, which is the reason of your problems. If you prefer `.we` support, just change it to the old `libJavaScriptCore.so`, you can check [travis file](https://github.com/apache/incubator-weex/blob/master/.travis.yml#L144) for a demo.

**Background Information**: There are many hack code in the old `libJavaScriptCore.so` to support `.we` file, I am not surprised  that `.we` is not supported by other Javascript interpreter.
