### ISSUE TITLE
[Android] 使用最新版0.28.0偶尔会出现这个crash，libjsc.so + 0x612a64，请大佬看看有没有办法解决？

### ISSUE THREAD

**Issue by bbssyyuui** [apache/incubator-weex#3066]
[Android] 使用最新版0.28.0偶尔会出现这个crash，**libjsc.so + 0x612a64**，请大佬看看有没有办法解决？

```
armARMv1 vendor(0x49) part(0x4900d450) features: half,thumb,fastmult,vfpv2,edsp,neon,vfpv3,tls,vfpv4,idiva,idivt8 CPUs

Thread 0 (crashed)
 0  libjsc.so + 0x612a64
     r0 = 0x974b49f4    r1 = 0xffbef340    r2 = 0xffbef3c0    r3 = 0x000000ef
     r4 = 0xffbef3c0    r5 = 0x00000008    r6 = 0x00000000    r7 = 0x0000015a
     r8 = 0xd8811b0c    r9 = 0xd8811ac0   r10 = 0x00000000   r12 = 0xffbef6c0
     fp = 0x000000ef    sp = 0xffbef328    lr = 0xefe19a90    pc = 0x96bb1a64
    Found by: given as instruction pointer in context
 1  libc.so + 0x4ea8e
     sp = 0xffbef340    pc = 0xefe19a90
    Found by: stack scanning
 2  boot-framework.oat + 0x8ef1e5
     sp = 0xffbef360    pc = 0x71f4c1e7
    Found by: stack scanning
 3  boot-framework.art + 0x61ccc2
     sp = 0xffbef364    pc = 0x70b7fcc4
    Found by: stack scanning
 4  libart.so + 0xe1bc5
     sp = 0xffbef390    pc = 0xec4e4bc7
    Found by: stack scanning
 5  NotoColorEmoji.ttf + 0x2e5798
     sp = 0xffbef39c    pc = 0xd697179a
    Found by: stack scanning
 6  libc.so + 0x5dc7b
     sp = 0xffbef41c    pc = 0xefe28c7d
    Found by: stack scanning
 7  libc.so + 0x8bd82
     sp = 0xffbef420    pc = 0xefe56d84
    Found by: stack scanning
 8  libart.so + 0x302b3f
     sp = 0xffbef440    pc = 0xec705b41
    Found by: stack scanning
 9  boot-framework.art + 0x61ccc2
     sp = 0xffbef444    pc = 0x70b7fcc4
    Found by: stack scanning
10  libart.so + 0x302b3f
     sp = 0xffbef470    pc = 0xec705b41
    Found by: stack scanning
11  base.art] + 0x35325a
     sp = 0xffbef478    pc = 0xbd08f25c
    Found by: stack scanning
12  boot-framework.art + 0x61ccc2
     sp = 0xffbef498    pc = 0x70b7fcc4
    Found by: stack scanning

libjsc.so:7F6AC0C3D3BBAD5DFC106499E4ACD5340
```

**Comment by YorkShen** [comment]
1. `libjsc.so` is in [jsc-android](https://www.npmjs.com/package/jsc-android), you should ask them.
2. According to my knowledge, `libjsc.so` only supports `armeabi-v7a`, `arm64-v8a`, `x86`. Check whether your device and apk run on these CPU architecture. If not, then this crash is normal, `libjsc.so` just doesn't support this case.

**Comment by bbssyyuui** [comment]
> 1. `libjsc.so` is in [jsc-android](https://www.npmjs.com/package/jsc-android), you should ask them.
> 2. According to my knowledge, `libjsc.so` only supports `armeabi-v7a`, `arm64-v8a`, `x86`. Check whether your device and apk run on these CPU architecture. If not, then this crash is normal, `libjsc.so` just doesn't support this case.

my device CPU is armeabi-v7a actually, and I use the weex sdk of v0.28.0

**Comment by YorkShen** [comment]
1. For ABI problems, both of your CPU architecture and `abiFilters` in your build.gradle matter.
2. Again, you should ask developers of libjsc, I can't answer your problem on behalf of them.
3. If you don't like the `libjsc`, you can switch back to the legacy libJavaScriptCore by building weex from source. Your can take the [travis file](https://github.com/apache/incubator-weex/blob/master/.travis.yml#L144) of Weex for an example.

**Comment by bbssyyuui** [comment]
ok, thanks anyway
