### ISSUE TITLE
AVPlayerViewController crash

### ISSUE THREAD

**Issue by changcan0798** [apache/incubator-weex#3068]
1WebCore0x189b49ad4WebCore::PlaybackSessionModelMediaElement::updateForEventName(WTF::AtomicString const&) + 724
2WebCore0x18a4888ccWebCore::EventTarget::fireEventListeners(WebCore::Event&, WTF::Vector<WTF::RefPtr<WebCore::RegisteredEventListener, WTF::DumbPtrTraits<WebCore::RegisteredEventListener> >, 1ul, WTF::CrashOnOverflow, 16ul>) + 736
3WebCore0x18a4861ecWebCore::EventTarget::fireEventListeners(WebCore::Event&) + 260
4WebCore0x18a483104WebCore::dispatchEventInDOM(WebCore::Event&, WebCore::EventPath const&) + 152
5WebCore0x18a482dc4WebCore::EventDispatcher::dispatchEvent(WebCore::Node&, WebCore::Event&) + 700
6WebCore0x18a6389e0WebCore::HTMLMediaElement::dispatchEvent(WebCore::Event&) + 192
7WebCore0x18a48b424WebCore::GenericEventQueue::dispatchOneEvent() + 168
8WebCore0x18a93a4d8WebCore::TaskDispatcher<WebCore::Timer>::sharedTimerFired() + 204
9WebCore0x18a957a7cWebCore::ThreadTimers::sharedTimerFiredInternal() + 352
10WebCore0x18a99c34cWebCore::timerFired(__CFRunLoopTimer*, void*) + 28
11CoreFoundation0x180e64804___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
12CoreFoundation0x180e64534___CFRunLoopDoTimer + 864
13CoreFoundation0x180e63d68___CFRunLoopDoTimers + 248
14CoreFoundation0x180e5ec44___CFRunLoopRun + 1880
15CoreFoundation0x180e5e1cc_CFRunLoopRunSpecific + 436
16WebCore0x189cbf52cRunWebThread(void*) + 592
17libsystem_pthread.dylib0x180aef2ac__pthread_body + 128
18libsystem_pthread.dylib0x180aef20c__pthread_start + 48
19libsystem_pthread.dylib0x180af2cf4_thread_start + 4

**Comment by YorkShen** [comment]
You should ask developer of Webcore, not here.
