### ISSUE TITLE
[Android]  0.28.0 weex scroller does not support `scrollstart` & `scrollend`

### ISSUE THREAD

**Issue by fund-iconfont** [apache/incubator-weex#3070]
https://weex.incubator.apache.org/zh/docs/components/scroller.html#%E4%BA%8B%E4%BB%B6
The document has listed that wxscroller has events : `scrollstart` & `scrollend`. But the actual is that it doesnot support.

**Comment by fund-iconfont** [comment]
The demo: http://dotwe.org/vue/63a8d2e2d3e41dd7f1fa994517046586

**Comment by YorkShen** [comment]
It worked well on my phone with Weex 0.28.

**Comment by zsmjhtn** [comment]
> https://weex.incubator.apache.org/zh/docs/components/scroller.html#%E4%BA%8B%E4%BB%B6
> The document has listed that wxscroller has events : `scrollstart` & `scrollend`. But the actual is that it doesnot support.

The Demo run on Web. And the doc means it does not work in Web.
You should try to run it on IOS/Aos
