### ISSUE TITLE
[其它] 苹果发布文章说，要停止上架混合式，webApp等应用

### ISSUE THREAD

**Issue by netzhouxiang** [apache/incubator-weex#3071]
官方地址：https://developer.apple.com/news/?id=09062019b

weex怎么搞

**Comment by adreamy** [comment]
> 官方地址：https://developer.apple.com/news/?id=09062019b
> 
> weex怎么搞

个人觉得不会有任何影响，大如腾讯公众号、小程序，阿里的小程序都在用类weex技术，完全没必要担心

**Comment by YorkShen** [comment]
烦请订阅[邮件列表](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)，相关问题已在今年9月份进行过[讨论](https://lists.apache.org/thread.html/fdf5f7d44e739d0814b41e12721b161b0946fc544f0a1707fec7f5c3%40%3Cdev.weex.apache.org%3E)。

**Comment by YorkShen** [comment]
> This update has nothing to do with Weex Apps, but Apps that people try to load from a remote server. Try not to load code from a server if your App(s) falls into the case mentioned above.

https://ionicframework.com/blog/making-sense-of-apples-tos/
