### ISSUE TITLE
无法引入多个ttf字体图标

### ISSUE THREAD

**Issue by xqd93** [apache/incubator-weex#3076]
```
        domModule.addRule('fontFace', {
		'fontFamily': 'iconfont2',
		'src': "url('https://at.alicdn.com/t/font_xxxxxxxxx1.ttf')"
	});
	domModule.addRule('fontFace', {
		'fontFamily': 'wrq-iconfont',
		'src': "url('https://at.alicdn.com/t/font_xxxxxxxxx2.ttf')"
	});
```

无法引入多个字体图标
安卓下，第一个无效
iOS下，第二个无效

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Unable to introduce multiple TTF font icons

1. Try latest version of Weex, e.g. Weex 0.28
2. According to the [demo](http://dotwe.org/vue/4641bfd0ab806674d62cb00a9ad2dddb) in the [document](https://weex.apache.org/docs/modules/dom.html#addrule), everything works fine on my phone with Weex 0.28`
3. Provide a runnable [demo](http://editor.weex.io/), there is nothing we can do with code sinppet.
