### ISSUE TITLE
SDK 0.26.0  BUG，从24换成26所有点击事件全部失效，也没有任何报错

### ISSUE THREAD

**Issue by wujianqiang6** [apache/incubator-weex#3077]
https://weex.apache.org/zh/download/download.html#_0-26-0

my project used 0.23.3.0-beta or 0.24 is no problem，but update to 0.26SDK .
all of ‘click’ are not invalid；
for example：<div @click="clickDiv"></div>

在使用 0.23.3.0-beta或者0.24的时候没有问题，但是在使用0.26的时候，
我页面上的所有click事件，都没有任何反应，也没有报错。为什么？

**Comment by cnryb** [comment]
你可以试试在 0.28上问题还在不在

**Comment by hechangpeng** [comment]
其实是有报错的。weex_js_server died 192。 你检查一下是否有trim函数。

**Comment by YorkShen** [comment]
请提供一个可运行的 [demo](http://dotwe.org/vue)

**Comment by wujianqiang6** [comment]
> 其实是有报错的。weex_js_server died 192。 你检查一下是否有trim函数。

是有trim，请我是什么原因呢。我改成0.28.0就没问题了。谢谢！

**Comment by YorkShen** [comment]
0.28和0.26的 JS 引擎不一样，不同的JS引擎可能对trim的处理有区别。
