### ISSUE TITLE
[Android]sdk更换到29，项目换成了AndroidX的包，然后weex在Android10系统上加渲染失败，报degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1错误

### ISSUE THREAD

**Issue by wangxiongtao** [apache/incubator-weex#3083]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question:  SDK changed to 29, project changed to AndroidX package, then weex failed to add rendering on Android 10

1. Weex doesn't support Android X yet.
2. We're focusing on fixing branding [issues recently](https://cwiki.apache.org/confluence/display/WEEX/Branding+issues), and I am afraid, we will not support Android X.
3. However, you're welcomed to create a PR for supporting Android X. I am happy to discuss design detail with you in [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list).

**Comment by shawn-tangsc** [comment]
怎么解决了吗？怎么解决的？
