### ISSUE TITLE
[Android] weex页面切换高概率白屏 看日志是weex_js_connection.cpp:192,server died  [0.26.0]

### ISSUE THREAD

**Issue by hechangpeng** [apache/incubator-weex#3092]
weex_js_connection.cpp:192,server died
script_side_in_multi_process.cpp:314,futex lock pi failed: No such process, 800013f5 5061 (0 0 0 800013f5)

**Comment by hechangpeng** [comment]
出现白屏后，back到前一个页面，weex直接挂了，点哪里都没反应。

**Comment by hponiang** [comment]
最好把详细日志放下

**Comment by hechangpeng** [comment]
script_side_in_multi_process.cpp:314,futex lock pi failed: No such process, 80002833 10279 (0 0 2827 0)


> 最好把详细日志放下

/WeexCore: script_side_in_multi_process.cpp:314,futex lock pi failed: No such process, 80002833 10279 (0 0 2827 0)
/WeexCore: weex_js_connection.cpp:192,server died
/WeexCore: script_bridge.h:168,xxx set_core_side is runing and 0x7f76303ab0
/WeexCore: script_bridge_in_multi_process.cpp:979,ScriptBridgeInMultiProcess
/WeexCore: multi_process_and_so_initializer.cpp:38,MultiProcessAndSoInitializer IS IN init
/WeexCore: script_bridge_in_multi_process.cpp:991,ScriptBridgeInMultiProcess finish 0x7f64fb79a0 0x0

**Comment by hechangpeng** [comment]
> 最好把详细日志放下

12-26 15:53:55.063 27062-27111/com.mobileshare.app E/WeexCore: weex_js_connection.cpp:192,server died
12-26 15:53:55.098 27062-27108/com.mobileshare.app E/WeexCore: script_side_in_multi_process.cpp:314,futex lock pi failed: No such process, 800069eb 27108 (0 0 69e4 0)
12-26 15:53:55.098 27062-27108/com.mobileshare.app E/WXBridge: reportServerCrash instanceId: crashFile: /crash_dump.log
12-26 15:53:55.098 27062-27108/com.mobileshare.app E/WXParams: getCrashFilePath:/data/data/com.mobileshare.app/app_crash
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WXParams: setCrashFilePath: /data/data/com.mobileshare.app/app_crash
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/weex: getLibLdPath is /data/app/com.mobileshare.app-1/lib/arm64:/vendor/lib64:/system/lib64
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WeexCore: params_utils.cpp:130,initFromParam is running 
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/weex: getUseSingleProcess is running false
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WeexCore: params_utils.cpp:197,g_use_single_process is false 
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/weex: getLibJscPath is running /data/app/com.mobileshare.app-1/lib/arm64
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WeexCore: params_utils.cpp:232,g_jscSoPath is /data/app/com.mobileshare.app-1/lib/arm64 
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/weex: getLibJssPath is running /data/app/com.mobileshare.app-1/lib/arm64/libweexjss.so
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WeexCore: params_utils.cpp:245,g_jssSoPath is /data/app/com.mobileshare.app-1/lib/arm64/libweexjss.so 
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WXParams: getCrashFilePath:/data/data/com.mobileshare.app/app_crash
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WeexCore: params_utils.cpp:257,g_crashFilePath is /data/data/com.mobileshare.app/app_crash 
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/weex: getLibIcuPath is running /system/usr/icu/icudt53l.dat
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WeexCore: params_utils.cpp:270,g_jssIcuPath is /system/usr/icu/icudt53l.dat 
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/weex: getLibLdPath is running /data/app/com.mobileshare.app-1/lib/arm64:/vendor/lib64:/system/lib64
12-26 15:53:55.105 27062-27108/com.mobileshare.app E/WeexCore: params_utils.cpp:283,lib_ld_path is /data/app/com.mobileshare.app-1/lib/arm64:/vendor/lib64:/system/lib64 
12-26 15:53:55.107 27062-27108/com.mobileshare.app E/WeexCore: script_bridge.h:168,xxx set_core_side is runing and 0x7f3a7bded0
12-26 15:53:55.107 27062-27108/com.mobileshare.app E/WeexCore: script_bridge_in_multi_process.cpp:979,ScriptBridgeInMultiProcess
12-26 15:53:55.107 27062-27108/com.mobileshare.app E/WeexCore: multi_process_and_so_initializer.cpp:38,MultiProcessAndSoInitializer IS IN init
12-26 15:53:55.107 27062-27108/com.mobileshare.app E/WeexCore: weex_js_connection.cpp:146,WeexJSConnection g_crashFileName: /data/data/com.mobileshare.app/app_crash/crash_dump.log
12-26 15:53:55.107 27062-27108/com.mobileshare.app E/WeexCore: weex_js_connection.cpp:266,startupPie :1
12-26 15:53:55.172 27062-27108/com.mobileshare.app E/WeexCore: script_bridge_in_multi_process.cpp:991,ScriptBridgeInMultiProcess finish 0x7f415f7a90 0x0
12-26 15:53:58.003 27062-27108/com.mobileshare.app E/WeexCore: render_page.cpp:72,[RenderPage] Delete RenderPage >>>> pageId: 40

**Comment by YorkShen** [comment]
The JavaScript process died for some unknown reason.

Just try Weex 0.28, wheere you can use whatever JavaScript interpreter you like.
