### ISSUE TITLE
[Android] -2013 when __WEEX_CALL_JAVASCRIPT__TypeError: t[0].apply is not a function. (In 't[0].apply(t,t.slice(2))', 't[0].apply' is undefined)  getTemplateInfo== template md5 d6e1a36b7e84509c17c4d60b7539d395 length 842756 base64 md5 1uGja36EUJwXxNYLdTnTlQ== response header {"templateSourceBase64MD5":["1uGja36EUJwXxNYLdTnTlQ=="],"templateSourceMD5":["d6e1a36b7e84509c17c4d60b7539d395"]} where weex version is org.apache.weex:sdk_legacy:0.28.0

### ISSUE THREAD

**Issue by FightingForDevelop** [apache/incubator-weex#3095]
Dear 
     Weex onException show code:-2013 and msg is "__WEEX_CALL_JAVASCRIPT__TypeError: t[0].apply is not a function. (In 't[0].apply(t,t.slice(2))', 't[0].apply' is undefined)  getTemplateInfo== template md5 d6e1a36b7e84509c17c4d60b7539d395 length 842756 base64 md5 1uGja36EUJwXxNYLdTnTlQ== response header {"templateSourceBase64MD5":["1uGja36EUJwXxNYLdTnTlQ=="],"templateSourceMD5":["d6e1a36b7e84509c17c4d60b7539d395"]}"
or "__WEEX_CALL_JAVASCRIPT__TypeError: undefined is not an object (evaluating 't.ref')  getTemplateInfo== template md5 null ,httpHeader:{}"
or "__WEEX_CALL_JAVASCRIPT__TypeError: this.form.quantity.trim is not a function. (In 'this.form.quantity.trim()', 'this.form.quantity.trim' is undefined)  getTemplateInfo== template md5 61816eeb786ca07ec458b4746705e4d9 length 635411 base64 md5 YYFu63hsoH7EWLR0ZwXk2Q== response header {"templateSourceBase64MD5":["YYFu63hsoH7EWLR0ZwXk2Q=="],"templateSourceMD5":["61816eeb786ca07ec458b4746705e4d9"]}"
This version we update weex_sdk to org.apache.weex:sdk_legacy:0.28.0,and add the libjsc.so such as armeabi-v7a, arm64-v8a, x86.I also add them in build.gradle ndk at the same time.
Because when QA run the automated testing,our project occurs white screen,so I copy the armeabi-v7a to armeabi.
Looking forward to your reply!  Ths

**Comment by YorkShen** [comment]
The stacktrace is pretty straightforward, there is something wrong in your JS code, `undefined is not an object (evaluating 't.ref') `.

FYI: Some corner case of JavaScript code may be supported by one JavaScript interpreter, and not supported by another JavaScript interpreter.

You need to chech the JS code to fix the problem.

**Comment by FightingForDevelop** [comment]
> The stacktrace is pretty straightforward, there is something wrong in your JS code, `undefined is not an object (evaluating 't.ref') `.
> 
> FYI: Some corner case of JavaScript code may be supported by one JavaScript interpreter, and not supported by another JavaScript interpreter.
> 
> You need to chech the JS code to fix the problem.

OK,thanks! I will chech with the web developer.

**Comment by FightingForDevelop** [comment]
> The stacktrace is pretty straightforward, there is something wrong in your JS code, `undefined is not an object (evaluating 't.ref') `.
> 
> FYI: Some corner case of JavaScript code may be supported by one JavaScript interpreter, and not supported by another JavaScript interpreter.
> 
> You need to chech the JS code to fix the problem.

Do I need to copy the armeabi-v7a to armeabi?

**Comment by YorkShen** [comment]
In most Android phones I have met, armeabi-v7a is compatibility with armeabi, which means you could just move files from `jni/armeabi-v7a` to `jni/armeabi` without any problems.

Of course, there are very few cases ( I only met once) where moving so files will cause you problems.

So, generally, you don't need to copy files.

**Comment by FightingForDevelop** [comment]
> In most Android phones I have met, armeabi-v7a is compatibility with armeabi, which means you could just move files from `jni/armeabi-v7a` to `jni/armeabi` without any problems.
> 
> Of course, there are very few cases ( I only met once) where moving so files will cause you problems.
> 
> So, generally, you don't need to copy files.

👌,thas
