### ISSUE TITLE
[Android]slider的infinite属性在只有两张图片时会失效（v0.28.0）

### ISSUE THREAD

**Issue by shenhuniurou** [apache/incubator-weex#3098]
当只有两张图片时，即使设置了infinite="true"，也无法无限循环，大于2张就没问题，目前发现只在Android平台出现这个bug，iOS正常。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> When there are only two pictures, even if infinite = "true" is set, the loop cannot be infinite. If there are more than two pictures, there is no problem. At present, it is found that this bug occurs only on the Android platform and iOS is normal.

Please provide a [demo](http://dotwe.org/vue), there is nothing we can do without a demo.
