### ISSUE TITLE
更新到0.28.0突然加载不到jsc-android-241213.1.0.tgz

### ISSUE THREAD

**Issue by yanghx1991** [apache/incubator-weex#3105]
apply from: 'https://raw.githubusercontent.com/apache/incubator-weex/release/0.28/android/sdk/buildSrc/download_jsc.gradle'
报错：
Could not read '/Users/yanghuaxiong/AndroidStudioProjects/git/wellcee_android/app/build/jsc/jsc-android-241213.1.0.tgz' as it does not exist.

**Comment by zsmjhtn** [comment]
open the  '/Users/yanghuaxiong/AndroidStudioProjects/git/wellcee_android/app/build/jsc/jsc-android-241213.1.0.tgz' in your  Finder and try to unzip it.
Can you unzip that file? Maybe some errors happen when you unzip it.
If the situation like mentiond above, you should optimize your Network && VPN.
BTW, the file is exist on Network.I can download it。

**Comment by YorkShen** [comment]
Check your network and VPN, the `jsc-android-241213.1.0.tgz` is hosted on a third-part npm server.

**Comment by hydrz** [comment]
so do i ... use this
`jsc_url = 'https://nan-files.oss-cn-hangzhou.aliyuncs.com/jsc-android-241213.1.0.tgz'`
