### ISSUE TITLE
[Android] "-9700", "white screen cause create instanceContext failed,check js stack ->

### ISSUE THREAD

**Issue by FightingForDevelop** [apache/incubator-weex#3106]
-9700
createInstanceContextSyntaxError: Unexpected end of script  getTemplateInfo== template md5 fc5037288db7909ee55f0052d56ec8 length 65536 base64 md5 APxQNyiNt5Ce5V8AUtVuyA== response header {"templateSourceBase64MD5":["APxQNyiNt5Ce5V8AUtVuyA=="],"templateSourceMD5":["fc5037288db7909ee55f0052d56ec8"]}

This is a weex page error. Can you tell me who should resolve it,android or web?And how to solve it.
Thanks very much.

**Comment by YorkShen** [comment]
> syntaxError: Unexpected end of script 

Check your JS file, the error message is pretty clear.

**Comment by FightingForDevelop** [comment]
> > syntaxError: Unexpected end of script
> 
> Check your JS file, the error message is pretty clear.

I'm sorray,I can't find any thing about the error in JS file. Can you give me some advices?

**Comment by YorkShen** [comment]
> Unexpected end of script 

This is the log reported by JS engine, which means your JS file is invalid.
