### ISSUE TITLE
Android <Text>组件，内容为特殊文字时，weex进程会挂掉

### ISSUE THREAD

**Issue by wujianqiang6** [apache/incubator-weex#3111]
Error: E/WeexCore: weex_js_connection.cpp:183,IPCException server died original owner has die

在安卓的Text 组件使用emoji表情，并且截取一半后，剩下的内容在text渲染后，会报错，结果导致整个app weex的页面都不能操作了。

<text>\uD83D\uDE1C</text> is Ok

<text>\uD83D</text> is Die

**Comment by YorkShen** [comment]
No response in a month, I will close it.

Feel free to reopen.
