### ISSUE TITLE
iOS WeexSDK 0.19+   file not found

### ISSUE THREAD

**Issue by LionBuer** [apache/incubator-weex#3112]
## Describe the bug
 iOS  WeexSDK 0.19 往上报错：  **fatal error:'core/api/wx_api.h' file not found**

## Environment
* Device: [ iPhone7]
* OS: [iOS9]
* Version [0.28.0]
* Build from source [yes]

**Comment by YorkShen** [comment]
Please upgrade to Weex 0.28, I think there is no `core/api/wx_api.h` in Weex 0.19.

**Comment by LionBuer** [comment]
就是更新到0.28才报错啊，在0.19上不会有这个错误

**Comment by LionBuer** [comment]
@YorkShen
