### ISSUE TITLE
[Android] Running the for statement in the JavaScriptcore takes a lot of time

### ISSUE THREAD

**Issue by st-dc** [apache/incubator-weex#3116]
JS sample code：
var start = new Date().valueOf()
var arr = []
for (var i = 0; i < 100000; i++) {
	var arrIn = []
	for (var j = 0; j < 1000; j++) {
		arrIn.push(j)
	}
	arr.push(arr)
}
var end = new Date().valueOf()
console.log("time：" + (end - start) + "ms")
JavaScriptCore takes 19000ms to complete.
The system WebView runs JS sample code, which only needs 3000ms to complete。
Please change JSC to V8!!!!!

**Comment by YorkShen** [comment]
From Weex 0.28, you can choose whaterver JS interpertator you want as long as you implement a group of interface.

You could:
* Use release version of your app instead of debug version. Debugbable Apps usually have performance punishment.
* Upgrade JSC version as you wish.
* Implement the interface with V8 and give us a Pull request.

**Comment by ArrayDC** [comment]
既然都知道有性能问题，官方为何还不更新优化？
这样才会更多人使用，吸引更多人贡献代码呀
 @YorkShen

**Comment by YorkShen** [comment]
We are not employeers/workers of V8/JSC or any other framework. Choose whaterver as your wish.

**Comment by wanganxp** [comment]
> We are not employeers/workers of V8/JSC or any other framework. Choose whaterver as your wish.

“我不是v8或jsc的员工”？这个说法，好不专业啊。
这就是淘宝的工程师吗？
淘宝有没有领导在关注这个事情？
如此慢的js引擎，你们内部使用时怎么过的性能测试？
你提供了项目只有jscore，你倒是再提供一个v8的样例啊！！！

**Comment by YorkShen** [comment]
> > We are not employeers/workers of V8/JSC or any other framework. Choose whaterver as your wish.
> 
> “我不是v8或jsc的员工”？这个说法，好不专业啊。
> 这就是淘宝的工程师吗？
> 淘宝有没有领导在关注这个事情？
> 如此慢的js引擎，你们内部使用时怎么过的性能测试？
> 你提供了项目只有jscore，你倒是再提供一个v8的样例啊！！！

1. Apache Weex 现在和淘宝无关(尽管源自淘宝)
2. 我不是淘宝的员工，现在没有任何人付钱(包括你在内)给我做 Apache Weex。
3. Talk is cheap, show me the code.
