### ISSUE TITLE
[Android]Unexpected behavior when use Promise where weex version is 0.28

### ISSUE THREAD

**Issue by chs97** [apache/incubator-weex#3127]
## Describe the bug

In 0.28 playground , this demo: http://dotwe.org/vue/4e2bacadb78695197bc7ac7a4864f28f
expected behavior :  show 11111 but playground show 1
## Environment
![image](https://user-images.githubusercontent.com/12679581/73640325-ff4e6800-46a8-11ea-98f2-d8aa3bfe7574.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/12679581/73640385-1e4cfa00-46a9-11ea-9ca3-3809e6fe0b9c.png)

## Screenshots

![image](https://user-images.githubusercontent.com/12679581/73640414-29078f00-46a9-11ea-8a58-d42e1eb4f8ea.png)

## Additional context

is jsfm change bug not push?

**Comment by chs97** [comment]
@YorkShen

**Comment by chs97** [comment]
build a jsfm make to Promise doesn't use native.and it work.

**Comment by YorkShen** [comment]
@chs97 Anything need I do?
