### ISSUE TITLE
[iOS] ！！！ Apple review was rejected, weex version is 0.28.0

### ISSUE THREAD

**Issue by xiaohuapunk** [apache/incubator-weex#3130]
![image](https://user-images.githubusercontent.com/9956517/73724456-5ebe7d80-4766-11ea-9b6a-9b4e97e886e9.png)

Could it be because of method naming?

**Comment by chenzefeng09** [comment]
关注

**Comment by yyqqing** [comment]
关注。

希望看到 owner 对 https://developer.apple.com/news/?id=09062019b 的评论

**Comment by YorkShen** [comment]
This is the [offical comment](https://lists.apache.org/thread.html/fdf5f7d44e739d0814b41e12721b161b0946fc544f0a1707fec7f5c3%40%3Cdev.weex.apache.org%3E) of such issue.

Highlight, 
> "This update has nothing to do with Weex Apps, but Apps that people try to load from a remote server. Try not to load code from a server if your App(s) falls into the case mentioned above”.
