### ISSUE TITLE
[Android][29] reportJSException >>>> instanceId:, exception function:initFramework, exception:failed to create ashmem region: Permission denied where weex version is 0.28.0

### ISSUE THREAD

**Issue by 770589235** [apache/incubator-weex#3146]

**Comment by 770589235** [comment]
WeexCore: WeexJSConnection g_crashFileName:/data/user/0/me.andpay.apos/app_crash/crash_dump.log
E/WeexCore: WeexProxy catch：failed to create ashmem region: Permission denied
E/WeexCore: RegisterIPCCallback is running
 E/WeexCore: RegisterIPCCallback is running2
 E/WeexCore: WeexJSConnection g_crashFileName: /data/user/0/me.andpay.apos/app_crash/crash_dump.log
 E/WeexCore: WeexProxy catch：failed to create ashmem region: Permission denied
 E/WeexCore: failed to create ashmem region: Permission denied
 E/weex: reportJSException >>>> instanceId:, exception function:initFramework, exception:failed to create ashmem region: Permission denied
 E/WeexCore: InitFramework sender is null
 E/weex: [WXBridgeManager] invokeInitFramework  ExecuteJavaScript fail

**Comment by 770589235** [comment]
WeexCore: WeexJSConnection g_crashFileName:/data/user/0/me.andpay.apos/app_crash/crash_dump.log
E/WeexCore: WeexProxy catch：failed to create ashmem region: Permission denied
E/WeexCore: RegisterIPCCallback is running
 E/WeexCore: RegisterIPCCallback is running2
 E/WeexCore: WeexJSConnection g_crashFileName: /data/user/0/me.andpay.apos/app_crash/crash_dump.log
 E/WeexCore: WeexProxy catch：failed to create ashmem region: Permission denied
 E/WeexCore: failed to create ashmem region: Permission denied
 E/weex: reportJSException >>>> instanceId:, exception function:initFramework, exception:failed to create ashmem region: Permission denied
 E/WeexCore: InitFramework sender is null
 E/weex: [WXBridgeManager] invokeInitFramework  ExecuteJavaScript fail

**Comment by jinbo1232007** [comment]
you may have set targetSdkVersion = 29,  try  down to 28, It works for me, as issues 
https://github.com/apache/incubator-weex/issues/2706

**Comment by zsmjhtn** [comment]
,try down to targetSdkVersion = 28, or targetSdkVersion = 26
