### ISSUE TITLE
[Android] When will JSC be upgrade??

### ISSUE THREAD

**Issue by EruYan** [apache/incubator-weex#3153]
JSC is still 2016 version, with low performance. 
Why not upgrade?

**Comment by ArrayDC** [comment]
期待升级，官方还继续维护吗？

**Comment by xiaohuapunk** [comment]
现在jsc的性能不太像，希望能升级一下

**Comment by cnryb** [comment]
Duplicate of #3139

**Comment by cnryb** [comment]
How did you determine that the JSC version was 2016 ？
