### ISSUE TITLE
[iOS]请问何时更新移除UIWebView的版本？

### ISSUE THREAD

**Issue by VictorJi** [apache/incubator-weex#3162]
你好，
我看master分支上在三个月前在WXWebComponet中已经使用WKWebView替换掉了UIWebView，而Pod上最新的0.28.0版本仍然使用的是UIWebView，请问何时更新移除UIWebView的版本？

**Comment by cnryb** [comment]
发布版本的问题在邮件列表里讨论比较合适，YorkShen 大佬最近比较忙。
https://weex.apache.org/zh/guide/contribute/how-to-contribute.html

**Comment by jianxiongc** [comment]
> 你好，
> 我看master分支上在三个月前在WXWebComponet中已经使用WKWebView替换掉了UIWebView，而Pod上最新的0.28.0版本仍然使用的是UIWebView，请问何时更新移除UIWebView的版本？

pod 'WeexSDK' , :git => 'https://github.com/apache/incubator-weex.git'
