### ISSUE TITLE
关于 weex 的调试看不到 js 文件, 打不了断点

### ISSUE THREAD

**Issue by aowuR** [apache/incubator-weex#3181]
weex debug 的话会报错:
![image](https://user-images.githubusercontent.com/29719695/77888373-bb3da500-729e-11ea-9ca9-8760a4fa85bd.png)
在 weex debug 的时候,mac 的隐藏文件里面会添加一个.wx 的文件 这里面的vue 和 vue-template-compiler 版本不相同...
通过查找,以前有人解决是:
weex xbind repair toolkit-repair
weex repair
这两个命令, 但是现在`weex xbind repair toolkit-repair`这个命令会下载失败,找不到包了已经

**Comment by cnryb** [comment]
你都没说清楚遇到了什么问题，怎么个不对法，怎么帮你呀。

**Comment by aowuR** [comment]
> 你都没说清楚遇到了什么问题，怎么个不对法，怎么帮你呀。

实在抱歉, 那会我也搞不清哪里有问题.  命令窗口小没看到报错 现在看到有报错:是 vue 和vue-template-compiler版本不一致.  但是在项目里面修改一样版本没有作用.似乎是在 我 mac 系统的 user/xxx/.wx/下面 这个是 weex 的文件吗?? 需要怎么更改这个
![image](https://user-images.githubusercontent.com/29719695/77884234-40bd5700-7297-11ea-9dc1-5dd13d104a18.png)

**Comment by cnryb** [comment]
我使用 weex create 创建了一个项目，执行 weex debug src 没有复现你的问题。
你可以尝试删除 /user/xxx/.wx 目录，重新执行命令试试看。

**Comment by aowuR** [comment]
> 我使用 weex create 创建了一个项目，执行 weex debug src 没有复现你的问题。
> 你可以尝试删除 /user/xxx/.wx 目录，重新执行命令试试看。

我估计还得研究研究 你这个方法我也试过了 .wx 这个文件是 weex debug 的时候下载的.  可能是我的环境哪里有问题吧 ...  真让人头大  哈哈哈哈 感谢你的回复
