### ISSUE TITLE
如何在页面间复用公共组件和样式？

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex#3226]
如题，目前公共组件都是重复打包到每个页面的js文件中。我看到文档里提到jsservice可以在weex实例间复用公共的js函数，那能不能不用公共组件呢？该如何操作？需要明白人指点一下

**Comment by cnryb** [comment]
要是我没记错的话，组件编译完也是 js 。 
也没有哪说 JS Service 里只能放函数呀，你肯定是被示例带歪了。

**Comment by chenzefeng09** [comment]
@cnryb 感谢！
