### ISSUE TITLE
[Android][iOS]这个没有V-show怎么隐藏组件啊 求一个weex的v-show

### ISSUE THREAD

**Issue by wujie1314** [apache/incubator-weex#3238]
这个没有V-show怎么隐藏组件啊，用v-if组件会重新渲染，缓存无法留下来啊，vue还有keep-alive，但是weex都用不起

**Comment by hanliuxin5** [comment]
```
 <lottie class="…."
            :style="{visibility: visible}"
                    ></lottie>
```
第一，用`visibility`来控制

第二，用`opacity`来控制

**Comment by cnryb** [comment]
个人意见，在iOS、Android中，组件会被翻译成相应的native组件。隐藏组件后，组件所占位置仍在。所以直接 v-if 会更好点。

**Comment by hanliuxin5** [comment]
@cnryb 对的，目前倒是可以通过控制 `style`  来解决位置的问题

**Comment by wakaryry** [comment]
直接用v-if控制，或者将其移动到可见屏幕之外。
