### ISSUE TITLE
[Android]Unexpected behavior when using websocket where weex version is 2.0.0

### ISSUE THREAD

**Issue by ericsoul1987** [apache/incubator-weex#3262]
## Describe the bug

用weex的playground里面的websocket实例里面的demo
无法使用。

真机调试，报“E/WebSocketModule: No implementation found for IWebSocketAdapter”

**Comment by zhangjingwei-gwi** [comment]
> 需要自己实现，我记得playground里有实现了，你看你的代码里初始化的时候是不是没设置，WXSDKEngine初始化时应该有这个 .setWebSocketAdapterFactory(new WebSocketAdapterFactory())

呃，native也不是很会啊，刚开始从weex开始搞的，是要在通过weex platform add android 生成的代码里面添加代码，可以参考playground 那个项目里面的copy过来？那这样我的项目里面就必须 维护 新增的这部分代码了。

**Comment by ericsoul1987** [comment]
好了大概梳理清楚了，要用commons那个工程里面实现了这个，之后呢我通过weex-cli2.0.0手脚架建的工程，建出来的weex工程是0.20.0.3的。总体来说就是不要用weex-cli，用playground的。
