### ISSUE TITLE
ios picker.pickDate无法选择日期

### ISSUE THREAD

**Issue by nikojxie** [apache/incubator-weex#3271]
环境：Xcode12 ios14

截图：

![1431600414019_ pic](https://user-images.githubusercontent.com/35838595/93568906-6a904480-f9c3-11ea-80fa-2d5bbfc37aab.jpg)

**Comment by lindeyi** [comment]
https://blog.csdn.net/sky_long_fly/article/details/108666501

**Comment by nikojxie** [comment]
ok 谢谢

**Comment by VernonJin** [comment]
> ok 谢谢

请问怎么解决的

**Comment by nikojxie** [comment]
> > ok 谢谢
> 
> 请问怎么解决的
看下这个吧
https://github.com/apache/incubator-weex/pull/3277/commits/6da2c67d3f4cb953557d37568a90a140014bd291
