### ISSUE TITLE
[iOS]Weex的版本还是0.28.0，最近有升级计划吗？

### ISSUE THREAD

**Issue by fisherlee** [apache/incubator-weex#3283]
用Xcode12编译weex有bug，比如网络图片不能显示，还有weex里面还有UIWebView。
我看到源码里面都已经解决了这些问题，不过weex的版本号还是0.28.0
请问最近有发布新版本的计划吗？

**Comment by ZhangHJ1002** [comment]
感觉是不打算用心维护了
这些问题都提了不知道多久了 也没有发版计划  
有个老项目是 17还是18版本的 新的版本的weexSdk 根本升级不上来  升级上来涉及动画的内存直接爆炸
老版本跑的一点问题都没有...
另外一个项目停在26版本准备有问题自己更新了
真的感觉是个kpi项目了

**Comment by aloe20** [comment]
能公布一下发版计划吗？

**Comment by cnryb** [comment]
@fisherlee 最近计划发布一个新版本

**Comment by illaclv** [comment]
@cnryb 您好，新版本会修复iOS列表loading时的异常情况吗？
1. 数据不满屏时，下拉底部出现加载更多，有人提了issues：我看了下好像是WXScrollerComponent.mm 中scrollViewDidEndDragging willDecelerate方法直接显示了loading导致
https://github.com/apache/incubator-weex/issues/3101
2. 列表上拉回弹 有几率导致列表上移
