### ISSUE TITLE
什么时候发布新的版本啊？

### ISSUE THREAD

**Issue by SunSeekerX** [apache/incubator-weex#3294]
看提交记录一直在更新。发布的 sdk 是一年前的了。不更新就直接归档。有更新能公布下计划吗。

**Comment by fisherlee** [comment]
这玩意就是个kpi项目，谁用谁倒霉。只能写写不重要的页面，项目主要功能依赖这个，早晚出大问题。

**Comment by chenzefeng09** [comment]
需要哪端的sdk可以自己编译下

**Comment by cnryb** [comment]
最近计划发布一个新版本

**Comment by aloe20** [comment]
> 最近计划发布一个新版本

这都快半个月了。你这最近是指多久呢
