### ISSUE TITLE
主 License 和 runtime\frameworks\legacy\core\LICENSE 对于 vue 的 copyright 不一致。

### ISSUE THREAD

**Issue by xiadengping** [apache/incubator-weex#3320]
runtime\frameworks\legacy\core\LICENS
Copyright (c) 2013-2015 Yuxi Evan You

主 License
Copyright (c) 2013-2014 Yuxi Evan You

差别在于年份的不同。

请看下是否需要统一。

**Comment by cnryb** [comment]
我对这些协议了解不太多。不过看起来是由于采用了比较古老的代码所导致的。
如果你认为有必要，请pr。

不过我个人认为没有太大的必要，因为我推测采用的代码上面应该就是那么写的，应该不会有人专门去修改这个时间。
