### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by liujianchao1995** [apache/incubator-weex#3324]
weex run android
(node:23608) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[√] Compile JSBundle done
? Select one of the device OnePlus8Pro
[√] Start hotreload server done
[√] Set native config done
[√] Copy JS source done
[√] Watch JS source done
- Total time: 2 mins 59.404 secsError: Command failed: call gradlew.bat clean assembleDebug
isLibProject: false, isAppProject: true
weex_plugin: []

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve com.android.support:support-v4:26.1.0.
     Required by:
         android:app:unspecified
      > Could not resolve com.android.support:support-v4:26.1.0.
         > Could not get resource 'https://maven.google.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.200.46] failed: Connection timed out: connect
   > Could not resolve com.android.support:appcompat-v7:26.1.0.
     Required by:
         android:app:unspecified
      > Could not resolve com.android.support:appcompat-v7:26.1.0.
         > Could not get resource 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.200.46] failed: Connection timed out: connect
   > Could not resolve com.android.support:design:26.1.0.
     Required by:
         android:app:unspecified
      > Could not resolve com.android.support:design:26.1.0.
         > Could not get resource 'https://maven.google.com/com/android/support/design/26.1.0/design-26.1.0.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/design/26.1.0/design-26.1.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.200.46] failed: Connection timed out: connect
   > Could not resolve com.android.support:support-annotations:26.1.0.
     Required by:
         android:app:unspecified
      > Could not resolve com.android.support:support-annotations:26.1.0.
         > Could not get resource 'https://maven.google.com/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.200.46] failed: Connection timed out: connect
   > Could not resolve com.android.support:appcompat-v7:26.1.0.
     Required by:
         android:app:unspecified > com.taobao.android:weex_inspector:0.20.3.0-beta
      > Could not resolve com.android.support:appcompat-v7:26.1.0.
         > Could not get resource 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.200.46] failed: Connection timed out: connect
   > Could not resolve com.android.support:support-v4:26.1.0.
     Required by:
         android:app:unspecified > com.journeyapps:zxing-android-embedded:3.4.0
      > Could not resolve com.android.support:support-v4:26.1.0.
         > Could not get resource 'https://maven.google.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.pom'.
            > Could not GET 'https://maven.google.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.pom'.
               > Connect to maven.google.com:443 [maven.google.com/216.58.200.46] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
- Total time: 2 mins 59.404 secs

**Comment by cnryb** [comment]
看起来是网络问题。
请科学上网后重试。

**Comment by liujianchao1995** [comment]
> 看起来是网络问题。
> 请科学上网后重试。

已经是科学上网了，这里面的链接直接访问都是可以的，速度也很快，就只在命令行启动weex应用时报错，唉，好难啊。。。

**Comment by cnryb** [comment]
浏览器中使用的代理，和系统的代理，Android studio的代理，都是可以分开设置的。

**Comment by Acmenbackpack** [comment]
> > 看起来是网络问题。
> > 请科学上网后重试。
> 
> 已经是科学上网了，这里面的链接直接访问都是可以的，速度也很快，就只在命令行启动weex应用时报错，唉，好难啊。。。

20210423遇到这个问题,请问你怎么解决的

**Comment by Acmenbackpack** [comment]
已经解决!
在build.gradle文件中把maven仓库换成阿里云的
https://maven.google.com/ -> https://maven.aliyun.com/repository/google/
